import { CefrLevel } from "@prisma/client";

/**
 * 250 deutsche Vokabeln für CEFR A2 – fünf Themenpakete zu je 50 Wörtern.
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 */
export const GERMAN_VOCAB_A2 = [
  {
    title: "Einkaufen & Geld",
    level: CefrLevel.A2,
    description: "Im Geschäft, an der Kasse und bei der Bank zurechtkommen",
    iconEmoji: "🛍️",
    items: [
      ["das Geld", "money", "Ich habe nicht genug Geld dabei.", "I do not have enough money with me.", "noun"],
      ["der Euro", "euro", "Das kostet zwanzig Euro.", "That costs twenty euros.", "noun"],
      ["der Preis", "price", "Der Preis ist wirklich fair.", "The price is really fair.", "noun"],
      ["billig", "cheap", "Dieses Hemd ist sehr billig.", "This shirt is very cheap.", "adjective"],
      ["teuer", "expensive", "Das Hotel war viel zu teuer.", "The hotel was much too expensive.", "adjective"],
      ["kaufen", "to buy", "Ich möchte ein neues Fahrrad kaufen.", "I want to buy a new bicycle.", "verb"],
      ["verkaufen", "to sell", "Er verkauft sein altes Auto.", "He is selling his old car.", "verb"],
      ["bezahlen", "to pay", "Kann ich mit Karte bezahlen?", "Can I pay by card?", "verb"],
      ["die Kasse", "checkout", "An der Kasse ist eine lange Schlange.", "There is a long line at the checkout.", "noun"],
      ["der Rabatt", "discount", "Auf Schuhe gibt es zehn Prozent Rabatt.", "There is a ten percent discount on shoes.", "noun"],
      ["das Angebot", "offer, deal", "Das Angebot gilt nur diese Woche.", "The offer is only valid this week.", "noun"],
      ["die Kreditkarte", "credit card", "Ich zahle meistens mit Kreditkarte.", "I usually pay by credit card.", "noun"],
      ["das Bargeld", "cash", "Nehmen Sie auch Bargeld an?", "Do you also accept cash?", "noun"],
      ["der Kassenbon", "receipt", "Bitte heben Sie den Kassenbon auf.", "Please keep the receipt.", "noun"],
      ["anprobieren", "to try on", "Darf ich diese Jacke anprobieren?", "May I try on this jacket?", "verb"],
      ["umtauschen", "to exchange", "Kann ich das Hemd umtauschen?", "Can I exchange the shirt?", "verb"],
      ["zurückgeben", "to give back, return", "Sie möchte die Schuhe zurückgeben.", "She wants to return the shoes.", "verb"],
      ["die Größe", "size", "Welche Größe brauchen Sie?", "What size do you need?", "noun"],
      ["die Farbe", "color", "Welche Farbe gefällt dir besser?", "Which color do you like better?", "noun"],
      ["das Geschäft", "shop", "Das Geschäft schließt um achtzehn Uhr.", "The shop closes at six p.m.", "noun"],
      ["das Kaufhaus", "department store", "Im Kaufhaus gibt es alles.", "The department store has everything.", "noun"],
      ["der Markt", "market", "Samstags gehen wir auf den Markt.", "On Saturdays we go to the market.", "noun"],
      ["die Öffnungszeiten", "opening hours", "Die Öffnungszeiten stehen an der Tür.", "The opening hours are on the door.", "noun"],
      ["geöffnet", "open", "Der Laden ist bis zwanzig Uhr geöffnet.", "The shop is open until eight p.m.", "adjective"],
      ["geschlossen", "closed", "Sonntags ist der Supermarkt geschlossen.", "The supermarket is closed on Sundays.", "adjective"],
      ["das Sonderangebot", "special offer", "Diese Woche gibt es ein Sonderangebot für Käse.", "This week there is a special offer on cheese.", "noun"],
      ["sparen", "to save", "Wir sparen Geld für den Urlaub.", "We are saving money for the vacation.", "verb"],
      ["ausgeben", "to spend", "Er gibt zu viel Geld für Kleidung aus.", "He spends too much money on clothes.", "verb"],
      ["leihen", "to lend, borrow", "Kannst du mir zehn Euro leihen?", "Can you lend me ten euros?", "verb"],
      ["die Schulden", "debts", "Er hat noch Schulden bei der Bank.", "He still has debts at the bank.", "noun"],
      ["das Konto", "account", "Ich muss mein Konto überprüfen.", "I need to check my account.", "noun"],
      ["die Bank", "bank", "Die Bank öffnet um neun Uhr.", "The bank opens at nine o'clock.", "noun"],
      ["der Geldautomat", "ATM", "Der Geldautomat ist um die Ecke.", "The ATM is around the corner.", "noun"],
      ["abheben", "to withdraw", "Ich muss noch Geld abheben.", "I still need to withdraw money.", "verb"],
      ["einzahlen", "to deposit", "Er zahlt sein Gehalt auf das Konto ein.", "He deposits his salary into the account.", "verb"],
      ["überweisen", "to transfer", "Ich überweise dir das Geld morgen.", "I will transfer you the money tomorrow.", "verb"],
      ["die Rechnung", "bill, invoice", "Die Rechnung kam per E-Mail.", "The invoice arrived by email.", "noun"],
      ["die Quittung", "receipt", "Ich brauche eine Quittung für die Firma.", "I need a receipt for the company.", "noun"],
      ["kostenlos", "free of charge", "Der Eintritt ist heute kostenlos.", "Admission is free today.", "adjective"],
      ["der Wert", "value", "Der Ring hat einen hohen Wert.", "The ring has a high value.", "noun"],
      ["wertvoll", "valuable", "Das Gemälde ist sehr wertvoll.", "The painting is very valuable.", "adjective"],
      ["die Tüte", "bag", "Möchten Sie eine Tüte dazu?", "Would you like a bag with that?", "noun"],
      ["die Kleidung", "clothing", "Im Sommer trage ich leichte Kleidung.", "In summer I wear light clothing.", "noun"],
      ["die Hose", "trousers", "Diese Hose ist mir zu eng.", "These trousers are too tight for me.", "noun"],
      ["das Hemd", "shirt", "Er trägt ein weißes Hemd zur Arbeit.", "He wears a white shirt to work.", "noun"],
      ["der Rock", "skirt", "Der Rock passt gut zu der Bluse.", "The skirt goes well with the blouse.", "noun"],
      ["die Jacke", "jacket", "Zieh eine Jacke an, es ist kalt.", "Put on a jacket, it is cold.", "noun"],
      ["die Schuhe", "shoes", "Meine Schuhe sind schon alt.", "My shoes are already old.", "noun"],
      ["anziehen", "to put on", "Zieh bitte deine Jacke an.", "Please put on your jacket.", "verb"],
      ["ausziehen", "to take off", "Zieh die nassen Schuhe aus.", "Take off your wet shoes.", "verb"],
    ],
  },
  {
    title: "Reisen & Verkehr",
    level: CefrLevel.A2,
    description: "Unterwegs mit Zug, Auto und Flugzeug",
    iconEmoji: "🚆",
    items: [
      ["der Zug", "train", "Der Zug fährt in fünf Minuten ab.", "The train departs in five minutes.", "noun"],
      ["der Bus", "bus", "Ich fahre jeden Tag mit dem Bus.", "I take the bus every day.", "noun"],
      ["das Auto", "car", "Unser Auto steht vor dem Haus.", "Our car is parked in front of the house.", "noun"],
      ["das Flugzeug", "airplane", "Das Flugzeug landet pünktlich.", "The airplane lands on time.", "noun"],
      ["das Schiff", "ship", "Das Schiff fährt über den See.", "The ship crosses the lake.", "noun"],
      ["das Fahrrad", "bicycle", "Ich fahre gern mit dem Fahrrad zur Arbeit.", "I like to ride my bike to work.", "noun"],
      ["die U-Bahn", "subway", "Die U-Bahn ist heute sehr voll.", "The subway is very crowded today.", "noun"],
      ["die Straßenbahn", "tram", "Die Straßenbahn hält direkt vor dem Museum.", "The tram stops right in front of the museum.", "noun"],
      ["das Taxi", "taxi", "Wir nehmen ein Taxi zum Flughafen.", "We are taking a taxi to the airport.", "noun"],
      ["der Bahnhof", "train station", "Der Bahnhof liegt im Stadtzentrum.", "The train station is in the city center.", "noun"],
      ["der Flughafen", "airport", "Der Flughafen ist weit außerhalb der Stadt.", "The airport is far outside the city.", "noun"],
      ["die Haltestelle", "bus stop", "Die nächste Haltestelle ist ganz in der Nähe.", "The next stop is very close.", "noun"],
      ["das Gleis", "platform", "Der Zug fährt von Gleis drei ab.", "The train departs from platform three.", "noun"],
      ["die Fahrkarte", "ticket", "Wo kann ich eine Fahrkarte kaufen?", "Where can I buy a ticket?", "noun"],
      ["der Fahrplan", "timetable", "Ich schaue kurz in den Fahrplan.", "I will quickly check the timetable.", "noun"],
      ["die Ankunft", "arrival", "Die Ankunft ist für vierzehn Uhr geplant.", "Arrival is planned for two p.m.", "noun"],
      ["die Abfahrt", "departure", "Die Abfahrt verzögert sich um zehn Minuten.", "The departure is delayed by ten minutes.", "noun"],
      ["die Verspätung", "delay", "Der Bus hat heute Verspätung.", "The bus is delayed today.", "noun"],
      ["umsteigen", "to change (transport)", "In Frankfurt müssen wir umsteigen.", "We have to change trains in Frankfurt.", "verb"],
      ["einsteigen", "to board", "Bitte steigen Sie schnell ein.", "Please board quickly.", "verb"],
      ["aussteigen", "to get off", "Wir steigen an der nächsten Station aus.", "We are getting off at the next station.", "verb"],
      ["der Koffer", "suitcase", "Mein Koffer ist sehr schwer.", "My suitcase is very heavy.", "noun"],
      ["das Gepäck", "luggage", "Bitte passen Sie auf Ihr Gepäck auf.", "Please watch your luggage.", "noun"],
      ["der Reisepass", "passport", "Vergiss deinen Reisepass nicht.", "Do not forget your passport.", "noun"],
      ["das Visum", "visa", "Für dieses Land brauchst du ein Visum.", "You need a visa for this country.", "noun"],
      ["die Grenze", "border", "Wir überqueren gleich die Grenze.", "We are crossing the border soon.", "noun"],
      ["der Zoll", "customs", "Am Zoll mussten wir lange warten.", "We had to wait a long time at customs.", "noun"],
      ["buchen", "to book", "Ich habe den Flug schon gebucht.", "I have already booked the flight.", "verb"],
      ["reservieren", "to reserve", "Wir haben einen Tisch reserviert.", "We have reserved a table.", "verb"],
      ["das Hotel", "hotel", "Das Hotel liegt direkt am Strand.", "The hotel is right on the beach.", "noun"],
      ["die Jugendherberge", "youth hostel", "Wir übernachten in einer Jugendherberge.", "We are staying at a youth hostel.", "noun"],
      ["das Zimmer", "room", "Das Zimmer hat einen schönen Ausblick.", "The room has a beautiful view.", "noun"],
      ["übernachten", "to stay overnight", "Wo möchtet ihr übernachten?", "Where would you like to stay overnight?", "verb"],
      ["der Urlaub", "vacation", "Wir fahren im August in den Urlaub.", "We are going on vacation in August.", "noun"],
      ["die Reise", "trip", "Die Reise nach Italien war wunderschön.", "The trip to Italy was wonderful.", "noun"],
      ["reisen", "to travel", "Sie reist gern allein.", "She likes to travel alone.", "verb"],
      ["der Tourist", "tourist", "Viele Touristen besuchen diese Stadt.", "Many tourists visit this city.", "noun"],
      ["die Sehenswürdigkeit", "sight, attraction", "Der Dom ist die bekannteste Sehenswürdigkeit.", "The cathedral is the most famous sight.", "noun"],
      ["die Karte", "map", "Schau mal auf die Karte.", "Take a look at the map.", "noun"],
      ["der Weg", "way, path", "Der Weg zum Bahnhof ist kurz.", "The way to the station is short.", "noun"],
      ["links", "left", "Das Museum ist auf der linken Seite.", "The museum is on the left side.", "adverb"],
      ["rechts", "right", "Biegen Sie an der Ampel rechts ab.", "Turn right at the traffic light.", "adverb"],
      ["geradeaus", "straight ahead", "Gehen Sie einfach geradeaus.", "Just go straight ahead.", "adverb"],
      ["die Richtung", "direction", "Wir fahren in die falsche Richtung.", "We are driving in the wrong direction.", "noun"],
      ["die Kreuzung", "intersection", "An der Kreuzung müssen wir links abbiegen.", "At the intersection we have to turn left.", "noun"],
      ["die Ampel", "traffic light", "Die Ampel ist gerade rot.", "The traffic light is currently red.", "noun"],
      ["parken", "to park", "Hier darf man nicht parken.", "You are not allowed to park here.", "verb"],
      ["der Parkplatz", "parking lot", "Der Parkplatz ist leider voll.", "The parking lot is unfortunately full.", "noun"],
      ["tanken", "to refuel", "Wir müssen noch tanken.", "We still need to refuel.", "verb"],
      ["die Tankstelle", "gas station", "Die nächste Tankstelle ist zwei Kilometer entfernt.", "The next gas station is two kilometers away.", "noun"],
    ],
  },
  {
    title: "Gesundheit & Körper",
    level: CefrLevel.A2,
    description: "Körperteile, Krankheiten und der Arztbesuch",
    iconEmoji: "🩺",
    items: [
      ["der Kopf", "head", "Mir tut der Kopf weh.", "My head hurts.", "noun"],
      ["der Bauch", "belly", "Nach dem Essen tut mir der Bauch weh.", "My stomach hurts after eating.", "noun"],
      ["der Rücken", "back", "Mein Rücken schmerzt seit Tagen.", "My back has been hurting for days.", "noun"],
      ["der Arm", "arm", "Sie hat sich am Arm verletzt.", "She injured her arm.", "noun"],
      ["das Bein", "leg", "Sein Bein ist im Gips.", "His leg is in a cast.", "noun"],
      ["die Hand", "hand", "Er hat sich in die Hand geschnitten.", "He cut his hand.", "noun"],
      ["der Fuß", "foot", "Mein Fuß ist geschwollen.", "My foot is swollen.", "noun"],
      ["das Herz", "heart", "Ihr Herz schlägt sehr schnell.", "Her heart is beating very fast.", "noun"],
      ["der Hals", "throat, neck", "Mein Hals tut beim Schlucken weh.", "My throat hurts when I swallow.", "noun"],
      ["die Nase", "nose", "Seine Nase ist ganz rot.", "His nose is completely red.", "noun"],
      ["der Mund", "mouth", "Öffnen Sie bitte den Mund.", "Please open your mouth.", "noun"],
      ["das Ohr", "ear", "Ich habe Schmerzen im Ohr.", "I have pain in my ear.", "noun"],
      ["der Zahn", "tooth", "Der Zahn muss gezogen werden.", "The tooth has to be pulled.", "noun"],
      ["krank", "sick", "Er ist seit gestern krank.", "He has been sick since yesterday.", "adjective"],
      ["gesund", "healthy", "Zum Glück bin ich wieder gesund.", "Luckily I am healthy again.", "adjective"],
      ["die Krankheit", "illness", "Die Krankheit dauerte nur wenige Tage.", "The illness only lasted a few days.", "noun"],
      ["die Erkältung", "cold", "Ich habe eine schlimme Erkältung.", "I have a bad cold.", "noun"],
      ["das Fieber", "fever", "Das Kind hat hohes Fieber.", "The child has a high fever.", "noun"],
      ["der Husten", "cough", "Der Husten will einfach nicht weggehen.", "The cough just will not go away.", "noun"],
      ["die Schmerzen", "pain", "Ich habe starke Schmerzen im Bein.", "I have severe pain in my leg.", "noun"],
      ["die Kopfschmerzen", "headache", "Sie hat oft Kopfschmerzen.", "She often has headaches.", "noun"],
      ["wehtun", "to hurt", "Mein Knie tut weh.", "My knee hurts.", "verb"],
      ["die Apotheke", "pharmacy", "Die Apotheke ist gleich um die Ecke.", "The pharmacy is just around the corner.", "noun"],
      ["das Medikament", "medication", "Nimm dieses Medikament dreimal täglich.", "Take this medication three times a day.", "noun"],
      ["die Tablette", "pill", "Er nimmt jeden Morgen eine Tablette.", "He takes a pill every morning.", "noun"],
      ["das Rezept", "prescription", "Der Arzt schreibt mir ein Rezept.", "The doctor is writing me a prescription.", "noun"],
      ["der Termin", "appointment", "Ich habe morgen einen Termin beim Zahnarzt.", "I have an appointment at the dentist tomorrow.", "noun"],
      ["die Untersuchung", "examination", "Die Untersuchung dauert etwa eine Stunde.", "The examination takes about an hour.", "noun"],
      ["die Behandlung", "treatment", "Die Behandlung war erfolgreich.", "The treatment was successful.", "noun"],
      ["die Verletzung", "injury", "Die Verletzung ist zum Glück nicht schlimm.", "Luckily the injury is not serious.", "noun"],
      ["sich verletzen", "to injure oneself", "Er hat sich beim Sport verletzt.", "He injured himself while playing sports.", "verb"],
      ["bluten", "to bleed", "Der Finger blutet stark.", "The finger is bleeding heavily.", "verb"],
      ["der Krankenwagen", "ambulance", "Ein Krankenwagen kam sofort.", "An ambulance came immediately.", "noun"],
      ["das Krankenhaus", "hospital", "Sie liegt seit Montag im Krankenhaus.", "She has been in the hospital since Monday.", "noun"],
      ["die Praxis", "doctor's practice", "Die Praxis öffnet um acht Uhr.", "The practice opens at eight o'clock.", "noun"],
      ["impfen", "to vaccinate", "Der Arzt impft die Kinder gegen Grippe.", "The doctor vaccinates the children against the flu.", "verb"],
      ["die Impfung", "vaccination", "Die Impfung dauert nur eine Minute.", "The vaccination only takes a minute.", "noun"],
      ["gesund werden", "to recover", "Ich hoffe, du wirst bald gesund.", "I hope you get well soon.", "phrase"],
      ["sich erholen", "to recover, rest", "Er muss sich noch eine Woche erholen.", "He still needs to rest for a week.", "verb"],
      ["müde", "tired", "Nach der Arbeit bin ich immer müde.", "I am always tired after work.", "adjective"],
      ["schwach", "weak", "Nach der Krankheit fühlt sie sich schwach.", "After the illness she feels weak.", "adjective"],
      ["stark", "strong", "Er ist körperlich sehr stark.", "He is physically very strong.", "adjective"],
      ["fit", "fit", "Sie hält sich mit Sport fit.", "She keeps fit with sports.", "adjective"],
      ["sich fühlen", "to feel", "Wie fühlst du dich heute?", "How are you feeling today?", "verb"],
      ["die Allergie", "allergy", "Er hat eine Allergie gegen Nüsse.", "He has an allergy to nuts.", "noun"],
      ["schwanger", "pregnant", "Meine Schwester ist schwanger.", "My sister is pregnant.", "adjective"],
      ["die Diät", "diet", "Sie macht seit einem Monat eine Diät.", "She has been on a diet for a month.", "noun"],
      ["abnehmen", "to lose weight", "Er möchte fünf Kilo abnehmen.", "He wants to lose five kilos.", "verb"],
      ["zunehmen", "to gain weight", "Im Urlaub habe ich zugenommen.", "I gained weight on vacation.", "verb"],
      ["die Ernährung", "nutrition", "Eine gesunde Ernährung ist wichtig.", "Healthy nutrition is important.", "noun"],
    ],
  },
  {
    title: "Wetter & Jahreszeiten",
    level: CefrLevel.A2,
    description: "Über das Wetter und die vier Jahreszeiten sprechen",
    iconEmoji: "☀️",
    items: [
      ["das Wetter", "weather", "Wie ist das Wetter heute?", "What is the weather like today?", "noun"],
      ["die Sonne", "sun", "Die Sonne scheint den ganzen Tag.", "The sun is shining all day.", "noun"],
      ["der Regen", "rain", "Der Regen hört langsam auf.", "The rain is slowly stopping.", "noun"],
      ["der Schnee", "snow", "Der Schnee liegt schon zehn Zentimeter hoch.", "The snow is already ten centimeters deep.", "noun"],
      ["der Wind", "wind", "Der Wind ist heute sehr stark.", "The wind is very strong today.", "noun"],
      ["die Wolke", "cloud", "Am Himmel sind nur wenige Wolken.", "There are only a few clouds in the sky.", "noun"],
      ["der Himmel", "sky", "Der Himmel ist heute ganz blau.", "The sky is completely blue today.", "noun"],
      ["das Gewitter", "thunderstorm", "In der Nacht gab es ein Gewitter.", "There was a thunderstorm during the night.", "noun"],
      ["der Blitz", "lightning", "Ein Blitz erhellte den Himmel.", "A lightning bolt lit up the sky.", "noun"],
      ["der Donner", "thunder", "Der Donner war sehr laut.", "The thunder was very loud.", "noun"],
      ["der Nebel", "fog", "Heute Morgen war dichter Nebel.", "There was thick fog this morning.", "noun"],
      ["das Eis", "ice", "Auf der Straße liegt Eis.", "There is ice on the road.", "noun"],
      ["kalt", "cold", "Draußen ist es sehr kalt.", "It is very cold outside.", "adjective"],
      ["warm", "warm", "Im Süden ist es viel wärmer.", "It is much warmer in the south.", "adjective"],
      ["heiß", "hot", "Im Sommer wird es hier sehr heiß.", "It gets very hot here in summer.", "adjective"],
      ["kühl", "cool", "Am Abend wird es kühl.", "It gets cool in the evening.", "adjective"],
      ["nass", "wet", "Meine Kleidung ist völlig nass.", "My clothes are completely wet.", "adjective"],
      ["trocken", "dry", "Der Sommer war dieses Jahr sehr trocken.", "The summer was very dry this year.", "adjective"],
      ["sonnig", "sunny", "Morgen wird es sonnig und warm.", "Tomorrow will be sunny and warm.", "adjective"],
      ["bewölkt", "cloudy", "Am Nachmittag wird es bewölkt.", "It will get cloudy in the afternoon.", "adjective"],
      ["windig", "windy", "An der Küste ist es oft windig.", "It is often windy on the coast.", "adjective"],
      ["regnen", "to rain", "Es regnet schon seit dem Morgen.", "It has been raining since the morning.", "verb"],
      ["schneien", "to snow", "Im Dezember schneit es meistens.", "It usually snows in December.", "verb"],
      ["scheinen", "to shine", "Die Sonne scheint sehr hell.", "The sun is shining very brightly.", "verb"],
      ["die Temperatur", "temperature", "Die Temperatur sinkt am Abend.", "The temperature drops in the evening.", "noun"],
      ["der Grad", "degree", "Heute haben wir zwanzig Grad.", "Today we have twenty degrees.", "noun"],
      ["das Thermometer", "thermometer", "Das Thermometer zeigt null Grad.", "The thermometer shows zero degrees.", "noun"],
      ["der Regenschirm", "umbrella", "Nimm einen Regenschirm mit.", "Take an umbrella with you.", "noun"],
      ["die Jahreszeit", "season", "Welche Jahreszeit magst du am liebsten?", "Which season do you like best?", "noun"],
      ["das Klima", "climate", "Das Klima hier ist sehr mild.", "The climate here is very mild.", "noun"],
      ["die Vorhersage", "forecast", "Die Vorhersage sagt Regen für morgen voraus.", "The forecast predicts rain for tomorrow.", "noun"],
      ["der Sturm", "storm", "Der Sturm hat viele Bäume umgeworfen.", "The storm knocked down many trees.", "noun"],
      ["das Hochwasser", "flood", "Das Hochwasser hat die Straße überflutet.", "The flood has flooded the street.", "noun"],
      ["die Dürre", "drought", "Die Dürre schadet den Bauern.", "The drought is harming the farmers.", "noun"],
      ["der Regenmantel", "raincoat", "Zieh deinen Regenmantel an.", "Put on your raincoat.", "noun"],
      ["die Mütze", "hat, cap", "Bei Kälte trägt er immer eine Mütze.", "He always wears a cap when it is cold.", "noun"],
      ["der Handschuh", "glove", "Ich habe meinen Handschuh verloren.", "I lost my glove.", "noun"],
      ["der Schal", "scarf", "Der Schal hält den Hals warm.", "The scarf keeps the neck warm.", "noun"],
      ["warm anziehen", "to dress warmly", "Zieh dich heute warm an.", "Dress warmly today.", "phrasal verb"],
      ["frieren", "to freeze, feel cold", "Ich friere ohne Jacke.", "I am freezing without a jacket.", "verb"],
      ["schwitzen", "to sweat", "Bei dieser Hitze schwitze ich stark.", "I sweat a lot in this heat.", "verb"],
      ["draußen", "outside", "Die Kinder spielen draußen.", "The children are playing outside.", "adverb"],
      ["drinnen", "inside", "Bei Regen bleiben wir drinnen.", "We stay inside when it rains.", "adverb"],
      ["angenehm", "pleasant", "Die Temperatur ist heute angenehm.", "The temperature is pleasant today.", "adjective"],
      ["unangenehm", "unpleasant", "Der kalte Wind ist unangenehm.", "The cold wind is unpleasant.", "adjective"],
      ["die Feuchtigkeit", "humidity", "Die Feuchtigkeit macht die Hitze schwerer erträglich.", "The humidity makes the heat harder to bear.", "noun"],
      ["der Sonnenschein", "sunshine", "Nach dem Regen kam der Sonnenschein.", "After the rain came the sunshine.", "noun"],
      ["der Regenbogen", "rainbow", "Am Himmel erschien ein Regenbogen.", "A rainbow appeared in the sky.", "noun"],
      ["die Kälte", "cold (noun)", "Die Kälte im Winter ist streng.", "The cold in winter is harsh.", "noun"],
      ["die Hitze", "heat", "Die Hitze im August war kaum auszuhalten.", "The heat in August was barely bearable.", "noun"],
    ],
  },
  {
    title: "Freizeit & Hobbys",
    level: CefrLevel.A2,
    description: "Über Hobbys, Sport und Kultur sprechen",
    iconEmoji: "🎨",
    items: [
      ["das Hobby", "hobby", "Mein Hobby ist Fotografieren.", "My hobby is photography.", "noun"],
      ["die Freizeit", "leisure time", "In meiner Freizeit lese ich gern.", "In my leisure time I like to read.", "noun"],
      ["der Sport", "sport", "Er treibt jeden Tag Sport.", "He does sports every day.", "noun"],
      ["schwimmen", "to swim", "Wir schwimmen jeden Sommer im See.", "We swim in the lake every summer.", "verb"],
      ["laufen", "to run", "Sie läuft jeden Morgen eine Stunde.", "She runs for an hour every morning.", "verb"],
      ["wandern", "to hike", "Am Wochenende wandern wir in den Bergen.", "On the weekend we hike in the mountains.", "verb"],
      ["tanzen", "to dance", "Sie tanzt seit Jahren Ballett.", "She has been dancing ballet for years.", "verb"],
      ["singen", "to sing", "Er singt in einem Chor.", "He sings in a choir.", "verb"],
      ["malen", "to paint", "Sie malt gern Landschaften.", "She likes to paint landscapes.", "verb"],
      ["zeichnen", "to draw", "Mein Sohn zeichnet sehr gut.", "My son draws very well.", "verb"],
      ["fotografieren", "to photograph", "Ich fotografiere gern alte Gebäude.", "I like to photograph old buildings.", "verb"],
      ["lesen", "to read", "Abends lese ich immer ein Buch.", "In the evening I always read a book.", "verb"],
      ["das Buch", "book", "Dieses Buch ist wirklich spannend.", "This book is really exciting.", "noun"],
      ["der Roman", "novel", "Ich lese gerade einen historischen Roman.", "I am currently reading a historical novel.", "noun"],
      ["die Zeitschrift", "magazine", "Sie kauft jede Woche eine Zeitschrift.", "She buys a magazine every week.", "noun"],
      ["das Kino", "cinema", "Wir gehen heute Abend ins Kino.", "We are going to the cinema tonight.", "noun"],
      ["der Film", "movie", "Der Film war leider ziemlich langweilig.", "Unfortunately the movie was quite boring.", "noun"],
      ["das Theater", "theater", "Sie geht oft ins Theater.", "She often goes to the theater.", "noun"],
      ["das Konzert", "concert", "Das Konzert beginnt um zwanzig Uhr.", "The concert starts at eight p.m.", "noun"],
      ["die Musik", "music", "Er hört gern klassische Musik.", "He likes to listen to classical music.", "noun"],
      ["das Instrument", "instrument", "Spielst du ein Instrument?", "Do you play an instrument?", "noun"],
      ["die Gitarre", "guitar", "Er lernt seit einem Jahr Gitarre.", "He has been learning guitar for a year.", "noun"],
      ["das Klavier", "piano", "Sie spielt sehr gut Klavier.", "She plays the piano very well.", "noun"],
      ["spielen", "to play", "Die Kinder spielen im Park.", "The children are playing in the park.", "verb"],
      ["das Spiel", "game", "Das Spiel war sehr spannend.", "The game was very exciting.", "noun"],
      ["die Mannschaft", "team", "Unsere Mannschaft hat gestern gewonnen.", "Our team won yesterday.", "noun"],
      ["das Training", "training", "Das Training beginnt um achtzehn Uhr.", "Training starts at six p.m.", "noun"],
      ["der Verein", "club", "Ich bin Mitglied in einem Sportverein.", "I am a member of a sports club.", "noun"],
      ["das Mitglied", "member", "Sie ist neues Mitglied im Chor.", "She is a new member of the choir.", "noun"],
      ["klettern", "to climb", "Er klettert jedes Wochenende in den Bergen.", "He goes climbing in the mountains every weekend.", "verb"],
      ["angeln", "to fish", "Mein Vater angelt am liebsten am See.", "My father likes to fish at the lake best.", "verb"],
      ["kochen", "to cook", "Am Wochenende koche ich gern für Freunde.", "On weekends I like to cook for friends.", "verb"],
      ["backen", "to bake", "Wir backen zusammen einen Kuchen.", "We are baking a cake together.", "verb"],
      ["nähen", "to sew", "Meine Oma näht ihre Kleider selbst.", "My grandma sews her own clothes.", "verb"],
      ["basteln", "to do crafts", "Die Kinder basteln gern in ihrer Freizeit.", "The children like to do crafts in their free time.", "verb"],
      ["sammeln", "to collect", "Er sammelt seit Jahren Briefmarken.", "He has been collecting stamps for years.", "verb"],
      ["die Sammlung", "collection", "Seine Sammlung umfasst tausend Stücke.", "His collection includes a thousand pieces.", "noun"],
      ["das Museum", "museum", "Am Sonntag besuchen wir das Museum.", "On Sunday we are visiting the museum.", "noun"],
      ["die Ausstellung", "exhibition", "Die Ausstellung dauert bis Ende Mai.", "The exhibition runs until the end of May.", "noun"],
      ["die Kunst", "art", "Moderne Kunst interessiert mich sehr.", "I am very interested in modern art.", "noun"],
      ["der Künstler", "artist", "Der Künstler stellt seine Bilder aus.", "The artist is exhibiting his paintings.", "noun"],
      ["interessant", "interesting", "Der Vortrag war wirklich interessant.", "The lecture was really interesting.", "adjective"],
      ["langweilig", "boring", "Dieser Film ist mir zu langweilig.", "This movie is too boring for me.", "adjective"],
      ["spannend", "exciting", "Das Buch wird immer spannender.", "The book keeps getting more exciting.", "adjective"],
      ["lustig", "funny", "Die Geschichte war wirklich lustig.", "The story was really funny.", "adjective"],
      ["das Interesse", "interest", "Er zeigt großes Interesse an Musik.", "He shows great interest in music.", "noun"],
      ["sich interessieren", "to be interested", "Ich interessiere mich für Fotografie.", "I am interested in photography.", "verb"],
      ["die Ferien", "holidays", "In den Ferien fahren wir ans Meer.", "During the holidays we go to the seaside.", "noun"],
      ["entspannen", "to relax", "Am Wochenende möchte ich einfach entspannen.", "On the weekend I just want to relax.", "verb"],
      ["die Entspannung", "relaxation", "Yoga bringt mir viel Entspannung.", "Yoga brings me a lot of relaxation.", "noun"],
    ],
  },
];
