import { CefrLevel } from "@prisma/client";

/**
 * 250 deutsche Vokabeln für CEFR C2 – fünf Themenpakete zu je 50 Wörtern.
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 */
export const GERMAN_VOCAB_C2 = [
  {
    title: "Fachsprache & Wissenschaft",
    level: CefrLevel.C2,
    description: "Wissenschaftliches Vokabular für Forschung, Methodik und akademisches Schreiben",
    iconEmoji: "🔬",
    items: [
      ["die Erkenntnistheorie", "epistemology", "Die Erkenntnistheorie untersucht die Grenzen menschlichen Wissens.", "Epistemology examines the limits of human knowledge.", "noun"],
      ["die Hypothese", "hypothesis", "Die Forscherin stellte eine kühne Hypothese auf.", "The researcher put forward a bold hypothesis.", "noun"],
      ["das Paradigma", "paradigm", "Ein neues Paradigma löste die alte Theorie ab.", "A new paradigm replaced the old theory.", "noun"],
      ["die Signifikanz", "significance", "Die statistische Signifikanz der Ergebnisse war zweifelhaft.", "The statistical significance of the results was doubtful.", "noun"],
      ["die Kausalität", "causality", "Korrelation impliziert nicht zwangsläufig Kausalität.", "Correlation does not necessarily imply causality.", "noun"],
      ["die Korrelation", "correlation", "Die Studie zeigt eine starke Korrelation zwischen beiden Faktoren.", "The study shows a strong correlation between both factors.", "noun"],
      ["empirisch", "empirical", "Die These wurde empirisch überprüft.", "The thesis was tested empirically.", "adjective"],
      ["die Methodik", "methodology", "Die Methodik der Studie wurde ausführlich beschrieben.", "The methodology of the study was described in detail.", "noun"],
      ["die Validität", "validity", "Die interne Validität des Experiments ist gegeben.", "The internal validity of the experiment is given.", "noun"],
      ["die Reliabilität", "reliability", "Die Reliabilität des Tests wurde mehrfach überprüft.", "The reliability of the test was checked repeatedly.", "noun"],
      ["die Quantifizierung", "quantification", "Die Quantifizierung subjektiver Empfindungen ist schwierig.", "The quantification of subjective sensations is difficult.", "noun"],
      ["das Postulat", "postulate", "Sein Postulat blieb wissenschaftlich umstritten.", "His postulate remained scientifically controversial.", "noun"],
      ["die Prämisse", "premise", "Die Argumentation beruht auf einer falschen Prämisse.", "The argument is based on a false premise.", "noun"],
      ["die Deduktion", "deduction", "Durch Deduktion gelangte er zum richtigen Schluss.", "Through deduction he arrived at the correct conclusion.", "noun"],
      ["die Induktion", "induction", "Induktion schließt vom Einzelfall auf das Allgemeine.", "Induction infers the general from the particular case.", "noun"],
      ["die Falsifizierbarkeit", "falsifiability", "Popper machte die Falsifizierbarkeit zum Kriterium für Wissenschaftlichkeit.", "Popper made falsifiability the criterion for scientific validity.", "noun"],
      ["das Axiom", "axiom", "Dieses Axiom wird in der Geometrie vorausgesetzt.", "This axiom is presupposed in geometry.", "noun"],
      ["die Kohärenz", "coherence", "Die Kohärenz seiner Argumentation überzeugte die Jury.", "The coherence of his argument convinced the jury.", "noun"],
      ["interdisziplinär", "interdisciplinary", "Das Projekt erfordert einen interdisziplinären Ansatz.", "The project requires an interdisciplinary approach.", "adjective"],
      ["die Komplexität", "complexity", "Die Komplexität des Systems überstieg alle Erwartungen.", "The complexity of the system exceeded all expectations.", "noun"],
      ["das Phänomen", "phenomenon", "Dieses Phänomen lässt sich physikalisch erklären.", "This phenomenon can be explained physically.", "noun"],
      ["die Determinante", "determinant", "Bildung gilt als wichtige Determinante des sozialen Aufstiegs.", "Education is considered an important determinant of social mobility.", "noun"],
      ["approximieren", "to approximate", "Der Wert lässt sich mithilfe dieser Formel approximieren.", "The value can be approximated using this formula.", "verb"],
      ["extrapolieren", "to extrapolate", "Aus den Daten lässt sich ein Trend extrapolieren.", "A trend can be extrapolated from the data.", "verb"],
      ["die Signifikanzschwelle", "significance threshold", "Das Ergebnis überschritt die festgelegte Signifikanzschwelle.", "The result exceeded the defined significance threshold.", "noun"],
      ["die Kontrollgruppe", "control group", "Die Kontrollgruppe erhielt ein Placebo.", "The control group received a placebo.", "noun"],
      ["die Stichprobe", "sample", "Die Stichprobe war für eine verlässliche Aussage zu klein.", "The sample was too small for a reliable conclusion.", "noun"],
      ["die Varianz", "variance", "Die Varianz der Messwerte war ungewöhnlich hoch.", "The variance of the measured values was unusually high.", "noun"],
      ["das Konfidenzintervall", "confidence interval", "Das Konfidenzintervall gibt die Genauigkeit der Schätzung an.", "The confidence interval indicates the precision of the estimate.", "noun"],
      ["die Plausibilität", "plausibility", "Die Plausibilität der Theorie wurde stark angezweifelt.", "The plausibility of the theory was strongly questioned.", "noun"],
      ["die Anomalie", "anomaly", "Die Messung ergab eine unerklärliche Anomalie.", "The measurement revealed an inexplicable anomaly.", "noun"],
      ["die Synthese", "synthesis", "Seine Arbeit ist eine Synthese verschiedener Denkschulen.", "His work is a synthesis of various schools of thought.", "noun"],
      ["dichotom", "dichotomous", "Eine dichotome Einteilung wird der Realität selten gerecht.", "A dichotomous classification rarely does justice to reality.", "adjective"],
      ["die Taxonomie", "taxonomy", "Die Taxonomie der Lebewesen wird ständig erweitert.", "The taxonomy of living beings is constantly being expanded.", "noun"],
      ["die Nomenklatur", "nomenclature", "Die chemische Nomenklatur folgt strengen Regeln.", "Chemical nomenclature follows strict rules.", "noun"],
      ["das Konstrukt", "construct", "Intelligenz ist ein theoretisches Konstrukt.", "Intelligence is a theoretical construct.", "noun"],
      ["die Heuristik", "heuristic", "Er löste das Problem mithilfe einer einfachen Heuristik.", "He solved the problem using a simple heuristic.", "noun"],
      ["die Simulation", "simulation", "Die Simulation bildete reale Bedingungen exakt nach.", "The simulation replicated real conditions precisely.", "noun"],
      ["das Modell", "model", "Das mathematische Modell bildet die Wirklichkeit nur vereinfacht ab.", "The mathematical model only represents reality in a simplified way.", "noun"],
      ["die Präzision", "precision", "Die Präzision der Messgeräte ist entscheidend.", "The precision of the measuring instruments is crucial.", "noun"],
      ["die Genauigkeit", "accuracy", "Die Genauigkeit der Vorhersage ließ zu wünschen übrig.", "The accuracy of the prediction left something to be desired.", "noun"],
      ["begutachten", "to peer-review", "Der Aufsatz wurde von zwei Experten begutachtet.", "The paper was peer-reviewed by two experts.", "verb"],
      ["die Fachzeitschrift", "academic journal", "Die Studie erschien in einer renommierten Fachzeitschrift.", "The study was published in a renowned academic journal.", "noun"],
      ["das Gutachterverfahren", "peer-review process", "Das Gutachterverfahren dauerte mehrere Monate.", "The peer-review process took several months.", "noun"],
      ["die Reproduzierbarkeit", "reproducibility", "Die mangelnde Reproduzierbarkeit stellte die Ergebnisse infrage.", "The lack of reproducibility called the results into question.", "noun"],
      ["die Verzerrung", "bias", "Eine systematische Verzerrung verfälschte die Daten.", "A systematic bias distorted the data.", "noun"],
      ["die Signifikanztestung", "significance testing", "Die Signifikanztestung bestätigte die Annahme.", "The significance testing confirmed the assumption.", "noun"],
      ["das Experiment", "experiment", "Das Experiment ließ sich unter Laborbedingungen wiederholen.", "The experiment could be repeated under laboratory conditions.", "noun"],
      ["die Dissertation", "dissertation", "Ihre Dissertation befasst sich mit Quantenmechanik.", "Her dissertation deals with quantum mechanics.", "noun"],
      ["verifizieren", "to verify", "Die Angaben ließen sich nicht verifizieren.", "The information could not be verified.", "verb"],
    ],
  },
  {
    title: "Literatur & Stilmittel",
    level: CefrLevel.C2,
    description: "Literaturwissenschaftliche Begriffe und rhetorische Stilmittel",
    iconEmoji: "🖋️",
    items: [
      ["die Metapher", "metaphor", "Die Metapher verleiht dem Gedicht seine Tiefe.", "The metaphor gives the poem its depth.", "noun"],
      ["die Metonymie", "metonymy", "„Die Krone\" steht metonymisch für den Monarchen.", "\"The crown\" stands metonymically for the monarch.", "noun"],
      ["die Allegorie", "allegory", "Der Roman ist eine Allegorie auf die Gesellschaft.", "The novel is an allegory of society.", "noun"],
      ["die Ironie", "irony", "Seine Ironie blieb vielen Lesern verborgen.", "His irony remained hidden from many readers.", "noun"],
      ["der Sarkasmus", "sarcasm", "Ihr Sarkasmus verletzte ihn zutiefst.", "Her sarcasm deeply hurt him.", "noun"],
      ["die Hyperbel", "hyperbole", "Die Hyperbel übertreibt bewusst, um Wirkung zu erzielen.", "The hyperbole deliberately exaggerates to create an effect.", "noun"],
      ["die Litotes", "litotes", "Mit einer Litotes wird etwas durch Verneinung des Gegenteils ausgedrückt.", "With litotes, something is expressed by negating its opposite.", "noun"],
      ["das Oxymoron", "oxymoron", "„Bittersüß\" ist ein bekanntes Oxymoron.", "\"Bittersweet\" is a well-known oxymoron.", "noun"],
      ["die Anapher", "anaphora", "Die Anapher verstärkt den rhythmischen Charakter der Rede.", "The anaphora reinforces the rhythmic character of the speech.", "noun"],
      ["die Alliteration", "alliteration", "Die Alliteration verleiht dem Vers Klang.", "The alliteration gives the verse sound.", "noun"],
      ["die Personifikation", "personification", "Die Personifikation des Todes ist ein altes literarisches Motiv.", "The personification of death is an old literary motif.", "noun"],
      ["die Symbolik", "symbolism", "Die Symbolik des Romans erschließt sich erst bei zweiter Lektüre.", "The symbolism of the novel only becomes clear on a second reading.", "noun"],
      ["die Erzählperspektive", "narrative perspective", "Der Autor wechselt mehrfach die Erzählperspektive.", "The author changes the narrative perspective several times.", "noun"],
      ["der Erzähler", "narrator", "Der unzuverlässige Erzähler verwirrt die Leserschaft absichtlich.", "The unreliable narrator deliberately confuses the readership.", "noun"],
      ["die Handlung", "plot", "Die Handlung entfaltet sich in mehreren Zeitebenen.", "The plot unfolds across several time levels.", "noun"],
      ["die Zäsur", "caesura", "Eine Zäsur unterbricht den Vers an markanter Stelle.", "A caesura interrupts the verse at a striking point.", "noun"],
      ["der Blankvers", "blank verse", "Shakespeare schrieb viele Dramen im Blankvers.", "Shakespeare wrote many dramas in blank verse.", "noun"],
      ["das Enjambement", "enjambment", "Das Enjambement lässt den Satz über die Verszeile hinausfließen.", "The enjambment lets the sentence flow beyond the verse line.", "noun"],
      ["die Epoche", "literary period", "Der Roman ist ein Musterbeispiel der Epoche des Naturalismus.", "The novel is a prime example of the naturalist period.", "noun"],
      ["der Realismus", "realism", "Der Realismus strebt eine möglichst genaue Wirklichkeitsdarstellung an.", "Realism aims for the most accurate representation of reality possible.", "noun"],
      ["die Rezeption", "reception", "Die Rezeption des Werkes wandelte sich im Laufe der Zeit.", "The reception of the work changed over time.", "noun"],
      ["die Ambiguität", "ambiguity", "Die Ambiguität des Titels lässt mehrere Deutungen zu.", "The ambiguity of the title allows for several interpretations.", "noun"],
      ["die Konnotation", "connotation", "Das Wort trägt eine negative Konnotation.", "The word carries a negative connotation.", "noun"],
      ["die Denotation", "denotation", "Im Gegensatz zur Konnotation bezeichnet die Denotation die wörtliche Bedeutung.", "Unlike connotation, denotation refers to the literal meaning.", "noun"],
      ["das Leitmotiv", "leitmotif", "Das Leitmotiv der Einsamkeit zieht sich durch den gesamten Roman.", "The leitmotif of loneliness runs through the entire novel.", "noun"],
      ["die Novelle", "novella", "Die Novelle zeichnet sich durch eine unerhörte Begebenheit aus.", "The novella is characterized by an extraordinary event.", "noun"],
      ["das Versmaß", "meter", "Das Versmaß folgt strengen metrischen Regeln.", "The meter follows strict metrical rules.", "noun"],
      ["der Reim", "rhyme", "Der Reim verleiht dem Gedicht musikalische Struktur.", "The rhyme gives the poem musical structure.", "noun"],
      ["die Strophe", "stanza", "Jede Strophe besteht aus vier Versen.", "Each stanza consists of four lines.", "noun"],
      ["die Prosa", "prose", "Er wechselte von der Lyrik zur Prosa.", "He switched from poetry to prose.", "noun"],
      ["die Satire", "satire", "Die Satire entlarvt gesellschaftliche Missstände mit spitzer Feder.", "The satire exposes social ills with a sharp pen.", "noun"],
      ["die Parodie", "parody", "Die Parodie imitiert den Stil bekannter Autoren.", "The parody imitates the style of famous authors.", "noun"],
      ["die Tragik", "tragic quality", "Die Tragik der Figur liegt in ihrer Unfähigkeit zu handeln.", "The tragedy of the character lies in her inability to act.", "noun"],
      ["die Katharsis", "catharsis", "Die Katharsis am Ende des Dramas befreit den Zuschauer.", "The catharsis at the end of the drama liberates the viewer.", "noun"],
      ["die Peripetie", "peripeteia", "Die Peripetie markiert den entscheidenden Wendepunkt der Handlung.", "The peripeteia marks the decisive turning point of the plot.", "noun"],
      ["der Protagonist", "protagonist", "Der Protagonist entwickelt sich im Laufe des Romans grundlegend.", "The protagonist develops fundamentally over the course of the novel.", "noun"],
      ["der Antagonist", "antagonist", "Der Antagonist verkörpert das genaue Gegenteil des Helden.", "The antagonist embodies the exact opposite of the hero.", "noun"],
      ["die Fabel", "fable", "Die Fabel vermittelt eine moralische Lehre.", "The fable conveys a moral lesson.", "noun"],
      ["die Parabel", "parable", "Die Parabel lässt sich auf die menschliche Existenz übertragen.", "The parable can be applied to human existence.", "noun"],
      ["das Motiv", "motif", "Das Motiv des Doppelgängers taucht in der Romantik häufig auf.", "The doppelganger motif appears frequently in Romanticism.", "noun"],
      ["die Stilistik", "stylistics", "Die Stilistik untersucht die sprachliche Gestaltung eines Textes.", "Stylistics examines the linguistic composition of a text.", "noun"],
      ["das Pathos", "pathos", "Das Pathos seiner Rede berührte das Publikum tief.", "The pathos of his speech deeply moved the audience.", "noun"],
      ["der Duktus", "tone", "Der nüchterne Duktus steht im Kontrast zum dramatischen Inhalt.", "The sober tone contrasts with the dramatic content.", "noun"],
      ["die Chiffre", "cipher", "Der Dichter verschlüsselt seine Gefühle in dunklen Chiffren.", "The poet encodes his feelings in obscure ciphers.", "noun"],
      ["die Vieldeutigkeit", "polysemy", "Die Vieldeutigkeit des Symbols regt zu vielfältigen Interpretationen an.", "The polysemy of the symbol invites diverse interpretations.", "noun"],
      ["das Sprachbild", "figure of speech", "Der Autor bedient sich kühner Sprachbilder.", "The author makes use of bold figures of speech.", "noun"],
      ["die Redewendung", "idiom", "Die Redewendung lässt sich nicht wörtlich übersetzen.", "The idiom cannot be translated literally.", "noun"],
      ["der Topos", "literary topos", "Der Topos der vergänglichen Schönheit findet sich in der gesamten Weltliteratur.", "The topos of transient beauty is found throughout world literature.", "noun"],
      ["die Intertextualität", "intertextuality", "Die Intertextualität verweist auf andere literarische Werke.", "Intertextuality refers to other literary works.", "noun"],
      ["rezipieren", "to critically receive", "Das Werk wurde von der Kritik höchst unterschiedlich rezipiert.", "The work was received very differently by critics.", "verb"],
    ],
  },
  {
    title: "Politik & Diplomatie",
    level: CefrLevel.C2,
    description: "Präzises Vokabular für Staatswesen, internationale Beziehungen und Diplomatie",
    iconEmoji: "🕊️",
    items: [
      ["die Souveränität", "sovereignty", "Die Souveränität des Staates wurde durch den Vertrag nicht angetastet.", "The sovereignty of the state was not affected by the treaty.", "noun"],
      ["die Legitimität", "legitimacy", "Die Legitimität der Wahl wurde international angezweifelt.", "The legitimacy of the election was questioned internationally.", "noun"],
      ["das Bündnis", "alliance", "Die beiden Länder schlossen ein militärisches Bündnis.", "The two countries formed a military alliance.", "noun"],
      ["die Diplomatie", "diplomacy", "Nur durch Diplomatie ließ sich der Konflikt entschärfen.", "Only through diplomacy could the conflict be defused.", "noun"],
      ["die Verhandlung", "negotiation", "Die Verhandlungen zogen sich über Monate hin.", "The negotiations dragged on for months.", "noun"],
      ["der Kompromiss", "compromise", "Beide Seiten einigten sich auf einen tragfähigen Kompromiss.", "Both sides agreed on a viable compromise.", "noun"],
      ["die Sanktion", "sanction", "Die UN verhängte Sanktionen gegen das Regime.", "The UN imposed sanctions on the regime.", "noun"],
      ["das Embargo", "embargo", "Das Handelsembargo traf die Wirtschaft hart.", "The trade embargo hit the economy hard.", "noun"],
      ["die Annexion", "annexation", "Die Annexion wurde von der internationalen Gemeinschaft verurteilt.", "The annexation was condemned by the international community.", "noun"],
      ["die Autonomie", "autonomy", "Die Region strebt nach größerer Autonomie.", "The region strives for greater autonomy.", "noun"],
      ["der Separatismus", "separatism", "Der Separatismus gewann in der Provinz zunehmend an Zulauf.", "Separatism gained increasing support in the province.", "noun"],
      ["die Koalition", "coalition", "Die Koalition zerbrach an Streitigkeiten über den Haushalt.", "The coalition broke apart over disputes about the budget.", "noun"],
      ["die Opposition", "opposition", "Die Opposition kritisierte die Reform scharf.", "The opposition sharply criticized the reform.", "noun"],
      ["das Plebiszit", "plebiscite", "Über die Verfassungsänderung wurde in einem Plebiszit abgestimmt.", "The constitutional amendment was voted on in a plebiscite.", "noun"],
      ["das Referendum", "referendum", "Das Referendum endete mit einer knappen Mehrheit für den Austritt.", "The referendum ended with a narrow majority for withdrawal.", "noun"],
      ["die Immunität", "immunity", "Der Abgeordnete berief sich auf seine parlamentarische Immunität.", "The MP invoked his parliamentary immunity.", "noun"],
      ["das Mandat", "mandate", "Die Partei erhielt kein ausreichendes Mandat zum Regieren.", "The party did not receive a sufficient mandate to govern.", "noun"],
      ["die Fraktion", "parliamentary group", "Die Fraktion stimmte geschlossen gegen den Antrag.", "The parliamentary group voted unanimously against the motion.", "noun"],
      ["das Gremium", "committee", "Ein unabhängiges Gremium prüft die Vorwürfe.", "An independent body is examining the allegations.", "noun"],
      ["die Lobby", "lobby", "Die Lobby der Industrie übte erheblichen Druck aus.", "The industry lobby exerted considerable pressure.", "noun"],
      ["das Machtgefüge", "power structure", "Der Umsturz veränderte das gesamte Machtgefüge der Region.", "The coup changed the entire power structure of the region.", "noun"],
      ["der Umsturz", "coup", "Der Umsturz verlief weitgehend unblutig.", "The coup proceeded largely bloodlessly.", "noun"],
      ["die Repression", "repression", "Die Repression gegen Andersdenkende nahm drastisch zu.", "Repression against dissidents increased drastically.", "noun"],
      ["das Exil", "exile", "Der Schriftsteller lebte jahrzehntelang im Exil.", "The writer lived in exile for decades.", "noun"],
      ["die Verfassung", "constitution", "Die Verfassung garantiert die Meinungsfreiheit.", "The constitution guarantees freedom of expression.", "noun"],
      ["das Gewaltmonopol", "monopoly on the use of force", "Der Staat beansprucht das Gewaltmonopol.", "The state claims the monopoly on the use of force.", "noun"],
      ["die Gewaltenteilung", "separation of powers", "Die Gewaltenteilung ist ein Grundpfeiler der Demokratie.", "The separation of powers is a cornerstone of democracy.", "noun"],
      ["die Judikative", "judiciary", "Die Unabhängigkeit der Judikative steht außer Frage.", "The independence of the judiciary is beyond question.", "noun"],
      ["die Exekutive", "executive", "Die Exekutive setzt die beschlossenen Gesetze um.", "The executive implements the enacted laws.", "noun"],
      ["die Legislative", "legislature", "Die Legislative verabschiedete das Gesetz mit knapper Mehrheit.", "The legislature passed the law with a narrow majority.", "noun"],
      ["der Gesandte", "envoy", "Der Gesandte überbrachte eine offizielle Protestnote.", "The envoy delivered an official note of protest.", "noun"],
      ["der Botschafter", "ambassador", "Der Botschafter wurde ins Außenministerium einbestellt.", "The ambassador was summoned to the foreign ministry.", "noun"],
      ["die Note", "diplomatic note", "Die Regierung übermittelte eine scharf formulierte Note.", "The government sent a sharply worded diplomatic note.", "noun"],
      ["das Abkommen", "agreement", "Das Abkommen trat nach der Ratifizierung in Kraft.", "The agreement came into force after ratification.", "noun"],
      ["die Ratifizierung", "ratification", "Die Ratifizierung des Vertrags scheiterte im Parlament.", "The ratification of the treaty failed in parliament.", "noun"],
      ["die Neutralität", "neutrality", "Die Schweiz bewahrt seit Jahrhunderten ihre Neutralität.", "Switzerland has maintained its neutrality for centuries.", "noun"],
      ["die Eskalation", "escalation", "Beide Seiten bemühten sich, eine weitere Eskalation zu vermeiden.", "Both sides tried to avoid further escalation.", "noun"],
      ["die Deeskalation", "de-escalation", "Die Deeskalation gelang nur durch Vermittlung Dritter.", "De-escalation was only achieved through third-party mediation.", "noun"],
      ["der Vermittler", "mediator", "Ein neutraler Vermittler leitete die Gespräche.", "A neutral mediator led the talks.", "noun"],
      ["die Geopolitik", "geopolitics", "Die Geopolitik der Region ist von Ressourcenkonflikten geprägt.", "The geopolitics of the region is shaped by resource conflicts.", "noun"],
      ["der Hegemon", "hegemon", "Die Großmacht agierte zunehmend als regionaler Hegemon.", "The great power increasingly acted as a regional hegemon.", "noun"],
      ["die Vormachtstellung", "dominant position", "Das Land verteidigte seine Vormachtstellung mit allen Mitteln.", "The country defended its dominant position by all means.", "noun"],
      ["die Repräsentation", "representation", "Die politische Repräsentation von Minderheiten bleibt unzureichend.", "The political representation of minorities remains inadequate.", "noun"],
      ["das Wahlsystem", "electoral system", "Das Wahlsystem begünstigt größere Parteien.", "The electoral system favors larger parties.", "noun"],
      ["die Klientelpolitik", "clientelism", "Klientelpolitik untergräbt das Vertrauen in staatliche Institutionen.", "Clientelism undermines trust in state institutions.", "noun"],
      ["der Populismus", "populism", "Der Populismus lebt von einfachen Antworten auf komplexe Fragen.", "Populism thrives on simple answers to complex questions.", "noun"],
      ["die Demagogie", "demagoguery", "Seine Rede war von reiner Demagogie geprägt.", "His speech was characterized by pure demagoguery.", "noun"],
      ["die Staatsräson", "reason of state", "Man rechtfertigte die Entscheidung mit der Staatsräson.", "The decision was justified by reason of state.", "noun"],
      ["der Gesellschaftsvertrag", "social contract", "Rousseau entwickelte die Theorie des Gesellschaftsvertrags.", "Rousseau developed the theory of the social contract.", "noun"],
      ["die Realpolitik", "realpolitik", "Bismarck gilt als Meister der Realpolitik.", "Bismarck is regarded as a master of realpolitik.", "noun"],
    ],
  },
  {
    title: "Psychologie & Soziologie",
    level: CefrLevel.C2,
    description: "Präzises Vokabular für seelische Vorgänge und gesellschaftliche Strukturen",
    iconEmoji: "🧠",
    items: [
      ["die Kognition", "cognition", "Die Kognition umfasst alle Prozesse der Wahrnehmung und des Denkens.", "Cognition encompasses all processes of perception and thought.", "noun"],
      ["die Wahrnehmung", "perception", "Die subjektive Wahrnehmung weicht oft von der Realität ab.", "Subjective perception often deviates from reality.", "noun"],
      ["das Unterbewusstsein", "subconscious", "Viele Entscheidungen werden im Unterbewusstsein getroffen.", "Many decisions are made in the subconscious.", "noun"],
      ["die Verdrängung", "repression", "Die Verdrängung schmerzhafter Erinnerungen ist ein bekannter Abwehrmechanismus.", "The repression of painful memories is a well-known defense mechanism.", "noun"],
      ["der Abwehrmechanismus", "defense mechanism", "Rationalisierung ist ein häufiger Abwehrmechanismus.", "Rationalization is a common defense mechanism.", "noun"],
      ["die Empathie", "empathy", "Empathie ermöglicht es, die Gefühle anderer nachzuvollziehen.", "Empathy makes it possible to understand others' feelings.", "noun"],
      ["die Introspektion", "introspection", "Durch Introspektion gelangte er zu neuen Einsichten über sich selbst.", "Through introspection he gained new insights into himself.", "noun"],
      ["die Resilienz", "resilience", "Ihre Resilienz half ihr, die Krise zu bewältigen.", "Her resilience helped her cope with the crisis.", "noun"],
      ["das Trauma", "trauma", "Das Trauma wirkte noch Jahre später nach.", "The trauma had effects even years later.", "noun"],
      ["die Neurose", "neurosis", "Seine Neurose äußerte sich in ständigem Selbstzweifel.", "His neurosis manifested itself in constant self-doubt.", "noun"],
      ["die Persönlichkeitsstörung", "personality disorder", "Die Diagnose einer Persönlichkeitsstörung erfordert eine sorgfältige Abklärung.", "The diagnosis of a personality disorder requires careful assessment.", "noun"],
      ["die Sozialisation", "socialization", "Die Sozialisation prägt das Verhalten eines Menschen entscheidend.", "Socialization decisively shapes a person's behavior.", "noun"],
      ["die Norm", "norm", "Gesellschaftliche Normen ändern sich im Laufe der Zeit.", "Social norms change over time.", "noun"],
      ["die Konformität", "conformity", "Der Druck zur Konformität war in der Gruppe enorm.", "The pressure to conform was enormous in the group.", "noun"],
      ["die Devianz", "deviance", "Devianz wird nicht in jeder Kultur gleich definiert.", "Deviance is not defined the same way in every culture.", "noun"],
      ["die Stigmatisierung", "stigmatization", "Die Stigmatisierung psychischer Erkrankungen erschwert die Behandlung.", "The stigmatization of mental illness complicates treatment.", "noun"],
      ["das Vorurteil", "prejudice", "Vorurteile entstehen oft aus mangelndem Kontakt zwischen Gruppen.", "Prejudices often arise from a lack of contact between groups.", "noun"],
      ["die Diskriminierung", "discrimination", "Diskriminierung am Arbeitsplatz ist gesetzlich verboten.", "Discrimination in the workplace is prohibited by law.", "noun"],
      ["das Stereotyp", "stereotype", "Das Stereotyp hält sich hartnäckig trotz gegenteiliger Beweise.", "The stereotype persists stubbornly despite evidence to the contrary.", "noun"],
      ["die Gruppendynamik", "group dynamics", "Die Gruppendynamik beeinflusste die Entscheidung erheblich.", "Group dynamics significantly influenced the decision.", "noun"],
      ["der Gruppenzwang", "peer pressure", "Gruppenzwang verleitet Jugendliche oft zu riskantem Verhalten.", "Peer pressure often leads adolescents to risky behavior.", "noun"],
      ["die Autorität", "authority", "Die Autorität des Lehrers wurde infrage gestellt.", "The teacher's authority was called into question.", "noun"],
      ["der Gehorsam", "obedience", "Milgrams Experiment untersuchte den Gehorsam gegenüber Autoritäten.", "Milgram's experiment examined obedience to authority.", "noun"],
      ["die Anpassung", "adaptation", "Die Anpassung an neue Lebensumstände fiel ihr schwer.", "Adapting to new living circumstances was difficult for her.", "noun"],
      ["die Entfremdung", "alienation", "Marx beschrieb die Entfremdung der Arbeiter von ihrer Arbeit.", "Marx described the alienation of workers from their labor.", "noun"],
      ["die Anomie", "anomie", "Durkheim prägte den Begriff der Anomie.", "Durkheim coined the term anomie.", "noun"],
      ["die soziale Schicht", "social stratum", "Die soziale Schicht beeinflusst die Bildungschancen erheblich.", "Social class significantly influences educational opportunities.", "noun"],
      ["die Mobilität", "mobility", "Soziale Mobilität ist in manchen Gesellschaften stark eingeschränkt.", "Social mobility is severely limited in some societies.", "noun"],
      ["das Milieu", "milieu", "Sein soziales Milieu prägte seine Weltanschauung.", "His social milieu shaped his worldview.", "noun"],
      ["die Identität", "identity", "Die kulturelle Identität wandelt sich durch Migration.", "Cultural identity changes through migration.", "noun"],
      ["die Selbstwahrnehmung", "self-perception", "Ihre Selbstwahrnehmung stimmte kaum mit dem Fremdbild überein.", "Her self-perception hardly matched the way others saw her.", "noun"],
      ["die Fremdwahrnehmung", "perception by others", "Fremdwahrnehmung und Selbstbild klaffen oft auseinander.", "Perception by others and self-image often diverge.", "noun"],
      ["die Introversion", "introversion", "Introversion wird fälschlicherweise oft mit Schüchternheit gleichgesetzt.", "Introversion is often mistakenly equated with shyness.", "noun"],
      ["die Extraversion", "extraversion", "Extraversion zeigt sich in ausgeprägter Geselligkeit.", "Extraversion shows itself in pronounced sociability.", "noun"],
      ["die Motivation", "motivation", "Intrinsische Motivation hält länger an als äußerer Druck.", "Intrinsic motivation lasts longer than external pressure.", "noun"],
      ["der Antrieb", "drive", "Sein Antrieb, sich zu verbessern, war ungebrochen.", "His drive to improve himself was unbroken.", "noun"],
      ["die Frustration", "frustration", "Anhaltende Frustration kann zu Aggression führen.", "Persistent frustration can lead to aggression.", "noun"],
      ["die Aggression", "aggression", "Aggression ist nicht zwangsläufig destruktiv.", "Aggression is not necessarily destructive.", "noun"],
      ["die Sublimierung", "sublimation", "Sublimierung wandelt triebhafte Energie in kreative Leistung um.", "Sublimation transforms instinctual energy into creative achievement.", "noun"],
      ["die Regression", "regression", "Unter Stress zeigte er Anzeichen von Regression.", "Under stress he showed signs of regression.", "noun"],
      ["die Projektion", "projection", "Projektion überträgt eigene Gefühle auf andere Personen.", "Projection transfers one's own feelings onto other people.", "noun"],
      ["die Rationalisierung", "rationalization", "Rationalisierung dient dazu, unangenehme Wahrheiten erträglicher zu machen.", "Rationalization serves to make unpleasant truths more bearable.", "noun"],
      ["die kognitive Dissonanz", "cognitive dissonance", "Kognitive Dissonanz entsteht, wenn Überzeugung und Verhalten widersprüchlich sind.", "Cognitive dissonance arises when belief and behavior are contradictory.", "noun"],
      ["die Bestätigungsverzerrung", "confirmation bias", "Die Bestätigungsverzerrung lässt uns widersprüchliche Fakten ignorieren.", "Confirmation bias makes us ignore contradictory facts.", "noun"],
      ["verallgemeinern", "to generalize", "Man sollte nicht vorschnell von Einzelfällen verallgemeinern.", "One should not hastily generalize from individual cases.", "verb"],
      ["die Verhaltensforschung", "behavioral research", "Die Verhaltensforschung liefert wichtige Erkenntnisse über soziale Interaktion.", "Behavioral research provides important insights into social interaction.", "noun"],
      ["das Kollektivbewusstsein", "collective consciousness", "Durkheim untersuchte das Kollektivbewusstsein einer Gesellschaft.", "Durkheim studied the collective consciousness of a society.", "noun"],
      ["die Massenpsychologie", "mass psychology", "Die Massenpsychologie erklärt Phänomene wie Panik in großen Menschenmengen.", "Mass psychology explains phenomena like panic in large crowds.", "noun"],
      ["die Empathiefähigkeit", "capacity for empathy", "Seine Empathiefähigkeit machte ihn zu einem geschätzten Therapeuten.", "His capacity for empathy made him a valued therapist.", "noun"],
      ["introspektiv", "introspective", "Sie neigt zu einer introspektiven, fast grüblerischen Art.", "She tends toward an introspective, almost brooding manner.", "adjective"],
    ],
  },
  {
    title: "Idiomatik & Feinheiten der Sprache",
    level: CefrLevel.C2,
    description: "Redewendungen und feste Wendungen, die nur Muttersprachler wirklich beherrschen",
    iconEmoji: "🗝️",
    items: [
      ["jemandem einen Bären aufbinden", "to pull someone's leg", "Glaub ihm nicht, er bindet dir nur einen Bären auf.", "Do not believe him, he is just pulling your leg.", "idiom"],
      ["die Katze im Sack kaufen", "to buy a pig in a poke", "Ohne Probefahrt kauft man die Katze im Sack.", "Without a test drive, you are buying a pig in a poke.", "idiom"],
      ["ins Fettnäpfchen treten", "to put one's foot in it", "Mit dieser Bemerkung ist er ordentlich ins Fettnäpfchen getreten.", "With that remark he really put his foot in it.", "idiom"],
      ["die Nase voll haben", "to be fed up", "Ich habe die Nase voll von diesen Ausreden.", "I am fed up with these excuses.", "idiom"],
      ["auf dem Holzweg sein", "to be on the wrong track", "Mit dieser Annahme bist du völlig auf dem Holzweg.", "With that assumption you are completely on the wrong track.", "idiom"],
      ["den Nagel auf den Kopf treffen", "to hit the nail on the head", "Mit dieser Analyse hat er den Nagel auf den Kopf getroffen.", "With that analysis he hit the nail on the head.", "idiom"],
      ["jemandem reinen Wein einschenken", "to tell someone the plain truth", "Es ist Zeit, ihm reinen Wein einzuschenken.", "It is time to tell him the plain truth.", "idiom"],
      ["um den heißen Brei herumreden", "to beat around the bush", "Hör auf, um den heißen Brei herumzureden, und sag es direkt.", "Stop beating around the bush and just say it.", "idiom"],
      ["die Kirche im Dorf lassen", "to not overreact", "Lass uns die Kirche im Dorf lassen, so schlimm ist es nicht.", "Let us not overreact, it is not that bad.", "idiom"],
      ["jemanden auf die Palme bringen", "to drive someone up the wall", "Seine ständige Nörgelei bringt mich auf die Palme.", "His constant nagging drives me up the wall.", "idiom"],
      ["ein Auge zudrücken", "to turn a blind eye", "Der Lehrer drückte diesmal ein Auge zu.", "The teacher turned a blind eye this time.", "idiom"],
      ["Haare spalten", "to split hairs", "Du spaltest wieder Haare, das ist doch nebensächlich.", "You are splitting hairs again, that is beside the point.", "idiom"],
      ["das Kind mit dem Bade ausschütten", "to throw out the baby with the bathwater", "Bei der Reform sollte man nicht das Kind mit dem Bade ausschütten.", "In the reform, one should not throw out the baby with the bathwater.", "idiom"],
      ["wie aus dem Ei gepellt", "looking spick and span", "Er erschien wie aus dem Ei gepellt zum Vorstellungsgespräch.", "He showed up looking spick and span for the interview.", "idiom"],
      ["jemandem die Daumen drücken", "to keep one's fingers crossed for someone", "Ich drücke dir die Daumen für die Prüfung.", "I will keep my fingers crossed for you for the exam.", "idiom"],
      ["sich etwas hinter die Ohren schreiben", "to remember something well", "Das solltest du dir hinter die Ohren schreiben.", "You should remember that well.", "idiom"],
      ["auf Wolke sieben schweben", "to be on cloud nine", "Seit der Verlobung schwebt sie auf Wolke sieben.", "Since the engagement she has been on cloud nine.", "idiom"],
      ["ins kalte Wasser springen", "to jump in at the deep end", "Am ersten Arbeitstag musste er gleich ins kalte Wasser springen.", "On his first day at work he had to jump straight in at the deep end.", "idiom"],
      ["die Flinte ins Korn werfen", "to throw in the towel", "Trotz aller Rückschläge warf sie nie die Flinte ins Korn.", "Despite all setbacks, she never threw in the towel.", "idiom"],
      ["Schwein haben", "to be lucky", "Bei dem Unfall hat er wirklich Schwein gehabt.", "He was really lucky in that accident.", "idiom"],
      ["jemandem einen Strich durch die Rechnung machen", "to throw a wrench in someone's plans", "Das schlechte Wetter machte uns einen Strich durch die Rechnung.", "The bad weather threw a wrench in our plans.", "idiom"],
      ["den Kürzeren ziehen", "to come off worse", "Bei der Verhandlung zog er den Kürzeren.", "He came off worse in the negotiation.", "idiom"],
      ["sich zwischen zwei Stühle setzen", "to fall between two stools", "Mit diesem Kompromiss setzt er sich zwischen zwei Stühle.", "With this compromise he falls between two stools.", "idiom"],
      ["etwas auf die lange Bank schieben", "to put something off", "Er schiebt die Entscheidung schon seit Wochen auf die lange Bank.", "He has been putting off the decision for weeks.", "idiom"],
      ["das A und O", "the be-all and end-all", "Ehrlichkeit ist das A und O einer guten Beziehung.", "Honesty is the be-all and end-all of a good relationship.", "idiom"],
      ["mit allen Wassern gewaschen sein", "to be a shrewd operator", "Der Anwalt ist mit allen Wassern gewaschen.", "The lawyer is a shrewd operator.", "idiom"],
      ["jemandem etwas unter die Nase reiben", "to rub something in someone's face", "Er rieb ihr ständig ihren Fehler unter die Nase.", "He kept rubbing her mistake in her face.", "idiom"],
      ["Öl ins Feuer gießen", "to add fuel to the fire", "Mit dieser Bemerkung goss er nur Öl ins Feuer.", "With that remark he just added fuel to the fire.", "idiom"],
      ["den Löffel abgeben", "to kick the bucket", "In der Geschichte gibt der Bösewicht am Ende den Löffel ab.", "In the story, the villain kicks the bucket in the end.", "idiom"],
      ["sich in Schale werfen", "to dress to the nines", "Für die Gala hat sie sich richtig in Schale geworfen.", "She really dressed to the nines for the gala.", "idiom"],
      ["jemanden über den Tisch ziehen", "to rip someone off", "Der Verkäufer wollte ihn beim Autokauf über den Tisch ziehen.", "The salesman wanted to rip him off when buying the car.", "idiom"],
      ["auf großem Fuß leben", "to live beyond one's means", "Sie lebten jahrelang auf großem Fuß.", "They lived beyond their means for years.", "idiom"],
      ["sich am Riemen reißen", "to pull oneself together", "Reiß dich zusammen, wir haben noch viel zu tun.", "Pull yourself together, we still have a lot to do.", "idiom"],
      ["jemandem einen Korb geben", "to turn someone down", "Sie gab ihm bei der Einladung einen Korb.", "She turned him down when he asked her out.", "idiom"],
      ["mit dem falschen Fuß aufstehen", "to get up on the wrong side of the bed", "Er ist heute wohl mit dem falschen Fuß aufgestanden.", "He must have gotten up on the wrong side of the bed today.", "idiom"],
      ["etwas an den Nagel hängen", "to give something up", "Nach dem Unfall hängte er den Profisport an den Nagel.", "After the accident he gave up professional sports.", "idiom"],
      ["sich keine grauen Haare wachsen lassen", "to not worry too much", "Lass dir deswegen keine grauen Haare wachsen.", "Do not worry too much about it.", "idiom"],
      ["wie Kraut und Rüben", "in complete disorder", "In seinem Büro sieht es aus wie Kraut und Rüben.", "His office looks like a complete mess.", "idiom"],
      ["jemanden im Regen stehen lassen", "to leave someone in the lurch", "Seine Freunde ließen ihn genau dann im Regen stehen, als er sie brauchte.", "His friends left him in the lurch exactly when he needed them.", "idiom"],
      ["die Kuh vom Eis holen", "to sort out a difficult situation", "Es wird schwer, diese Kuh vom Eis zu holen.", "It will be hard to sort out this difficult situation.", "idiom"],
      ["jemandem Honig um den Mund schmieren", "to butter someone up", "Er schmiert dem Chef ständig Honig um den Mund.", "He is always buttering up the boss.", "idiom"],
      ["mit gemischten Gefühlen", "with mixed feelings", "Sie betrachtete den Umzug mit gemischten Gefühlen.", "She viewed the move with mixed feelings.", "phrase"],
      ["das Zünglein an der Waage", "the deciding factor", "Seine Stimme war das Zünglein an der Waage.", "His vote was the deciding factor.", "idiom"],
      ["jemandem ein Dorn im Auge sein", "to be a thorn in someone's side", "Der Konkurrent war ihm schon lange ein Dorn im Auge.", "The competitor had long been a thorn in his side.", "idiom"],
      ["auf Sand gebaut sein", "to be built on shaky foundations", "Sein ganzes Geschäftsmodell ist auf Sand gebaut.", "His entire business model is built on shaky foundations.", "idiom"],
      ["sich die Radieschen von unten ansehen", "to be pushing up daisies", "In dieser Erzählung sieht sich der Verräter am Ende die Radieschen von unten an.", "In this tale, the traitor ends up pushing up daisies.", "idiom"],
      ["den Braten riechen", "to smell a rat", "Sie roch den Braten und verließ die Verhandlung sofort.", "She smelled a rat and immediately left the negotiation.", "idiom"],
      ["Schwamm drüber", "let us forget about it", "Schwamm drüber, das ist längst vergessen.", "Let us forget about it, that is long forgotten.", "phrase"],
      ["jemandem die Show stehlen", "to steal the show", "Mit ihrer Rede stahl sie allen anderen Rednern die Show.", "With her speech she stole the show from all the other speakers.", "idiom"],
      ["unter die Lupe nehmen", "to scrutinize", "Die Kommission nahm die Verträge genau unter die Lupe.", "The commission scrutinized the contracts closely.", "idiom"],
    ],
  },
];
