import { CefrLevel } from "@prisma/client";

/**
 * 250 deutsche Vokabeln für CEFR A1 – fünf Themenpakete zu je 50 Wörtern.
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 */
export const GERMAN_VOCAB_A1 = [
  {
    title: "Begrüßung & Alltag",
    level: CefrLevel.A1,
    description: "Die wichtigsten Wörter für den ersten Kontakt und den Alltag",
    iconEmoji: "👋",
    items: [
      ["hallo", "hello", "Hallo, wie geht es dir?", "Hello, how are you?", "interjection"],
      ["auf Wiedersehen", "goodbye", "Auf Wiedersehen, bis morgen!", "Goodbye, see you tomorrow!", "phrase"],
      ["bitte", "please", "Ein Glas Wasser, bitte.", "A glass of water, please.", "adverb"],
      ["danke", "thank you", "Danke für deine Hilfe.", "Thank you for your help.", "phrase"],
      ["ja", "yes", "Ja, das ist richtig.", "Yes, that is correct.", "adverb"],
      ["nein", "no", "Nein, das stimmt nicht.", "No, that is not true.", "adverb"],
      ["gut", "good", "Das Essen ist sehr gut.", "The food is very good.", "adjective"],
      ["schlecht", "bad", "Mir geht es heute schlecht.", "I feel bad today.", "adjective"],
      ["die Entschuldigung", "apology, excuse me", "Entschuldigung, wo ist der Bahnhof?", "Excuse me, where is the train station?", "noun"],
      ["der Name", "name", "Mein Name ist Anna.", "My name is Anna.", "noun"],
      ["heißen", "to be called", "Wie heißt du?", "What is your name?", "verb"],
      ["wohnen", "to live", "Ich wohne in Berlin.", "I live in Berlin.", "verb"],
      ["kommen", "to come", "Woher kommst du?", "Where do you come from?", "verb"],
      ["sein", "to be", "Ich bin müde.", "I am tired.", "verb"],
      ["haben", "to have", "Ich habe eine Frage.", "I have a question.", "verb"],
      ["sprechen", "to speak", "Sprichst du Deutsch?", "Do you speak German?", "verb"],
      ["verstehen", "to understand", "Ich verstehe das nicht.", "I do not understand that.", "verb"],
      ["die Sprache", "language", "Deutsch ist eine schwere Sprache.", "German is a difficult language.", "noun"],
      ["Deutsch", "German (language)", "Ich lerne seit einem Jahr Deutsch.", "I have been learning German for a year.", "noun"],
      ["Englisch", "English (language)", "Sie spricht sehr gut Englisch.", "She speaks English very well.", "noun"],
      ["der Tag", "day", "Ich habe einen langen Tag.", "I am having a long day.", "noun"],
      ["die Nacht", "night", "Gute Nacht und schlaf gut.", "Good night and sleep well.", "noun"],
      ["der Morgen", "morning", "Am Morgen trinke ich Kaffee.", "In the morning I drink coffee.", "noun"],
      ["der Abend", "evening", "Am Abend lese ich gern.", "In the evening I like to read.", "noun"],
      ["heute", "today", "Heute ist es sonnig.", "Today it is sunny.", "adverb"],
      ["morgen", "tomorrow", "Morgen fahre ich nach Hause.", "Tomorrow I am going home.", "adverb"],
      ["gestern", "yesterday", "Gestern war ich im Kino.", "Yesterday I was at the cinema.", "adverb"],
      ["hier", "here", "Ich wohne hier seit zwei Jahren.", "I have lived here for two years.", "adverb"],
      ["dort", "there", "Das Buch liegt dort auf dem Tisch.", "The book is lying there on the table.", "adverb"],
      ["und", "and", "Ich trinke Kaffee und esse Brot.", "I drink coffee and eat bread.", "conjunction"],
      ["oder", "or", "Möchtest du Tee oder Kaffee?", "Would you like tea or coffee?", "conjunction"],
      ["aber", "but", "Ich bin müde, aber glücklich.", "I am tired, but happy.", "conjunction"],
      ["der Freund", "friend", "Er ist mein bester Freund.", "He is my best friend.", "noun"],
      ["die Freundin", "girlfriend, female friend", "Meine Freundin kommt aus Spanien.", "My friend comes from Spain.", "noun"],
      ["der Mann", "man", "Der Mann trägt einen blauen Mantel.", "The man is wearing a blue coat.", "noun"],
      ["die Frau", "woman", "Die Frau arbeitet im Krankenhaus.", "The woman works at the hospital.", "noun"],
      ["das Kind", "child", "Das Kind spielt im Garten.", "The child is playing in the garden.", "noun"],
      ["alt", "old", "Mein Opa ist sehr alt.", "My grandpa is very old.", "adjective"],
      ["jung", "young", "Die Lehrerin ist noch jung.", "The teacher is still young.", "adjective"],
      ["neu", "new", "Ich habe ein neues Handy.", "I have a new phone.", "adjective"],
      ["wie", "how", "Wie geht es dir?", "How are you?", "adverb"],
      ["was", "what", "Was machst du gerade?", "What are you doing right now?", "pronoun"],
      ["wer", "who", "Wer ist das?", "Who is that?", "pronoun"],
      ["wo", "where", "Wo wohnst du?", "Where do you live?", "adverb"],
      ["warum", "why", "Warum lernst du Deutsch?", "Why are you learning German?", "adverb"],
      ["wann", "when", "Wann kommst du an?", "When are you arriving?", "adverb"],
      ["helfen", "to help", "Kannst du mir helfen?", "Can you help me?", "verb"],
      ["fragen", "to ask", "Darf ich dich etwas fragen?", "May I ask you something?", "verb"],
      ["antworten", "to answer", "Bitte antworte mir schnell.", "Please answer me quickly.", "verb"],
      ["sagen", "to say", "Was hast du gesagt?", "What did you say?", "verb"],
    ],
  },
  {
    title: "Familie & Personen",
    level: CefrLevel.A1,
    description: "Familienmitglieder und Menschen im Alltag beschreiben",
    iconEmoji: "👨‍👩‍👧",
    items: [
      ["die Familie", "family", "Meine Familie ist sehr groß.", "My family is very big.", "noun"],
      ["die Mutter", "mother", "Meine Mutter kocht sehr gut.", "My mother cooks very well.", "noun"],
      ["der Vater", "father", "Mein Vater arbeitet in einer Bank.", "My father works at a bank.", "noun"],
      ["die Eltern", "parents", "Meine Eltern wohnen in München.", "My parents live in Munich.", "noun"],
      ["der Sohn", "son", "Ihr Sohn geht schon zur Schule.", "Her son already goes to school.", "noun"],
      ["die Tochter", "daughter", "Seine Tochter ist drei Jahre alt.", "His daughter is three years old.", "noun"],
      ["der Bruder", "brother", "Mein Bruder spielt Fußball.", "My brother plays football.", "noun"],
      ["die Schwester", "sister", "Meine Schwester studiert Medizin.", "My sister studies medicine.", "noun"],
      ["die Großmutter", "grandmother", "Meine Großmutter backt gern Kuchen.", "My grandmother likes to bake cakes.", "noun"],
      ["der Großvater", "grandfather", "Mein Großvater liest jeden Tag Zeitung.", "My grandfather reads the newspaper every day.", "noun"],
      ["die Großeltern", "grandparents", "Am Wochenende besuchen wir die Großeltern.", "On the weekend we visit our grandparents.", "noun"],
      ["der Onkel", "uncle", "Mein Onkel wohnt in Hamburg.", "My uncle lives in Hamburg.", "noun"],
      ["die Tante", "aunt", "Meine Tante arbeitet als Ärztin.", "My aunt works as a doctor.", "noun"],
      ["der Cousin", "male cousin", "Mein Cousin ist genauso alt wie ich.", "My cousin is the same age as me.", "noun"],
      ["die Cousine", "female cousin", "Meine Cousine wohnt in Wien.", "My cousin lives in Vienna.", "noun"],
      ["der Ehemann", "husband", "Ihr Ehemann kocht heute Abend.", "Her husband is cooking tonight.", "noun"],
      ["die Ehefrau", "wife", "Sein Ehefrau arbeitet als Lehrerin.", "His wife works as a teacher.", "noun"],
      ["das Baby", "baby", "Das Baby schläft im Kinderwagen.", "The baby is sleeping in the stroller.", "noun"],
      ["der Junge", "boy", "Der Junge spielt mit dem Ball.", "The boy is playing with the ball.", "noun"],
      ["das Mädchen", "girl", "Das Mädchen malt ein Bild.", "The girl is painting a picture.", "noun"],
      ["die Person", "person", "Diese Person kenne ich nicht.", "I do not know this person.", "noun"],
      ["die Leute", "people", "Viele Leute warten am Bahnhof.", "Many people are waiting at the station.", "noun"],
      ["der Nachbar", "neighbor", "Unser Nachbar ist sehr freundlich.", "Our neighbor is very friendly.", "noun"],
      ["der Kollege", "colleague", "Mein Kollege hilft mir oft.", "My colleague often helps me.", "noun"],
      ["der Chef", "boss", "Der Chef ist heute nicht im Büro.", "The boss is not in the office today.", "noun"],
      ["der Lehrer", "teacher", "Der Lehrer erklärt die Aufgabe.", "The teacher explains the task.", "noun"],
      ["der Schüler", "pupil", "Der Schüler macht seine Hausaufgaben.", "The pupil is doing his homework.", "noun"],
      ["der Arzt", "doctor", "Der Arzt untersucht den Patienten.", "The doctor examines the patient.", "noun"],
      ["die Krankenschwester", "nurse", "Die Krankenschwester ist sehr geduldig.", "The nurse is very patient.", "noun"],
      ["der Polizist", "police officer", "Der Polizist hilft dem alten Mann.", "The police officer helps the old man.", "noun"],
      ["verheiratet", "married", "Meine Schwester ist verheiratet.", "My sister is married.", "adjective"],
      ["ledig", "single", "Er ist noch ledig.", "He is still single.", "adjective"],
      ["geschieden", "divorced", "Meine Eltern sind geschieden.", "My parents are divorced.", "adjective"],
      ["das Geburtsdatum", "date of birth", "Wie lautet dein Geburtsdatum?", "What is your date of birth?", "noun"],
      ["geboren", "born", "Ich bin in Köln geboren.", "I was born in Cologne.", "adjective"],
      ["leben", "to live", "Sie lebt seit Jahren in Berlin.", "She has lived in Berlin for years.", "verb"],
      ["sterben", "to die", "Der alte Hund ist letzte Woche gestorben.", "The old dog died last week.", "verb"],
      ["lieben", "to love", "Ich liebe meine Familie.", "I love my family.", "verb"],
      ["mögen", "to like", "Ich mag klassische Musik.", "I like classical music.", "verb"],
      ["kennen", "to know (a person)", "Kennst du meine Schwester?", "Do you know my sister?", "verb"],
      ["treffen", "to meet", "Wir treffen uns um sechs Uhr.", "We are meeting at six o'clock.", "verb"],
      ["besuchen", "to visit", "Ich besuche meine Oma am Sonntag.", "I am visiting my grandma on Sunday.", "verb"],
      ["das Foto", "photo", "Das Foto zeigt die ganze Familie.", "The photo shows the whole family.", "noun"],
      ["das Gesicht", "face", "Sie hat ein freundliches Gesicht.", "She has a friendly face.", "noun"],
      ["die Augen", "eyes", "Er hat blaue Augen.", "He has blue eyes.", "noun"],
      ["die Haare", "hair", "Sie hat lange braune Haare.", "She has long brown hair.", "noun"],
      ["groß", "tall, big", "Mein Bruder ist sehr groß.", "My brother is very tall.", "adjective"],
      ["klein", "small", "Das Baby hat kleine Hände.", "The baby has small hands.", "adjective"],
      ["schön", "beautiful", "Das ist ein schönes Foto.", "That is a beautiful photo.", "adjective"],
      ["nett", "nice", "Deine Freunde sind sehr nett.", "Your friends are very nice.", "adjective"],
    ],
  },
  {
    title: "Zahlen & Zeit",
    level: CefrLevel.A1,
    description: "Zahlen, Uhrzeit, Wochentage und Monate",
    iconEmoji: "🕐",
    items: [
      ["eins", "one", "Ich habe nur eine Schwester.", "I only have one sister.", "numeral"],
      ["zwei", "two", "Wir brauchen zwei Tickets.", "We need two tickets.", "numeral"],
      ["drei", "three", "Das Baby ist drei Monate alt.", "The baby is three months old.", "numeral"],
      ["vier", "four", "Der Tisch hat vier Stühle.", "The table has four chairs.", "numeral"],
      ["fünf", "five", "Ich stehe um fünf Uhr auf.", "I get up at five o'clock.", "numeral"],
      ["sechs", "six", "Die Schule beginnt um sechs Uhr.", "School starts at six o'clock.", "numeral"],
      ["sieben", "seven", "Eine Woche hat sieben Tage.", "A week has seven days.", "numeral"],
      ["acht", "eight", "Ich arbeite acht Stunden am Tag.", "I work eight hours a day.", "numeral"],
      ["neun", "nine", "Der Film beginnt um neun Uhr.", "The movie starts at nine o'clock.", "numeral"],
      ["zehn", "ten", "Ich zähle bis zehn.", "I count to ten.", "numeral"],
      ["elf", "eleven", "Sie kommt um elf Uhr an.", "She arrives at eleven o'clock.", "numeral"],
      ["zwölf", "twelve", "Um zwölf Uhr essen wir Mittag.", "At twelve o'clock we have lunch.", "numeral"],
      ["zwanzig", "twenty", "Ich bin zwanzig Jahre alt.", "I am twenty years old.", "numeral"],
      ["dreißig", "thirty", "Die Fahrt dauert dreißig Minuten.", "The trip takes thirty minutes.", "numeral"],
      ["hundert", "hundred", "Das kostet hundert Euro.", "That costs a hundred euros.", "numeral"],
      ["tausend", "thousand", "Die Stadt hat tausend Einwohner.", "The town has a thousand inhabitants.", "numeral"],
      ["die Uhr", "clock, watch", "Die Uhr an der Wand geht falsch.", "The clock on the wall is wrong.", "noun"],
      ["die Uhrzeit", "time of day", "Wie spät ist es, welche Uhrzeit haben wir?", "What time is it?", "noun"],
      ["die Stunde", "hour", "Der Unterricht dauert eine Stunde.", "The lesson lasts one hour.", "noun"],
      ["die Minute", "minute", "Warte bitte fünf Minuten.", "Please wait five minutes.", "noun"],
      ["die Sekunde", "second", "Eine Minute hat sechzig Sekunden.", "A minute has sixty seconds.", "noun"],
      ["die Woche", "week", "Ich arbeite fünf Tage pro Woche.", "I work five days a week.", "noun"],
      ["der Monat", "month", "Der Kurs dauert einen Monat.", "The course lasts one month.", "noun"],
      ["das Jahr", "year", "Nächstes Jahr reise ich nach Italien.", "Next year I am traveling to Italy.", "noun"],
      ["Montag", "Monday", "Am Montag beginnt die Arbeit wieder.", "On Monday work starts again.", "noun"],
      ["Dienstag", "Tuesday", "Am Dienstag habe ich Deutschkurs.", "On Tuesday I have German class.", "noun"],
      ["Mittwoch", "Wednesday", "Mittwoch ist die Mitte der Woche.", "Wednesday is the middle of the week.", "noun"],
      ["Donnerstag", "Thursday", "Am Donnerstag gehe ich einkaufen.", "On Thursday I go shopping.", "noun"],
      ["Freitag", "Friday", "Freitag ist mein Lieblingstag.", "Friday is my favorite day.", "noun"],
      ["Samstag", "Saturday", "Am Samstag schlafe ich lange.", "On Saturday I sleep in.", "noun"],
      ["Sonntag", "Sunday", "Sonntag ist ein ruhiger Tag.", "Sunday is a quiet day.", "noun"],
      ["Januar", "January", "Im Januar ist es sehr kalt.", "In January it is very cold.", "noun"],
      ["Februar", "February", "Mein Geburtstag ist im Februar.", "My birthday is in February.", "noun"],
      ["der Frühling", "spring", "Im Frühling blühen die Blumen.", "In spring the flowers bloom.", "noun"],
      ["der Sommer", "summer", "Der Sommer ist meine Lieblingsjahreszeit.", "Summer is my favorite season.", "noun"],
      ["der Herbst", "autumn", "Im Herbst fallen die Blätter.", "In autumn the leaves fall.", "noun"],
      ["der Winter", "winter", "Im Winter schneit es oft.", "In winter it often snows.", "noun"],
      ["früh", "early", "Ich stehe immer früh auf.", "I always get up early.", "adjective"],
      ["spät", "late", "Wir kommen leider spät an.", "Unfortunately we are arriving late.", "adjective"],
      ["jetzt", "now", "Ich muss jetzt gehen.", "I have to go now.", "adverb"],
      ["später", "later", "Wir sprechen später darüber.", "We will talk about it later.", "adverb"],
      ["immer", "always", "Er kommt immer pünktlich.", "He always arrives on time.", "adverb"],
      ["nie", "never", "Sie trinkt nie Kaffee.", "She never drinks coffee.", "adverb"],
      ["manchmal", "sometimes", "Manchmal koche ich für die ganze Familie.", "Sometimes I cook for the whole family.", "adverb"],
      ["oft", "often", "Wir gehen oft spazieren.", "We often go for a walk.", "adverb"],
      ["selten", "rarely", "Er ist selten krank.", "He is rarely sick.", "adverb"],
      ["der Kalender", "calendar", "Der Kalender hängt in der Küche.", "The calendar hangs in the kitchen.", "noun"],
      ["das Datum", "date", "Welches Datum haben wir heute?", "What date is it today?", "noun"],
      ["die Pause", "break", "Wir machen jetzt eine kurze Pause.", "We are taking a short break now.", "noun"],
      ["der Termin", "appointment", "Ich habe morgen einen Termin beim Arzt.", "I have an appointment at the doctor's tomorrow.", "noun"],
    ],
  },
  {
    title: "Essen & Trinken",
    level: CefrLevel.A1,
    description: "Lebensmittel, Getränke und der Restaurantbesuch",
    iconEmoji: "🍞",
    items: [
      ["das Brot", "bread", "Ich kaufe jeden Tag frisches Brot.", "I buy fresh bread every day.", "noun"],
      ["die Butter", "butter", "Streich Butter auf das Brot.", "Spread butter on the bread.", "noun"],
      ["der Käse", "cheese", "Ich esse gern Käse mit Brot.", "I like to eat cheese with bread.", "noun"],
      ["die Milch", "milk", "Trinkst du Kaffee mit Milch?", "Do you drink coffee with milk?", "noun"],
      ["das Ei", "egg", "Zum Frühstück esse ich ein Ei.", "For breakfast I eat an egg.", "noun"],
      ["der Zucker", "sugar", "Ich nehme keinen Zucker in den Tee.", "I do not take sugar in my tea.", "noun"],
      ["das Salz", "salt", "Die Suppe braucht mehr Salz.", "The soup needs more salt.", "noun"],
      ["der Reis", "rice", "Wir essen heute Reis mit Gemüse.", "We are eating rice with vegetables today.", "noun"],
      ["die Nudeln", "noodles, pasta", "Die Kinder lieben Nudeln mit Tomatensoße.", "The children love pasta with tomato sauce.", "noun"],
      ["das Fleisch", "meat", "Er isst kein Fleisch mehr.", "He no longer eats meat.", "noun"],
      ["der Fisch", "fish", "Am Freitag gibt es oft Fisch.", "On Fridays there is often fish.", "noun"],
      ["das Gemüse", "vegetables", "Gemüse ist sehr gesund.", "Vegetables are very healthy.", "noun"],
      ["das Obst", "fruit", "Ich esse jeden Tag frisches Obst.", "I eat fresh fruit every day.", "noun"],
      ["der Apfel", "apple", "Ein Apfel liegt auf dem Tisch.", "An apple is lying on the table.", "noun"],
      ["die Banane", "banana", "Die Banane ist schon reif.", "The banana is already ripe.", "noun"],
      ["die Kartoffel", "potato", "Wir kochen Kartoffeln zum Abendessen.", "We are cooking potatoes for dinner.", "noun"],
      ["die Tomate", "tomato", "Der Salat hat viele Tomaten.", "The salad has a lot of tomatoes.", "noun"],
      ["der Kaffee", "coffee", "Ich trinke jeden Morgen Kaffee.", "I drink coffee every morning.", "noun"],
      ["der Tee", "tea", "Möchtest du eine Tasse Tee?", "Would you like a cup of tea?", "noun"],
      ["das Wasser", "water", "Bitte gib mir ein Glas Wasser.", "Please give me a glass of water.", "noun"],
      ["der Saft", "juice", "Der Orangensaft schmeckt sehr gut.", "The orange juice tastes very good.", "noun"],
      ["der Wein", "wine", "Zum Essen trinken wir Wein.", "We drink wine with the meal.", "noun"],
      ["das Bier", "beer", "Er trinkt gern ein kaltes Bier.", "He likes to drink a cold beer.", "noun"],
      ["das Frühstück", "breakfast", "Das Frühstück steht auf dem Tisch.", "Breakfast is on the table.", "noun"],
      ["das Mittagessen", "lunch", "Das Mittagessen ist um zwölf Uhr fertig.", "Lunch is ready at twelve o'clock.", "noun"],
      ["das Abendessen", "dinner", "Was gibt es heute zum Abendessen?", "What is for dinner today?", "noun"],
      ["der Hunger", "hunger", "Ich habe großen Hunger.", "I am very hungry.", "noun"],
      ["der Durst", "thirst", "Nach dem Sport habe ich Durst.", "After sports I am thirsty.", "noun"],
      ["essen", "to eat", "Wir essen jetzt zu Abend.", "We are eating dinner now.", "verb"],
      ["trinken", "to drink", "Kinder sollten viel Wasser trinken.", "Children should drink a lot of water.", "verb"],
      ["kochen", "to cook", "Meine Mutter kocht sehr gerne.", "My mother likes to cook very much.", "verb"],
      ["schmecken", "to taste", "Der Kuchen schmeckt fantastisch.", "The cake tastes fantastic.", "verb"],
      ["lecker", "delicious", "Das Essen im Restaurant war lecker.", "The food at the restaurant was delicious.", "adjective"],
      ["süß", "sweet", "Der Kuchen ist mir zu süß.", "The cake is too sweet for me.", "adjective"],
      ["sauer", "sour", "Die Zitrone ist sehr sauer.", "The lemon is very sour.", "adjective"],
      ["scharf", "spicy", "Das Curry ist mir zu scharf.", "The curry is too spicy for me.", "adjective"],
      ["das Restaurant", "restaurant", "Wir essen heute im Restaurant.", "We are eating at the restaurant today.", "noun"],
      ["die Speisekarte", "menu", "Können wir die Speisekarte haben?", "Can we have the menu?", "noun"],
      ["die Rechnung", "bill", "Die Rechnung, bitte.", "The bill, please.", "noun"],
      ["der Kellner", "waiter", "Der Kellner bringt das Essen.", "The waiter brings the food.", "noun"],
      ["der Teller", "plate", "Der Teller ist schon leer.", "The plate is already empty.", "noun"],
      ["die Tasse", "cup", "Er trinkt Kaffee aus einer großen Tasse.", "He drinks coffee from a big cup.", "noun"],
      ["das Glas", "glass", "Ein Glas Milch, bitte.", "A glass of milk, please.", "noun"],
      ["die Gabel", "fork", "Ich brauche eine Gabel und ein Messer.", "I need a fork and a knife.", "noun"],
      ["das Messer", "knife", "Das Messer ist sehr scharf.", "The knife is very sharp.", "noun"],
      ["der Löffel", "spoon", "Sie isst die Suppe mit einem Löffel.", "She eats the soup with a spoon.", "noun"],
      ["die Serviette", "napkin", "Die Serviette liegt neben dem Teller.", "The napkin is lying next to the plate.", "noun"],
      ["bestellen", "to order", "Ich möchte gern eine Pizza bestellen.", "I would like to order a pizza.", "verb"],
      ["bezahlen", "to pay", "Können wir bitte bezahlen?", "Can we pay, please?", "verb"],
      ["der Supermarkt", "supermarket", "Ich kaufe im Supermarkt ein.", "I shop at the supermarket.", "noun"],
    ],
  },
  {
    title: "Zuhause & Wohnen",
    level: CefrLevel.A1,
    description: "Wohnung, Möbel und das Zuhause beschreiben",
    iconEmoji: "🏠",
    items: [
      ["das Haus", "house", "Wir wohnen in einem kleinen Haus.", "We live in a small house.", "noun"],
      ["die Wohnung", "apartment", "Die Wohnung hat drei Zimmer.", "The apartment has three rooms.", "noun"],
      ["das Zimmer", "room", "Mein Zimmer ist sehr hell.", "My room is very bright.", "noun"],
      ["die Küche", "kitchen", "Die Küche ist klein, aber praktisch.", "The kitchen is small but practical.", "noun"],
      ["das Bad", "bathroom", "Das Bad ist neben dem Schlafzimmer.", "The bathroom is next to the bedroom.", "noun"],
      ["das Schlafzimmer", "bedroom", "Im Schlafzimmer steht ein großes Bett.", "There is a big bed in the bedroom.", "noun"],
      ["das Wohnzimmer", "living room", "Wir sitzen abends im Wohnzimmer.", "In the evening we sit in the living room.", "noun"],
      ["der Balkon", "balcony", "Vom Balkon sieht man den Park.", "You can see the park from the balcony.", "noun"],
      ["der Garten", "garden", "Die Kinder spielen im Garten.", "The children are playing in the garden.", "noun"],
      ["die Tür", "door", "Bitte mach die Tür zu.", "Please close the door.", "noun"],
      ["das Fenster", "window", "Mach bitte das Fenster auf.", "Please open the window.", "noun"],
      ["der Tisch", "table", "Das Essen steht auf dem Tisch.", "The food is on the table.", "noun"],
      ["der Stuhl", "chair", "Der Stuhl steht am Fenster.", "The chair is by the window.", "noun"],
      ["das Bett", "bed", "Das Bett ist sehr bequem.", "The bed is very comfortable.", "noun"],
      ["der Schrank", "cupboard, wardrobe", "Die Kleidung liegt im Schrank.", "The clothes are in the wardrobe.", "noun"],
      ["das Sofa", "sofa", "Wir sitzen gern auf dem Sofa.", "We like to sit on the sofa.", "noun"],
      ["die Lampe", "lamp", "Die Lampe steht auf dem Tisch.", "The lamp is on the table.", "noun"],
      ["der Spiegel", "mirror", "Der Spiegel hängt im Bad.", "The mirror hangs in the bathroom.", "noun"],
      ["die Wand", "wall", "An der Wand hängt ein Bild.", "A picture hangs on the wall.", "noun"],
      ["der Boden", "floor", "Der Boden in der Küche ist aus Holz.", "The floor in the kitchen is made of wood.", "noun"],
      ["das Dach", "roof", "Das Dach ist rot.", "The roof is red.", "noun"],
      ["der Schlüssel", "key", "Ich habe meinen Schlüssel verloren.", "I lost my key.", "noun"],
      ["die Adresse", "address", "Wie lautet deine Adresse?", "What is your address?", "noun"],
      ["die Straße", "street", "Wir wohnen in einer ruhigen Straße.", "We live on a quiet street.", "noun"],
      ["die Stadt", "city", "Berlin ist eine große Stadt.", "Berlin is a big city.", "noun"],
      ["das Dorf", "village", "Meine Großeltern wohnen in einem Dorf.", "My grandparents live in a village.", "noun"],
      ["die Miete", "rent", "Die Miete ist jeden Monat fällig.", "The rent is due every month.", "noun"],
      ["der Vermieter", "landlord", "Der Vermieter repariert die Heizung.", "The landlord is repairing the heating.", "noun"],
      ["sauber", "clean", "Die Küche ist immer sauber.", "The kitchen is always clean.", "adjective"],
      ["schmutzig", "dirty", "Meine Schuhe sind ganz schmutzig.", "My shoes are completely dirty.", "adjective"],
      ["aufräumen", "to tidy up", "Ich muss noch mein Zimmer aufräumen.", "I still need to tidy up my room.", "verb"],
      ["putzen", "to clean", "Am Samstag putzen wir die Wohnung.", "On Saturday we clean the apartment.", "verb"],
      ["der Fernseher", "television", "Der Fernseher steht im Wohnzimmer.", "The television is in the living room.", "noun"],
      ["der Kühlschrank", "refrigerator", "Die Milch ist im Kühlschrank.", "The milk is in the refrigerator.", "noun"],
      ["die Waschmaschine", "washing machine", "Die Waschmaschine ist kaputt.", "The washing machine is broken.", "noun"],
      ["der Herd", "stove", "Das Wasser kocht auf dem Herd.", "The water is boiling on the stove.", "noun"],
      ["die Heizung", "heating", "Die Heizung funktioniert nicht.", "The heating is not working.", "noun"],
      ["das Licht", "light", "Bitte mach das Licht an.", "Please turn on the light.", "noun"],
      ["der Strom", "electricity", "Der Strom ist heute Nacht ausgefallen.", "The electricity went out last night.", "noun"],
      ["die Treppe", "stairs", "Die Wohnung ist über die Treppe erreichbar.", "The apartment is reached via the stairs.", "noun"],
      ["der Aufzug", "elevator", "Wir nehmen den Aufzug in den vierten Stock.", "We take the elevator to the fourth floor.", "noun"],
      ["der Keller", "basement", "Die Fahrräder stehen im Keller.", "The bicycles are in the basement.", "noun"],
      ["der Dachboden", "attic", "Alte Möbel stehen auf dem Dachboden.", "Old furniture is in the attic.", "noun"],
      ["die Garage", "garage", "Das Auto steht in der Garage.", "The car is in the garage.", "noun"],
      ["die Möbel", "furniture", "Wir kaufen neue Möbel für die Wohnung.", "We are buying new furniture for the apartment.", "noun"],
      ["der Teppich", "carpet", "Der Teppich liegt im Wohnzimmer.", "The carpet is in the living room.", "noun"],
      ["das Kissen", "pillow, cushion", "Das Kissen ist sehr weich.", "The pillow is very soft.", "noun"],
      ["die Decke", "blanket", "Nachts brauche ich eine warme Decke.", "At night I need a warm blanket.", "noun"],
      ["umziehen", "to move house", "Wir ziehen nächsten Monat um.", "We are moving next month.", "verb"],
      ["die Nachbarschaft", "neighborhood", "Die Nachbarschaft ist sehr ruhig.", "The neighborhood is very quiet.", "noun"],
    ],
  },
];
