import { CefrLevel } from '@prisma/client';

export const GERMAN_VOCAB_C1 = [
  {
    title: 'Wissenschaft & Forschung',
    level: CefrLevel.C1,
    description: 'Wortschatz für wissenschaftliches Arbeiten, Studien und akademische Diskussionen',
    iconEmoji: '🔬',
    items: [
      ['die Erkenntnis', 'insight / finding', 'Die Studie liefert wichtige neue Erkenntnisse.', 'The study provides important new insights.', 'noun'],
      ['die Hypothese', 'hypothesis', 'Die Hypothese konnte nicht bestätigt werden.', 'The hypothesis could not be confirmed.', 'noun'],
      ['erforschen', 'to investigate / research', 'Forscher erforschen die Ursachen des Phänomens.', 'Researchers are investigating the causes of the phenomenon.', 'verb'],
      ['die Fragestellung', 'research question', 'Die Fragestellung der Arbeit ist klar formuliert.', 'The research question of the paper is clearly formulated.', 'noun'],
      ['nachweisen', 'to prove / demonstrate', 'Die Wirkung konnte experimentell nachgewiesen werden.', 'The effect could be demonstrated experimentally.', 'verb'],
      ['der Nachweis', 'proof / evidence', 'Es gibt keinen eindeutigen Nachweis für diese These.', 'There is no clear evidence for this thesis.', 'noun'],
      ['die Stichprobe', 'sample (statistics)', 'Die Stichprobe umfasste tausend Teilnehmer.', 'The sample comprised a thousand participants.', 'noun'],
      ['die Auswertung', 'evaluation / analysis', 'Die Auswertung der Daten dauerte mehrere Monate.', 'The analysis of the data took several months.', 'noun'],
      ['auswerten', 'to evaluate / analyze', 'Die Ergebnisse wurden statistisch ausgewertet.', 'The results were evaluated statistically.', 'verb'],
      ['die Methodik', 'methodology', 'Die Methodik der Studie wird im zweiten Kapitel erläutert.', 'The methodology of the study is explained in the second chapter.', 'noun'],
      ['die Annahme', 'assumption', 'Diese Annahme muss kritisch hinterfragt werden.', 'This assumption needs to be critically questioned.', 'noun'],
      ['zugrunde liegen', 'to underlie', 'Welche Theorie liegt diesem Modell zugrunde?', 'Which theory underlies this model?', 'phrasal verb'],
      ['die Wechselwirkung', 'interaction', 'Die Wechselwirkung zwischen den beiden Faktoren ist komplex.', 'The interaction between the two factors is complex.', 'noun'],
      ['der Widerspruch', 'contradiction', 'Die Ergebnisse stehen im Widerspruch zu früheren Studien.', 'The results contradict earlier studies.', 'noun'],
      ['widersprüchlich', 'contradictory', 'Die Datenlage ist widersprüchlich.', 'The data situation is contradictory.', 'adjective'],
      ['die Signifikanz', 'significance (statistical)', 'Der Unterschied erreichte statistische Signifikanz.', 'The difference reached statistical significance.', 'noun'],
      ['belegen', 'to substantiate / document', 'Die These wird durch zahlreiche Studien belegt.', 'The thesis is substantiated by numerous studies.', 'verb'],
      ['der Beleg', 'evidence / documentation', 'Für diese Behauptung fehlt jeglicher Beleg.', 'There is no evidence whatsoever for this claim.', 'noun'],
      ['die Verallgemeinerung', 'generalization', 'Eine solche Verallgemeinerung ist wissenschaftlich nicht haltbar.', 'Such a generalization is not scientifically tenable.', 'noun'],
      ['verallgemeinern', 'to generalize', 'Man sollte die Ergebnisse nicht vorschnell verallgemeinern.', 'One should not generalize the results prematurely.', 'verb'],
      ['die Fachliteratur', 'specialist literature', 'Die Fachliteratur zu diesem Thema ist umfangreich.', 'The specialist literature on this topic is extensive.', 'noun'],
      ['das Gutachten', 'expert report / assessment', 'Das Gutachten kam zu einem eindeutigen Ergebnis.', 'The expert report came to a clear conclusion.', 'noun'],
      ['begutachten', 'to review / assess', 'Der Aufsatz wurde von zwei Experten begutachtet.', 'The paper was reviewed by two experts.', 'verb'],
      ['die Objektivität', 'objectivity', 'Die Objektivität der Untersuchung wurde angezweifelt.', 'The objectivity of the investigation was questioned.', 'noun'],
      ['voreingenommen', 'biased', 'Der Gutachter wurde als voreingenommen kritisiert.', 'The reviewer was criticized as biased.', 'adjective'],
      ['die Verzerrung', 'bias / distortion', 'Eine systematische Verzerrung beeinflusste die Ergebnisse.', 'A systematic bias influenced the results.', 'noun'],
      ['der Zusammenhang', 'correlation / context', 'Es besteht ein enger Zusammenhang zwischen beiden Größen.', 'There is a close correlation between both variables.', 'noun'],
      ['kausal', 'causal', 'Ein kausaler Zusammenhang ließ sich nicht nachweisen.', 'A causal connection could not be proven.', 'adjective'],
      ['die Kausalität', 'causality', 'Korrelation bedeutet nicht zwangsläufig Kausalität.', 'Correlation does not necessarily imply causality.', 'noun'],
      ['empirisch', 'empirical', 'Die Theorie stützt sich auf empirische Daten.', 'The theory is based on empirical data.', 'adjective'],
      ['theoretisch fundiert', 'theoretically grounded', 'Das Modell ist theoretisch fundiert.', 'The model is theoretically grounded.', 'phrase'],
      ['die Plausibilität', 'plausibility', 'Die Plausibilität der Erklärung wurde infrage gestellt.', 'The plausibility of the explanation was called into question.', 'noun'],
      ['plausibel', 'plausible', 'Diese Erklärung erscheint durchaus plausibel.', 'This explanation seems quite plausible.', 'adjective'],
      ['die Publikation', 'publication', 'Die Publikation erschien in einer angesehenen Fachzeitschrift.', 'The publication appeared in a renowned journal.', 'noun'],
      ['veröffentlichen', 'to publish', 'Die Ergebnisse wurden erst kürzlich veröffentlicht.', 'The results were only recently published.', 'verb'],
      ['der Forschungsstand', 'state of research', 'Der aktuelle Forschungsstand wird im Überblick dargestellt.', 'The current state of research is outlined.', 'noun'],
      ['die Fördermittel', 'research funding', 'Für das Projekt wurden umfangreiche Fördermittel bewilligt.', 'Extensive research funding was approved for the project.', 'noun'],
      ['interdisziplinär', 'interdisciplinary', 'Das Projekt verfolgt einen interdisziplinären Ansatz.', 'The project pursues an interdisciplinary approach.', 'adjective'],
      ['der Ansatz', 'approach', 'Der neue Ansatz eröffnet vielversprechende Perspektiven.', 'The new approach opens up promising perspectives.', 'noun'],
      ['die Herangehensweise', 'approach / method', 'Ihre Herangehensweise unterscheidet sich grundlegend von der üblichen.', 'Her approach differs fundamentally from the usual one.', 'noun'],
      ['die Erhebung', 'survey / collection of data', 'Die Erhebung der Daten erfolgte anonym.', 'The data collection was carried out anonymously.', 'noun'],
      ['erheben', 'to collect / raise', 'Die Daten wurden über einen Fragebogen erhoben.', 'The data were collected via a questionnaire.', 'verb'],
      ['die Reproduzierbarkeit', 'reproducibility', 'Die Reproduzierbarkeit der Ergebnisse ist entscheidend.', 'The reproducibility of the results is crucial.', 'noun'],
      ['die Falsifizierbarkeit', 'falsifiability', 'Falsifizierbarkeit gilt als Kriterium wissenschaftlicher Theorien.', 'Falsifiability is considered a criterion of scientific theories.', 'noun'],
      ['widerlegen', 'to refute', 'Die These wurde durch neue Befunde widerlegt.', 'The thesis was refuted by new findings.', 'verb'],
      ['die Widerlegung', 'refutation', 'Eine überzeugende Widerlegung steht noch aus.', 'A convincing refutation is still pending.', 'noun'],
      ['bestätigen', 'to confirm', 'Die Folgestudie bestätigte die ursprünglichen Befunde.', 'The follow-up study confirmed the original findings.', 'verb'],
      ['der Befund', 'finding', 'Die Befunde stimmen mit früheren Untersuchungen überein.', 'The findings are consistent with previous studies.', 'noun'],
      ['die Modellbildung', 'model building', 'Die Modellbildung stützt sich auf vereinfachende Annahmen.', 'The model building relies on simplifying assumptions.', 'noun'],
      ['schlussfolgern', 'to conclude / infer', 'Daraus lässt sich nicht zwingend schlussfolgern, dass...', 'From this one cannot necessarily conclude that...', 'verb'],
    ],
  },
  {
    title: 'Recht & Verwaltung',
    level: CefrLevel.C1,
    description: 'Wortschatz für Gesetze, Behörden und juristische Zusammenhänge',
    iconEmoji: '⚖️',
    items: [
      ['die Verordnung', 'regulation / ordinance', 'Die neue Verordnung tritt im nächsten Monat in Kraft.', 'The new regulation comes into force next month.', 'noun'],
      ['der Erlass', 'decree', 'Der Erlass wurde vom Ministerium unterzeichnet.', 'The decree was signed by the ministry.', 'noun'],
      ['die Vorschrift', 'regulation / rule', 'Alle Vorschriften müssen eingehalten werden.', 'All regulations must be complied with.', 'noun'],
      ['vorschreiben', 'to prescribe / stipulate', 'Das Gesetz schreibt eine schriftliche Kündigung vor.', 'The law stipulates a written notice of termination.', 'verb'],
      ['die Zuständigkeit', 'jurisdiction / responsibility', 'Für diesen Fall liegt die Zuständigkeit beim Landgericht.', 'Jurisdiction for this case lies with the regional court.', 'noun'],
      ['zuständig sein', 'to be responsible / in charge', 'Welche Behörde ist dafür zuständig?', 'Which authority is responsible for that?', 'phrase'],
      ['die Behörde', 'authority / agency', 'Der Antrag muss bei der zuständigen Behörde eingereicht werden.', 'The application must be submitted to the responsible authority.', 'noun'],
      ['der Bescheid', 'official notice / ruling', 'Der Bescheid wurde per Post zugestellt.', 'The official notice was delivered by mail.', 'noun'],
      ['die Genehmigung', 'permit / approval', 'Ohne Genehmigung darf nicht gebaut werden.', 'Construction may not proceed without a permit.', 'noun'],
      ['genehmigen', 'to approve / authorize', 'Der Antrag wurde schließlich genehmigt.', 'The application was finally approved.', 'verb'],
      ['die Klage', 'lawsuit', 'Er reichte Klage gegen seinen früheren Arbeitgeber ein.', 'He filed a lawsuit against his former employer.', 'noun'],
      ['klagen', 'to sue / file a lawsuit', 'Sie will vor Gericht klagen.', 'She wants to sue in court.', 'verb'],
      ['der Anspruch', 'claim / entitlement', 'Sie hat Anspruch auf Schadensersatz.', 'She is entitled to compensation.', 'noun'],
      ['beanspruchen', 'to claim / demand', 'Er beansprucht sein Erbe.', 'He is claiming his inheritance.', 'verb'],
      ['die Haftung', 'liability', 'Die Haftung des Herstellers ist gesetzlich geregelt.', "The manufacturer's liability is regulated by law.", 'noun'],
      ['haften', 'to be liable', 'Der Betreiber haftet für entstandene Schäden.', 'The operator is liable for damages incurred.', 'verb'],
      ['der Vertrag', 'contract', 'Beide Parteien haben den Vertrag unterschrieben.', 'Both parties have signed the contract.', 'noun'],
      ['die Vertragsklausel', 'contract clause', 'Diese Vertragsklausel ist rechtlich umstritten.', 'This contract clause is legally disputed.', 'noun'],
      ['kündigen', 'to terminate / give notice', 'Der Mieter hat fristgerecht gekündigt.', 'The tenant gave notice within the deadline.', 'verb'],
      ['die Frist', 'deadline / time limit', 'Die Frist zur Einreichung läuft in zwei Wochen ab.', 'The submission deadline expires in two weeks.', 'noun'],
      ['fristgerecht', 'within the deadline', 'Der Widerspruch muss fristgerecht eingelegt werden.', 'The objection must be filed within the deadline.', 'adjective'],
      ['der Widerspruch (Rechtsmittel)', 'objection / appeal', 'Gegen den Bescheid kann Widerspruch eingelegt werden.', 'An objection can be filed against the ruling.', 'noun'],
      ['einlegen (Widerspruch)', 'to file (an objection)', 'Er hat rechtzeitig Widerspruch eingelegt.', 'He filed the objection in time.', 'verb'],
      ['das Urteil', 'verdict / judgment', 'Das Urteil ist noch nicht rechtskräftig.', 'The verdict is not yet legally binding.', 'noun'],
      ['rechtskräftig', 'legally binding / final', 'Das Urteil wurde rechtskräftig.', 'The verdict became legally binding.', 'adjective'],
      ['verurteilen', 'to convict / sentence', 'Der Angeklagte wurde zu einer Geldstrafe verurteilt.', 'The defendant was sentenced to a fine.', 'verb'],
      ['der Angeklagte', 'the accused / defendant', 'Der Angeklagte bestritt die Vorwürfe.', 'The defendant denied the allegations.', 'noun'],
      ['die Berufung', 'appeal', 'Der Anwalt legte Berufung gegen das Urteil ein.', 'The lawyer filed an appeal against the verdict.', 'noun'],
      ['der Sachverhalt', 'facts of the case', 'Der Sachverhalt muss noch geklärt werden.', 'The facts of the case still need to be clarified.', 'noun'],
      ['die Vollmacht', 'power of attorney', 'Er handelte in Vollmacht seines Vaters.', 'He acted under power of attorney from his father.', 'noun'],
      ['bevollmächtigen', 'to authorize', 'Sie wurde bevollmächtigt, den Vertrag zu unterzeichnen.', 'She was authorized to sign the contract.', 'verb'],
      ['die Verjährung', 'statute of limitations', 'Der Anspruch unterliegt der Verjährung.', 'The claim is subject to the statute of limitations.', 'noun'],
      ['verjähren', 'to become statute-barred', 'Die Forderung ist bereits verjährt.', 'The claim has already become statute-barred.', 'verb'],
      ['die Vollstreckung', 'enforcement', 'Die Vollstreckung des Urteils wurde beantragt.', 'Enforcement of the judgment was requested.', 'noun'],
      ['das Gesetzbuch', 'legal code', 'Der Paragraf steht im Bürgerlichen Gesetzbuch.', 'The paragraph is in the Civil Code.', 'noun'],
      ['der Paragraf', 'section / paragraph (legal)', 'Dieser Paragraf regelt die Kündigungsfristen.', 'This section regulates the notice periods.', 'noun'],
      ['die Gesetzgebung', 'legislation', 'Die aktuelle Gesetzgebung sieht das nicht vor.', 'The current legislation does not provide for this.', 'noun'],
      ['der Gesetzentwurf', 'draft bill', 'Der Gesetzentwurf wurde im Parlament diskutiert.', 'The draft bill was discussed in parliament.', 'noun'],
      ['verabschieden (ein Gesetz)', 'to pass (a law)', 'Das Gesetz wurde einstimmig verabschiedet.', 'The law was passed unanimously.', 'verb'],
      ['die Verfassung', 'constitution', 'Das Grundrecht ist in der Verfassung verankert.', 'The fundamental right is enshrined in the constitution.', 'noun'],
      ['verfassungswidrig', 'unconstitutional', 'Das Gericht erklärte das Gesetz für verfassungswidrig.', 'The court declared the law unconstitutional.', 'adjective'],
      ['die Auflage', 'condition / requirement', 'Die Genehmigung wurde nur unter Auflagen erteilt.', 'The permit was granted only under certain conditions.', 'noun'],
      ['die Zustimmung', 'consent / approval', 'Ohne Zustimmung der Eigentümer geht nichts.', 'Nothing can proceed without the owners’ consent.', 'noun'],
      ['zustimmen', 'to agree / consent', 'Der Vorstand hat dem Vorschlag zugestimmt.', 'The board agreed to the proposal.', 'verb'],
      ['die Verpflichtung', 'obligation', 'Er kam seiner Verpflichtung nicht nach.', 'He did not fulfill his obligation.', 'noun'],
      ['verpflichten', 'to obligate / commit', 'Der Vertrag verpflichtet beide Seiten zur Geheimhaltung.', 'The contract obligates both parties to confidentiality.', 'verb'],
      ['der Vorbehalt', 'reservation / proviso', 'Er stimmte nur unter Vorbehalt zu.', 'He agreed only with reservations.', 'noun'],
      ['die Streitigkeit', 'dispute', 'Streitigkeiten sollen außergerichtlich beigelegt werden.', 'Disputes should be settled out of court.', 'noun'],
      ['beilegen (einen Streit)', 'to settle (a dispute)', 'Der Konflikt konnte gütlich beigelegt werden.', 'The conflict could be settled amicably.', 'verb'],
      ['die Instanz', 'legal instance / court level', 'Der Fall ging in die nächste Instanz.', 'The case went to the next instance.', 'noun'],
    ],
  },
  {
    title: 'Philosophie & Abstraktes Denken',
    level: CefrLevel.C1,
    description: 'Begriffe für philosophische Konzepte und abstrakte Überlegungen',
    iconEmoji: '💭',
    items: [
      ['die Erkenntnistheorie', 'epistemology', 'Die Erkenntnistheorie fragt, wie Wissen überhaupt möglich ist.', 'Epistemology asks how knowledge is possible at all.', 'noun'],
      ['das Bewusstsein', 'consciousness', 'Das menschliche Bewusstsein bleibt ein Rätsel der Wissenschaft.', 'Human consciousness remains a mystery to science.', 'noun'],
      ['die Wahrnehmung', 'perception', 'Unsere Wahrnehmung der Wirklichkeit ist subjektiv geprägt.', 'Our perception of reality is shaped subjectively.', 'noun'],
      ['wahrnehmen', 'to perceive', 'Jeder Mensch nimmt die Welt anders wahr.', 'Every person perceives the world differently.', 'verb'],
      ['die Vernunft', 'reason', 'Die Vernunft sollte über die Gefühle siegen.', 'Reason should prevail over emotions.', 'noun'],
      ['vernünftig', 'reasonable / rational', 'Das ist eine durchaus vernünftige Entscheidung.', 'That is a thoroughly reasonable decision.', 'adjective'],
      ['die Existenz', 'existence', 'Die Frage nach der Existenz Gottes beschäftigt Philosophen seit Jahrtausenden.', 'The question of the existence of God has occupied philosophers for millennia.', 'noun'],
      ['das Wesen', 'essence / nature', 'Was ist das Wesen des Menschen?', 'What is the essence of humankind?', 'noun'],
      ['die Moral', 'morality', 'Seine Moral steht außer Frage.', 'His morality is beyond question.', 'noun'],
      ['die Ethik', 'ethics', 'Die Ethik befasst sich mit Fragen von Gut und Böse.', 'Ethics deals with questions of good and evil.', 'noun'],
      ['der Grundsatz', 'principle', 'Dieser Grundsatz gilt für alle Bereiche des Lebens.', 'This principle applies to all areas of life.', 'noun'],
      ['die Weltanschauung', 'worldview', 'Ihre Weltanschauung hat sich im Laufe der Jahre gewandelt.', 'Her worldview has changed over the years.', 'noun'],
      ['das Paradox', 'paradox', 'Das Paradox lässt sich nur schwer auflösen.', 'The paradox is difficult to resolve.', 'noun'],
      ['paradox', 'paradoxical', 'Es klingt paradox, ist aber wahr.', 'It sounds paradoxical, but it is true.', 'adjective'],
      ['die Widersprüchlichkeit', 'inconsistency / contradictoriness', 'Die Widersprüchlichkeit seiner Argumente fiel schnell auf.', 'The inconsistency of his arguments was quickly noticed.', 'noun'],
      ['die Abstraktion', 'abstraction', 'Diese Theorie erfordert ein hohes Maß an Abstraktion.', 'This theory requires a high degree of abstraction.', 'noun'],
      ['abstrahieren', 'to abstract', 'Man muss von Einzelfällen abstrahieren, um Muster zu erkennen.', 'One must abstract from individual cases to recognize patterns.', 'verb'],
      ['der Begriff', 'concept / term', 'Der Begriff der Freiheit ist schwer zu definieren.', 'The concept of freedom is difficult to define.', 'noun'],
      ['die Denkweise', 'way of thinking', 'Seine Denkweise unterscheidet sich stark von meiner.', 'His way of thinking differs greatly from mine.', 'noun'],
      ['reflektieren', 'to reflect (on)', 'Sie reflektiert regelmäßig über ihr eigenes Handeln.', 'She regularly reflects on her own actions.', 'verb'],
      ['die Reflexion', 'reflection', 'Kritische Reflexion ist ein Zeichen von Reife.', 'Critical reflection is a sign of maturity.', 'noun'],
      ['der Zweifel', 'doubt', 'An seinen Motiven besteht kein Zweifel.', 'There is no doubt about his motives.', 'noun'],
      ['bezweifeln', 'to doubt', 'Ich bezweifle, dass diese Methode funktioniert.', 'I doubt that this method works.', 'verb'],
      ['die Gewissheit', 'certainty', 'Absolute Gewissheit gibt es in der Philosophie kaum.', 'Absolute certainty hardly exists in philosophy.', 'noun'],
      ['gewiss', 'certain', 'Eines ist gewiss: Die Zeit vergeht.', 'One thing is certain: time passes.', 'adjective'],
      ['die Willensfreiheit', 'free will', 'Die Debatte über die Willensfreiheit ist bis heute nicht entschieden.', 'The debate about free will remains unresolved to this day.', 'noun'],
      ['determiniert', 'determined (philosophy)', 'Ist unser Verhalten vollständig determiniert?', 'Is our behavior completely determined?', 'adjective'],
      ['der Sinn (des Lebens)', 'meaning (of life)', 'Viele Menschen suchen nach dem Sinn ihres Lebens.', 'Many people search for the meaning of their lives.', 'noun'],
      ['sinnlos', 'meaningless / pointless', 'Ohne Ziel erscheint ihm alles sinnlos.', 'Without a goal, everything seems meaningless to him.', 'adjective'],
      ['die Vergänglichkeit', 'transience / impermanence', 'Die Vergänglichkeit des Lebens beschäftigt viele Dichter.', 'The transience of life occupies many poets.', 'noun'],
      ['vergänglich', 'transient', 'Schönheit ist vergänglich.', 'Beauty is transient.', 'adjective'],
      ['das Ideal', 'ideal', 'Er strebt nach einem hohen Ideal.', 'He strives for a high ideal.', 'noun'],
      ['idealisieren', 'to idealize', 'Man sollte die Vergangenheit nicht idealisieren.', 'One should not idealize the past.', 'verb'],
      ['die Utopie', 'utopia', 'Eine gerechte Gesellschaft bleibt für viele eine Utopie.', 'A just society remains a utopia for many.', 'noun'],
      ['utopisch', 'utopian', 'Seine Pläne wirken ziemlich utopisch.', 'His plans seem quite utopian.', 'adjective'],
      ['die Dialektik', 'dialectic', 'Die Dialektik von These und Antithese führt zur Synthese.', 'The dialectic of thesis and antithesis leads to synthesis.', 'noun'],
      ['der Widerspruchsgeist', 'contrarian spirit', 'Sein Widerspruchsgeist macht Diskussionen mit ihm anstrengend.', 'His contrarian spirit makes discussions with him tiring.', 'noun'],
      ['die Subjektivität', 'subjectivity', 'Die Subjektivität der Wahrnehmung ist unbestritten.', 'The subjectivity of perception is undisputed.', 'noun'],
      ['objektiv', 'objective', 'Ein objektives Urteil ist hier kaum möglich.', 'An objective judgment is hardly possible here.', 'adjective'],
      ['die Immanenz', 'immanence', 'Der Begriff der Immanenz spielt in dieser Theorie eine zentrale Rolle.', 'The concept of immanence plays a central role in this theory.', 'noun'],
      ['transzendent', 'transcendent', 'Manche Denker suchen nach etwas Transzendentem.', 'Some thinkers search for something transcendent.', 'adjective'],
      ['die Selbstverwirklichung', 'self-actualization', 'Für sie ist Selbstverwirklichung wichtiger als Geld.', 'For her, self-actualization is more important than money.', 'noun'],
      ['das Streben', 'striving / pursuit', 'Das Streben nach Glück treibt viele Menschen an.', 'The pursuit of happiness drives many people.', 'noun'],
      ['streben (nach)', 'to strive (for)', 'Er strebt nach Anerkennung.', 'He strives for recognition.', 'verb'],
      ['die Erkenntnisgrenze', 'limit of knowledge', 'Es gibt eine Erkenntnisgrenze, die Wissenschaft nicht überwinden kann.', 'There is a limit of knowledge that science cannot overcome.', 'noun'],
      ['das Dilemma', 'dilemma', 'Sie steckt in einem moralischen Dilemma.', 'She is caught in a moral dilemma.', 'noun'],
      ['die Konsequenz (Folgerichtigkeit)', 'consistency / logical consequence', 'Seine Argumentation überzeugt durch ihre Konsequenz.', 'His argumentation is convincing due to its consistency.', 'noun'],
      ['nachvollziehbar', 'comprehensible / understandable', 'Seine Beweggründe sind durchaus nachvollziehbar.', "His motives are entirely understandable.", 'adjective'],
      ['die Denkfigur', 'conceptual pattern / figure of thought', 'Diese Denkfigur taucht in vielen philosophischen Texten auf.', 'This conceptual pattern appears in many philosophical texts.', 'noun'],
      ['hinterfragen', 'to question / scrutinize', 'Man sollte gängige Annahmen kritisch hinterfragen.', 'One should critically question common assumptions.', 'verb'],
    ],
  },
  {
    title: 'Wirtschaft & Finanzen',
    level: CefrLevel.C1,
    description: 'Vokabular für Märkte, Unternehmen und finanzielle Zusammenhänge',
    iconEmoji: '📈',
    items: [
      ['die Konjunktur', 'economic situation / cycle', 'Die Konjunktur zeigt erste Anzeichen einer Erholung.', 'The economy is showing early signs of recovery.', 'noun'],
      ['der Aufschwung', 'upturn / boom', 'Der wirtschaftliche Aufschwung hält weiter an.', 'The economic upturn continues.', 'noun'],
      ['der Abschwung', 'downturn', 'Ein Abschwung der Weltwirtschaft wird befürchtet.', 'A downturn in the global economy is feared.', 'noun'],
      ['die Rezession', 'recession', 'Das Land steckt in einer tiefen Rezession.', 'The country is in a deep recession.', 'noun'],
      ['die Inflation', 'inflation', 'Die Inflation treibt die Preise in die Höhe.', 'Inflation is driving prices up.', 'noun'],
      ['die Geldpolitik', 'monetary policy', 'Die Zentralbank hat ihre Geldpolitik gelockert.', 'The central bank has eased its monetary policy.', 'noun'],
      ['der Leitzins', 'key interest rate', 'Die Notenbank hob den Leitzins erneut an.', 'The central bank raised the key interest rate again.', 'noun'],
      ['die Rendite', 'return / yield', 'Die Anleihe bietet eine attraktive Rendite.', 'The bond offers an attractive yield.', 'noun'],
      ['investieren', 'to invest', 'Das Unternehmen investiert massiv in neue Technologien.', 'The company is investing heavily in new technologies.', 'verb'],
      ['die Investition', 'investment', 'Die Investition hat sich langfristig gelohnt.', 'The investment paid off in the long run.', 'noun'],
      ['der Umsatz', 'revenue / turnover', 'Der Umsatz stieg im letzten Quartal deutlich.', 'Revenue rose significantly in the last quarter.', 'noun'],
      ['der Gewinn', 'profit', 'Das Unternehmen konnte seinen Gewinn verdoppeln.', 'The company was able to double its profit.', 'noun'],
      ['der Verlust', 'loss', 'Der Konzern verzeichnete einen erheblichen Verlust.', 'The corporation recorded a considerable loss.', 'noun'],
      ['die Bilanz', 'balance sheet', 'Die Bilanz weist rote Zahlen auf.', 'The balance sheet shows a deficit.', 'noun'],
      ['bilanzieren', 'to balance the books / assess', 'Nach zehn Jahren lässt sich positiv bilanzieren.', 'After ten years, the assessment is positive.', 'verb'],
      ['die Insolvenz', 'insolvency / bankruptcy', 'Das Unternehmen musste Insolvenz anmelden.', 'The company had to file for insolvency.', 'noun'],
      ['der Konkurs', 'bankruptcy', 'Die Firma ging in den Konkurs.', 'The firm went bankrupt.', 'noun'],
      ['die Fusion', 'merger', 'Die Fusion der beiden Konzerne steht kurz bevor.', 'The merger of the two corporations is imminent.', 'noun'],
      ['fusionieren', 'to merge', 'Die zwei Banken haben fusioniert.', 'The two banks have merged.', 'verb'],
      ['die Übernahme', 'takeover / acquisition', 'Die Übernahme wurde von den Aktionären genehmigt.', 'The takeover was approved by the shareholders.', 'noun'],
      ['übernehmen (Firma)', 'to take over (a company)', 'Der Konzern übernahm den kleineren Wettbewerber.', 'The corporation took over the smaller competitor.', 'verb'],
      ['der Wettbewerb', 'competition', 'Der Wettbewerb in der Branche hat sich verschärft.', 'Competition in the industry has intensified.', 'noun'],
      ['wettbewerbsfähig', 'competitive', 'Das Unternehmen bleibt international wettbewerbsfähig.', 'The company remains internationally competitive.', 'adjective'],
      ['der Marktanteil', 'market share', 'Der Marktanteil wuchs auf über zwanzig Prozent.', 'Market share grew to over twenty percent.', 'noun'],
      ['die Nachfrage', 'demand', 'Die Nachfrage nach dem Produkt übersteigt das Angebot.', 'Demand for the product exceeds supply.', 'noun'],
      ['das Angebot', 'supply / offer', 'Angebot und Nachfrage bestimmen den Preis.', 'Supply and demand determine the price.', 'noun'],
      ['die Verschuldung', 'indebtedness / debt level', 'Die Verschuldung des Staates ist stark gestiegen.', "The state's indebtedness has increased sharply.", 'noun'],
      ['sich verschulden', 'to go into debt', 'Viele Haushalte haben sich hoch verschuldet.', 'Many households have gone deeply into debt.', 'verb'],
      ['die Rücklage', 'reserve (financial)', 'Das Unternehmen bildete Rücklagen für schlechte Zeiten.', 'The company built up reserves for hard times.', 'noun'],
      ['die Abschreibung', 'depreciation / write-off', 'Die Abschreibung mindert den steuerpflichtigen Gewinn.', 'Depreciation reduces the taxable profit.', 'noun'],
      ['abschreiben (steuerlich)', 'to depreciate / write off', 'Die Maschine wird über zehn Jahre abgeschrieben.', 'The machine is depreciated over ten years.', 'verb'],
      ['die Steuerlast', 'tax burden', 'Die Steuerlast für Unternehmen wurde gesenkt.', 'The tax burden for companies was reduced.', 'noun'],
      ['die Subvention', 'subsidy', 'Der Sektor erhält staatliche Subventionen.', 'The sector receives government subsidies.', 'noun'],
      ['subventionieren', 'to subsidize', 'Der Staat subventioniert erneuerbare Energien.', 'The state subsidizes renewable energy.', 'verb'],
      ['der Konsum', 'consumption', 'Der private Konsum stützt die Konjunktur.', 'Private consumption supports the economy.', 'noun'],
      ['die Kaufkraft', 'purchasing power', 'Die Kaufkraft der Verbraucher ist gesunken.', 'Consumer purchasing power has declined.', 'noun'],
      ['die Wertschöpfung', 'value creation', 'Die Wertschöpfung findet zunehmend im Ausland statt.', 'Value creation increasingly takes place abroad.', 'noun'],
      ['die Lieferkette', 'supply chain', 'Die globale Lieferkette wurde stark gestört.', 'The global supply chain was severely disrupted.', 'noun'],
      ['die Diversifizierung', 'diversification', 'Diversifizierung soll das Risiko streuen.', 'Diversification is meant to spread the risk.', 'noun'],
      ['diversifizieren', 'to diversify', 'Das Unternehmen diversifiziert sein Portfolio.', 'The company is diversifying its portfolio.', 'verb'],
      ['der Aktienkurs', 'share price', 'Der Aktienkurs fiel nach der Ankündigung deutlich.', 'The share price fell significantly after the announcement.', 'noun'],
      ['spekulieren', 'to speculate', 'Anleger spekulieren auf steigende Kurse.', 'Investors are speculating on rising prices.', 'verb'],
      ['die Spekulation', 'speculation', 'Die Spekulation trieb den Preis in die Höhe.', 'Speculation drove the price up.', 'noun'],
      ['der Risikofaktor', 'risk factor', 'Die politische Instabilität gilt als Risikofaktor.', 'Political instability is considered a risk factor.', 'noun'],
      ['absichern', 'to hedge / secure', 'Das Unternehmen sichert sich gegen Währungsschwankungen ab.', 'The company hedges against currency fluctuations.', 'verb'],
      ['die Absicherung', 'hedging / safeguard', 'Die Absicherung erfolgt über Terminkontrakte.', 'Hedging is carried out via futures contracts.', 'noun'],
      ['nachhaltig (wirtschaftlich)', 'sustainable (economically)', 'Nachhaltiges Wachstum ist das erklärte Ziel.', 'Sustainable growth is the declared goal.', 'adjective'],
      ['die Rentabilität', 'profitability', 'Die Rentabilität des Projekts wurde infrage gestellt.', "The project's profitability was called into question.", 'noun'],
      ['rentabel', 'profitable', 'Das Geschäftsmodell ist inzwischen rentabel.', 'The business model has become profitable.', 'adjective'],
      ['der Etat', 'budget', 'Der Etat für Werbung wurde deutlich gekürzt.', 'The advertising budget was significantly cut.', 'noun'],
    ],
  },
  {
    title: 'Nuancierte Ausdrucksweise & Redewendungen',
    level: CefrLevel.C1,
    description: 'Feste Wendungen und differenzierte Formulierungen für gewähltes Deutsch',
    iconEmoji: '🗣️',
    items: [
      ['auf den Punkt bringen', 'to put it precisely / hit the nail on the head', 'Sie hat das Problem auf den Punkt gebracht.', 'She put the problem precisely.', 'idiom'],
      ['im Grunde genommen', 'basically / fundamentally', 'Im Grunde genommen hat er recht.', 'Basically, he is right.', 'phrase'],
      ['nicht von der Hand zu weisen', 'not to be dismissed / undeniable', 'Diese Gefahr ist nicht von der Hand zu weisen.', 'This danger cannot be dismissed.', 'idiom'],
      ['den Nagel auf den Kopf treffen', 'to hit the nail on the head', 'Mit dieser Bemerkung hat er den Nagel auf den Kopf getroffen.', 'With that remark, he hit the nail on the head.', 'idiom'],
      ['ins Gewicht fallen', 'to carry weight / matter significantly', 'Dieser Unterschied fällt kaum ins Gewicht.', 'This difference hardly matters.', 'idiom'],
      ['eine Rolle spielen', 'to play a role', 'Geld spielt dabei keine unwesentliche Rolle.', 'Money plays a not insignificant role in this.', 'phrase'],
      ['in Kauf nehmen', 'to accept / put up with', 'Er nahm die Kritik billigend in Kauf.', 'He readily accepted the criticism.', 'idiom'],
      ['sich etwas zu Herzen nehmen', 'to take something to heart', 'Sie hat sich den Ratschlag zu Herzen genommen.', 'She took the advice to heart.', 'idiom'],
      ['unter die Lupe nehmen', 'to scrutinize closely', 'Die Behörde nahm die Bilanzen genau unter die Lupe.', 'The authority scrutinized the balance sheets closely.', 'idiom'],
      ['auf Anhieb', 'right away / at first attempt', 'Die Lösung fand er auf Anhieb.', 'He found the solution right away.', 'phrase'],
      ['im Nachhinein', 'in hindsight', 'Im Nachhinein war die Entscheidung richtig.', 'In hindsight, the decision was correct.', 'phrase'],
      ['gang und gäbe', 'common practice / customary', 'Solche Verzögerungen sind hier gang und gäbe.', 'Such delays are common practice here.', 'idiom'],
      ['einen Wandel durchmachen', 'to undergo a transformation', 'Die Branche hat einen tiefgreifenden Wandel durchgemacht.', 'The industry has undergone a profound transformation.', 'phrase'],
      ['sich etablieren', 'to become established', 'Das Start-up hat sich am Markt etabliert.', 'The start-up has become established in the market.', 'verb'],
      ['maßgeblich', 'decisive / significant', 'Er war maßgeblich an der Entwicklung beteiligt.', 'He was significantly involved in the development.', 'adjective'],
      ['gravierend', 'serious / grave', 'Der Fehler hatte gravierende Folgen.', 'The mistake had serious consequences.', 'adjective'],
      ['erheblich', 'considerable', 'Die Kosten sind erheblich gestiegen.', 'The costs have risen considerably.', 'adjective'],
      ['geradezu', 'downright / practically', 'Seine Reaktion war geradezu übertrieben.', 'His reaction was downright exaggerated.', 'adverb'],
      ['keineswegs', 'by no means', 'Das ist keineswegs sicher.', 'That is by no means certain.', 'adverb'],
      ['allenfalls', 'at most / if anything', 'Das dauert allenfalls eine Stunde.', 'That takes at most an hour.', 'adverb'],
      ['durchaus', 'quite / indeed', 'Das ist durchaus möglich.', 'That is quite possible.', 'adverb'],
      ['gleichwohl', 'nevertheless', 'Er war müde, arbeitete gleichwohl weiter.', 'He was tired, but nevertheless kept working.', 'conjunction'],
      ['nichtsdestotrotz', 'nonetheless', 'Der Plan war riskant, wurde nichtsdestotrotz umgesetzt.', 'The plan was risky but was implemented nonetheless.', 'adverb'],
      ['insofern', 'in that respect / insofar as', 'Insofern hat er nicht ganz unrecht.', "In that respect, he isn't entirely wrong.", 'adverb'],
      ['zumal', 'especially since', 'Er blieb zu Hause, zumal es stark regnete.', 'He stayed home, especially since it was raining heavily.', 'conjunction'],
      ['sofern', 'provided that', 'Sofern nichts dazwischenkommt, treffen wir uns morgen.', 'Provided nothing comes up, we will meet tomorrow.', 'conjunction'],
      ['sofern nicht', 'unless', 'Sofern nicht anders vereinbart, gilt die Standardfrist.', 'Unless agreed otherwise, the standard deadline applies.', 'phrase'],
      ['angesichts', 'in view of / given', 'Angesichts der Umstände war das eine kluge Entscheidung.', 'Given the circumstances, that was a wise decision.', 'preposition'],
      ['ungeachtet', 'regardless of', 'Ungeachtet der Kritik hielt sie an ihrem Plan fest.', 'Regardless of the criticism, she stuck to her plan.', 'preposition'],
      ['infolgedessen', 'as a result', 'Die Nachfrage sank, infolgedessen fielen die Preise.', 'Demand fell, and as a result prices dropped.', 'adverb'],
      ['demzufolge', 'accordingly / consequently', 'Die Lage hat sich verschlechtert, demzufolge sind Maßnahmen nötig.', 'The situation has worsened; accordingly, measures are necessary.', 'adverb'],
      ['bezeichnenderweise', 'tellingly / characteristically', 'Bezeichnenderweise äußerte sich niemand dazu.', 'Tellingly, no one commented on it.', 'adverb'],
      ['bemerkenswerterweise', 'remarkably', 'Bemerkenswerterweise blieb der Erfolg aus.', 'Remarkably, success did not follow.', 'adverb'],
      ['vermeintlich', 'supposed / ostensible', 'Der vermeintliche Vorteil erwies sich als Nachteil.', 'The supposed advantage turned out to be a disadvantage.', 'adjective'],
      ['scheinbar', 'apparently / seemingly', 'Scheinbar hat niemand den Fehler bemerkt.', 'Apparently, no one noticed the mistake.', 'adverb'],
      ['vielmehr', 'rather', 'Es geht nicht um Geld, vielmehr um Prinzipien.', "It's not about money, but rather about principles.", 'adverb'],
      ['zwar ... aber', 'admittedly ... but', 'Er ist zwar jung, aber sehr erfahren.', 'He is admittedly young, but very experienced.', 'phrase'],
      ['einerseits ... andererseits', 'on the one hand ... on the other hand', 'Einerseits ist es riskant, andererseits lohnenswert.', 'On the one hand it is risky, on the other hand rewarding.', 'phrase'],
      ['nicht zuletzt', 'not least', 'Der Erfolg beruht nicht zuletzt auf harter Arbeit.', 'The success is due, not least, to hard work.', 'phrase'],
      ['unter Vorbehalt', 'with reservations / provisionally', 'Die Zahlen gelten unter Vorbehalt.', 'The figures are provisional.', 'phrase'],
      ['im Zuge', 'in the course of', 'Im Zuge der Reform wurden viele Stellen abgebaut.', 'In the course of the reform, many jobs were cut.', 'phrase'],
      ['im Hinblick auf', 'with regard to', 'Im Hinblick auf die Kosten ist Vorsicht geboten.', 'With regard to the costs, caution is advised.', 'phrase'],
      ['in Anbetracht', 'in consideration of', 'In Anbetracht der Lage wurde die Reise verschoben.', 'In consideration of the situation, the trip was postponed.', 'phrase'],
      ['einen Kompromiss eingehen', 'to reach a compromise', 'Beide Seiten mussten einen Kompromiss eingehen.', 'Both sides had to reach a compromise.', 'phrase'],
      ['auf Kosten von', 'at the expense of', 'Der Erfolg ging auf Kosten der Qualität.', 'The success came at the expense of quality.', 'phrase'],
      ['sich einen Reim auf etwas machen', 'to make sense of something', 'Ich kann mir keinen Reim darauf machen.', 'I cannot make any sense of it.', 'idiom'],
      ['die Katze aus dem Sack lassen', 'to let the cat out of the bag', 'Endlich ließ er die Katze aus dem Sack.', 'He finally let the cat out of the bag.', 'idiom'],
      ['jemandem reinen Wein einschenken', 'to be completely honest with someone', 'Er schenkte ihr endlich reinen Wein ein.', 'He was finally completely honest with her.', 'idiom'],
      ['sich aus dem Staub machen', 'to make off / disappear', 'Nach dem Vorfall machte er sich aus dem Staub.', 'After the incident, he made off.', 'idiom'],
      ['ins Rollen bringen', 'to set in motion / get started', 'Der Bericht brachte die Ermittlungen ins Rollen.', 'The report set the investigation in motion.', 'idiom'],
    ],
  },
];
