import { CefrLevel } from '@prisma/client';

/**
 * 250 deutsche Vokabeln für Niveau B2, aufgeteilt in fünf Themen à 50 Wörter.
 * Struktur kompatibel mit `VocabDeckSeed` aus `../seed.ts` (bewusst ohne
 * Import, um keinen Zirkelbezug zu erzeugen).
 */
export const GERMAN_VOCAB_B2 = [
  {
    title: 'Gesellschaft & Politik',
    level: CefrLevel.B2,
    description: 'Wortschatz rund um Politik, Demokratie und gesellschaftliche Themen',
    iconEmoji: '🏛️',
    items: [
      ['die Gesellschaft', 'society', 'Die Gesellschaft verändert sich ständig.', 'Society is constantly changing.', 'noun'],
      ['die Politik', 'politics', 'Er interessiert sich sehr für Politik.', 'He is very interested in politics.', 'noun'],
      ['die Demokratie', 'democracy', 'Deutschland ist eine parlamentarische Demokratie.', 'Germany is a parliamentary democracy.', 'noun'],
      ['die Wahl', 'election', 'Die nächste Wahl findet im Herbst statt.', 'The next election takes place in autumn.', 'noun'],
      ['der Wähler', 'voter', 'Viele Wähler blieben zu Hause.', 'Many voters stayed at home.', 'noun'],
      ['die Partei', 'political party', 'Er ist Mitglied einer kleinen Partei.', 'He is a member of a small party.', 'noun'],
      ['die Regierung', 'government', 'Die Regierung plant eine Steuerreform.', 'The government is planning a tax reform.', 'noun'],
      ['die Opposition', 'opposition', 'Die Opposition kritisiert den Gesetzentwurf scharf.', 'The opposition sharply criticizes the bill.', 'noun'],
      ['das Parlament', 'parliament', 'Das Gesetz wurde im Parlament verabschiedet.', 'The law was passed in parliament.', 'noun'],
      ['der Abgeordnete', 'member of parliament', 'Der Abgeordnete stellte eine kritische Frage.', 'The MP asked a critical question.', 'noun'],
      ['die Gesetzgebung', 'legislation', 'Die Gesetzgebung dauert oft mehrere Jahre.', 'Legislation often takes several years.', 'noun'],
      ['das Gesetz', 'law', 'Dieses Gesetz tritt nächstes Jahr in Kraft.', 'This law comes into force next year.', 'noun'],
      ['die Verfassung', 'constitution', 'Die Verfassung schützt die Grundrechte der Bürger.', "The constitution protects citizens' fundamental rights.", 'noun'],
      ['das Grundrecht', 'fundamental right', 'Meinungsfreiheit ist ein wichtiges Grundrecht.', 'Freedom of speech is an important fundamental right.', 'noun'],
      ['die Meinungsfreiheit', 'freedom of speech', 'Die Meinungsfreiheit ist im Grundgesetz verankert.', 'Freedom of speech is enshrined in the constitution.', 'noun'],
      ['die Pressefreiheit', 'freedom of the press', 'Ohne Pressefreiheit gibt es keine echte Demokratie.', 'Without freedom of the press, there is no real democracy.', 'noun'],
      ['der Bürger', 'citizen', 'Jeder Bürger hat das Recht zu wählen.', 'Every citizen has the right to vote.', 'noun'],
      ['die Staatsbürgerschaft', 'citizenship', 'Sie hat die deutsche Staatsbürgerschaft beantragt.', 'She applied for German citizenship.', 'noun'],
      ['die Integration', 'integration', 'Sprachkurse fördern die Integration von Migranten.', 'Language courses promote the integration of migrants.', 'noun'],
      ['die Migration', 'migration', 'Migration prägt die Geschichte vieler Länder.', 'Migration shapes the history of many countries.', 'noun'],
      ['der Flüchtling', 'refugee', 'Die Stadt hat viele Flüchtlinge aufgenommen.', 'The city has taken in many refugees.', 'noun'],
      ['das Asyl', 'asylum', 'Er hat politisches Asyl beantragt.', 'He applied for political asylum.', 'noun'],
      ['die Toleranz', 'tolerance', 'Toleranz gegenüber anderen Meinungen ist wichtig.', 'Tolerance towards other opinions is important.', 'noun'],
      ['die Diskriminierung', 'discrimination', 'Diskriminierung am Arbeitsplatz ist verboten.', 'Discrimination in the workplace is prohibited.', 'noun'],
      ['die Gleichberechtigung', 'equality', 'Die Gleichberechtigung von Mann und Frau ist noch nicht erreicht.', 'Equality between men and women has not yet been achieved.', 'noun'],
      ['die Gerechtigkeit', 'justice', 'Sie kämpft für soziale Gerechtigkeit.', 'She fights for social justice.', 'noun'],
      ['die Ungleichheit', 'inequality', 'Die soziale Ungleichheit nimmt weiter zu.', 'Social inequality continues to increase.', 'noun'],
      ['die Armut', 'poverty', 'Armut betrifft auch Kinder in reichen Ländern.', 'Poverty also affects children in rich countries.', 'noun'],
      ['der Wohlstand', 'prosperity', 'Der Wohlstand des Landes ist gestiegen.', "The country's prosperity has increased.", 'noun'],
      ['die Solidarität', 'solidarity', 'Die Nachbarn zeigten großartige Solidarität.', 'The neighbors showed great solidarity.', 'noun'],
      ['der Konflikt', 'conflict', 'Der Konflikt eskalierte innerhalb weniger Tage.', 'The conflict escalated within a few days.', 'noun'],
      ['die Demonstration', 'demonstration', 'Tausende nahmen an der Demonstration teil.', 'Thousands took part in the demonstration.', 'noun'],
      ['der Protest', 'protest', 'Der Protest richtete sich gegen die Regierung.', 'The protest was directed against the government.', 'noun'],
      ['die Reform', 'reform', 'Die Reform des Rentensystems wird diskutiert.', 'The reform of the pension system is being discussed.', 'noun'],
      ['der Widerstand', 'resistance', 'Die Bevölkerung leistete friedlichen Widerstand.', 'The population offered peaceful resistance.', 'noun'],
      ['die Verantwortung', 'responsibility', 'Politiker tragen eine große Verantwortung.', 'Politicians bear great responsibility.', 'noun'],
      ['das Engagement', 'commitment', 'Ihr Engagement für den Umweltschutz ist beeindruckend.', 'Her commitment to environmental protection is impressive.', 'noun'],
      ['sich engagieren', 'to get involved', 'Viele Jugendliche engagieren sich politisch.', 'Many young people get politically involved.', 'verb'],
      ['abstimmen', 'to vote (on something)', 'Das Parlament stimmt morgen über das Gesetz ab.', 'Parliament votes on the law tomorrow.', 'verb'],
      ['wählen', 'to elect, to vote', 'Am Sonntag können die Bürger wählen.', 'On Sunday, citizens can vote.', 'verb'],
      ['protestieren', 'to protest', 'Die Studenten protestierten gegen die Studiengebühren.', 'The students protested against tuition fees.', 'verb'],
      ['diskriminieren', 'to discriminate', 'Niemand darf wegen seiner Herkunft diskriminiert werden.', 'No one may be discriminated against because of their origin.', 'verb'],
      ['debattieren', 'to debate', 'Die Abgeordneten debattierten stundenlang.', 'The MPs debated for hours.', 'verb'],
      ['die Debatte', 'debate', 'Die Debatte über Klimapolitik wird hitziger.', 'The debate on climate policy is getting more heated.', 'noun'],
      ['der Kompromiss', 'compromise', 'Am Ende einigten sich beide Seiten auf einen Kompromiss.', 'In the end, both sides agreed on a compromise.', 'noun'],
      ['die Koalition', 'coalition', 'Die Koalition aus drei Parteien hielt fünf Jahre.', 'The coalition of three parties lasted five years.', 'noun'],
      ['der Skandal', 'scandal', 'Der Skandal kostete den Minister sein Amt.', 'The scandal cost the minister his post.', 'noun'],
      ['die Korruption', 'corruption', 'Das Land kämpft seit Jahren gegen Korruption.', 'The country has been fighting corruption for years.', 'noun'],
      ['transparent', 'transparent', 'Die Regierung soll transparenter arbeiten.', 'The government should work more transparently.', 'adjective'],
      ['gesellschaftlich', 'societal, social', 'Der Klimawandel ist eine gesellschaftliche Herausforderung.', 'Climate change is a societal challenge.', 'adjective'],
    ],
  },
  {
    title: 'Umwelt & Nachhaltigkeit',
    level: CefrLevel.B2,
    description: 'Wortschatz zu Klimawandel, Umweltschutz und Nachhaltigkeit',
    iconEmoji: '🌍',
    items: [
      ['die Umwelt', 'environment', 'Wir müssen die Umwelt besser schützen.', 'We need to protect the environment better.', 'noun'],
      ['der Klimawandel', 'climate change', 'Der Klimawandel betrifft die ganze Welt.', 'Climate change affects the whole world.', 'noun'],
      ['die Erderwärmung', 'global warming', 'Die Erderwärmung lässt die Gletscher schmelzen.', 'Global warming is causing glaciers to melt.', 'noun'],
      ['die Nachhaltigkeit', 'sustainability', 'Nachhaltigkeit spielt in der Wirtschaft eine größere Rolle.', 'Sustainability plays a bigger role in the economy.', 'noun'],
      ['nachhaltig', 'sustainable', 'Wir sollten nachhaltiger konsumieren.', 'We should consume more sustainably.', 'adjective'],
      ['der Treibhauseffekt', 'greenhouse effect', 'CO2 verstärkt den Treibhauseffekt.', 'CO2 intensifies the greenhouse effect.', 'noun'],
      ['die Emission', 'emission', 'Die Emissionen müssen drastisch sinken.', 'Emissions must fall drastically.', 'noun'],
      ['das CO2', 'carbon dioxide', 'Bäume speichern große Mengen CO2.', 'Trees store large amounts of CO2.', 'noun'],
      ['die Umweltverschmutzung', 'environmental pollution', 'Die Umweltverschmutzung schadet vielen Tierarten.', 'Environmental pollution harms many animal species.', 'noun'],
      ['der Müll', 'waste, garbage', 'Bitte trenne den Müll richtig.', 'Please sort the waste correctly.', 'noun'],
      ['recyceln', 'to recycle', 'Wir recyceln Glas, Papier und Plastik.', 'We recycle glass, paper, and plastic.', 'verb'],
      ['das Recycling', 'recycling', 'Recycling spart wertvolle Rohstoffe.', 'Recycling saves valuable raw materials.', 'noun'],
      ['die Ressource', 'resource', 'Wasser ist eine begrenzte Ressource.', 'Water is a limited resource.', 'noun'],
      ['erneuerbar', 'renewable', 'Erneuerbare Energien werden immer wichtiger.', 'Renewable energies are becoming increasingly important.', 'adjective'],
      ['die erneuerbare Energie', 'renewable energy', 'Das Land investiert stark in erneuerbare Energie.', 'The country invests heavily in renewable energy.', 'phrase'],
      ['die Solarenergie', 'solar energy', 'Das Dach ist mit Solarenergie ausgestattet.', 'The roof is equipped with solar energy.', 'noun'],
      ['die Windkraft', 'wind power', 'Windkraft liefert einen großen Teil des Stroms.', 'Wind power supplies a large share of the electricity.', 'noun'],
      ['der Klimaschutz', 'climate protection', 'Der Klimaschutz steht ganz oben auf der Agenda.', 'Climate protection is at the top of the agenda.', 'noun'],
      ['die Artenvielfalt', 'biodiversity', 'Die Artenvielfalt im Regenwald ist einzigartig.', 'The biodiversity in the rainforest is unique.', 'noun'],
      ['das Aussterben', 'extinction', 'Das Aussterben vieler Arten schreitet schnell voran.', 'The extinction of many species is progressing rapidly.', 'noun'],
      ['die bedrohte Art', 'endangered species', 'Der Tiger gilt als bedrohte Art.', 'The tiger is considered an endangered species.', 'phrase'],
      ['der Regenwald', 'rainforest', 'Der Regenwald wird für Weideland gerodet.', 'The rainforest is being cleared for pastureland.', 'noun'],
      ['die Abholzung', 'deforestation', 'Die Abholzung zerstört wichtige Lebensräume.', 'Deforestation destroys important habitats.', 'noun'],
      ['die Dürre', 'drought', 'Die anhaltende Dürre zerstörte die Ernte.', 'The persistent drought destroyed the harvest.', 'noun'],
      ['die Überschwemmung', 'flood', 'Die Überschwemmung richtete großen Schaden an.', 'The flood caused great damage.', 'noun'],
      ['der Meeresspiegel', 'sea level', 'Der Meeresspiegel steigt jedes Jahr ein wenig.', 'Sea level rises a little every year.', 'noun'],
      ['schmelzen', 'to melt', 'Die Gletscher schmelzen immer schneller.', 'The glaciers are melting faster and faster.', 'verb'],
      ['der Gletscher', 'glacier', 'Der Gletscher hat stark an Masse verloren.', 'The glacier has lost a lot of mass.', 'noun'],
      ['die Verschmutzung', 'pollution', 'Die Verschmutzung der Flüsse muss aufhören.', 'The pollution of rivers must stop.', 'noun'],
      ['verschmutzen', 'to pollute', 'Fabriken verschmutzen oft die Luft.', 'Factories often pollute the air.', 'verb'],
      ['der Schadstoff', 'pollutant', 'Schadstoffe belasten die Atemluft.', 'Pollutants contaminate the air we breathe.', 'noun'],
      ['die Abgase', 'exhaust fumes', 'Die Abgase der Autos verschmutzen die Städte.', 'Car exhaust fumes pollute the cities.', 'noun'],
      ['der Verbrauch', 'consumption', 'Der Verbrauch von Plastik muss sinken.', 'The consumption of plastic must decrease.', 'noun'],
      ['verbrauchen', 'to consume, use up', 'Die Klimaanlage verbraucht viel Strom.', 'The air conditioner uses a lot of electricity.', 'verb'],
      ['Energie sparen', 'to save energy', 'Man kann leicht Energie sparen.', 'One can easily save energy.', 'phrase'],
      ['die Energiewende', 'energy transition', 'Die Energiewende soll bis 2045 abgeschlossen sein.', 'The energy transition is meant to be completed by 2045.', 'noun'],
      ['das Ökosystem', 'ecosystem', 'Jede Art spielt eine Rolle im Ökosystem.', 'Every species plays a role in the ecosystem.', 'noun'],
      ['die Umweltschutzorganisation', 'environmental protection organization', 'Er arbeitet für eine internationale Umweltschutzorganisation.', 'He works for an international environmental protection organization.', 'noun'],
      ['der Umweltschützer', 'environmentalist', 'Umweltschützer fordern strengere Gesetze.', 'Environmentalists demand stricter laws.', 'noun'],
      ['die Verpackung', 'packaging', 'Zu viel Verpackung landet im Müll.', 'Too much packaging ends up in the trash.', 'noun'],
      ['die Plastiktüte', 'plastic bag', 'Plastiktüten sind in vielen Läden verboten.', 'Plastic bags are banned in many stores.', 'noun'],
      ['der Einwegartikel', 'disposable item', 'Einwegartikel belasten die Umwelt stark.', 'Disposable items place a heavy burden on the environment.', 'noun'],
      ['die Mülltrennung', 'waste separation', 'Die Mülltrennung funktioniert in Deutschland gut.', 'Waste separation works well in Germany.', 'noun'],
      ['der Kompost', 'compost', 'Küchenabfälle landen bei uns auf dem Kompost.', 'Kitchen waste goes onto our compost.', 'noun'],
      ['die CO2-Bilanz', 'carbon footprint', 'Fliegen verschlechtert die persönliche CO2-Bilanz.', 'Flying worsens your personal carbon footprint.', 'noun'],
      ['umweltfreundlich', 'environmentally friendly', 'Wir suchen ein umweltfreundlicheres Verkehrsmittel.', 'We are looking for a more environmentally friendly means of transport.', 'adjective'],
      ['umweltschädlich', 'environmentally harmful', 'Dieses Reinigungsmittel ist umweltschädlich.', 'This cleaning agent is environmentally harmful.', 'adjective'],
      ['der ökologische Fußabdruck', 'ecological footprint', 'Jeder kann seinen ökologischen Fußabdruck verringern.', 'Everyone can reduce their ecological footprint.', 'phrase'],
      ['die Biolandwirtschaft', 'organic farming', 'Die Biolandwirtschaft verzichtet auf chemische Pestizide.', 'Organic farming avoids chemical pesticides.', 'noun'],
      ['bewusst', 'conscious, mindful', 'Sie kauft sehr bewusst und nachhaltig ein.', 'She shops very consciously and sustainably.', 'adjective'],
    ],
  },
  {
    title: 'Wissenschaft & Technik',
    level: CefrLevel.B2,
    description: 'Wortschatz zu Forschung, Technik und Digitalisierung',
    iconEmoji: '🔬',
    items: [
      ['die Wissenschaft', 'science', 'Die Wissenschaft liefert wichtige Erkenntnisse.', 'Science provides important insights.', 'noun'],
      ['der Wissenschaftler', 'scientist', 'Der Wissenschaftler veröffentlichte seine Ergebnisse.', 'The scientist published his results.', 'noun'],
      ['die Forschung', 'research', 'Die Forschung wird großzügig finanziert.', 'The research is generously funded.', 'noun'],
      ['forschen', 'to do research', 'Sie forscht seit Jahren zu erneuerbaren Energien.', 'She has been researching renewable energy for years.', 'verb'],
      ['das Experiment', 'experiment', 'Das Experiment lieferte überraschende Ergebnisse.', 'The experiment yielded surprising results.', 'noun'],
      ['die Studie', 'study', 'Eine neue Studie bestätigt diesen Zusammenhang.', 'A new study confirms this connection.', 'noun'],
      ['die Erkenntnis', 'insight, finding', 'Diese Erkenntnis verändert unser Weltbild.', 'This insight changes our view of the world.', 'noun'],
      ['der Beweis', 'proof', 'Es gibt noch keinen endgültigen Beweis.', 'There is still no final proof.', 'noun'],
      ['beweisen', 'to prove', 'Der Test bewies seine Theorie.', 'The test proved his theory.', 'verb'],
      ['die Hypothese', 'hypothesis', 'Die Hypothese muss noch getestet werden.', 'The hypothesis still needs to be tested.', 'noun'],
      ['die Theorie', 'theory', 'Diese Theorie ist heute weitgehend anerkannt.', 'This theory is now widely accepted.', 'noun'],
      ['die Technik', 'technology, technique', 'Die Technik entwickelt sich rasant weiter.', 'Technology is developing rapidly.', 'noun'],
      ['die Technologie', 'technology', 'Neue Technologien verändern unseren Alltag.', 'New technologies are changing our everyday life.', 'noun'],
      ['die Erfindung', 'invention', 'Das Internet gilt als bahnbrechende Erfindung.', 'The internet is considered a groundbreaking invention.', 'noun'],
      ['erfinden', 'to invent', 'Wer hat eigentlich das Telefon erfunden?', 'Who actually invented the telephone?', 'verb'],
      ['die Entwicklung', 'development', 'Die Entwicklung neuer Impfstoffe dauert lange.', 'The development of new vaccines takes a long time.', 'noun'],
      ['entwickeln', 'to develop', 'Das Team entwickelt eine neue App.', 'The team is developing a new app.', 'verb'],
      ['der Fortschritt', 'progress', 'Der technische Fortschritt verläuft rasant.', 'Technical progress is proceeding rapidly.', 'noun'],
      ['die Innovation', 'innovation', 'Innovation ist der Schlüssel zum Erfolg.', 'Innovation is the key to success.', 'noun'],
      ['innovativ', 'innovative', 'Das Unternehmen gilt als besonders innovativ.', 'The company is considered particularly innovative.', 'adjective'],
      ['die künstliche Intelligenz', 'artificial intelligence', 'Künstliche Intelligenz verändert viele Branchen.', 'Artificial intelligence is changing many industries.', 'phrase'],
      ['der Roboter', 'robot', 'Roboter übernehmen viele Aufgaben in der Fabrik.', 'Robots take over many tasks in the factory.', 'noun'],
      ['die Automatisierung', 'automation', 'Die Automatisierung ersetzt einfache Tätigkeiten.', 'Automation replaces simple tasks.', 'noun'],
      ['automatisieren', 'to automate', 'Wir wollen den gesamten Prozess automatisieren.', 'We want to automate the entire process.', 'verb'],
      ['das Gerät', 'device', 'Dieses Gerät misst den Blutdruck.', 'This device measures blood pressure.', 'noun'],
      ['der Algorithmus', 'algorithm', 'Ein Algorithmus wählt die passenden Werbeanzeigen aus.', 'An algorithm selects the appropriate ads.', 'noun'],
      ['die Software', 'software', 'Die Software muss regelmäßig aktualisiert werden.', 'The software needs to be updated regularly.', 'noun'],
      ['die Hardware', 'hardware', 'Die alte Hardware ist zu langsam geworden.', 'The old hardware has become too slow.', 'noun'],
      ['digital', 'digital', 'Viele Behördengänge sind heute digital möglich.', 'Many official procedures are now possible digitally.', 'adjective'],
      ['die Digitalisierung', 'digitalization', 'Die Digitalisierung verändert den Arbeitsmarkt.', 'Digitalization is changing the labor market.', 'noun'],
      ['das Netzwerk', 'network', 'Das Netzwerk verbindet Millionen von Computern.', 'The network connects millions of computers.', 'noun'],
      ['die Datenbank', 'database', 'Die Kundendaten liegen in einer zentralen Datenbank.', "The customer data is stored in a central database.", 'noun'],
      ['die Daten', 'data', 'Die Firma sammelt große Mengen an Daten.', 'The company collects large amounts of data.', 'noun'],
      ['der Datenschutz', 'data protection', 'Der Datenschutz spielt online eine große Rolle.', 'Data protection plays a big role online.', 'noun'],
      ['die Sicherheit', 'security', 'Die Sicherheit des Systems wurde verbessert.', 'The security of the system has been improved.', 'noun'],
      ['die Verschlüsselung', 'encryption', 'Die Verschlüsselung schützt die Nachrichten vor Fremden.', 'Encryption protects the messages from strangers.', 'noun'],
      ['das Virus', 'virus', 'Ein Virus hat das ganze Netzwerk lahmgelegt.', 'A virus paralyzed the entire network.', 'noun'],
      ['der Hacker', 'hacker', 'Ein Hacker drang in das System ein.', 'A hacker broke into the system.', 'noun'],
      ['die Cyberkriminalität', 'cybercrime', 'Die Cyberkriminalität nimmt weltweit zu.', 'Cybercrime is increasing worldwide.', 'noun'],
      ['die Raumfahrt', 'space travel', 'Die Raumfahrt fasziniert die Menschen seit Jahrzehnten.', 'Space travel has fascinated people for decades.', 'noun'],
      ['der Satellit', 'satellite', 'Der Satellit sendet Wetterdaten zur Erde.', 'The satellite sends weather data to Earth.', 'noun'],
      ['das Raumschiff', 'spaceship', 'Das Raumschiff landete sicher auf dem Mond.', 'The spaceship landed safely on the moon.', 'noun'],
      ['die Genetik', 'genetics', 'Die Genetik erklärt viele Erbkrankheiten.', 'Genetics explains many hereditary diseases.', 'noun'],
      ['das Gen', 'gene', 'Dieses Gen beeinflusst die Augenfarbe.', 'This gene influences eye color.', 'noun'],
      ['klonen', 'to clone', 'Wissenschaftler klonten das erste Schaf 1996.', 'Scientists cloned the first sheep in 1996.', 'verb'],
      ['die Biotechnologie', 'biotechnology', 'Die Biotechnologie entwickelt neue Medikamente.', 'Biotechnology develops new medicines.', 'noun'],
      ['die Medizintechnik', 'medical technology', 'Die Medizintechnik rettet täglich Leben.', 'Medical technology saves lives every day.', 'noun'],
      ['das Patent', 'patent', 'Die Firma meldete ein neues Patent an.', 'The company registered a new patent.', 'noun'],
      ['patentieren', 'to patent', 'Er ließ seine Erfindung patentieren.', 'He had his invention patented.', 'verb'],
      ['bahnbrechend', 'groundbreaking', 'Das war eine bahnbrechende Entdeckung.', 'That was a groundbreaking discovery.', 'adjective'],
    ],
  },
  {
    title: 'Kultur & Kunst',
    level: CefrLevel.B2,
    description: 'Wortschatz zu Kunst, Literatur, Musik und Film',
    iconEmoji: '🎭',
    items: [
      ['die Kultur', 'culture', 'Jedes Land hat seine eigene Kultur.', 'Every country has its own culture.', 'noun'],
      ['die Kunst', 'art', 'Kunst kann viele Formen annehmen.', 'Art can take many forms.', 'noun'],
      ['der Künstler', 'artist', 'Der Künstler stellte seine neuesten Werke aus.', 'The artist exhibited his latest works.', 'noun'],
      ['das Kunstwerk', 'work of art', 'Dieses Kunstwerk wurde für Millionen versteigert.', 'This work of art was auctioned for millions.', 'noun'],
      ['das Gemälde', 'painting', 'Das Gemälde hängt im Museum.', 'The painting hangs in the museum.', 'noun'],
      ['malen', 'to paint', 'Sie malt am liebsten Landschaften.', 'She likes to paint landscapes best.', 'verb'],
      ['der Maler', 'painter', 'Der Maler arbeitete jahrelang an diesem Bild.', 'The painter worked on this picture for years.', 'noun'],
      ['die Ausstellung', 'exhibition', 'Die Ausstellung zieht viele Besucher an.', 'The exhibition attracts many visitors.', 'noun'],
      ['das Museum', 'museum', 'Am Sonntag ist der Eintritt ins Museum frei.', 'On Sunday, admission to the museum is free.', 'noun'],
      ['die Galerie', 'gallery', 'Die Galerie zeigt junge, unbekannte Künstler.', 'The gallery shows young, unknown artists.', 'noun'],
      ['die Skulptur', 'sculpture', 'Die Skulptur steht mitten auf dem Platz.', 'The sculpture stands in the middle of the square.', 'noun'],
      ['die Bildhauerei', 'sculpture (art form)', 'Er hat sich auf Bildhauerei spezialisiert.', 'He specialized in sculpture.', 'noun'],
      ['die Architektur', 'architecture', 'Die Architektur der Stadt beeindruckt viele Touristen.', "The city's architecture impresses many tourists.", 'noun'],
      ['der Architekt', 'architect', 'Der Architekt entwarf ein außergewöhnliches Gebäude.', 'The architect designed an extraordinary building.', 'noun'],
      ['das Denkmal', 'monument', 'Das Denkmal erinnert an die Opfer des Krieges.', 'The monument commemorates the victims of the war.', 'noun'],
      ['das Erbe', 'heritage', 'Die Altstadt gehört zum Kulturerbe der Stadt.', "The old town is part of the city's cultural heritage.", 'noun'],
      ['die Tradition', 'tradition', 'Diese Tradition wird seit Generationen gepflegt.', 'This tradition has been maintained for generations.', 'noun'],
      ['traditionell', 'traditional', 'Sie trägt zum Fest traditionelle Kleidung.', 'She wears traditional clothing for the festival.', 'adjective'],
      ['der Brauch', 'custom', 'Dieser Brauch ist in der Region weit verbreitet.', 'This custom is widespread in the region.', 'noun'],
      ['das Theater', 'theater', 'Wir gehen heute Abend ins Theater.', "We're going to the theater tonight.", 'noun'],
      ['die Aufführung', 'performance', 'Die Aufführung dauerte fast drei Stunden.', 'The performance lasted almost three hours.', 'noun'],
      ['die Inszenierung', 'staging, production', 'Die Inszenierung überraschte das Publikum.', 'The production surprised the audience.', 'noun'],
      ['der Regisseur', 'director', 'Der Regisseur führte bei diesem Film erstmals Regie.', 'The director directed this film for the first time.', 'noun'],
      ['das Drehbuch', 'screenplay', 'Sie schrieb das Drehbuch innerhalb weniger Monate.', 'She wrote the screenplay within a few months.', 'noun'],
      ['der Roman', 'novel', 'Der Roman wurde in dreißig Sprachen übersetzt.', 'The novel was translated into thirty languages.', 'noun'],
      ['der Schriftsteller', 'writer', 'Der Schriftsteller lebt zurückgezogen auf dem Land.', 'The writer lives secluded in the countryside.', 'noun'],
      ['die Literatur', 'literature', 'Sie studiert deutsche Literatur.', 'She studies German literature.', 'noun'],
      ['das Gedicht', 'poem', 'Er lernte das Gedicht auswendig.', 'He memorized the poem.', 'noun'],
      ['die Lyrik', 'poetry', 'Die Lyrik dieser Epoche ist sehr gefühlvoll.', 'The poetry of this era is very emotional.', 'noun'],
      ['die Erzählung', 'narrative, story', 'Die Erzählung spielt im neunzehnten Jahrhundert.', 'The story is set in the nineteenth century.', 'noun'],
      ['der Verlag', 'publishing house', 'Der Verlag veröffentlicht jedes Jahr viele neue Bücher.', 'The publisher releases many new books every year.', 'noun'],
      ['veröffentlichen', 'to publish', 'Sie veröffentlichte ihren ersten Roman mit zwanzig.', 'She published her first novel at twenty.', 'verb'],
      ['die Musik', 'music', 'Musik verbindet Menschen aus aller Welt.', 'Music connects people from all over the world.', 'noun'],
      ['der Komponist', 'composer', 'Der Komponist schrieb die Musik für den Film.', 'The composer wrote the music for the film.', 'noun'],
      ['komponieren', 'to compose', 'Er komponiert seit seiner Kindheit.', 'He has been composing since childhood.', 'verb'],
      ['das Orchester', 'orchestra', 'Das Orchester spielte vor ausverkauftem Haus.', 'The orchestra played to a sold-out house.', 'noun'],
      ['die Melodie', 'melody', 'Die Melodie geht einem nicht mehr aus dem Kopf.', 'The melody gets stuck in your head.', 'noun'],
      ['der Rhythmus', 'rhythm', 'Der Rhythmus dieses Liedes ist sehr mitreißend.', 'The rhythm of this song is very catchy.', 'noun'],
      ['der Tanz', 'dance', 'Der Tanz stammt ursprünglich aus Südamerika.', 'The dance originally comes from South America.', 'noun'],
      ['tanzen', 'to dance', 'Sie tanzen jeden Freitagabend Salsa.', 'They dance salsa every Friday evening.', 'verb'],
      ['der Film', 'film, movie', 'Der Film gewann mehrere internationale Preise.', 'The film won several international awards.', 'noun'],
      ['die Filmkritik', 'film review', 'Die Filmkritik war überraschend positiv.', 'The film review was surprisingly positive.', 'noun'],
      ['die Kritik', 'criticism, review', 'Der Autor nimmt Kritik sehr ernst.', 'The author takes criticism very seriously.', 'noun'],
      ['kritisieren', 'to criticize', 'Kritiker kritisierten das Ende des Buches.', 'Critics criticized the ending of the book.', 'verb'],
      ['die Ästhetik', 'aesthetics', 'Die Ästhetik des Gebäudes spaltet die Meinungen.', 'The aesthetics of the building divide opinions.', 'noun'],
      ['ästhetisch', 'aesthetic', 'Das Design wirkt sehr ästhetisch.', 'The design looks very aesthetic.', 'adjective'],
      ['der Stil', 'style', 'Jeder Künstler entwickelt seinen eigenen Stil.', 'Every artist develops their own style.', 'noun'],
      ['das Meisterwerk', 'masterpiece', 'Dieses Gemälde gilt als sein Meisterwerk.', 'This painting is considered his masterpiece.', 'noun'],
      ['die Kreativität', 'creativity', 'Kreativität lässt sich schwer messen.', 'Creativity is hard to measure.', 'noun'],
      ['kreativ', 'creative', 'Sie arbeitet als kreative Direktorin einer Agentur.', 'She works as the creative director of an agency.', 'adjective'],
    ],
  },
  {
    title: 'Wirtschaft & Konsum',
    level: CefrLevel.B2,
    description: 'Wortschatz zu Wirtschaft, Handel und Konsum',
    iconEmoji: '📈',
    items: [
      ['die Wirtschaft', 'economy', 'Die Wirtschaft wächst langsamer als erwartet.', 'The economy is growing more slowly than expected.', 'noun'],
      ['wirtschaftlich', 'economic', 'Das Land steckt in einer wirtschaftlichen Krise.', 'The country is in an economic crisis.', 'adjective'],
      ['das Unternehmen', 'company', 'Das Unternehmen stellt in diesem Jahr viele Mitarbeiter ein.', 'The company is hiring many employees this year.', 'noun'],
      ['der Konzern', 'corporation', 'Der Konzern beschäftigt weltweit tausende Mitarbeiter.', 'The corporation employs thousands of workers worldwide.', 'noun'],
      ['die Branche', 'industry, sector', 'Die Automobilbranche steht vor großen Veränderungen.', 'The automotive industry is facing major changes.', 'noun'],
      ['der Markt', 'market', 'Das neue Produkt kommt nächsten Monat auf den Markt.', 'The new product will hit the market next month.', 'noun'],
      ['die Nachfrage', 'demand', 'Die Nachfrage nach Elektroautos steigt stetig.', 'Demand for electric cars is steadily increasing.', 'noun'],
      ['das Angebot', 'supply, offer', 'Das Angebot übersteigt derzeit die Nachfrage.', 'Supply currently exceeds demand.', 'noun'],
      ['die Konkurrenz', 'competition', 'Die Konkurrenz auf dem Markt ist hart.', 'Competition in the market is fierce.', 'noun'],
      ['konkurrieren', 'to compete', 'Beide Firmen konkurrieren um denselben Kunden.', 'Both companies compete for the same customer.', 'verb'],
      ['der Wettbewerb', 'competition, contest', 'Der Wettbewerb fördert bessere Produkte.', 'Competition promotes better products.', 'noun'],
      ['der Gewinn', 'profit', 'Der Gewinn des Unternehmens stieg im letzten Quartal.', "The company's profit increased last quarter.", 'noun'],
      ['der Verlust', 'loss', 'Die Firma machte im ersten Jahr Verlust.', 'The company made a loss in the first year.', 'noun'],
      ['die Investition', 'investment', 'Diese Investition zahlt sich langfristig aus.', 'This investment pays off in the long run.', 'noun'],
      ['investieren', 'to invest', 'Sie investiert einen Teil ihres Gehalts in Aktien.', 'She invests part of her salary in stocks.', 'verb'],
      ['der Aktienmarkt', 'stock market', 'Der Aktienmarkt reagierte nervös auf die Nachricht.', 'The stock market reacted nervously to the news.', 'noun'],
      ['die Aktie', 'share, stock', 'Die Aktie verlor innerhalb eines Tages zehn Prozent.', 'The stock lost ten percent in one day.', 'noun'],
      ['der Umsatz', 'revenue, turnover', 'Der Umsatz hat sich in fünf Jahren verdoppelt.', 'Revenue has doubled in five years.', 'noun'],
      ['die Steuer', 'tax', 'Die Steuer auf Benzin wurde erhöht.', 'The tax on gasoline was increased.', 'noun'],
      ['besteuern', 'to tax', 'Der Staat besteuert hohe Einkommen stärker.', 'The state taxes high incomes more heavily.', 'verb'],
      ['das Einkommen', 'income', 'Ihr monatliches Einkommen reicht kaum aus.', 'Her monthly income is barely enough.', 'noun'],
      ['das Gehalt', 'salary', 'Er verhandelte erfolgreich über ein höheres Gehalt.', 'He successfully negotiated a higher salary.', 'noun'],
      ['der Verbraucher', 'consumer', 'Verbraucher achten heute mehr auf Qualität.', 'Consumers pay more attention to quality today.', 'noun'],
      ['konsumieren', 'to consume', 'Wir konsumieren viel mehr, als wir brauchen.', 'We consume much more than we need.', 'verb'],
      ['der Konsum', 'consumption', 'Der übermäßige Konsum schadet der Umwelt.', 'Excessive consumption harms the environment.', 'noun'],
      ['die Werbung', 'advertising', 'Werbung beeinflusst unser Kaufverhalten stark.', 'Advertising strongly influences our buying behavior.', 'noun'],
      ['bewerben', 'to advertise (something)', 'Die Firma bewirbt ihr neues Produkt im Fernsehen.', 'The company advertises its new product on TV.', 'verb'],
      ['das Produkt', 'product', 'Das Produkt verkauft sich besser als erwartet.', 'The product is selling better than expected.', 'noun'],
      ['produzieren', 'to produce', 'Die Fabrik produziert täglich tausende Teile.', 'The factory produces thousands of parts every day.', 'verb'],
      ['die Produktion', 'production', 'Die Produktion wurde ins Ausland verlagert.', 'Production was relocated abroad.', 'noun'],
      ['der Hersteller', 'manufacturer', 'Der Hersteller garantiert zwei Jahre Gewährleistung.', 'The manufacturer guarantees a two-year warranty.', 'noun'],
      ['der Lieferant', 'supplier', 'Der Lieferant konnte die Ware nicht rechtzeitig liefern.', 'The supplier could not deliver the goods on time.', 'noun'],
      ['liefern', 'to deliver', 'Das Paket wird morgen geliefert.', 'The package will be delivered tomorrow.', 'verb'],
      ['die Lieferkette', 'supply chain', 'Die Lieferkette wurde durch die Krise unterbrochen.', 'The supply chain was disrupted by the crisis.', 'noun'],
      ['der Handel', 'trade', 'Der internationale Handel schafft viele Arbeitsplätze.', 'International trade creates many jobs.', 'noun'],
      ['handeln', 'to trade, to act', 'Die beiden Länder handeln seit Jahrzehnten miteinander.', 'The two countries have been trading with each other for decades.', 'verb'],
      ['der Export', 'export', 'Der Export von Maschinen stieg deutlich.', 'The export of machinery increased significantly.', 'noun'],
      ['exportieren', 'to export', 'Deutschland exportiert viele Autos nach Asien.', 'Germany exports many cars to Asia.', 'verb'],
      ['der Import', 'import', 'Der Import von Rohstoffen ist für das Land wichtig.', 'The import of raw materials is important for the country.', 'noun'],
      ['importieren', 'to import', 'Das Land importiert den Großteil seines Öls.', 'The country imports most of its oil.', 'verb'],
      ['die Globalisierung', 'globalization', 'Die Globalisierung verändert die Weltwirtschaft grundlegend.', 'Globalization is fundamentally changing the world economy.', 'noun'],
      ['die Inflation', 'inflation', 'Die hohe Inflation belastet viele Haushalte.', 'High inflation is burdening many households.', 'noun'],
      ['die Rezession', 'recession', 'Experten befürchten eine baldige Rezession.', 'Experts fear an imminent recession.', 'noun'],
      ['die Krise', 'crisis', 'Die Firma hat die Krise gut überstanden.', 'The company weathered the crisis well.', 'noun'],
      ['die Schulden', 'debt', 'Das Land hat hohe Schulden angehäuft.', 'The country has accumulated high debt.', 'noun'],
      ['sich verschulden', 'to go into debt', 'Viele junge Leute verschulden sich für ihr Studium.', 'Many young people go into debt for their studies.', 'verb'],
      ['das Darlehen', 'loan', 'Sie nahm ein Darlehen für die Wohnung auf.', 'She took out a loan for the apartment.', 'noun'],
      ['die Rechnung', 'invoice, bill', 'Bitte bezahlen Sie die Rechnung innerhalb von vierzehn Tagen.', 'Please pay the invoice within fourteen days.', 'noun'],
      ['der Kredit', 'credit, loan', 'Die Bank gewährte ihm einen günstigen Kredit.', 'The bank granted him a favorable loan.', 'noun'],
      ['die Kaufkraft', 'purchasing power', "Die Kaufkraft der Verbraucher ist gesunken.", "Consumers' purchasing power has declined.", 'noun'],
    ],
  },
];
