import { CefrLevel } from '@prisma/client';

export const GERMAN_VOCAB_B1 = [
  {
    title: 'Arbeit & Beruf',
    level: CefrLevel.B1,
    description: 'Bewerbung, Büroalltag und Karriere',
    iconEmoji: '💼',
    items: [
      ['die Bewerbung', 'application', 'Ich habe meine Bewerbung abgeschickt.', 'I have sent my application.', 'noun'],
      ['der Lebenslauf', 'CV, resume', 'Bitte schicken Sie Ihren Lebenslauf.', 'Please send your CV.', 'noun'],
      ['das Vorstellungsgespräch', 'job interview', 'Das Vorstellungsgespräch war sehr lang.', 'The job interview was very long.', 'noun'],
      ['die Stelle', 'position, job', 'Die Stelle wurde schon besetzt.', 'The position has already been filled.', 'noun'],
      ['der Arbeitgeber', 'employer', 'Mein Arbeitgeber ist sehr freundlich.', 'My employer is very friendly.', 'noun'],
      ['der Arbeitnehmer', 'employee', 'Der Arbeitnehmer hat viele Rechte.', 'The employee has many rights.', 'noun'],
      ['das Gehalt', 'salary', 'Das Gehalt wird monatlich überwiesen.', 'The salary is transferred monthly.', 'noun'],
      ['der Vertrag', 'contract', 'Wir haben den Vertrag unterschrieben.', 'We signed the contract.', 'noun'],
      ['die Kündigung', 'termination, notice', 'Er hat die Kündigung erhalten.', 'He received the notice of termination.', 'noun'],
      ['kündigen', 'to quit, to terminate', 'Sie hat ihren Job gekündigt.', 'She quit her job.', 'verb'],
      ['sich bewerben', 'to apply', 'Ich möchte mich um die Stelle bewerben.', 'I would like to apply for the position.', 'verb'],
      ['einstellen', 'to hire', 'Die Firma will drei neue Leute einstellen.', 'The company wants to hire three new people.', 'verb'],
      ['entlassen', 'to dismiss, to fire', 'Der Chef musste zwei Mitarbeiter entlassen.', 'The boss had to dismiss two employees.', 'verb'],
      ['die Probezeit', 'probation period', 'Die Probezeit dauert sechs Monate.', 'The probation period lasts six months.', 'noun'],
      ['die Überstunde', 'overtime', 'Ich musste gestern Überstunden machen.', 'I had to work overtime yesterday.', 'noun'],
      ['der Kollege', 'colleague (male)', 'Mein Kollege hilft mir oft.', 'My colleague often helps me.', 'noun'],
      ['die Kollegin', 'colleague (female)', 'Meine Kollegin ist im Urlaub.', 'My colleague is on vacation.', 'noun'],
      ['der Chef', 'boss (male)', 'Der Chef ist heute nicht im Büro.', 'The boss is not in the office today.', 'noun'],
      ['die Chefin', 'boss (female)', 'Die Chefin lobt selten.', 'The boss rarely gives praise.', 'noun'],
      ['die Besprechung', 'meeting', 'Die Besprechung beginnt um neun Uhr.', 'The meeting starts at nine o’clock.', 'noun'],
      ['die Konferenz', 'conference', 'Die Konferenz findet online statt.', 'The conference takes place online.', 'noun'],
      ['der Termin', 'appointment', 'Ich habe morgen einen wichtigen Termin.', 'I have an important appointment tomorrow.', 'noun'],
      ['die Aufgabe', 'task', 'Diese Aufgabe ist ziemlich schwierig.', 'This task is quite difficult.', 'noun'],
      ['die Verantwortung', 'responsibility', 'Sie trägt viel Verantwortung im Projekt.', 'She carries a lot of responsibility in the project.', 'noun'],
      ['verantwortlich', 'responsible', 'Wer ist für diesen Fehler verantwortlich?', 'Who is responsible for this mistake?', 'adjective'],
      ['die Erfahrung', 'experience', 'Er hat viel Erfahrung in diesem Bereich.', 'He has a lot of experience in this field.', 'noun'],
      ['die Qualifikation', 'qualification', 'Ihre Qualifikationen passen genau zur Stelle.', 'Her qualifications match the position exactly.', 'noun'],
      ['die Fähigkeit', 'skill, ability', 'Er hat die Fähigkeit, gut zuzuhören.', 'He has the ability to listen well.', 'noun'],
      ['die Ausbildung', 'training, apprenticeship', 'Sie macht eine Ausbildung zur Krankenschwester.', 'She is doing an apprenticeship as a nurse.', 'noun'],
      ['die Karriere', 'career', 'Er will schnell Karriere machen.', 'He wants to advance his career quickly.', 'noun'],
      ['befördern', 'to promote', 'Man hat sie zur Abteilungsleiterin befördert.', 'She was promoted to department head.', 'verb'],
      ['die Beförderung', 'promotion', 'Er freut sich über seine Beförderung.', 'He is happy about his promotion.', 'noun'],
      ['der Urlaub', 'vacation, leave', 'Wir fahren im Sommer in den Urlaub.', 'We are going on vacation in summer.', 'noun'],
      ['der Feierabend', 'end of the workday', 'Endlich ist Feierabend!', 'Finally, the workday is over!', 'noun'],
      ['die Teilzeit', 'part-time', 'Sie arbeitet seit der Geburt in Teilzeit.', 'She has been working part-time since giving birth.', 'noun'],
      ['die Vollzeit', 'full-time', 'Er sucht eine Stelle in Vollzeit.', 'He is looking for a full-time job.', 'noun'],
      ['selbstständig', 'self-employed, independent', 'Meine Schwester ist seit zwei Jahren selbstständig.', 'My sister has been self-employed for two years.', 'adjective'],
      ['der Betrieb', 'company, business, operation', 'Der Betrieb beschäftigt fünfzig Mitarbeiter.', 'The company employs fifty staff.', 'noun'],
      ['die Firma', 'company, firm', 'Die Firma wurde vor zehn Jahren gegründet.', 'The company was founded ten years ago.', 'noun'],
      ['das Büro', 'office', 'Mein Büro liegt im dritten Stock.', 'My office is on the third floor.', 'noun'],
      ['die Abteilung', 'department', 'Er arbeitet in der Marketingabteilung.', 'He works in the marketing department.', 'noun'],
      ['der Auftrag', 'order, assignment', 'Wir haben einen großen Auftrag bekommen.', 'We got a big order.', 'noun'],
      ['die Frist', 'deadline', 'Die Frist für die Anmeldung läuft morgen ab.', 'The registration deadline expires tomorrow.', 'noun'],
      ['der Bericht', 'report', 'Bitte schreiben Sie bis Freitag einen Bericht.', 'Please write a report by Friday.', 'noun'],
      ['die Präsentation', 'presentation', 'Ihre Präsentation hat alle überzeugt.', 'Her presentation convinced everyone.', 'noun'],
      ['das Projekt', 'project', 'Das Projekt wird nächste Woche abgeschlossen.', 'The project will be completed next week.', 'noun'],
      ['das Team', 'team', 'Unser Team arbeitet sehr gut zusammen.', 'Our team works together very well.', 'noun'],
      ['zusammenarbeiten', 'to collaborate, to work together', 'Wir müssen enger zusammenarbeiten.', 'We need to work together more closely.', 'verb'],
      ['die Gehaltserhöhung', 'pay raise', 'Er hat um eine Gehaltserhöhung gebeten.', 'He asked for a pay raise.', 'noun'],
      ['der Ruhestand', 'retirement', 'Meine Oma genießt ihren Ruhestand.', 'My grandma enjoys her retirement.', 'noun'],
    ],
  },
  {
    title: 'Schule & Ausbildung',
    level: CefrLevel.B1,
    description: 'Schule, Studium und lebenslanges Lernen',
    iconEmoji: '🎓',
    items: [
      ['die Schule', 'school', 'Die Schule beginnt um acht Uhr.', 'School starts at eight o’clock.', 'noun'],
      ['der Unterricht', 'lessons, class', 'Der Unterricht fällt heute aus.', 'Class is cancelled today.', 'noun'],
      ['der Lehrer', 'teacher (male)', 'Unser Lehrer erklärt sehr geduldig.', 'Our teacher explains very patiently.', 'noun'],
      ['die Lehrerin', 'teacher (female)', 'Die Lehrerin lobt gute Arbeit.', 'The teacher praises good work.', 'noun'],
      ['der Schüler', 'pupil, student (male)', 'Der Schüler meldet sich oft.', 'The pupil often raises his hand.', 'noun'],
      ['die Schülerin', 'pupil, student (female)', 'Die Schülerin schreibt einen Test.', 'The pupil is writing a test.', 'noun'],
      ['die Klasse', 'class', 'Unsere Klasse hat 25 Schüler.', 'Our class has 25 pupils.', 'noun'],
      ['das Fach', 'subject', 'Mathematik ist mein Lieblingsfach.', 'Math is my favorite subject.', 'noun'],
      ['die Prüfung', 'exam', 'Die Prüfung war schwieriger als erwartet.', 'The exam was more difficult than expected.', 'noun'],
      ['die Note', 'grade, mark', 'Sie hat eine gute Note bekommen.', 'She got a good grade.', 'noun'],
      ['das Zeugnis', 'report card', 'Das Zeugnis kommt am letzten Schultag.', 'The report card comes on the last day of school.', 'noun'],
      ['die Hausaufgabe', 'homework', 'Hast du deine Hausaufgaben schon gemacht?', 'Have you already done your homework?', 'noun'],
      ['bestehen', 'to pass', 'Ich hoffe, ich bestehe die Prüfung.', 'I hope I pass the exam.', 'verb'],
      ['durchfallen', 'to fail', 'Er ist leider durch die Prüfung gefallen.', 'Unfortunately, he failed the exam.', 'verb'],
      ['wiederholen', 'to repeat, to review', 'Wir sollten den Stoff noch einmal wiederholen.', 'We should review the material once more.', 'verb'],
      ['das Studium', 'studies, degree course', 'Ihr Studium dauert vier Jahre.', 'Her degree course takes four years.', 'noun'],
      ['der Student', 'student (male, university)', 'Der Student wohnt im Wohnheim.', 'The student lives in the dormitory.', 'noun'],
      ['die Studentin', 'student (female, university)', 'Die Studentin arbeitet nebenbei.', 'The student works on the side.', 'noun'],
      ['die Universität', 'university', 'Die Universität liegt im Zentrum der Stadt.', 'The university is located in the city center.', 'noun'],
      ['die Hochschule', 'college, university', 'Er studiert an einer technischen Hochschule.', 'He studies at a technical college.', 'noun'],
      ['studieren', 'to study (at university)', 'Sie studiert Medizin in Berlin.', 'She studies medicine in Berlin.', 'verb'],
      ['lernen', 'to learn, to study', 'Ich muss heute Abend noch lernen.', 'I still have to study tonight.', 'verb'],
      ['das Semester', 'semester', 'Das neue Semester beginnt im April.', 'The new semester starts in April.', 'noun'],
      ['die Vorlesung', 'lecture', 'Die Vorlesung dauert neunzig Minuten.', 'The lecture lasts ninety minutes.', 'noun'],
      ['das Seminar', 'seminar', 'Im Seminar diskutieren wir viel.', 'We discuss a lot in the seminar.', 'noun'],
      ['die Klausur', 'written exam (university)', 'Die Klausur findet nächste Woche statt.', 'The written exam takes place next week.', 'noun'],
      ['der Abschluss', 'degree, graduation', 'Nach dem Abschluss sucht sie eine Stelle.', 'After graduation, she is looking for a job.', 'noun'],
      ['das Diplom', 'diploma', 'Er hat sein Diplom mit Auszeichnung bekommen.', 'He received his diploma with honors.', 'noun'],
      ['der Bachelor', 'bachelor’s degree', 'Sie macht ihren Bachelor in Psychologie.', 'She is doing her bachelor’s degree in psychology.', 'noun'],
      ['der Master', 'master’s degree', 'Nach dem Bachelor will er den Master machen.', 'After the bachelor’s, he wants to do a master’s.', 'noun'],
      ['das Stipendium', 'scholarship', 'Sie hat ein Stipendium für ihr Studium bekommen.', 'She received a scholarship for her studies.', 'noun'],
      ['die Bibliothek', 'library', 'Ich lerne oft in der Bibliothek.', 'I often study in the library.', 'noun'],
      ['ausleihen', 'to borrow, to lend', 'Ich möchte dieses Buch ausleihen.', 'I would like to borrow this book.', 'verb'],
      ['das Lehrbuch', 'textbook', 'Das Lehrbuch ist ziemlich teuer.', 'The textbook is quite expensive.', 'noun'],
      ['der Stundenplan', 'timetable, schedule', 'Mein Stundenplan ist dieses Semester voll.', 'My timetable is full this semester.', 'noun'],
      ['die Pause', 'break', 'In der Pause essen wir meistens etwas.', 'During the break, we usually eat something.', 'noun'],
      ['das Klassenzimmer', 'classroom', 'Das Klassenzimmer ist hell und modern.', 'The classroom is bright and modern.', 'noun'],
      ['die Tafel', 'blackboard, whiteboard', 'Der Lehrer schreibt die Wörter an die Tafel.', 'The teacher writes the words on the board.', 'noun'],
      ['der Stift', 'pen, pencil', 'Hast du einen Stift für mich?', 'Do you have a pen for me?', 'noun'],
      ['das Heft', 'notebook, exercise book', 'Schreib die Vokabeln in dein Heft.', 'Write the vocabulary in your notebook.', 'noun'],
      ['die Aufmerksamkeit', 'attention', 'Die Lehrerin verlangt volle Aufmerksamkeit.', 'The teacher demands full attention.', 'noun'],
      ['aufpassen', 'to pay attention', 'Bitte passt im Unterricht besser auf.', 'Please pay better attention in class.', 'verb'],
      ['sich konzentrieren', 'to concentrate', 'Ich kann mich heute schlecht konzentrieren.', 'I can’t concentrate well today.', 'verb'],
      ['der Fleiß', 'diligence', 'Ihr Fleiß hat sich am Ende gelohnt.', 'Her diligence paid off in the end.', 'noun'],
      ['fleißig', 'diligent, hardworking', 'Er ist ein sehr fleißiger Schüler.', 'He is a very diligent pupil.', 'adjective'],
      ['faul', 'lazy', "Sei nicht so faul und lern endlich!", "Don't be so lazy and finally study!", 'adjective'],
      ['das Praktikum', 'internship', 'Sie macht ein Praktikum bei einer Bank.', 'She is doing an internship at a bank.', 'noun'],
      ['der Praktikant', 'intern (male)', 'Der Praktikant lernt sehr schnell.', 'The intern learns very quickly.', 'noun'],
      ['die Fortbildung', 'further training, continuing education', 'Die Firma zahlt für seine Fortbildung.', 'The company pays for his further training.', 'noun'],
      ['das lebenslange Lernen', 'lifelong learning', 'Lebenslanges Lernen wird immer wichtiger.', 'Lifelong learning is becoming increasingly important.', 'phrase'],
    ],
  },
  {
    title: 'Wohnen & Umzug',
    level: CefrLevel.B1,
    description: 'Wohnung suchen, mieten und einrichten',
    iconEmoji: '🏠',
    items: [
      ['die Wohnung', 'apartment, flat', 'Die Wohnung hat zwei Zimmer und eine Küche.', 'The apartment has two rooms and a kitchen.', 'noun'],
      ['das Haus', 'house', 'Wir wollen ein Haus auf dem Land kaufen.', 'We want to buy a house in the countryside.', 'noun'],
      ['die Miete', 'rent', 'Die Miete steigt jedes Jahr ein bisschen.', 'The rent increases a little every year.', 'noun'],
      ['mieten', 'to rent', 'Wir mieten seit drei Jahren diese Wohnung.', 'We have been renting this apartment for three years.', 'verb'],
      ['vermieten', 'to rent out, to let', 'Sie vermietet ein Zimmer an Studenten.', 'She rents out a room to students.', 'verb'],
      ['der Vermieter', 'landlord', 'Der Vermieter repariert die Heizung nicht.', 'The landlord does not repair the heating.', 'noun'],
      ['der Mieter', 'tenant', 'Der Mieter zahlt die Miete immer pünktlich.', 'The tenant always pays the rent on time.', 'noun'],
      ['der Umzug', 'move, relocation', 'Der Umzug war sehr anstrengend.', 'The move was very exhausting.', 'noun'],
      ['umziehen', 'to move house', 'Wir ziehen nächsten Monat nach Hamburg um.', 'We are moving to Hamburg next month.', 'verb'],
      ['die Kaution', 'deposit', 'Die Kaution beträgt drei Monatsmieten.', 'The deposit is three months’ rent.', 'noun'],
      ['der Makler', 'real estate agent', 'Der Makler hat uns drei Wohnungen gezeigt.', 'The real estate agent showed us three apartments.', 'noun'],
      ['die Immobilie', 'property, real estate', 'Immobilien in der Stadt sind sehr teuer.', 'Real estate in the city is very expensive.', 'noun'],
      ['erwerben', 'to acquire', 'Sie möchten ein Grundstück erwerben.', 'They would like to acquire a plot of land.', 'verb'],
      ['die Nebenkosten', 'utility costs, additional costs', 'Die Nebenkosten sind im letzten Jahr gestiegen.', 'The utility costs have risen in the past year.', 'noun'],
      ['der Mietvertrag', 'rental agreement, lease', 'Wir haben den Mietvertrag für zwei Jahre unterschrieben.', 'We signed the lease for two years.', 'noun'],
      ['der Auszug', 'move-out', 'Der Auszug muss bis Ende des Monats erfolgen.', 'The move-out must take place by the end of the month.', 'noun'],
      ['der Einzug', 'move-in', 'Zum Einzug haben wir eine kleine Party gemacht.', 'We had a small party to celebrate the move-in.', 'noun'],
      ['das Zimmer', 'room', 'Das Zimmer ist klein, aber gemütlich.', 'The room is small but cozy.', 'noun'],
      ['das Wohnzimmer', 'living room', 'Im Wohnzimmer steht ein großes Sofa.', 'There is a large sofa in the living room.', 'noun'],
      ['das Schlafzimmer', 'bedroom', 'Das Schlafzimmer geht nach Süden raus.', 'The bedroom faces south.', 'noun'],
      ['die Küche', 'kitchen', 'Die Küche ist frisch renoviert.', 'The kitchen has just been renovated.', 'noun'],
      ['das Badezimmer', 'bathroom', 'Das Badezimmer hat leider kein Fenster.', 'Unfortunately, the bathroom has no window.', 'noun'],
      ['der Balkon', 'balcony', 'Wir frühstücken im Sommer oft auf dem Balkon.', 'In summer, we often have breakfast on the balcony.', 'noun'],
      ['der Keller', 'basement, cellar', 'Die Fahrräder stehen im Keller.', 'The bicycles are in the basement.', 'noun'],
      ['der Dachboden', 'attic', 'Auf dem Dachboden lagern wir alte Möbel.', 'We store old furniture in the attic.', 'noun'],
      ['der Aufzug', 'elevator, lift', 'Der Aufzug ist heute leider kaputt.', 'Unfortunately, the elevator is broken today.', 'noun'],
      ['das Erdgeschoss', 'ground floor', 'Unsere Wohnung liegt im Erdgeschoss.', 'Our apartment is on the ground floor.', 'noun'],
      ['das Stockwerk', 'floor, storey', 'Das Haus hat insgesamt fünf Stockwerke.', 'The building has five floors in total.', 'noun'],
      ['die Nachbarschaft', 'neighborhood', 'Die Nachbarschaft ist sehr ruhig und grün.', 'The neighborhood is very quiet and green.', 'noun'],
      ['der Nachbar', 'neighbor (male)', 'Unser Nachbar hört abends laut Musik.', 'Our neighbor plays loud music in the evenings.', 'noun'],
      ['die Nachbarin', 'neighbor (female)', 'Die Nachbarin gießt unsere Blumen im Urlaub.', 'The neighbor waters our flowers while we’re on vacation.', 'noun'],
      ['renovieren', 'to renovate', 'Wir renovieren gerade das Badezimmer.', 'We are currently renovating the bathroom.', 'verb'],
      ['einrichten', 'to furnish', 'Sie hat die Wohnung sehr geschmackvoll eingerichtet.', 'She furnished the apartment very tastefully.', 'verb'],
      ['die Möbel', 'furniture', 'Die Möbel kommen erst nächste Woche.', 'The furniture will not arrive until next week.', 'noun'],
      ['der Schrank', 'cupboard, wardrobe', 'Der Schrank passt genau in die Ecke.', 'The wardrobe fits exactly into the corner.', 'noun'],
      ['das Regal', 'shelf', 'Das Regal ist voller Bücher.', 'The shelf is full of books.', 'noun'],
      ['der Teppich', 'carpet, rug', 'Der Teppich liegt mitten im Wohnzimmer.', 'The rug lies in the middle of the living room.', 'noun'],
      ['die Heizung', 'heating', 'Die Heizung funktioniert im Winter nicht richtig.', 'The heating does not work properly in winter.', 'noun'],
      ['der Strom', 'electricity', 'Der Strom ist letzte Nacht ausgefallen.', 'The electricity went out last night.', 'noun'],
      ['der Hausmeister', 'caretaker, janitor', 'Der Hausmeister kümmert sich um den Garten.', 'The caretaker takes care of the garden.', 'noun'],
      ['die Hausordnung', 'house rules', 'Bitte lesen Sie die Hausordnung aufmerksam durch.', 'Please read the house rules carefully.', 'noun'],
      ['der Lärm', 'noise', 'Der Lärm von der Baustelle stört uns sehr.', 'The noise from the construction site bothers us a lot.', 'noun'],
      ['ruhig', 'quiet, calm', 'Die Straße ist nachts sehr ruhig.', 'The street is very quiet at night.', 'adjective'],
      ['gemütlich', 'cozy', 'Das kleine Café ist wirklich gemütlich.', 'The little café is really cozy.', 'adjective'],
      ['geräumig', 'spacious', 'Die neue Wohnung ist viel geräumiger.', 'The new apartment is much more spacious.', 'adjective'],
      ['hell', 'bright', 'Das Zimmer ist sehr hell und freundlich.', 'The room is very bright and friendly.', 'adjective'],
      ['die Aussicht', 'view', 'Von hier hat man eine tolle Aussicht auf die Stadt.', 'From here, you have a great view of the city.', 'noun'],
      ['zentral gelegen', 'centrally located', 'Die Wohnung ist zentral gelegen und gut angebunden.', 'The apartment is centrally located and well connected.', 'phrase'],
      ['die Wohngemeinschaft', 'shared flat, flatshare', 'Ich lebe seit einem Jahr in einer Wohngemeinschaft.', 'I have been living in a flatshare for a year.', 'noun'],
      ['der Mitbewohner', 'roommate, flatmate', 'Mein Mitbewohner kocht sehr gern.', 'My roommate really likes to cook.', 'noun'],
    ],
  },
  {
    title: 'Medien & Kommunikation',
    level: CefrLevel.B1,
    description: 'Nachrichten, soziale Medien und Gespräche',
    iconEmoji: '📱',
    items: [
      ['die Nachricht', 'news, message', 'Hast du die Nachricht schon gelesen?', 'Have you already read the message?', 'noun'],
      ['die Zeitung', 'newspaper', 'Mein Vater liest jeden Morgen die Zeitung.', 'My father reads the newspaper every morning.', 'noun'],
      ['die Zeitschrift', 'magazine', 'Diese Zeitschrift erscheint einmal im Monat.', 'This magazine is published once a month.', 'noun'],
      ['das Fernsehen', 'television', 'Wir schauen abends selten Fernsehen.', 'We rarely watch television in the evenings.', 'noun'],
      ['der Sender', 'channel, broadcaster', 'Dieser Sender zeigt viele Dokumentationen.', 'This channel shows many documentaries.', 'noun'],
      ['die Sendung', 'program, broadcast', 'Die Sendung beginnt um zwanzig Uhr.', 'The program starts at eight p.m.', 'noun'],
      ['der Rundfunk', 'broadcasting, radio', 'Der öffentliche Rundfunk wird durch Gebühren finanziert.', 'Public broadcasting is financed through fees.', 'noun'],
      ['das Radio', 'radio', 'Im Auto hört sie immer Radio.', 'She always listens to the radio in the car.', 'noun'],
      ['der Artikel', 'article', 'Ich habe einen interessanten Artikel gelesen.', 'I read an interesting article.', 'noun'],
      ['die Schlagzeile', 'headline', 'Die Schlagzeile war sehr reißerisch.', 'The headline was very sensational.', 'noun'],
      ['die Reportage', 'report, feature', 'Die Reportage handelt von der Klimakrise.', 'The feature is about the climate crisis.', 'noun'],
      ['das Interview', 'interview', 'Das Interview mit der Politikerin war spannend.', 'The interview with the politician was exciting.', 'noun'],
      ['der Journalist', 'journalist (male)', 'Der Journalist recherchiert seit Wochen zu diesem Thema.', 'The journalist has been researching this topic for weeks.', 'noun'],
      ['die Journalistin', 'journalist (female)', 'Die Journalistin schreibt für eine große Zeitung.', 'The journalist writes for a major newspaper.', 'noun'],
      ['die Redaktion', 'editorial office, editorial staff', 'Die Redaktion prüft jeden Artikel genau.', 'The editorial staff checks every article carefully.', 'noun'],
      ['veröffentlichen', 'to publish', 'Der Verlag veröffentlicht das Buch im Herbst.', 'The publisher will publish the book in autumn.', 'verb'],
      ['berichten', 'to report', 'Die Presse berichtet ausführlich über den Unfall.', 'The press reports extensively on the accident.', 'verb'],
      ['informieren', 'to inform', 'Bitte informieren Sie uns über Änderungen.', 'Please inform us of any changes.', 'verb'],
      ['die Information', 'information', 'Ich brauche noch ein paar Informationen.', 'I still need a bit more information.', 'noun'],
      ['die Werbung', 'advertising', 'Zu viel Werbung nervt viele Zuschauer.', 'Too much advertising annoys many viewers.', 'noun'],
      ['der Werbespot', 'commercial, advertisement', 'Der Werbespot lief während der Pause.', 'The commercial aired during the break.', 'noun'],
      ['das soziale Netzwerk', 'social network', 'Sie ist in mehreren sozialen Netzwerken aktiv.', 'She is active on several social networks.', 'phrase'],
      ['der Beitrag', 'post, contribution', 'Ihr Beitrag wurde tausendmal geteilt.', 'Her post was shared a thousand times.', 'noun'],
      ['teilen', 'to share', 'Kannst du diesen Link mit mir teilen?', 'Can you share this link with me?', 'verb'],
      ['hochladen', 'to upload', 'Er lädt jede Woche ein neues Video hoch.', 'He uploads a new video every week.', 'verb'],
      ['herunterladen', 'to download', 'Ich möchte mir die App herunterladen.', 'I would like to download the app.', 'verb'],
      ['die Meldung', 'report, announcement', 'Eine kurze Meldung erschien in allen Zeitungen.', 'A short report appeared in all newspapers.', 'noun'],
      ['die Quelle', 'source', 'Nenn bitte deine Quelle für diese Behauptung.', 'Please name your source for this claim.', 'noun'],
      ['glaubwürdig', 'credible', 'Diese Website wirkt nicht sehr glaubwürdig.', 'This website does not seem very credible.', 'adjective'],
      ['die Zensur', 'censorship', 'In manchen Ländern gibt es strenge Zensur.', 'In some countries, there is strict censorship.', 'noun'],
      ['die Meinungsfreiheit', 'freedom of speech', 'Die Meinungsfreiheit ist ein wichtiges Grundrecht.', 'Freedom of speech is an important basic right.', 'noun'],
      ['die Öffentlichkeit', 'the public', 'Die Öffentlichkeit reagierte schockiert auf die Nachricht.', 'The public reacted with shock to the news.', 'noun'],
      ['öffentlich', 'public', 'Die Sitzung ist heute öffentlich.', 'The meeting is public today.', 'adjective'],
      ['das Abonnement', 'subscription', 'Ich habe ein Abonnement für diese Zeitschrift.', 'I have a subscription to this magazine.', 'noun'],
      ['abonnieren', 'to subscribe', 'Viele Leute abonnieren seinen Kanal.', 'Many people subscribe to his channel.', 'verb'],
      ['der Kommentar', 'comment', 'Unter dem Video stehen hunderte Kommentare.', 'There are hundreds of comments under the video.', 'noun'],
      ['kommentieren', 'to comment', 'Bitte kommentiert nicht so unhöflich.', 'Please don’t comment so rudely.', 'verb'],
      ['die Diskussion', 'discussion', 'Die Diskussion wurde sehr emotional.', 'The discussion became very emotional.', 'noun'],
      ['diskutieren', 'to discuss', 'Wir diskutieren oft über aktuelle Themen.', 'We often discuss current topics.', 'verb'],
      ['das Gespräch', 'conversation', 'Das Gespräch dauerte fast eine Stunde.', 'The conversation lasted almost an hour.', 'noun'],
      ['sich unterhalten', 'to chat, to converse', 'Wir haben uns lange über Politik unterhalten.', 'We talked for a long time about politics.', 'verb'],
      ['anrufen', 'to call, to phone', 'Ruf mich bitte heute Abend an.', 'Please call me tonight.', 'verb'],
      ['das Telefonat', 'phone call', 'Das Telefonat mit dem Kunden dauerte lange.', 'The phone call with the customer took a long time.', 'noun'],
      ['die SMS', 'text message', 'Ich schicke dir schnell eine SMS.', 'I’ll quickly send you a text message.', 'noun'],
      ['die E-Mail', 'email', 'Hast du meine E-Mail schon beantwortet?', 'Have you already answered my email?', 'noun'],
      ['der Anhang', 'attachment', 'Die Datei ist im Anhang der E-Mail.', 'The file is attached to the email.', 'noun'],
      ['senden', 'to send', 'Ich sende Ihnen die Unterlagen morgen.', 'I will send you the documents tomorrow.', 'verb'],
      ['empfangen', 'to receive', 'Wir haben Ihre Nachricht leider nicht empfangen.', 'Unfortunately, we did not receive your message.', 'verb'],
      ['die Verbindung', 'connection', 'Die Verbindung ist im Zug oft schlecht.', 'The connection is often bad on the train.', 'noun'],
      ['das Signal', 'signal', 'Hier gibt es kein Signal für das Handy.', 'There is no signal for the phone here.', 'noun'],
    ],
  },
  {
    title: 'Gefühle & Beziehungen',
    level: CefrLevel.B1,
    description: 'Emotionen, Freundschaft und Partnerschaft',
    iconEmoji: '❤️',
    items: [
      ['das Gefühl', 'feeling', 'Ich habe ein komisches Gefühl bei dieser Sache.', 'I have a strange feeling about this matter.', 'noun'],
      ['glücklich', 'happy', 'Sie wirkt heute sehr glücklich.', 'She seems very happy today.', 'adjective'],
      ['traurig', 'sad', 'Der Film hat ein trauriges Ende.', 'The movie has a sad ending.', 'adjective'],
      ['wütend', 'angry', 'Er war wütend über die Verspätung.', 'He was angry about the delay.', 'adjective'],
      ['ängstlich', 'anxious, fearful', 'Das Kind ist sehr ängstlich im Dunkeln.', 'The child is very fearful in the dark.', 'adjective'],
      ['eifersüchtig', 'jealous', 'Er wird schnell eifersüchtig.', 'He gets jealous quickly.', 'adjective'],
      ['enttäuscht', 'disappointed', 'Ich bin von dem Ergebnis enttäuscht.', 'I am disappointed with the result.', 'adjective'],
      ['stolz', 'proud', 'Die Eltern sind sehr stolz auf ihre Tochter.', 'The parents are very proud of their daughter.', 'adjective'],
      ['verliebt', 'in love', 'Die beiden sind total verliebt.', 'The two of them are totally in love.', 'adjective'],
      ['einsam', 'lonely', 'Nach dem Umzug fühlte sie sich sehr einsam.', 'After the move, she felt very lonely.', 'adjective'],
      ['gelangweilt', 'bored', 'Die Kinder wirkten gelangweilt.', 'The children seemed bored.', 'adjective'],
      ['überrascht', 'surprised', 'Ich war total überrascht von der Party.', 'I was totally surprised by the party.', 'adjective'],
      ['nervös', 'nervous', 'Vor der Prüfung war ich sehr nervös.', 'I was very nervous before the exam.', 'adjective'],
      ['entspannt', 'relaxed', 'Nach dem Urlaub fühlt er sich entspannt.', 'After the vacation, he feels relaxed.', 'adjective'],
      ['zufrieden', 'content, satisfied', 'Sie ist mit ihrem Job sehr zufrieden.', 'She is very satisfied with her job.', 'adjective'],
      ['unzufrieden', 'dissatisfied', 'Viele Kunden sind mit dem Service unzufrieden.', 'Many customers are dissatisfied with the service.', 'adjective'],
      ['sich freuen', 'to be happy, to look forward to', 'Ich freue mich auf das Wochenende.', 'I am looking forward to the weekend.', 'verb'],
      ['sich ärgern', 'to be annoyed', 'Er ärgert sich über den Stau.', 'He is annoyed about the traffic jam.', 'verb'],
      ['sich fühlen', 'to feel', 'Wie fühlst du dich heute?', 'How do you feel today?', 'verb'],
      ['lieben', 'to love', 'Ich liebe meine Familie über alles.', 'I love my family more than anything.', 'verb'],
      ['hassen', 'to hate', 'Sie hasst es, früh aufzustehen.', 'She hates getting up early.', 'verb'],
      ['vermissen', 'to miss (someone)', 'Ich vermisse meine Freunde aus der Heimat.', 'I miss my friends from home.', 'verb'],
      ['sich verlieben', 'to fall in love', 'Er hat sich sofort in sie verliebt.', 'He fell in love with her immediately.', 'verb'],
      ['die Beziehung', 'relationship', 'Die beiden führen eine glückliche Beziehung.', 'The two of them have a happy relationship.', 'noun'],
      ['die Freundschaft', 'friendship', 'Ihre Freundschaft besteht seit der Kindheit.', 'Their friendship has existed since childhood.', 'noun'],
      ['die Partnerschaft', 'partnership', 'Eine gute Partnerschaft braucht Vertrauen.', 'A good partnership needs trust.', 'noun'],
      ['der Partner', 'partner (male)', 'Mein Partner unterstützt mich in allem.', 'My partner supports me in everything.', 'noun'],
      ['die Partnerin', 'partner (female)', 'Seine Partnerin arbeitet als Ärztin.', 'His partner works as a doctor.', 'noun'],
      ['heiraten', 'to marry', 'Sie wollen im nächsten Sommer heiraten.', 'They want to get married next summer.', 'verb'],
      ['die Hochzeit', 'wedding', 'Die Hochzeit findet in einem alten Schloss statt.', 'The wedding will take place in an old castle.', 'noun'],
      ['sich trennen', 'to separate, to break up', 'Sie haben sich nach zehn Jahren getrennt.', 'They broke up after ten years.', 'verb'],
      ['die Trennung', 'separation, breakup', 'Die Trennung war für beide sehr schmerzhaft.', 'The breakup was very painful for both of them.', 'noun'],
      ['sich scheiden lassen', 'to get divorced', 'Meine Eltern haben sich letztes Jahr scheiden lassen.', 'My parents got divorced last year.', 'phrase'],
      ['die Scheidung', 'divorce', 'Die Scheidung dauerte fast zwei Jahre.', 'The divorce took almost two years.', 'noun'],
      ['vertrauen', 'to trust', 'Ich vertraue meinen besten Freunden vollkommen.', 'I trust my best friends completely.', 'verb'],
      ['das Vertrauen', 'trust', 'Vertrauen ist die Basis jeder Beziehung.', 'Trust is the basis of every relationship.', 'noun'],
      ['der Streit', 'argument, quarrel', 'Der Streit begann wegen einer Kleinigkeit.', 'The argument started over a trivial matter.', 'noun'],
      ['sich streiten', 'to argue', 'Die Geschwister streiten sich ständig.', 'The siblings argue constantly.', 'verb'],
      ['sich versöhnen', 'to reconcile, to make up', 'Zum Glück haben sie sich wieder versöhnt.', 'Fortunately, they made up again.', 'verb'],
      ['verzeihen', 'to forgive', 'Kannst du mir diesen Fehler verzeihen?', 'Can you forgive me for this mistake?', 'verb'],
      ['die Entschuldigung', 'apology', 'Seine Entschuldigung klang nicht sehr ehrlich.', 'His apology did not sound very sincere.', 'noun'],
      ['sich entschuldigen', 'to apologize', 'Er hat sich bei mir entschuldigt.', 'He apologized to me.', 'verb'],
      ['unterstützen', 'to support', 'Meine Familie unterstützt mich in jeder Situation.', 'My family supports me in every situation.', 'verb'],
      ['die Unterstützung', 'support', 'Ich bin dankbar für ihre Unterstützung.', 'I am grateful for her support.', 'noun'],
      ['der Respekt', 'respect', 'Er behandelt alle Kollegen mit Respekt.', 'He treats all colleagues with respect.', 'noun'],
      ['respektieren', 'to respect', 'Wir sollten die Meinung anderer respektieren.', 'We should respect the opinions of others.', 'verb'],
      ['die Rücksicht', 'consideration', 'Bitte nimm mehr Rücksicht auf deine Nachbarn.', 'Please be more considerate of your neighbors.', 'noun'],
      ['rücksichtsvoll', 'considerate', 'Er ist ein sehr rücksichtsvoller Mensch.', 'He is a very considerate person.', 'adjective'],
      ['ehrlich', 'honest', 'Sei bitte ehrlich zu mir.', 'Please be honest with me.', 'adjective'],
      ['die Ehrlichkeit', 'honesty', 'Ehrlichkeit ist mir sehr wichtig.', 'Honesty is very important to me.', 'noun'],
    ],
  },
];
