import { CefrLevel } from '@prisma/client';

/**
 * 250 spanische Vokabeln für CEFR A2 – fünf Themenpakete zu je 50 Wörtern.
 *
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 * Übersetzt wird ins Deutsche, weil die Oberfläche deutsch ist. Substantive
 * stehen mit Artikel, Verben im Infinitiv. Wörter aus A1 werden nicht wiederholt.
 */
export const SPANISH_VOCAB_A2 = [
  {
    title: 'Einkaufen & Geld',
    level: CefrLevel.A2,
    description: 'Im Geschäft, an der Kasse und bei der Bank zurechtkommen',
    iconEmoji: '🛍️',
    items: [
      ['la tienda', 'der Laden', 'La tienda cierra a las ocho.', 'Der Laden schließt um acht.', 'noun'],
      ['el supermercado', 'der Supermarkt', 'Voy al supermercado cada viernes.', 'Ich gehe jeden Freitag in den Supermarkt.', 'noun'],
      ['el mercado', 'der Markt', 'En el mercado la fruta es más barata.', 'Auf dem Markt ist das Obst billiger.', 'noun'],
      ['la panadería', 'die Bäckerei', 'Compro pan en la panadería de la esquina.', 'Ich kaufe Brot in der Bäckerei an der Ecke.', 'noun'],
      ['la farmacia', 'die Apotheke', 'La farmacia está abierta toda la noche.', 'Die Apotheke hat die ganze Nacht offen.', 'noun'],
      ['el centro comercial', 'das Einkaufszentrum', 'Quedamos en el centro comercial.', 'Wir treffen uns im Einkaufszentrum.', 'noun'],
      ['la caja', 'die Kasse', 'Hay mucha cola en la caja.', 'An der Kasse ist eine lange Schlange.', 'noun'],
      ['el cajero automático', 'der Geldautomat', 'Saco dinero del cajero automático.', 'Ich hebe Geld am Geldautomaten ab.', 'noun'],
      ['el dinero', 'das Geld', 'No llevo dinero encima.', 'Ich habe kein Geld dabei.', 'noun'],
      ['el billete', 'der Geldschein', 'Solo tengo un billete de cincuenta.', 'Ich habe nur einen Fünfzigerschein.', 'noun'],
      ['la moneda', 'die Münze', 'Necesito una moneda para el carrito.', 'Ich brauche eine Münze für den Einkaufswagen.', 'noun'],
      ['el precio', 'der Preis', 'El precio ha subido mucho.', 'Der Preis ist stark gestiegen.', 'noun'],
      ['la oferta', 'das Angebot', 'El pescado está de oferta.', 'Der Fisch ist im Angebot.', 'noun'],
      ['el descuento', 'der Rabatt', '¿Hay descuento para estudiantes?', 'Gibt es einen Rabatt für Studenten?', 'noun'],
      ['las rebajas', 'der Schlussverkauf', 'En enero empiezan las rebajas.', 'Im Januar beginnt der Schlussverkauf.', 'noun'],
      ['la ganga', 'das Schnäppchen', 'Este abrigo es una ganga.', 'Dieser Mantel ist ein Schnäppchen.', 'noun'],
      ['el escaparate', 'das Schaufenster', 'Vi los zapatos en el escaparate.', 'Ich habe die Schuhe im Schaufenster gesehen.', 'noun'],
      ['el cliente', 'der Kunde', 'El cliente siempre tiene razón.', 'Der Kunde hat immer recht.', 'noun'],
      ['el vendedor', 'der Verkäufer', 'El vendedor es muy paciente.', 'Der Verkäufer ist sehr geduldig.', 'noun'],
      ['la bolsa', 'die Tüte', '¿Quiere una bolsa de papel?', 'Möchten Sie eine Papiertüte?', 'noun'],
      ['el carrito', 'der Einkaufswagen', 'El carrito ya está lleno.', 'Der Einkaufswagen ist schon voll.', 'noun'],
      ['la lista de la compra', 'die Einkaufsliste', 'He olvidado la lista de la compra.', 'Ich habe die Einkaufsliste vergessen.', 'noun'],
      ['el recibo', 'der Kassenbon', 'Guarde el recibo, por favor.', 'Bewahren Sie bitte den Kassenbon auf.', 'noun'],
      ['la factura', 'die Rechnung', 'La factura llega a final de mes.', 'Die Rechnung kommt Ende des Monats.', 'noun'],
      ['la tarjeta de crédito', 'die Kreditkarte', '¿Puedo pagar con tarjeta de crédito?', 'Kann ich mit Kreditkarte bezahlen?', 'noun'],
      ['el efectivo', 'das Bargeld', 'Prefiero pagar en efectivo.', 'Ich zahle lieber bar.', 'noun'],
      ['el banco', 'die Bank', 'El banco abre a las nueve.', 'Die Bank öffnet um neun.', 'noun'],
      ['la cuenta bancaria', 'das Bankkonto', 'Abrí una cuenta bancaria ayer.', 'Ich habe gestern ein Bankkonto eröffnet.', 'noun'],
      ['el cambio', 'das Wechselgeld', 'Quédese con el cambio.', 'Behalten Sie das Wechselgeld.', 'noun'],
      ['el impuesto', 'die Steuer', 'El precio incluye el impuesto.', 'Der Preis enthält die Steuer.', 'noun'],
      ['la talla', 'die Kleidergröße', '¿Qué talla usa usted?', 'Welche Größe haben Sie?', 'noun'],
      ['el probador', 'die Umkleidekabine', 'El probador está al fondo.', 'Die Umkleidekabine ist hinten.', 'noun'],
      ['la ropa', 'die Kleidung', 'La ropa de invierno es cara.', 'Winterkleidung ist teuer.', 'noun'],
      ['la camisa', 'das Hemd', 'La camisa blanca está limpia.', 'Das weiße Hemd ist sauber.', 'noun'],
      ['los pantalones', 'die Hose', 'Estos pantalones me quedan grandes.', 'Diese Hose ist mir zu groß.', 'noun'],
      ['los zapatos', 'die Schuhe', 'Necesito zapatos nuevos.', 'Ich brauche neue Schuhe.', 'noun'],
      ['el abrigo', 'der Mantel', 'Llevo un abrigo gris.', 'Ich trage einen grauen Mantel.', 'noun'],
      ['el vestido', 'das Kleid', 'El vestido azul es precioso.', 'Das blaue Kleid ist wunderschön.', 'noun'],
      ['el bolso', 'die Handtasche', 'He dejado el bolso en casa.', 'Ich habe die Handtasche zu Hause gelassen.', 'noun'],
      ['el regalo', 'das Geschenk', 'Busco un regalo para mi madre.', 'Ich suche ein Geschenk für meine Mutter.', 'noun'],
      ['comprar', 'kaufen', 'Compro verdura los sábados.', 'Ich kaufe samstags Gemüse.', 'verb'],
      ['vender', 'verkaufen', 'Venden fruta muy fresca.', 'Sie verkaufen sehr frisches Obst.', 'verb'],
      ['pagar', 'bezahlen', 'Pago yo, no te preocupes.', 'Ich bezahle, keine Sorge.', 'verb'],
      ['costar', 'kosten', '¿Cuánto cuesta este libro?', 'Wie viel kostet dieses Buch?', 'verb'],
      ['gastar', 'ausgeben', 'Gasto demasiado en ropa.', 'Ich gebe zu viel für Kleidung aus.', 'verb'],
      ['ahorrar', 'sparen', 'Ahorro para un viaje largo.', 'Ich spare für eine lange Reise.', 'verb'],
      ['devolver', 'zurückgeben, umtauschen', 'Quiero devolver esta camisa.', 'Ich möchte dieses Hemd zurückgeben.', 'verb'],
      ['cambiar', 'wechseln, umtauschen', '¿Puedo cambiar el jersey por otra talla?', 'Kann ich den Pullover gegen eine andere Größe tauschen?', 'verb'],
      ['elegir', 'auswählen', 'Es difícil elegir entre los dos.', 'Es ist schwer, zwischen beiden zu wählen.', 'verb'],
      ['gratis', 'kostenlos', 'El envío es gratis.', 'Der Versand ist kostenlos.', 'adjective'],
    ],
  },
  {
    title: 'Reisen & Verkehr',
    level: CefrLevel.A2,
    description: 'Unterwegs mit Zug, Auto und Flugzeug',
    iconEmoji: '🚆',
    items: [
      ['el viaje', 'die Reise', 'El viaje dura cinco horas.', 'Die Reise dauert fünf Stunden.', 'noun'],
      ['el tren', 'der Zug', 'El tren sale del andén tres.', 'Der Zug fährt von Gleis drei ab.', 'noun'],
      ['el autobús', 'der Bus', 'El autobús pasa cada diez minutos.', 'Der Bus fährt alle zehn Minuten.', 'noun'],
      ['el avión', 'das Flugzeug', 'El avión aterriza a las seis.', 'Das Flugzeug landet um sechs.', 'noun'],
      ['el coche', 'das Auto', 'Vamos en coche hasta Valencia.', 'Wir fahren mit dem Auto bis Valencia.', 'noun'],
      ['la bicicleta', 'das Fahrrad', 'Voy al trabajo en bicicleta.', 'Ich fahre mit dem Fahrrad zur Arbeit.', 'noun'],
      ['el metro', 'die U-Bahn', 'El metro es lo más rápido.', 'Die U-Bahn ist am schnellsten.', 'noun'],
      ['el taxi', 'das Taxi', 'Cogemos un taxi al aeropuerto.', 'Wir nehmen ein Taxi zum Flughafen.', 'noun'],
      ['el barco', 'das Schiff', 'El barco llega a la isla al mediodía.', 'Das Schiff erreicht die Insel mittags.', 'noun'],
      ['la estación', 'der Bahnhof', 'Te espero en la estación.', 'Ich warte am Bahnhof auf dich.', 'noun'],
      ['el aeropuerto', 'der Flughafen', 'El aeropuerto está lejos del centro.', 'Der Flughafen ist weit vom Zentrum entfernt.', 'noun'],
      ['la parada', 'die Haltestelle', 'Bájate en la próxima parada.', 'Steig an der nächsten Haltestelle aus.', 'noun'],
      ['el andén', 'der Bahnsteig', 'El andén está lleno de gente.', 'Der Bahnsteig ist voller Menschen.', 'noun'],
      ['el billete de ida y vuelta', 'die Rückfahrkarte', 'Quiero un billete de ida y vuelta.', 'Ich möchte eine Rückfahrkarte.', 'noun'],
      ['el horario', 'der Fahrplan', 'Mira el horario en la pantalla.', 'Schau auf den Fahrplan auf dem Bildschirm.', 'noun'],
      ['el retraso', 'die Verspätung', 'El tren lleva veinte minutos de retraso.', 'Der Zug hat zwanzig Minuten Verspätung.', 'noun'],
      ['la maleta', 'der Koffer', 'Mi maleta pesa demasiado.', 'Mein Koffer ist zu schwer.', 'noun'],
      ['la mochila', 'der Rucksack', 'Llevo el portátil en la mochila.', 'Ich habe den Laptop im Rucksack.', 'noun'],
      ['el equipaje', 'das Gepäck', 'Dejamos el equipaje en el hotel.', 'Wir lassen das Gepäck im Hotel.', 'noun'],
      ['el pasaporte', 'der Reisepass', 'Mi pasaporte caduca en marzo.', 'Mein Reisepass läuft im März ab.', 'noun'],
      ['el hotel', 'das Hotel', 'El hotel está frente al mar.', 'Das Hotel liegt direkt am Meer.', 'noun'],
      ['la reserva', 'die Reservierung', 'Tengo una reserva a nombre de Ruiz.', 'Ich habe eine Reservierung auf den Namen Ruiz.', 'noun'],
      ['la recepción', 'die Rezeption', 'Pregunta en la recepción.', 'Frag an der Rezeption.', 'noun'],
      ['el camping', 'der Campingplatz', 'Dormimos en un camping cerca del río.', 'Wir schlafen auf einem Campingplatz am Fluss.', 'noun'],
      ['las vacaciones', 'der Urlaub', 'Las vacaciones empiezan el lunes.', 'Der Urlaub beginnt am Montag.', 'noun'],
      ['la playa', 'der Strand', 'La playa está a diez minutos.', 'Der Strand ist zehn Minuten entfernt.', 'noun'],
      ['la montaña', 'der Berg', 'En verano vamos a la montaña.', 'Im Sommer fahren wir in die Berge.', 'noun'],
      ['el mapa', 'die Karte', 'Sin mapa me pierdo siempre.', 'Ohne Karte verlaufe ich mich immer.', 'noun'],
      ['la excursión', 'der Ausflug', 'Hacemos una excursión al lago.', 'Wir machen einen Ausflug zum See.', 'noun'],
      ['la frontera', 'die Grenze', 'Cruzamos la frontera por la noche.', 'Wir überqueren nachts die Grenze.', 'noun'],
      ['el carné de conducir', 'der Führerschein', 'Se me ha caducado el carné de conducir.', 'Mein Führerschein ist abgelaufen.', 'noun'],
      ['la gasolina', 'das Benzin', 'La gasolina está muy cara.', 'Das Benzin ist sehr teuer.', 'noun'],
      ['la autopista', 'die Autobahn', 'La autopista está cortada.', 'Die Autobahn ist gesperrt.', 'noun'],
      ['el semáforo', 'die Ampel', 'Gira a la izquierda en el semáforo.', 'Bieg an der Ampel links ab.', 'noun'],
      ['el atasco', 'der Stau', 'Hay un atasco de cinco kilómetros.', 'Es gibt einen fünf Kilometer langen Stau.', 'noun'],
      ['el accidente', 'der Unfall', 'Ha habido un accidente en la curva.', 'In der Kurve ist ein Unfall passiert.', 'noun'],
      ['la ruta', 'die Strecke, Route', 'Esta ruta es más corta.', 'Diese Strecke ist kürzer.', 'noun'],
      ['el asiento', 'der Sitzplatz', 'Mi asiento está junto a la ventana.', 'Mein Sitzplatz ist am Fenster.', 'noun'],
      ['la salida', 'die Abfahrt, der Ausgang', 'La salida es a las siete en punto.', 'Die Abfahrt ist um Punkt sieben.', 'noun'],
      ['la llegada', 'die Ankunft', 'La llegada está prevista a mediodía.', 'Die Ankunft ist für mittags geplant.', 'noun'],
      ['viajar', 'reisen', 'Viajo mucho por trabajo.', 'Ich reise viel beruflich.', 'verb'],
      ['volar', 'fliegen', 'Volamos a Lima en octubre.', 'Wir fliegen im Oktober nach Lima.', 'verb'],
      ['conducir', 'Auto fahren', 'No me gusta conducir de noche.', 'Ich fahre nachts nicht gern Auto.', 'verb'],
      ['aparcar', 'parken', 'Aquí no se puede aparcar.', 'Hier darf man nicht parken.', 'verb'],
      ['llegar', 'ankommen', 'Llegamos tarde por el atasco.', 'Wegen des Staus kommen wir zu spät an.', 'verb'],
      ['reservar', 'reservieren', 'He reservado una mesa para dos.', 'Ich habe einen Tisch für zwei reserviert.', 'verb'],
      ['alquilar', 'mieten', 'Alquilamos un coche en el aeropuerto.', 'Wir mieten am Flughafen ein Auto.', 'verb'],
      ['perder', 'verpassen, verlieren', 'He perdido el último tren.', 'Ich habe den letzten Zug verpasst.', 'verb'],
      ['rápido', 'schnell', 'El tren es más rápido que el coche.', 'Der Zug ist schneller als das Auto.', 'adjective'],
      ['lejos', 'weit weg', 'El pueblo está lejos de aquí.', 'Das Dorf ist weit von hier entfernt.', 'adverb'],
    ],
  },
  {
    title: 'Gesundheit & Körper',
    level: CefrLevel.A2,
    description: 'Körperteile, Krankheiten und der Arztbesuch',
    iconEmoji: '🩺',
    items: [
      ['el cuerpo', 'der Körper', 'El deporte es bueno para el cuerpo.', 'Sport ist gut für den Körper.', 'noun'],
      ['la cabeza', 'der Kopf', 'Me duele la cabeza.', 'Ich habe Kopfschmerzen.', 'noun'],
      ['el pelo', 'das Haar', 'Tiene el pelo muy largo.', 'Sie hat sehr lange Haare.', 'noun'],
      ['la cara', 'das Gesicht', 'Se lava la cara con agua fría.', 'Er wäscht sich das Gesicht mit kaltem Wasser.', 'noun'],
      ['el ojo', 'das Auge', 'Tiene los ojos verdes.', 'Sie hat grüne Augen.', 'noun'],
      ['la nariz', 'die Nase', 'Me sangra la nariz.', 'Meine Nase blutet.', 'noun'],
      ['la boca', 'der Mund', 'Abre la boca, por favor.', 'Mach bitte den Mund auf.', 'noun'],
      ['la oreja', 'das Ohr', 'Me duele la oreja derecha.', 'Mein rechtes Ohr tut weh.', 'noun'],
      ['el diente', 'der Zahn', 'Me duele un diente desde ayer.', 'Seit gestern tut mir ein Zahn weh.', 'noun'],
      ['el cuello', 'der Hals, Nacken', 'Tengo el cuello rígido.', 'Mein Nacken ist steif.', 'noun'],
      ['el hombro', 'die Schulter', 'Me he hecho daño en el hombro.', 'Ich habe mir die Schulter verletzt.', 'noun'],
      ['el brazo', 'der Arm', 'Se rompió el brazo esquiando.', 'Er hat sich beim Skifahren den Arm gebrochen.', 'noun'],
      ['la mano', 'die Hand', 'Lávate las manos antes de comer.', 'Wasch dir vor dem Essen die Hände.', 'noun'],
      ['el dedo', 'der Finger', 'Me he cortado un dedo.', 'Ich habe mir in den Finger geschnitten.', 'noun'],
      ['la espalda', 'der Rücken', 'Me duele la espalda al levantarme.', 'Beim Aufstehen tut mir der Rücken weh.', 'noun'],
      ['el estómago', 'der Magen', 'Tengo el estómago revuelto.', 'Mir ist übel.', 'noun'],
      ['la pierna', 'das Bein', 'Después de correr me duelen las piernas.', 'Nach dem Laufen tun mir die Beine weh.', 'noun'],
      ['la rodilla', 'das Knie', 'Llevo una venda en la rodilla.', 'Ich habe einen Verband am Knie.', 'noun'],
      ['el pie', 'der Fuß', 'Tengo los pies fríos.', 'Ich habe kalte Füße.', 'noun'],
      ['el corazón', 'das Herz', 'El corazón late muy deprisa.', 'Das Herz schlägt sehr schnell.', 'noun'],
      ['la piel', 'die Haut', 'El sol daña la piel.', 'Die Sonne schadet der Haut.', 'noun'],
      ['la sangre', 'das Blut', 'No soporto ver sangre.', 'Ich kann kein Blut sehen.', 'noun'],
      ['el hueso', 'der Knochen', 'La radiografía muestra el hueso roto.', 'Das Röntgenbild zeigt den gebrochenen Knochen.', 'noun'],
      ['la salud', 'die Gesundheit', 'La salud es lo más importante.', 'Gesundheit ist das Wichtigste.', 'noun'],
      ['la enfermedad', 'die Krankheit', 'Es una enfermedad poco frecuente.', 'Das ist eine seltene Krankheit.', 'noun'],
      ['el dolor', 'der Schmerz', 'El dolor ha desaparecido.', 'Der Schmerz ist verschwunden.', 'noun'],
      ['la fiebre', 'das Fieber', 'El niño tiene fiebre alta.', 'Das Kind hat hohes Fieber.', 'noun'],
      ['el resfriado', 'die Erkältung', 'Tengo un resfriado desde el lunes.', 'Ich habe seit Montag eine Erkältung.', 'noun'],
      ['la tos', 'der Husten', 'La tos no me deja dormir.', 'Der Husten lässt mich nicht schlafen.', 'noun'],
      ['la gripe', 'die Grippe', 'Media oficina tiene gripe.', 'Das halbe Büro hat Grippe.', 'noun'],
      ['la herida', 'die Wunde', 'La herida ya está curada.', 'Die Wunde ist schon verheilt.', 'noun'],
      ['la medicina', 'das Medikament', 'Toma la medicina después de comer.', 'Nimm das Medikament nach dem Essen.', 'noun'],
      ['la pastilla', 'die Tablette', 'Una pastilla cada ocho horas.', 'Eine Tablette alle acht Stunden.', 'noun'],
      ['la receta', 'das Rezept', 'Sin receta no venden este jarabe.', 'Ohne Rezept verkaufen sie diesen Sirup nicht.', 'noun'],
      ['la cita', 'der Termin', 'Tengo cita con el dentista.', 'Ich habe einen Termin beim Zahnarzt.', 'noun'],
      ['el hospital', 'das Krankenhaus', 'Lo llevaron al hospital en ambulancia.', 'Man brachte ihn mit dem Krankenwagen ins Krankenhaus.', 'noun'],
      ['la consulta', 'die Praxis, Sprechstunde', 'La consulta abre por la tarde.', 'Die Praxis hat nachmittags geöffnet.', 'noun'],
      ['la enfermera', 'die Krankenschwester', 'La enfermera me puso una inyección.', 'Die Krankenschwester gab mir eine Spritze.', 'noun'],
      ['las urgencias', 'die Notaufnahme', 'Fuimos a urgencias de madrugada.', 'Wir sind früh morgens in die Notaufnahme gefahren.', 'noun'],
      ['el seguro médico', 'die Krankenversicherung', 'Mi seguro médico lo cubre.', 'Meine Krankenversicherung übernimmt das.', 'noun'],
      ['doler', 'wehtun', 'Me duelen los ojos de leer.', 'Vom Lesen tun mir die Augen weh.', 'verb'],
      ['sentirse', 'sich fühlen', 'Hoy me siento mucho mejor.', 'Heute fühle ich mich viel besser.', 'verb'],
      ['curar', 'heilen', 'Este té cura el dolor de garganta.', 'Dieser Tee heilt Halsschmerzen.', 'verb'],
      ['recuperarse', 'sich erholen', 'Se recupera muy despacio.', 'Er erholt sich sehr langsam.', 'verb'],
      ['toser', 'husten', 'Toso mucho por la noche.', 'Nachts huste ich viel.', 'verb'],
      ['respirar', 'atmen', 'Respira hondo, por favor.', 'Atmen Sie bitte tief ein.', 'verb'],
      ['operar', 'operieren', 'La operan mañana por la mañana.', 'Sie wird morgen früh operiert.', 'verb'],
      ['sano', 'gesund', 'Mi abuela está sana a sus ochenta años.', 'Meine Großmutter ist mit achtzig gesund.', 'adjective'],
      ['grave', 'ernst, schwer', 'Por suerte no es nada grave.', 'Zum Glück ist es nichts Ernstes.', 'adjective'],
      ['débil', 'schwach', 'Después de la gripe me siento débil.', 'Nach der Grippe fühle ich mich schwach.', 'adjective'],
    ],
  },
  {
    title: 'Wetter & Jahreszeiten',
    level: CefrLevel.A2,
    description: 'Über das Wetter und die vier Jahreszeiten sprechen',
    iconEmoji: '☀️',
    items: [
      ['el tiempo', 'das Wetter', '¿Qué tiempo hace hoy?', 'Wie ist heute das Wetter?', 'noun'],
      ['el clima', 'das Klima', 'El clima del sur es más suave.', 'Das Klima im Süden ist milder.', 'noun'],
      ['la estación del año', 'die Jahreszeit', 'El otoño es mi estación del año favorita.', 'Der Herbst ist meine Lieblingsjahreszeit.', 'noun'],
      ['la primavera', 'der Frühling', 'En primavera florecen los almendros.', 'Im Frühling blühen die Mandelbäume.', 'noun'],
      ['el verano', 'der Sommer', 'El verano aquí es muy largo.', 'Der Sommer ist hier sehr lang.', 'noun'],
      ['el otoño', 'der Herbst', 'En otoño caen las hojas.', 'Im Herbst fallen die Blätter.', 'noun'],
      ['el invierno', 'der Winter', 'El invierno pasado nevó poco.', 'Letzten Winter hat es kaum geschneit.', 'noun'],
      ['el sol', 'die Sonne', 'El sol sale a las siete.', 'Die Sonne geht um sieben auf.', 'noun'],
      ['la lluvia', 'der Regen', 'La lluvia ha estropeado la fiesta.', 'Der Regen hat das Fest verdorben.', 'noun'],
      ['la nieve', 'der Schnee', 'La nieve cubre las montañas.', 'Der Schnee bedeckt die Berge.', 'noun'],
      ['la nube', 'die Wolke', 'No hay ni una nube en el cielo.', 'Es ist keine Wolke am Himmel.', 'noun'],
      ['el viento', 'der Wind', 'El viento sopla del norte.', 'Der Wind weht aus Norden.', 'noun'],
      ['la tormenta', 'das Gewitter, der Sturm', 'Se acerca una tormenta fuerte.', 'Ein starkes Gewitter zieht auf.', 'noun'],
      ['el trueno', 'der Donner', 'El trueno asustó al perro.', 'Der Donner hat den Hund erschreckt.', 'noun'],
      ['el relámpago', 'der Blitz', 'Vi un relámpago sobre el mar.', 'Ich sah einen Blitz über dem Meer.', 'noun'],
      ['la niebla', 'der Nebel', 'Hay mucha niebla en el valle.', 'Im Tal ist dichter Nebel.', 'noun'],
      ['el hielo', 'das Eis, Glatteis', 'Cuidado, hay hielo en la carretera.', 'Vorsicht, auf der Straße ist Glatteis.', 'noun'],
      ['la temperatura', 'die Temperatur', 'La temperatura baja por la noche.', 'Nachts sinkt die Temperatur.', 'noun'],
      ['el grado', 'das Grad', 'Estamos a treinta grados.', 'Wir haben dreißig Grad.', 'noun'],
      ['el paraguas', 'der Regenschirm', 'Coge el paraguas, va a llover.', 'Nimm den Regenschirm mit, es wird regnen.', 'noun'],
      ['la bufanda', 'der Schal', 'Sin bufanda hace demasiado frío.', 'Ohne Schal ist es zu kalt.', 'noun'],
      ['los guantes', 'die Handschuhe', 'He perdido un guante en el autobús.', 'Ich habe im Bus einen Handschuh verloren.', 'noun'],
      ['las gafas de sol', 'die Sonnenbrille', 'Necesito gafas de sol en la playa.', 'Am Strand brauche ich eine Sonnenbrille.', 'noun'],
      ['la sombra', 'der Schatten', 'Sentémonos a la sombra.', 'Setzen wir uns in den Schatten.', 'noun'],
      ['el cielo', 'der Himmel', 'El cielo está completamente azul.', 'Der Himmel ist ganz blau.', 'noun'],
      ['el arcoíris', 'der Regenbogen', 'Después de la lluvia salió un arcoíris.', 'Nach dem Regen kam ein Regenbogen.', 'noun'],
      ['la humedad', 'die Feuchtigkeit', 'La humedad aquí es insoportable.', 'Die Feuchtigkeit ist hier unerträglich.', 'noun'],
      ['la sequía', 'die Dürre', 'La sequía dura ya tres años.', 'Die Dürre dauert schon drei Jahre.', 'noun'],
      ['la inundación', 'die Überschwemmung', 'La inundación cortó la carretera.', 'Die Überschwemmung hat die Straße gesperrt.', 'noun'],
      ['el pronóstico del tiempo', 'die Wettervorhersage', 'El pronóstico del tiempo anuncia lluvia.', 'Die Wettervorhersage kündigt Regen an.', 'noun'],
      ['llover', 'regnen', 'Llueve desde esta mañana.', 'Es regnet seit heute Morgen.', 'verb'],
      ['nevar', 'schneien', 'En diciembre suele nevar.', 'Im Dezember schneit es meistens.', 'verb'],
      ['hacer sol', 'sonnig sein', 'Hoy hace sol todo el día.', 'Heute scheint den ganzen Tag die Sonne.', 'phrase'],
      ['hacer frío', 'kalt sein', 'En la sierra hace mucho frío.', 'Im Gebirge ist es sehr kalt.', 'phrase'],
      ['hacer calor', 'heiß sein', 'En agosto hace un calor terrible.', 'Im August ist es furchtbar heiß.', 'phrase'],
      ['soplar', 'wehen', 'Sopla un viento muy fuerte.', 'Es weht ein sehr starker Wind.', 'verb'],
      ['helar', 'frieren', 'Esta noche va a helar.', 'Heute Nacht wird es frieren.', 'verb'],
      ['mojarse', 'nass werden', 'Me he mojado entera.', 'Ich bin völlig nass geworden.', 'verb'],
      ['despejarse', 'aufklaren', 'Por la tarde se despeja el cielo.', 'Am Nachmittag klart der Himmel auf.', 'verb'],
      ['secarse', 'trocknen', 'La ropa se seca rápido al sol.', 'Die Wäsche trocknet in der Sonne schnell.', 'verb'],
      ['caluroso', 'heiß, warm', 'Fue un verano muy caluroso.', 'Es war ein sehr heißer Sommer.', 'adjective'],
      ['frío', 'kalt', 'El agua del mar está fría.', 'Das Meerwasser ist kalt.', 'adjective'],
      ['fresco', 'frisch, kühl', 'Por la noche hace fresco.', 'Nachts ist es kühl.', 'adjective'],
      ['templado', 'mild', 'El clima es templado todo el año.', 'Das Klima ist ganzjährig mild.', 'adjective'],
      ['húmedo', 'feucht', 'El aire está muy húmedo.', 'Die Luft ist sehr feucht.', 'adjective'],
      ['seco', 'trocken', 'El verano fue seco y largo.', 'Der Sommer war trocken und lang.', 'adjective'],
      ['soleado', 'sonnig', 'Nos espera un día soleado.', 'Uns erwartet ein sonniger Tag.', 'adjective'],
      ['nublado', 'bewölkt', 'Está nublado desde el amanecer.', 'Seit dem Morgengrauen ist es bewölkt.', 'adjective'],
      ['ventoso', 'windig', 'La costa es muy ventosa.', 'An der Küste ist es sehr windig.', 'adjective'],
      ['agradable', 'angenehm', 'Hace una temperatura agradable.', 'Die Temperatur ist angenehm.', 'adjective'],
    ],
  },
  {
    title: 'Freizeit & Hobbys',
    level: CefrLevel.A2,
    description: 'Über Hobbys, Sport und Kultur sprechen',
    iconEmoji: '🎨',
    items: [
      ['el tiempo libre', 'die Freizeit', 'En mi tiempo libre leo mucho.', 'In meiner Freizeit lese ich viel.', 'noun'],
      ['la afición', 'das Hobby', 'Su afición es la fotografía.', 'Sein Hobby ist die Fotografie.', 'noun'],
      ['el deporte', 'der Sport', 'Hago deporte tres veces por semana.', 'Ich treibe dreimal pro Woche Sport.', 'noun'],
      ['el fútbol', 'der Fußball', 'El fútbol es el deporte más popular.', 'Fußball ist die beliebteste Sportart.', 'noun'],
      ['el baloncesto', 'der Basketball', 'Jugué al baloncesto en el instituto.', 'Ich habe in der Schule Basketball gespielt.', 'noun'],
      ['la natación', 'das Schwimmen', 'La natación es buena para la espalda.', 'Schwimmen ist gut für den Rücken.', 'noun'],
      ['el gimnasio', 'das Fitnessstudio', 'Voy al gimnasio antes del trabajo.', 'Ich gehe vor der Arbeit ins Fitnessstudio.', 'noun'],
      ['el equipo', 'die Mannschaft', 'Nuestro equipo ganó la liga.', 'Unsere Mannschaft hat die Liga gewonnen.', 'noun'],
      ['el partido', 'das Spiel', 'El partido empieza a las nueve.', 'Das Spiel beginnt um neun.', 'noun'],
      ['el jugador', 'der Spieler', 'Ese jugador es muy rápido.', 'Dieser Spieler ist sehr schnell.', 'noun'],
      ['el entrenamiento', 'das Training', 'El entrenamiento dura dos horas.', 'Das Training dauert zwei Stunden.', 'noun'],
      ['la música', 'die Musik', 'Escucho música mientras cocino.', 'Ich höre Musik, während ich koche.', 'noun'],
      ['la canción', 'das Lied', 'Esta canción me encanta.', 'Dieses Lied gefällt mir sehr.', 'noun'],
      ['el concierto', 'das Konzert', 'El concierto fue increíble.', 'Das Konzert war unglaublich.', 'noun'],
      ['el instrumento', 'das Instrument', '¿Tocas algún instrumento?', 'Spielst du ein Instrument?', 'noun'],
      ['la guitarra', 'die Gitarre', 'Aprendo a tocar la guitarra.', 'Ich lerne Gitarre spielen.', 'noun'],
      ['el piano', 'das Klavier', 'Hay un piano viejo en el salón.', 'Im Wohnzimmer steht ein altes Klavier.', 'noun'],
      ['el baile', 'der Tanz', 'El baile empieza a medianoche.', 'Der Tanz beginnt um Mitternacht.', 'noun'],
      ['el cine', 'das Kino', 'Vamos al cine el viernes.', 'Wir gehen am Freitag ins Kino.', 'noun'],
      ['la película', 'der Film', 'La película dura tres horas.', 'Der Film dauert drei Stunden.', 'noun'],
      ['el teatro', 'das Theater', 'El teatro está en el centro.', 'Das Theater ist im Zentrum.', 'noun'],
      ['la obra de teatro', 'das Theaterstück', 'La obra de teatro es de Lorca.', 'Das Theaterstück ist von Lorca.', 'noun'],
      ['el museo', 'das Museum', 'El museo es gratis los domingos.', 'Das Museum ist sonntags kostenlos.', 'noun'],
      ['la exposición', 'die Ausstellung', 'La exposición cierra el mes que viene.', 'Die Ausstellung schließt nächsten Monat.', 'noun'],
      ['la novela', 'der Roman', 'Estoy leyendo una novela policíaca.', 'Ich lese gerade einen Kriminalroman.', 'noun'],
      ['la revista', 'die Zeitschrift', 'Compro una revista para el viaje.', 'Ich kaufe eine Zeitschrift für die Reise.', 'noun'],
      ['el periódico', 'die Zeitung', 'Leo el periódico con el desayuno.', 'Ich lese die Zeitung beim Frühstück.', 'noun'],
      ['la fiesta', 'die Party, das Fest', 'La fiesta terminó muy tarde.', 'Die Party endete sehr spät.', 'noun'],
      ['el juego', 'das Spiel', 'Este juego es para toda la familia.', 'Dieses Spiel ist für die ganze Familie.', 'noun'],
      ['el ajedrez', 'das Schach', 'Juego al ajedrez con mi abuelo.', 'Ich spiele mit meinem Großvater Schach.', 'noun'],
      ['el videojuego', 'das Videospiel', 'Mi hijo pasa horas con los videojuegos.', 'Mein Sohn verbringt Stunden mit Videospielen.', 'noun'],
      ['la foto', 'das Foto', 'Hazme una foto delante de la catedral.', 'Mach ein Foto von mir vor der Kathedrale.', 'noun'],
      ['la cámara', 'die Kamera', 'La cámara se quedó sin batería.', 'Die Kamera hatte keinen Akku mehr.', 'noun'],
      ['el dibujo', 'die Zeichnung', 'Este dibujo lo hizo mi hija.', 'Diese Zeichnung hat meine Tochter gemacht.', 'noun'],
      ['la pintura', 'die Malerei, das Gemälde', 'Le interesa la pintura moderna.', 'Sie interessiert sich für moderne Malerei.', 'noun'],
      ['el paseo', 'der Spaziergang', 'Damos un paseo por el río.', 'Wir machen einen Spaziergang am Fluss.', 'noun'],
      ['la piscina', 'das Schwimmbad', 'La piscina abre en junio.', 'Das Schwimmbad öffnet im Juni.', 'noun'],
      ['el parque', 'der Park', 'Los niños juegan en el parque.', 'Die Kinder spielen im Park.', 'noun'],
      ['el club', 'der Verein, Club', 'Soy socio de un club de tenis.', 'Ich bin Mitglied in einem Tennisverein.', 'noun'],
      ['la entrada', 'die Eintrittskarte', 'Las entradas están agotadas.', 'Die Karten sind ausverkauft.', 'noun'],
      ['jugar', 'spielen', 'Jugamos a las cartas los domingos.', 'Wir spielen sonntags Karten.', 'verb'],
      ['correr', 'laufen, rennen', 'Corro cinco kilómetros cada mañana.', 'Ich laufe jeden Morgen fünf Kilometer.', 'verb'],
      ['nadar', 'schwimmen', 'Nado mejor que corro.', 'Ich schwimme besser, als ich laufe.', 'verb'],
      ['bailar', 'tanzen', 'Bailamos hasta las tres.', 'Wir haben bis drei getanzt.', 'verb'],
      ['cantar', 'singen', 'Canta en un coro desde niña.', 'Sie singt seit ihrer Kindheit in einem Chor.', 'verb'],
      ['tocar', 'spielen (Instrument)', 'Toca el violín muy bien.', 'Er spielt sehr gut Geige.', 'verb'],
      ['dibujar', 'zeichnen', 'Dibujo cuando estoy nervioso.', 'Ich zeichne, wenn ich nervös bin.', 'verb'],
      ['entrenar', 'trainieren', 'Entrenamos los martes y jueves.', 'Wir trainieren dienstags und donnerstags.', 'verb'],
      ['ganar', 'gewinnen', 'Ganamos por dos goles.', 'Wir haben mit zwei Toren gewonnen.', 'verb'],
      ['divertirse', 'sich amüsieren', 'Nos divertimos muchísimo.', 'Wir haben uns sehr amüsiert.', 'verb'],
    ],
  },
];
