import { CefrLevel } from '@prisma/client';

/**
 * 250 spanische Vokabeln für CEFR A1 – fünf Themenpakete zu je 50 Wörtern.
 *
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 * Übersetzt wird ins Deutsche, weil die Oberfläche deutsch ist – anders als bei
 * den Deutsch-Stapeln, die für Lernende aus aller Welt ins Englische gehen.
 * Substantive stehen mit Artikel, Verben im Infinitiv.
 */
export const SPANISH_VOCAB_A1 = [
  {
    title: 'Begrüßung & Alltag',
    level: CefrLevel.A1,
    description: 'Die wichtigsten Wörter für den ersten Kontakt und den Alltag',
    iconEmoji: '👋',
    items: [
      ['hola', 'hallo', '¡Hola! ¿Cómo estás?', 'Hallo! Wie geht es dir?', 'interjection'],
      ['adiós', 'auf Wiedersehen', 'Adiós, hasta mañana.', 'Auf Wiedersehen, bis morgen.', 'interjection'],
      ['buenos días', 'guten Morgen', 'Buenos días, señora López.', 'Guten Morgen, Frau López.', 'phrase'],
      ['buenas noches', 'gute Nacht', 'Buenas noches, que duermas bien.', 'Gute Nacht, schlaf gut.', 'phrase'],
      ['por favor', 'bitte', 'Un café, por favor.', 'Einen Kaffee, bitte.', 'phrase'],
      ['gracias', 'danke', 'Gracias por tu ayuda.', 'Danke für deine Hilfe.', 'interjection'],
      ['de nada', 'gern geschehen', 'De nada, no es nada.', 'Gern geschehen, das ist nichts.', 'phrase'],
      ['perdón', 'Entschuldigung', 'Perdón, ¿dónde está la estación?', 'Entschuldigung, wo ist der Bahnhof?', 'noun'],
      ['sí', 'ja', 'Sí, eso es correcto.', 'Ja, das ist richtig.', 'adverb'],
      ['no', 'nein', 'No, no es verdad.', 'Nein, das stimmt nicht.', 'adverb'],
      ['bueno', 'gut', 'La comida está muy buena.', 'Das Essen ist sehr gut.', 'adjective'],
      ['malo', 'schlecht', 'Hoy hace mal tiempo.', 'Heute ist schlechtes Wetter.', 'adjective'],
      ['el nombre', 'der Name', 'Mi nombre es Ana.', 'Mein Name ist Ana.', 'noun'],
      ['llamarse', 'heißen', '¿Cómo te llamas?', 'Wie heißt du?', 'verb'],
      ['ser', 'sein (dauerhaft)', 'Yo soy estudiante.', 'Ich bin Studentin.', 'verb'],
      ['estar', 'sein (Zustand, Ort)', 'Estoy en casa.', 'Ich bin zu Hause.', 'verb'],
      ['tener', 'haben', 'Tengo una pregunta.', 'Ich habe eine Frage.', 'verb'],
      ['hablar', 'sprechen', '¿Hablas español?', 'Sprichst du Spanisch?', 'verb'],
      ['entender', 'verstehen', 'No entiendo esta palabra.', 'Ich verstehe dieses Wort nicht.', 'verb'],
      ['vivir', 'wohnen, leben', 'Vivo en Madrid.', 'Ich wohne in Madrid.', 'verb'],
      ['venir', 'kommen', '¿De dónde vienes?', 'Woher kommst du?', 'verb'],
      ['ir', 'gehen, fahren', 'Voy al trabajo.', 'Ich gehe zur Arbeit.', 'verb'],
      ['el idioma', 'die Sprache', 'El español es un idioma bonito.', 'Spanisch ist eine schöne Sprache.', 'noun'],
      ['la palabra', 'das Wort', 'No conozco esa palabra.', 'Ich kenne dieses Wort nicht.', 'noun'],
      ['el día', 'der Tag', 'Hoy es un día largo.', 'Heute ist ein langer Tag.', 'noun'],
      ['la noche', 'die Nacht', 'La noche está tranquila.', 'Die Nacht ist ruhig.', 'noun'],
      ['la mañana', 'der Morgen', 'Por la mañana bebo café.', 'Am Morgen trinke ich Kaffee.', 'noun'],
      ['la tarde', 'der Nachmittag', 'Por la tarde estudio.', 'Am Nachmittag lerne ich.', 'noun'],
      ['hoy', 'heute', 'Hoy hace sol.', 'Heute scheint die Sonne.', 'adverb'],
      ['mañana', 'morgen', 'Mañana voy a casa.', 'Morgen fahre ich nach Hause.', 'adverb'],
      ['ayer', 'gestern', 'Ayer estuve en el cine.', 'Gestern war ich im Kino.', 'adverb'],
      ['aquí', 'hier', 'Vivo aquí desde hace dos años.', 'Ich wohne seit zwei Jahren hier.', 'adverb'],
      ['allí', 'dort', 'El libro está allí, en la mesa.', 'Das Buch liegt dort auf dem Tisch.', 'adverb'],
      ['y', 'und', 'Bebo café y como pan.', 'Ich trinke Kaffee und esse Brot.', 'conjunction'],
      ['o', 'oder', '¿Quieres té o café?', 'Möchtest du Tee oder Kaffee?', 'conjunction'],
      ['pero', 'aber', 'Estoy cansado, pero contento.', 'Ich bin müde, aber zufrieden.', 'conjunction'],
      ['porque', 'weil', 'No voy porque estoy enfermo.', 'Ich gehe nicht, weil ich krank bin.', 'conjunction'],
      ['cómo', 'wie', '¿Cómo estás hoy?', 'Wie geht es dir heute?', 'adverb'],
      ['qué', 'was', '¿Qué haces ahora?', 'Was machst du gerade?', 'pronoun'],
      ['quién', 'wer', '¿Quién es esa persona?', 'Wer ist diese Person?', 'pronoun'],
      ['dónde', 'wo', '¿Dónde vives?', 'Wo wohnst du?', 'adverb'],
      ['cuándo', 'wann', '¿Cuándo llegas?', 'Wann kommst du an?', 'adverb'],
      ['por qué', 'warum', '¿Por qué aprendes español?', 'Warum lernst du Spanisch?', 'adverb'],
      ['ayudar', 'helfen', '¿Me puedes ayudar?', 'Kannst du mir helfen?', 'verb'],
      ['querer', 'wollen, mögen', 'Quiero un vaso de agua.', 'Ich möchte ein Glas Wasser.', 'verb'],
      ['poder', 'können', 'No puedo venir hoy.', 'Ich kann heute nicht kommen.', 'verb'],
      ['muy', 'sehr', 'Estoy muy contento.', 'Ich bin sehr zufrieden.', 'adverb'],
      ['mucho', 'viel', 'Trabajo mucho.', 'Ich arbeite viel.', 'adverb'],
      ['poco', 'wenig', 'Hablo poco español.', 'Ich spreche wenig Spanisch.', 'adverb'],
      ['también', 'auch', 'Yo también soy de Alemania.', 'Ich bin auch aus Deutschland.', 'adverb'],
    ],
  },
  {
    title: 'Familie & Personen',
    level: CefrLevel.A1,
    description: 'Familienmitglieder und Menschen im Alltag beschreiben',
    iconEmoji: '👨‍👩‍👧',
    items: [
      ['la familia', 'die Familie', 'Mi familia es pequeña.', 'Meine Familie ist klein.', 'noun'],
      ['el padre', 'der Vater', 'Mi padre trabaja en un banco.', 'Mein Vater arbeitet in einer Bank.', 'noun'],
      ['la madre', 'die Mutter', 'Mi madre cocina muy bien.', 'Meine Mutter kocht sehr gut.', 'noun'],
      ['los padres', 'die Eltern', 'Mis padres viven en Sevilla.', 'Meine Eltern wohnen in Sevilla.', 'noun'],
      ['el hijo', 'der Sohn', 'Su hijo tiene ocho años.', 'Ihr Sohn ist acht Jahre alt.', 'noun'],
      ['la hija', 'die Tochter', 'Mi hija va a la escuela.', 'Meine Tochter geht zur Schule.', 'noun'],
      ['el hermano', 'der Bruder', 'Mi hermano es más alto que yo.', 'Mein Bruder ist größer als ich.', 'noun'],
      ['la hermana', 'die Schwester', 'Tengo una hermana pequeña.', 'Ich habe eine kleine Schwester.', 'noun'],
      ['el abuelo', 'der Großvater', 'Mi abuelo tiene noventa años.', 'Mein Großvater ist neunzig.', 'noun'],
      ['la abuela', 'die Großmutter', 'Mi abuela vive con nosotros.', 'Meine Großmutter wohnt bei uns.', 'noun'],
      ['el tío', 'der Onkel', 'Mi tío vive en México.', 'Mein Onkel wohnt in Mexiko.', 'noun'],
      ['la tía', 'die Tante', 'Mi tía es profesora.', 'Meine Tante ist Lehrerin.', 'noun'],
      ['el primo', 'der Cousin', 'Mi primo viene el domingo.', 'Mein Cousin kommt am Sonntag.', 'noun'],
      ['la prima', 'die Cousine', 'Mi prima estudia medicina.', 'Meine Cousine studiert Medizin.', 'noun'],
      ['el marido', 'der Ehemann', 'Su marido es muy amable.', 'Ihr Mann ist sehr freundlich.', 'noun'],
      ['la esposa', 'die Ehefrau', 'Viajo con mi esposa.', 'Ich reise mit meiner Frau.', 'noun'],
      ['el bebé', 'das Baby', 'El bebé duerme tranquilo.', 'Das Baby schläft ruhig.', 'noun'],
      ['el hombre', 'der Mann', 'El hombre lleva un abrigo azul.', 'Der Mann trägt einen blauen Mantel.', 'noun'],
      ['la mujer', 'die Frau', 'La mujer trabaja en el hospital.', 'Die Frau arbeitet im Krankenhaus.', 'noun'],
      ['el niño', 'das Kind, der Junge', 'El niño juega en el jardín.', 'Das Kind spielt im Garten.', 'noun'],
      ['la niña', 'das Mädchen', 'La niña lee un libro.', 'Das Mädchen liest ein Buch.', 'noun'],
      ['el chico', 'der Junge', 'Ese chico es mi vecino.', 'Dieser Junge ist mein Nachbar.', 'noun'],
      ['la chica', 'das Mädchen, junge Frau', 'La chica habla tres idiomas.', 'Das Mädchen spricht drei Sprachen.', 'noun'],
      ['el señor', 'der Herr', 'El señor Pérez llega tarde.', 'Herr Pérez kommt zu spät.', 'noun'],
      ['la señora', 'die Dame, Frau', 'La señora pregunta la hora.', 'Die Dame fragt nach der Uhrzeit.', 'noun'],
      ['la persona', 'die Person', 'Es una persona muy simpática.', 'Sie ist eine sehr nette Person.', 'noun'],
      ['la gente', 'die Leute', 'Hay mucha gente en la calle.', 'Es sind viele Leute auf der Straße.', 'noun'],
      ['el amigo', 'der Freund', 'Él es mi mejor amigo.', 'Er ist mein bester Freund.', 'noun'],
      ['la amiga', 'die Freundin', 'Mi amiga viene de Italia.', 'Meine Freundin kommt aus Italien.', 'noun'],
      ['el vecino', 'der Nachbar', 'Mi vecino tiene un perro.', 'Mein Nachbar hat einen Hund.', 'noun'],
      ['el compañero', 'der Kollege, Mitschüler', 'Mi compañero de trabajo es holandés.', 'Mein Arbeitskollege ist Niederländer.', 'noun'],
      ['el jefe', 'der Chef', 'El jefe llega a las nueve.', 'Der Chef kommt um neun.', 'noun'],
      ['el médico', 'der Arzt', 'El médico habla con el paciente.', 'Der Arzt spricht mit dem Patienten.', 'noun'],
      ['el profesor', 'der Lehrer', 'El profesor explica la lección.', 'Der Lehrer erklärt die Lektion.', 'noun'],
      ['el estudiante', 'der Student, Schüler', 'El estudiante pregunta mucho.', 'Der Student fragt viel.', 'noun'],
      ['alto', 'groß (Person), hoch', 'Mi hermano es muy alto.', 'Mein Bruder ist sehr groß.', 'adjective'],
      ['bajo', 'klein (Person), niedrig', 'Ella es baja y delgada.', 'Sie ist klein und schlank.', 'adjective'],
      ['joven', 'jung', 'La profesora todavía es joven.', 'Die Lehrerin ist noch jung.', 'adjective'],
      ['viejo', 'alt', 'Mi abuelo ya es viejo.', 'Mein Großvater ist schon alt.', 'adjective'],
      ['simpático', 'sympathisch, nett', 'Tus amigos son muy simpáticos.', 'Deine Freunde sind sehr nett.', 'adjective'],
      ['amable', 'freundlich', 'El camarero es muy amable.', 'Der Kellner ist sehr freundlich.', 'adjective'],
      ['divertido', 'lustig', 'La película es muy divertida.', 'Der Film ist sehr lustig.', 'adjective'],
      ['cansado', 'müde', 'Estoy cansado después del trabajo.', 'Nach der Arbeit bin ich müde.', 'adjective'],
      ['contento', 'zufrieden, froh', 'Estoy contento con el resultado.', 'Ich bin mit dem Ergebnis zufrieden.', 'adjective'],
      ['triste', 'traurig', 'Hoy estoy un poco triste.', 'Heute bin ich etwas traurig.', 'adjective'],
      ['enfermo', 'krank', 'Mi hija está enferma.', 'Meine Tochter ist krank.', 'adjective'],
      ['conocer', 'kennen, kennenlernen', 'Conozco a su hermana.', 'Ich kenne seine Schwester.', 'verb'],
      ['presentar', 'vorstellen', 'Te presento a mi amigo Pablo.', 'Ich stelle dir meinen Freund Pablo vor.', 'verb'],
      ['el cumpleaños', 'der Geburtstag', 'Mi cumpleaños es en mayo.', 'Mein Geburtstag ist im Mai.', 'noun'],
      ['la edad', 'das Alter', '¿Qué edad tiene tu hijo?', 'Wie alt ist dein Sohn?', 'noun'],
    ],
  },
  {
    title: 'Zahlen & Zeit',
    level: CefrLevel.A1,
    description: 'Zahlen, Uhrzeit, Wochentage und Monate',
    iconEmoji: '🕐',
    items: [
      ['uno', 'eins', 'Solo tengo un hermano.', 'Ich habe nur einen Bruder.', 'numeral'],
      ['dos', 'zwei', 'Quiero dos cafés.', 'Ich möchte zwei Kaffee.', 'numeral'],
      ['tres', 'drei', 'La clase dura tres horas.', 'Der Unterricht dauert drei Stunden.', 'numeral'],
      ['cuatro', 'vier', 'Somos cuatro en casa.', 'Wir sind vier zu Hause.', 'numeral'],
      ['cinco', 'fünf', 'El tren sale a las cinco.', 'Der Zug fährt um fünf.', 'numeral'],
      ['seis', 'sechs', 'Trabajo seis días.', 'Ich arbeite sechs Tage.', 'numeral'],
      ['siete', 'sieben', 'Cenamos a las siete.', 'Wir essen um sieben zu Abend.', 'numeral'],
      ['ocho', 'acht', 'La tienda abre a las ocho.', 'Der Laden öffnet um acht.', 'numeral'],
      ['nueve', 'neun', 'La reunión es a las nueve.', 'Die Besprechung ist um neun.', 'numeral'],
      ['diez', 'zehn', 'Tengo diez minutos.', 'Ich habe zehn Minuten.', 'numeral'],
      ['once', 'elf', 'Son las once de la mañana.', 'Es ist elf Uhr morgens.', 'numeral'],
      ['doce', 'zwölf', 'El museo cierra a las doce.', 'Das Museum schließt um zwölf.', 'numeral'],
      ['veinte', 'zwanzig', 'El libro cuesta veinte euros.', 'Das Buch kostet zwanzig Euro.', 'numeral'],
      ['treinta', 'dreißig', 'Espero treinta minutos.', 'Ich warte dreißig Minuten.', 'numeral'],
      ['cincuenta', 'fünfzig', 'Hay cincuenta personas.', 'Es sind fünfzig Personen da.', 'numeral'],
      ['cien', 'hundert', 'Cuesta cien euros.', 'Es kostet hundert Euro.', 'numeral'],
      ['mil', 'tausend', 'La ciudad tiene mil habitantes.', 'Die Stadt hat tausend Einwohner.', 'numeral'],
      ['primero', 'erster', 'Es mi primer día aquí.', 'Es ist mein erster Tag hier.', 'adjective'],
      ['último', 'letzter', 'Es el último tren.', 'Das ist der letzte Zug.', 'adjective'],
      ['el número', 'die Nummer, Zahl', '¿Cuál es tu número de teléfono?', 'Wie ist deine Telefonnummer?', 'noun'],
      ['la hora', 'die Stunde, Uhrzeit', '¿Qué hora es?', 'Wie spät ist es?', 'noun'],
      ['el minuto', 'die Minute', 'Espera un minuto, por favor.', 'Warte bitte eine Minute.', 'noun'],
      ['la semana', 'die Woche', 'La semana pasada estuve enfermo.', 'Letzte Woche war ich krank.', 'noun'],
      ['el fin de semana', 'das Wochenende', 'El fin de semana descanso.', 'Am Wochenende ruhe ich mich aus.', 'noun'],
      ['el mes', 'der Monat', 'Este mes tengo vacaciones.', 'Diesen Monat habe ich Urlaub.', 'noun'],
      ['el año', 'das Jahr', 'El año pasado viajé a España.', 'Letztes Jahr bin ich nach Spanien gereist.', 'noun'],
      ['el lunes', 'der Montag', 'El lunes empiezo a trabajar.', 'Am Montag fange ich an zu arbeiten.', 'noun'],
      ['el martes', 'der Dienstag', 'El martes tengo clase.', 'Am Dienstag habe ich Unterricht.', 'noun'],
      ['el miércoles', 'der Mittwoch', 'Los miércoles voy al gimnasio.', 'Mittwochs gehe ich ins Fitnessstudio.', 'noun'],
      ['el jueves', 'der Donnerstag', 'El jueves llega mi hermana.', 'Am Donnerstag kommt meine Schwester.', 'noun'],
      ['el viernes', 'der Freitag', 'El viernes salimos a cenar.', 'Am Freitag gehen wir essen.', 'noun'],
      ['el sábado', 'der Samstag', 'El sábado hay mercado.', 'Am Samstag ist Markt.', 'noun'],
      ['el domingo', 'der Sonntag', 'El domingo duermo mucho.', 'Am Sonntag schlafe ich lange.', 'noun'],
      ['enero', 'Januar', 'En enero hace frío.', 'Im Januar ist es kalt.', 'noun'],
      ['febrero', 'Februar', 'Febrero es un mes corto.', 'Februar ist ein kurzer Monat.', 'noun'],
      ['marzo', 'März', 'En marzo empieza la primavera.', 'Im März beginnt der Frühling.', 'noun'],
      ['abril', 'April', 'En abril llueve mucho.', 'Im April regnet es viel.', 'noun'],
      ['mayo', 'Mai', 'Mi cumpleaños es en mayo.', 'Mein Geburtstag ist im Mai.', 'noun'],
      ['junio', 'Juni', 'En junio termina el curso.', 'Im Juni endet der Kurs.', 'noun'],
      ['julio', 'Juli', 'En julio vamos a la playa.', 'Im Juli fahren wir an den Strand.', 'noun'],
      ['agosto', 'August', 'En agosto la ciudad está vacía.', 'Im August ist die Stadt leer.', 'noun'],
      ['septiembre', 'September', 'En septiembre empieza la escuela.', 'Im September beginnt die Schule.', 'noun'],
      ['octubre', 'Oktober', 'En octubre hace viento.', 'Im Oktober ist es windig.', 'noun'],
      ['noviembre', 'November', 'En noviembre anochece pronto.', 'Im November wird es früh dunkel.', 'noun'],
      ['diciembre', 'Dezember', 'En diciembre celebramos la Navidad.', 'Im Dezember feiern wir Weihnachten.', 'noun'],
      ['el reloj', 'die Uhr', 'Mi reloj va atrasado.', 'Meine Uhr geht nach.', 'noun'],
      ['temprano', 'früh', 'Me levanto temprano.', 'Ich stehe früh auf.', 'adverb'],
      ['tarde', 'spät', 'Llegas siempre tarde.', 'Du kommst immer zu spät.', 'adverb'],
      ['siempre', 'immer', 'Siempre desayuno en casa.', 'Ich frühstücke immer zu Hause.', 'adverb'],
      ['nunca', 'nie', 'Nunca bebo café por la noche.', 'Ich trinke nachts nie Kaffee.', 'adverb'],
    ],
  },
  {
    title: 'Essen & Trinken',
    level: CefrLevel.A1,
    description: 'Lebensmittel, Getränke und der Restaurantbesuch',
    iconEmoji: '🍞',
    items: [
      ['el pan', 'das Brot', 'Compro pan por la mañana.', 'Ich kaufe morgens Brot.', 'noun'],
      ['la leche', 'die Milch', 'Bebo leche con el desayuno.', 'Ich trinke Milch zum Frühstück.', 'noun'],
      ['el agua', 'das Wasser', 'Bebo agua todos los días.', 'Ich trinke jeden Tag Wasser.', 'noun'],
      ['el café', 'der Kaffee', 'Un café con leche, por favor.', 'Einen Milchkaffee, bitte.', 'noun'],
      ['el té', 'der Tee', 'Prefiero el té verde.', 'Ich mag lieber grünen Tee.', 'noun'],
      ['el zumo', 'der Saft', 'Un zumo de naranja, por favor.', 'Einen Orangensaft, bitte.', 'noun'],
      ['la cerveza', 'das Bier', 'La cerveza está muy fría.', 'Das Bier ist sehr kalt.', 'noun'],
      ['el vino', 'der Wein', 'Este vino es de Rioja.', 'Dieser Wein ist aus Rioja.', 'noun'],
      ['el desayuno', 'das Frühstück', 'El desayuno es a las ocho.', 'Das Frühstück ist um acht.', 'noun'],
      ['la comida', 'das Essen, Mittagessen', 'La comida está lista.', 'Das Essen ist fertig.', 'noun'],
      ['la cena', 'das Abendessen', 'La cena es ligera.', 'Das Abendessen ist leicht.', 'noun'],
      ['el arroz', 'der Reis', 'El arroz con verduras está rico.', 'Der Reis mit Gemüse schmeckt gut.', 'noun'],
      ['la carne', 'das Fleisch', 'No como carne.', 'Ich esse kein Fleisch.', 'noun'],
      ['el pescado', 'der Fisch', 'El pescado es muy fresco.', 'Der Fisch ist sehr frisch.', 'noun'],
      ['el pollo', 'das Hähnchen', 'Hoy hay pollo con patatas.', 'Heute gibt es Hähnchen mit Kartoffeln.', 'noun'],
      ['el huevo', 'das Ei', 'Quiero dos huevos fritos.', 'Ich möchte zwei Spiegeleier.', 'noun'],
      ['el queso', 'der Käse', 'Este queso es español.', 'Dieser Käse ist spanisch.', 'noun'],
      ['la fruta', 'das Obst', 'Como fruta cada día.', 'Ich esse jeden Tag Obst.', 'noun'],
      ['la manzana', 'der Apfel', 'La manzana está verde.', 'Der Apfel ist grün.', 'noun'],
      ['el plátano', 'die Banane', 'Un plátano para el desayuno.', 'Eine Banane zum Frühstück.', 'noun'],
      ['la naranja', 'die Orange', 'Las naranjas son dulces.', 'Die Orangen sind süß.', 'noun'],
      ['la verdura', 'das Gemüse', 'Compro verdura en el mercado.', 'Ich kaufe Gemüse auf dem Markt.', 'noun'],
      ['el tomate', 'die Tomate', 'La ensalada lleva tomate.', 'Im Salat ist Tomate.', 'noun'],
      ['la patata', 'die Kartoffel', 'Las patatas están cocidas.', 'Die Kartoffeln sind gekocht.', 'noun'],
      ['la ensalada', 'der Salat', 'De primero, una ensalada.', 'Als Vorspeise einen Salat.', 'noun'],
      ['la sopa', 'die Suppe', 'La sopa está caliente.', 'Die Suppe ist heiß.', 'noun'],
      ['el azúcar', 'der Zucker', 'El café sin azúcar, por favor.', 'Den Kaffee ohne Zucker, bitte.', 'noun'],
      ['la sal', 'das Salz', '¿Me pasas la sal?', 'Reichst du mir das Salz?', 'noun'],
      ['el aceite', 'das Öl', 'El aceite de oliva es bueno.', 'Olivenöl ist gut.', 'noun'],
      ['el postre', 'die Nachspeise', 'De postre quiero fruta.', 'Als Nachtisch möchte ich Obst.', 'noun'],
      ['el helado', 'das Eis', 'El helado de chocolate está rico.', 'Das Schokoladeneis schmeckt gut.', 'noun'],
      ['el restaurante', 'das Restaurant', 'El restaurante abre a la una.', 'Das Restaurant öffnet um eins.', 'noun'],
      ['el camarero', 'der Kellner', 'El camarero trae la carta.', 'Der Kellner bringt die Karte.', 'noun'],
      ['la carta', 'die Speisekarte', '¿Nos trae la carta, por favor?', 'Bringen Sie uns bitte die Karte?', 'noun'],
      ['la cuenta', 'die Rechnung', 'La cuenta, por favor.', 'Die Rechnung, bitte.', 'noun'],
      ['el plato', 'der Teller, das Gericht', 'Este plato es típico de aquí.', 'Dieses Gericht ist typisch für hier.', 'noun'],
      ['el vaso', 'das Glas', 'Un vaso de agua, por favor.', 'Ein Glas Wasser, bitte.', 'noun'],
      ['la taza', 'die Tasse', 'Una taza de café con leche.', 'Eine Tasse Milchkaffee.', 'noun'],
      ['el tenedor', 'die Gabel', 'Falta un tenedor en la mesa.', 'Auf dem Tisch fehlt eine Gabel.', 'noun'],
      ['el cuchillo', 'das Messer', 'El cuchillo no corta bien.', 'Das Messer schneidet nicht gut.', 'noun'],
      ['la cuchara', 'der Löffel', 'Necesito una cuchara para la sopa.', 'Ich brauche einen Löffel für die Suppe.', 'noun'],
      ['comer', 'essen', 'Comemos a las dos.', 'Wir essen um zwei.', 'verb'],
      ['beber', 'trinken', 'Bebo mucha agua.', 'Ich trinke viel Wasser.', 'verb'],
      ['cocinar', 'kochen', 'Mi padre cocina los domingos.', 'Mein Vater kocht sonntags.', 'verb'],
      ['probar', 'probieren', '¿Quieres probar el queso?', 'Möchtest du den Käse probieren?', 'verb'],
      ['pedir', 'bestellen, bitten um', 'Voy a pedir la cuenta.', 'Ich bestelle die Rechnung.', 'verb'],
      ['tener hambre', 'Hunger haben', 'Tengo mucha hambre.', 'Ich habe großen Hunger.', 'phrase'],
      ['tener sed', 'Durst haben', '¿Tienes sed?', 'Hast du Durst?', 'phrase'],
      ['rico', 'lecker', 'La tortilla está muy rica.', 'Die Tortilla ist sehr lecker.', 'adjective'],
      ['caliente', 'heiß, warm', 'La sopa está demasiado caliente.', 'Die Suppe ist zu heiß.', 'adjective'],
    ],
  },
  {
    title: 'Zuhause & Wohnen',
    level: CefrLevel.A1,
    description: 'Wohnung, Möbel und das Zuhause beschreiben',
    iconEmoji: '🏠',
    items: [
      ['la casa', 'das Haus', 'Nuestra casa es pequeña.', 'Unser Haus ist klein.', 'noun'],
      ['el piso', 'die Wohnung', 'Vivo en un piso céntrico.', 'Ich wohne in einer zentralen Wohnung.', 'noun'],
      ['la habitación', 'das Zimmer', 'La habitación tiene dos ventanas.', 'Das Zimmer hat zwei Fenster.', 'noun'],
      ['el salón', 'das Wohnzimmer', 'Vemos la tele en el salón.', 'Wir sehen im Wohnzimmer fern.', 'noun'],
      ['la cocina', 'die Küche', 'La cocina es muy luminosa.', 'Die Küche ist sehr hell.', 'noun'],
      ['el baño', 'das Bad', 'El baño está al final del pasillo.', 'Das Bad ist am Ende des Flurs.', 'noun'],
      ['el dormitorio', 'das Schlafzimmer', 'Mi dormitorio es tranquilo.', 'Mein Schlafzimmer ist ruhig.', 'noun'],
      ['la puerta', 'die Tür', 'Cierra la puerta, por favor.', 'Mach bitte die Tür zu.', 'noun'],
      ['la ventana', 'das Fenster', 'Abre la ventana, hace calor.', 'Mach das Fenster auf, es ist warm.', 'noun'],
      ['la mesa', 'der Tisch', 'La mesa es de madera.', 'Der Tisch ist aus Holz.', 'noun'],
      ['la silla', 'der Stuhl', 'Esta silla es muy cómoda.', 'Dieser Stuhl ist sehr bequem.', 'noun'],
      ['la cama', 'das Bett', 'La cama es grande.', 'Das Bett ist groß.', 'noun'],
      ['el sofá', 'das Sofa', 'El gato duerme en el sofá.', 'Die Katze schläft auf dem Sofa.', 'noun'],
      ['el armario', 'der Schrank', 'La ropa está en el armario.', 'Die Kleidung ist im Schrank.', 'noun'],
      ['la lámpara', 'die Lampe', 'La lámpara no funciona.', 'Die Lampe funktioniert nicht.', 'noun'],
      ['la nevera', 'der Kühlschrank', 'La leche está en la nevera.', 'Die Milch ist im Kühlschrank.', 'noun'],
      ['la lavadora', 'die Waschmaschine', 'La lavadora es nueva.', 'Die Waschmaschine ist neu.', 'noun'],
      ['la ducha', 'die Dusche', 'La ducha está rota.', 'Die Dusche ist kaputt.', 'noun'],
      ['el espejo', 'der Spiegel', 'Hay un espejo en el baño.', 'Im Bad hängt ein Spiegel.', 'noun'],
      ['el suelo', 'der Boden', 'El suelo está limpio.', 'Der Boden ist sauber.', 'noun'],
      ['la pared', 'die Wand', 'La pared es blanca.', 'Die Wand ist weiß.', 'noun'],
      ['la llave', 'der Schlüssel', 'He perdido las llaves.', 'Ich habe die Schlüssel verloren.', 'noun'],
      ['el ascensor', 'der Aufzug', 'El ascensor no funciona hoy.', 'Der Aufzug geht heute nicht.', 'noun'],
      ['la escalera', 'die Treppe', 'Subo por la escalera.', 'Ich gehe die Treppe hoch.', 'noun'],
      ['el jardín', 'der Garten', 'El jardín tiene muchas flores.', 'Der Garten hat viele Blumen.', 'noun'],
      ['el balcón', 'der Balkon', 'Desayunamos en el balcón.', 'Wir frühstücken auf dem Balkon.', 'noun'],
      ['la calle', 'die Straße', 'Vivo en la calle Mayor.', 'Ich wohne in der Calle Mayor.', 'noun'],
      ['el barrio', 'das Viertel', 'Mi barrio es muy tranquilo.', 'Mein Viertel ist sehr ruhig.', 'noun'],
      ['la ciudad', 'die Stadt', 'Barcelona es una ciudad grande.', 'Barcelona ist eine große Stadt.', 'noun'],
      ['el pueblo', 'das Dorf', 'Mis abuelos viven en un pueblo.', 'Meine Großeltern wohnen in einem Dorf.', 'noun'],
      ['la dirección', 'die Adresse', '¿Cuál es tu dirección?', 'Wie ist deine Adresse?', 'noun'],
      ['el alquiler', 'die Miete', 'El alquiler es muy caro.', 'Die Miete ist sehr teuer.', 'noun'],
      ['la luz', 'das Licht', 'Apaga la luz, por favor.', 'Mach bitte das Licht aus.', 'noun'],
      ['abrir', 'öffnen', 'Abro la ventana cada mañana.', 'Ich öffne jeden Morgen das Fenster.', 'verb'],
      ['cerrar', 'schließen', 'Cierro la puerta con llave.', 'Ich schließe die Tür ab.', 'verb'],
      ['encender', 'anmachen, einschalten', 'Enciende la lámpara.', 'Mach die Lampe an.', 'verb'],
      ['apagar', 'ausmachen', 'Apaga la televisión.', 'Mach den Fernseher aus.', 'verb'],
      ['limpiar', 'putzen', 'Limpio la cocina los sábados.', 'Ich putze samstags die Küche.', 'verb'],
      ['dormir', 'schlafen', 'Duermo ocho horas.', 'Ich schlafe acht Stunden.', 'verb'],
      ['descansar', 'sich ausruhen', 'Necesito descansar un poco.', 'Ich muss mich etwas ausruhen.', 'verb'],
      ['buscar', 'suchen', 'Busco un piso nuevo.', 'Ich suche eine neue Wohnung.', 'verb'],
      ['grande', 'groß', 'Es una habitación grande.', 'Das ist ein großes Zimmer.', 'adjective'],
      ['pequeño', 'klein', 'Tengo un problema pequeño.', 'Ich habe ein kleines Problem.', 'adjective'],
      ['nuevo', 'neu', 'Tengo un móvil nuevo.', 'Ich habe ein neues Handy.', 'adjective'],
      ['cómodo', 'bequem', 'El sofá es muy cómodo.', 'Das Sofa ist sehr bequem.', 'adjective'],
      ['limpio', 'sauber', 'La casa está limpia.', 'Das Haus ist sauber.', 'adjective'],
      ['sucio', 'schmutzig', 'El suelo está sucio.', 'Der Boden ist schmutzig.', 'adjective'],
      ['caro', 'teuer', 'Este piso es demasiado caro.', 'Diese Wohnung ist zu teuer.', 'adjective'],
      ['barato', 'billig', 'El alquiler aquí es barato.', 'Die Miete ist hier billig.', 'adjective'],
      ['tranquilo', 'ruhig', 'La calle es muy tranquila.', 'Die Straße ist sehr ruhig.', 'adjective'],
    ],
  },
];
