import { CefrLevel } from '@prisma/client';

/**
 * 250 spanische Vokabeln für CEFR C2 – fünf Themenpakete zu je 50 Wörtern.
 *
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 * Übersetzt wird ins Deutsche, weil die Oberfläche deutsch ist. Substantive
 * stehen mit Artikel, Verben im Infinitiv. Wörter aus A1–C1 werden nicht wiederholt.
 */
export const SPANISH_VOCAB_C2 = [
  {
    title: 'Fachsprache & Wissenschaft',
    level: CefrLevel.C2,
    description: 'Präzises Vokabular für Forschung, Methodik und akademisches Schreiben',
    iconEmoji: '🔬',
    items: [
      ['la epistemología', 'die Erkenntnistheorie', 'La epistemología cuestiona los criterios de verdad.', 'Die Erkenntnistheorie hinterfragt Wahrheitskriterien.', 'noun'],
      ['la heurística', 'die Heuristik', 'Aplicaron una heurística sencilla.', 'Sie wandten eine einfache Heuristik an.', 'noun'],
      ['la taxonomía', 'die Taxonomie', 'La taxonomía propuesta tiene cinco categorías.', 'Die vorgeschlagene Taxonomie hat fünf Kategorien.', 'noun'],
      ['la nomenclatura', 'die Nomenklatur', 'La nomenclatura se unificó en 1998.', 'Die Nomenklatur wurde 1998 vereinheitlicht.', 'noun'],
      ['el corpus', 'das Korpus', 'El corpus abarca dos millones de palabras.', 'Das Korpus umfasst zwei Millionen Wörter.', 'noun'],
      ['la casuística', 'die Kasuistik', 'La casuística es demasiado dispar.', 'Die Fallgestaltung ist zu uneinheitlich.', 'noun'],
      ['el constructo', 'das Konstrukt', 'La inteligencia es un constructo discutido.', 'Intelligenz ist ein umstrittenes Konstrukt.', 'noun'],
      ['la operacionalización', 'die Operationalisierung', 'La operacionalización del concepto es débil.', 'Die Operationalisierung des Begriffs ist schwach.', 'noun'],
      ['el umbral de significación', 'die Signifikanzschwelle', 'Fijaron el umbral de significación en 0,01.', 'Sie setzten die Signifikanzschwelle auf 0,01.', 'noun'],
      ['el intervalo de confianza', 'das Konfidenzintervall', 'El intervalo de confianza es muy amplio.', 'Das Konfidenzintervall ist sehr breit.', 'noun'],
      ['la desviación típica', 'die Standardabweichung', 'La desviación típica duplica la media.', 'Die Standardabweichung ist doppelt so groß wie der Mittelwert.', 'noun'],
      ['el valor atípico', 'der Ausreißer', 'Excluyeron dos valores atípicos.', 'Sie schlossen zwei Ausreißer aus.', 'noun'],
      ['el metaanálisis', 'die Metaanalyse', 'El metaanálisis agrupa cuarenta estudios.', 'Die Metaanalyse fasst vierzig Studien zusammen.', 'noun'],
      ['el estudio longitudinal', 'die Längsschnittstudie', 'El estudio longitudinal duró veinte años.', 'Die Längsschnittstudie lief zwanzig Jahre.', 'noun'],
      ['el grupo de control', 'die Kontrollgruppe', 'El grupo de control no recibió tratamiento.', 'Die Kontrollgruppe erhielt keine Behandlung.', 'noun'],
      ['el factor de confusión', 'der Störfaktor', 'La edad actúa como factor de confusión.', 'Das Alter wirkt als Störfaktor.', 'noun'],
      ['la robustez', 'die Robustheit', 'Comprobaron la robustez del resultado.', 'Sie prüften die Robustheit des Ergebnisses.', 'noun'],
      ['la parsimonia', 'die Sparsamkeit (des Modells)', 'Se impone el criterio de parsimonia.', 'Es gilt das Sparsamkeitsprinzip.', 'noun'],
      ['la salvedad', 'der Vorbehalt', 'Acepto la tesis con una salvedad.', 'Ich akzeptiere die These mit einem Vorbehalt.', 'noun'],
      ['el corolario', 'die Folgerung', 'Como corolario, el modelo debe revisarse.', 'Als Folgerung muss das Modell überarbeitet werden.', 'noun'],
      ['la disquisición', 'die ausführliche Erörterung', 'La disquisición ocupa veinte páginas.', 'Die Erörterung nimmt zwanzig Seiten ein.', 'noun'],
      ['el escolio', 'die erläuternde Anmerkung', 'Añadió un escolio al margen.', 'Er fügte am Rand eine Anmerkung hinzu.', 'noun'],
      ['la exégesis', 'die Exegese', 'Su exégesis del texto es controvertida.', 'Seine Exegese des Textes ist umstritten.', 'noun'],
      ['la hermenéutica', 'die Hermeneutik', 'Trabaja desde una hermenéutica histórica.', 'Sie arbeitet aus einer historischen Hermeneutik heraus.', 'noun'],
      ['el estado del arte', 'der Stand der Technik', 'El prototipo supera el estado del arte.', 'Der Prototyp übertrifft den Stand der Technik.', 'noun'],
      ['la ponderación', 'die Gewichtung', 'La ponderación de los criterios es discutible.', 'Die Gewichtung der Kriterien ist strittig.', 'noun'],
      ['la salvaguarda', 'die Schutzvorkehrung', 'Establecieron salvaguardas éticas estrictas.', 'Sie schufen strenge ethische Schutzvorkehrungen.', 'noun'],
      ['la trazabilidad', 'die Nachverfolgbarkeit', 'La trazabilidad del dato es completa.', 'Die Nachverfolgbarkeit der Daten ist vollständig.', 'noun'],
      ['el sesgo de publicación', 'der Publikationsbias', 'El sesgo de publicación infla el efecto.', 'Der Publikationsbias bläht den Effekt auf.', 'noun'],
      ['la reproducibilidad', 'die Reproduzierbarkeit', 'La crisis de reproducibilidad sacudió el campo.', 'Die Reproduzierbarkeitskrise erschütterte das Fach.', 'noun'],
      ['dilucidar', 'aufklären, erhellen', 'Queda por dilucidar el mecanismo exacto.', 'Der genaue Mechanismus bleibt zu klären.', 'verb'],
      ['discernir', 'unterscheiden, erkennen', 'Cuesta discernir causa de correlación.', 'Es fällt schwer, Ursache von Korrelation zu unterscheiden.', 'verb'],
      ['esclarecer', 'aufklären', 'El informe esclarece varios puntos oscuros.', 'Der Bericht klärt mehrere dunkle Punkte auf.', 'verb'],
      ['acotar', 'eingrenzen', 'Conviene acotar el objeto de estudio.', 'Der Untersuchungsgegenstand sollte eingegrenzt werden.', 'verb'],
      ['extrapolar', 'extrapolieren', 'No es lícito extrapolar a otra especie.', 'Eine Extrapolation auf eine andere Art ist unzulässig.', 'verb'],
      ['converger', 'konvergieren', 'Los tres métodos convergen en el mismo valor.', 'Die drei Methoden konvergieren auf denselben Wert.', 'verb'],
      ['subyacer', 'zugrunde liegen', 'Un supuesto tácito subyace al modelo.', 'Dem Modell liegt eine stillschweigende Annahme zugrunde.', 'verb'],
      ['dirimir', 'entscheiden, schlichten', 'El experimento dirime la controversia.', 'Das Experiment entscheidet den Streit.', 'verb'],
      ['ceñir el alcance', 'den Geltungsbereich begrenzen', 'Conviene ceñir el alcance de la conclusión.', 'Der Geltungsbereich der Schlussfolgerung sollte begrenzt werden.', 'phrase'],
      ['adolecer de', 'kranken an', 'El estudio adolece de una muestra sesgada.', 'Die Studie krankt an einer verzerrten Stichprobe.', 'phrase'],
      ['incurrir en', 'begehen, verfallen in', 'Incurre en una petición de principio.', 'Er begeht einen Zirkelschluss.', 'phrase'],
      ['taxativo', 'strikt, abschließend', 'La norma es taxativa al respecto.', 'Die Vorschrift ist hierzu abschließend.', 'adjective'],
      ['inequívoco', 'unzweideutig', 'La evidencia es inequívoca.', 'Die Evidenz ist unzweideutig.', 'adjective'],
      ['soslayable', 'vermeidbar', 'El problema no es soslayable.', 'Das Problem ist nicht zu umgehen.', 'adjective'],
      ['consustancial', 'wesenseigen', 'La incertidumbre es consustancial al método.', 'Die Unsicherheit ist dem Verfahren wesenseigen.', 'adjective'],
      ['heurístico', 'heuristisch', 'Es un criterio meramente heurístico.', 'Das ist ein rein heuristisches Kriterium.', 'adjective'],
      ['de índole', 'von der Art', 'Son problemas de índole metodológica.', 'Es sind Probleme methodischer Art.', 'phrase'],
      ['a tenor de', 'gemäß, nach Maßgabe von', 'A tenor de los datos, la hipótesis cae.', 'Nach Maßgabe der Daten fällt die Hypothese.', 'phrase'],
      ['en aras de', 'im Interesse von', 'En aras de la brevedad, omito detalles.', 'Im Interesse der Kürze lasse ich Details aus.', 'phrase'],
      ['so pena de', 'bei Strafe von', 'Debe citarse la fuente, so pena de plagio.', 'Die Quelle ist zu nennen, sonst droht Plagiat.', 'phrase'],
    ],
  },
  {
    title: 'Literatur & Stilmittel',
    level: CefrLevel.C2,
    description: 'Literaturwissenschaftliche Begriffe und rhetorische Stilmittel',
    iconEmoji: '🖋️',
    items: [
      ['la retórica', 'die Rhetorik', 'Domina la retórica clásica.', 'Er beherrscht die klassische Rhetorik.', 'noun'],
      ['la metáfora', 'die Metapher', 'La metáfora estructura todo el poema.', 'Die Metapher strukturiert das ganze Gedicht.', 'noun'],
      ['la metonimia', 'die Metonymie', 'Usa la metonimia con naturalidad.', 'Sie verwendet die Metonymie ganz selbstverständlich.', 'noun'],
      ['la sinécdoque', 'die Synekdoche', 'La sinécdoque toma la parte por el todo.', 'Die Synekdoche nimmt den Teil für das Ganze.', 'noun'],
      ['la hipérbole', 'die Hyperbel', 'La hipérbole resta credibilidad al texto.', 'Die Hyperbel nimmt dem Text an Glaubwürdigkeit.', 'noun'],
      ['la lítote', 'die Litotes', 'La lítote afirma negando lo contrario.', 'Die Litotes bejaht, indem sie das Gegenteil verneint.', 'noun'],
      ['la ironía', 'die Ironie', 'La ironía recorre toda la novela.', 'Ironie durchzieht den ganzen Roman.', 'noun'],
      ['el sarcasmo', 'der Sarkasmus', 'Su sarcasmo incomoda al lector.', 'Sein Sarkasmus macht den Leser unbehaglich.', 'noun'],
      ['la alegoría', 'die Allegorie', 'La obra es una alegoría del poder.', 'Das Werk ist eine Allegorie der Macht.', 'noun'],
      ['el símil', 'der Vergleich', 'El símil resulta demasiado obvio.', 'Der Vergleich wirkt zu naheliegend.', 'noun'],
      ['la aliteración', 'die Alliteration', 'La aliteración refuerza el ritmo.', 'Die Alliteration verstärkt den Rhythmus.', 'noun'],
      ['la anáfora', 'die Anapher', 'La anáfora abre cada estrofa.', 'Die Anapher eröffnet jede Strophe.', 'noun'],
      ['el hipérbaton', 'das Hyperbaton', 'El hipérbaton dificulta la lectura.', 'Das Hyperbaton erschwert das Lesen.', 'noun'],
      ['el oxímoron', 'das Oxymoron', 'Un oxímoron condensa la tensión.', 'Ein Oxymoron verdichtet die Spannung.', 'noun'],
      ['la elipsis', 'die Ellipse', 'La elipsis acelera la narración.', 'Die Ellipse beschleunigt die Erzählung.', 'noun'],
      ['la prosopopeya', 'die Personifikation', 'La prosopopeya da voz al río.', 'Die Personifikation gibt dem Fluss eine Stimme.', 'noun'],
      ['el leitmotiv', 'das Leitmotiv', 'El mar es el leitmotiv de la trilogía.', 'Das Meer ist das Leitmotiv der Trilogie.', 'noun'],
      ['el narrador omnisciente', 'der allwissende Erzähler', 'El narrador omnisciente juzga a sus personajes.', 'Der allwissende Erzähler richtet über seine Figuren.', 'noun'],
      ['el punto de vista', 'die Erzählperspektive', 'El punto de vista cambia cada capítulo.', 'Die Erzählperspektive wechselt pro Kapitel.', 'noun'],
      ['el monólogo interior', 'der innere Monolog', 'El monólogo interior domina la segunda parte.', 'Der innere Monolog beherrscht den zweiten Teil.', 'noun'],
      ['la analepsis', 'die Rückblende', 'Una analepsis explica el crimen.', 'Eine Rückblende erklärt das Verbrechen.', 'noun'],
      ['el desenlace', 'der Ausgang, die Auflösung', 'El desenlace resulta inverosímil.', 'Die Auflösung wirkt unglaubwürdig.', 'noun'],
      ['el clímax', 'der Höhepunkt', 'El clímax llega demasiado pronto.', 'Der Höhepunkt kommt zu früh.', 'noun'],
      ['la verosimilitud', 'die Wahrscheinlichkeit, Glaubhaftigkeit', 'La verosimilitud se resiente en el final.', 'Die Glaubhaftigkeit leidet am Ende.', 'noun'],
      ['el registro', 'das Sprachregister', 'Alterna registro culto y coloquial.', 'Er wechselt zwischen gehobenem und umgangssprachlichem Register.', 'noun'],
      ['la prosa', 'die Prosa', 'Su prosa es seca y exacta.', 'Seine Prosa ist trocken und exakt.', 'noun'],
      ['el verso libre', 'der freie Vers', 'Escribe en verso libre desde los ochenta.', 'Sie schreibt seit den Achtzigern in freien Versen.', 'noun'],
      ['la rima consonante', 'der reine Reim', 'La rima consonante suena hoy anticuada.', 'Der reine Reim klingt heute altmodisch.', 'noun'],
      ['la métrica', 'das Versmaß', 'La métrica del soneto es rígida.', 'Das Versmaß des Sonetts ist streng.', 'noun'],
      ['la cadencia', 'die Kadenz, der Tonfall', 'La cadencia de la frase es casi musical.', 'Die Kadenz des Satzes ist fast musikalisch.', 'noun'],
      ['el seudónimo', 'das Pseudonym', 'Publicó bajo seudónimo durante años.', 'Sie veröffentlichte jahrelang unter Pseudonym.', 'noun'],
      ['la intertextualidad', 'die Intertextualität', 'La intertextualidad exige un lector culto.', 'Intertextualität verlangt einen belesenen Leser.', 'noun'],
      ['el canon literario', 'der literarische Kanon', 'El canon literario se está revisando.', 'Der literarische Kanon wird gerade überprüft.', 'noun'],
      ['la vanguardia', 'die Avantgarde', 'Perteneció a la vanguardia de los años veinte.', 'Er gehörte zur Avantgarde der Zwanzigerjahre.', 'noun'],
      ['la pluma', 'die Feder, der Stil', 'Tiene una pluma afilada.', 'Sie hat eine scharfe Feder.', 'noun'],
      ['narrar', 'erzählen', 'Narra sin adornos ni compasión.', 'Er erzählt ohne Schmuck und ohne Mitleid.', 'verb'],
      ['evocar', 'heraufbeschwören', 'El olor evoca la infancia entera.', 'Der Geruch beschwört die ganze Kindheit herauf.', 'verb'],
      ['aludir a', 'anspielen auf', 'El título alude a un salmo.', 'Der Titel spielt auf einen Psalm an.', 'phrase'],
      ['insinuar', 'andeuten', 'El texto insinúa más de lo que dice.', 'Der Text deutet mehr an, als er sagt.', 'verb'],
      ['parodiar', 'parodieren', 'Parodia el lenguaje burocrático.', 'Sie parodiert die Behördensprache.', 'verb'],
      ['plasmar', 'gestalten, festhalten', 'Plasmó su exilio en tres novelas.', 'Er hielt sein Exil in drei Romanen fest.', 'verb'],
      ['urdir', 'ersinnen, spinnen', 'Urdió una trama impecable.', 'Sie spann eine makellose Handlung.', 'verb'],
      ['despojar de', 'entkleiden, berauben', 'Despoja el relato de todo sentimentalismo.', 'Er entkleidet die Erzählung jeder Sentimentalität.', 'phrase'],
      ['lapidario', 'lapidar', 'Cierra con una frase lapidaria.', 'Er schließt mit einem lapidaren Satz.', 'adjective'],
      ['prolijo', 'weitschweifig', 'El prólogo es innecesariamente prolijo.', 'Das Vorwort ist unnötig weitschweifig.', 'adjective'],
      ['conciso', 'prägnant', 'Prefiero un estilo conciso.', 'Ich ziehe einen prägnanten Stil vor.', 'adjective'],
      ['críptico', 'kryptisch', 'El último verso es críptico.', 'Der letzte Vers ist kryptisch.', 'adjective'],
      ['ampuloso', 'schwülstig', 'Su discurso resultó ampuloso.', 'Seine Rede wirkte schwülstig.', 'adjective'],
      ['certero', 'treffsicher', 'Es un retrato certero de la época.', 'Das ist ein treffsicheres Porträt der Epoche.', 'adjective'],
      ['a modo de', 'als eine Art', 'Cita a Quevedo a modo de epígrafe.', 'Er zitiert Quevedo als eine Art Motto.', 'phrase'],
    ],
  },
  {
    title: 'Politik & Diplomatie',
    level: CefrLevel.C2,
    description: 'Präzises Vokabular für Staatswesen, internationale Beziehungen und Diplomatie',
    iconEmoji: '🕊️',
    items: [
      ['la soberanía', 'die Souveränität', 'Invocan la soberanía nacional.', 'Sie berufen sich auf die nationale Souveränität.', 'noun'],
      ['la injerencia', 'die Einmischung', 'Denunciaron una injerencia extranjera.', 'Sie prangerten eine ausländische Einmischung an.', 'noun'],
      ['el tratado', 'der Vertrag (völkerrechtlich)', 'El tratado se ratificó por unanimidad.', 'Der Vertrag wurde einstimmig ratifiziert.', 'noun'],
      ['la ratificación', 'die Ratifizierung', 'La ratificación depende del senado.', 'Die Ratifizierung hängt vom Senat ab.', 'noun'],
      ['el protocolo', 'das Protokoll', 'El protocolo de actuación es estricto.', 'Das Handlungsprotokoll ist streng.', 'noun'],
      ['la cumbre', 'der Gipfel', 'La cumbre terminó sin acuerdo.', 'Der Gipfel endete ohne Einigung.', 'noun'],
      ['la mediación', 'die Vermittlung', 'Ofrecieron su mediación a las partes.', 'Sie boten den Parteien ihre Vermittlung an.', 'noun'],
      ['el alto el fuego', 'der Waffenstillstand', 'El alto el fuego se rompió de inmediato.', 'Der Waffenstillstand brach sofort zusammen.', 'noun'],
      ['la tregua', 'die Waffenruhe', 'La tregua permitió evacuar civiles.', 'Die Waffenruhe erlaubte die Evakuierung von Zivilisten.', 'noun'],
      ['la sanción', 'die Sanktion', 'Las sanciones afectan al sector energético.', 'Die Sanktionen treffen den Energiesektor.', 'noun'],
      ['el embargo', 'das Embargo', 'El embargo dura ya una década.', 'Das Embargo dauert bereits ein Jahrzehnt.', 'noun'],
      ['el bloqueo', 'die Blockade', 'El bloqueo agravó la crisis humanitaria.', 'Die Blockade verschärfte die humanitäre Krise.', 'noun'],
      ['la disuasión', 'die Abschreckung', 'La disuasión sustituye al enfrentamiento.', 'Abschreckung ersetzt die Konfrontation.', 'noun'],
      ['la represalia', 'die Vergeltung', 'Anunciaron represalias comerciales.', 'Sie kündigten Handelsvergeltung an.', 'noun'],
      ['la beligerancia', 'die Kriegsbeteiligung', 'Evitan reconocer su beligerancia.', 'Sie vermeiden es, ihre Kriegsbeteiligung einzuräumen.', 'noun'],
      ['la neutralidad', 'die Neutralität', 'Mantuvieron una neutralidad incómoda.', 'Sie hielten eine unbequeme Neutralität.', 'noun'],
      ['el statu quo', 'der Status quo', 'Nadie quiere alterar el statu quo.', 'Niemand will den Status quo ändern.', 'noun'],
      ['el equilibrio de poder', 'das Machtgleichgewicht', 'El equilibrio de poder se desplazó.', 'Das Machtgleichgewicht verschob sich.', 'noun'],
      ['la hegemonía', 'die Hegemonie', 'Su hegemonía regional se debilita.', 'Ihre regionale Hegemonie schwächt sich ab.', 'noun'],
      ['la geopolítica', 'die Geopolitik', 'La geopolítica del gas define alianzas.', 'Die Geopolitik des Gases bestimmt Bündnisse.', 'noun'],
      ['el multilateralismo', 'der Multilateralismus', 'Defienden el multilateralismo frente al unilateralismo.', 'Sie verteidigen den Multilateralismus gegen den Unilateralismus.', 'noun'],
      ['la coalición', 'die Koalition', 'La coalición se rompió en seis meses.', 'Die Koalition zerbrach in sechs Monaten.', 'noun'],
      ['la abstención', 'die Enthaltung', 'La abstención decidió la votación.', 'Die Enthaltung entschied die Abstimmung.', 'noun'],
      ['la moción de censura', 'das Misstrauensvotum', 'La moción de censura prosperó.', 'Das Misstrauensvotum hatte Erfolg.', 'noun'],
      ['el escaño', 'der Parlamentssitz', 'Perdieron doce escaños.', 'Sie verloren zwölf Sitze.', 'noun'],
      ['el cabildeo', 'die Lobbyarbeit', 'El cabildeo empresarial fue intenso.', 'Die Unternehmenslobby war sehr aktiv.', 'noun'],
      ['el clientelismo', 'die Klientelpolitik', 'El clientelismo corroe la administración.', 'Klientelpolitik zersetzt die Verwaltung.', 'noun'],
      ['el populismo', 'der Populismus', 'El populismo simplifica lo complejo.', 'Der Populismus vereinfacht Komplexes.', 'noun'],
      ['la demagogia', 'die Demagogie', 'Acusó al rival de pura demagogia.', 'Er warf dem Rivalen reine Demagogie vor.', 'noun'],
      ['la legitimidad', 'die Legitimität', 'Cuestionan la legitimidad del proceso.', 'Sie stellen die Legitimität des Verfahrens infrage.', 'noun'],
      ['el estado de derecho', 'der Rechtsstaat', 'El estado de derecho exige jueces independientes.', 'Der Rechtsstaat erfordert unabhängige Richter.', 'noun'],
      ['la separación de poderes', 'die Gewaltenteilung', 'La separación de poderes está erosionada.', 'Die Gewaltenteilung ist ausgehöhlt.', 'noun'],
      ['la rendición de cuentas', 'die Rechenschaftspflicht', 'Exigen rendición de cuentas al ejecutivo.', 'Sie fordern Rechenschaft von der Exekutive.', 'noun'],
      ['el comunicado conjunto', 'die gemeinsame Erklärung', 'Firmaron un comunicado conjunto ambiguo.', 'Sie unterzeichneten eine vage gemeinsame Erklärung.', 'noun'],
      ['la nota verbal', 'die Verbalnote', 'Entregaron una nota verbal de protesta.', 'Sie überreichten eine Protestnote.', 'noun'],
      ['negociar a puerta cerrada', 'hinter verschlossenen Türen verhandeln', 'Negociaron a puerta cerrada tres días.', 'Sie verhandelten drei Tage hinter verschlossenen Türen.', 'phrase'],
      ['mediar', 'vermitteln', 'Noruega medió entre ambos bandos.', 'Norwegen vermittelte zwischen beiden Lagern.', 'verb'],
      ['ratificar', 'ratifizieren', 'El parlamento ratificó el acuerdo.', 'Das Parlament ratifizierte das Abkommen.', 'verb'],
      ['vetar', 'ein Veto einlegen', 'Vetó la resolución en el consejo.', 'Er legte im Rat ein Veto gegen die Resolution ein.', 'verb'],
      ['recrudecerse', 'sich verschärfen', 'El conflicto se recrudeció en otoño.', 'Der Konflikt verschärfte sich im Herbst.', 'verb'],
      ['escalar', 'eskalieren', 'La tensión escaló en pocas horas.', 'Die Spannung eskalierte binnen Stunden.', 'verb'],
      ['distender', 'entspannen', 'El gesto distendió el ambiente.', 'Die Geste entspannte die Atmosphäre.', 'verb'],
      ['claudicar', 'nachgeben, kapitulieren', 'No piensan claudicar ante la presión.', 'Sie wollen dem Druck nicht nachgeben.', 'verb'],
      ['zanjar el litigio', 'den Streit beilegen', 'Zanjaron el litigio fronterizo en 2019.', 'Sie legten den Grenzstreit 2019 bei.', 'phrase'],
      ['beligerante', 'kriegführend, kämpferisch', 'Adoptó un tono beligerante.', 'Er schlug einen kämpferischen Ton an.', 'adjective'],
      ['conciliador', 'versöhnlich', 'Su discurso fue sorprendentemente conciliador.', 'Seine Rede war überraschend versöhnlich.', 'adjective'],
      ['inapelable', 'unanfechtbar', 'La decisión es inapelable.', 'Die Entscheidung ist unanfechtbar.', 'adjective'],
      ['soberano', 'souverän', 'Es una decisión soberana del país.', 'Das ist eine souveräne Entscheidung des Landes.', 'adjective'],
      ['de facto', 'faktisch', 'Ejerce un control de facto sobre la región.', 'Er übt faktische Kontrolle über die Region aus.', 'phrase'],
      ['a instancias de', 'auf Betreiben von', 'Se convocó a instancias de Francia.', 'Sie wurde auf Betreiben Frankreichs einberufen.', 'phrase'],
    ],
  },
  {
    title: 'Psychologie & Soziologie',
    level: CefrLevel.C2,
    description: 'Präzises Vokabular für seelische Vorgänge und gesellschaftliche Strukturen',
    iconEmoji: '🧠',
    items: [
      ['la cognición', 'die Kognition', 'La cognición social explica el prejuicio.', 'Soziale Kognition erklärt das Vorurteil.', 'noun'],
      ['el sesgo cognitivo', 'die kognitive Verzerrung', 'El sesgo cognitivo actúa sin que lo notemos.', 'Die kognitive Verzerrung wirkt unbemerkt.', 'noun'],
      ['la disonancia cognitiva', 'die kognitive Dissonanz', 'La disonancia cognitiva empuja a justificarse.', 'Kognitive Dissonanz treibt zur Rechtfertigung.', 'noun'],
      ['el condicionamiento', 'die Konditionierung', 'El condicionamiento explica parte del hábito.', 'Konditionierung erklärt einen Teil der Gewohnheit.', 'noun'],
      ['el refuerzo', 'die Verstärkung', 'El refuerzo intermitente es el más potente.', 'Intermittierende Verstärkung ist die wirksamste.', 'noun'],
      ['la resiliencia', 'die Resilienz', 'La resiliencia se entrena, no se hereda.', 'Resilienz wird trainiert, nicht vererbt.', 'noun'],
      ['la empatía', 'die Empathie', 'La empatía no equivale a estar de acuerdo.', 'Empathie ist nicht dasselbe wie Zustimmung.', 'noun'],
      ['la autoestima', 'das Selbstwertgefühl', 'Su autoestima depende del reconocimiento ajeno.', 'Ihr Selbstwertgefühl hängt von fremder Anerkennung ab.', 'noun'],
      ['la motivación intrínseca', 'die intrinsische Motivation', 'La motivación intrínseca dura más.', 'Intrinsische Motivation hält länger an.', 'noun'],
      ['el trauma', 'das Trauma', 'El trauma se manifiesta años después.', 'Das Trauma zeigt sich Jahre später.', 'noun'],
      ['el duelo', 'die Trauer(arbeit)', 'El duelo no sigue fases ordenadas.', 'Trauer verläuft nicht in geordneten Phasen.', 'noun'],
      ['la ansiedad', 'die Angststörung', 'La ansiedad anticipa amenazas inexistentes.', 'Angst nimmt nicht existente Bedrohungen vorweg.', 'noun'],
      ['el estigma', 'das Stigma', 'El estigma retrasa la búsqueda de ayuda.', 'Das Stigma verzögert die Suche nach Hilfe.', 'noun'],
      ['el apego', 'die Bindung', 'El apego seguro predice relaciones estables.', 'Sichere Bindung sagt stabile Beziehungen voraus.', 'noun'],
      ['la introspección', 'die Introspektion', 'La introspección tiene límites conocidos.', 'Introspektion hat bekannte Grenzen.', 'noun'],
      ['la proyección', 'die Projektion', 'Su crítica es pura proyección.', 'Seine Kritik ist reine Projektion.', 'noun'],
      ['el inconsciente', 'das Unbewusste', 'El inconsciente sigue siendo un concepto útil.', 'Das Unbewusste bleibt ein nützlicher Begriff.', 'noun'],
      ['la socialización', 'die Sozialisation', 'La socialización temprana marca el acento.', 'Die frühe Sozialisation prägt den Akzent.', 'noun'],
      ['la norma social', 'die soziale Norm', 'La norma social pesa más que la ley.', 'Die soziale Norm wiegt schwerer als das Gesetz.', 'noun'],
      ['el rol social', 'die soziale Rolle', 'Cambia de rol social sin esfuerzo.', 'Sie wechselt mühelos die soziale Rolle.', 'noun'],
      ['el estrato social', 'die soziale Schicht', 'El estrato social condiciona el acceso.', 'Die soziale Schicht bedingt den Zugang.', 'noun'],
      ['la movilidad social', 'die soziale Mobilität', 'La movilidad social se ha reducido.', 'Die soziale Mobilität hat abgenommen.', 'noun'],
      ['el capital cultural', 'das kulturelle Kapital', 'El capital cultural se hereda en silencio.', 'Kulturelles Kapital wird stillschweigend vererbt.', 'noun'],
      ['la cohesión social', 'der gesellschaftliche Zusammenhalt', 'La cohesión social se erosiona lentamente.', 'Der gesellschaftliche Zusammenhalt erodiert langsam.', 'noun'],
      ['la exclusión', 'die Ausgrenzung', 'La exclusión empieza por el lenguaje.', 'Ausgrenzung beginnt mit der Sprache.', 'noun'],
      ['la marginación', 'die Marginalisierung', 'Denuncian la marginación de esos barrios.', 'Sie prangern die Marginalisierung dieser Viertel an.', 'noun'],
      ['la anomia', 'die Anomie', 'La anomia describe la falta de normas compartidas.', 'Anomie beschreibt das Fehlen geteilter Normen.', 'noun'],
      ['la aculturación', 'die Akkulturation', 'La aculturación no borra la identidad.', 'Akkulturation löscht die Identität nicht aus.', 'noun'],
      ['la identidad colectiva', 'die kollektive Identität', 'La identidad colectiva se construye narrando.', 'Kollektive Identität entsteht durch Erzählen.', 'noun'],
      ['el imaginario social', 'das soziale Imaginäre', 'El imaginario social precede al debate.', 'Das soziale Imaginäre geht der Debatte voraus.', 'noun'],
      ['el conformismo', 'der Konformismus', 'El conformismo explica la mayoría silenciosa.', 'Konformismus erklärt die schweigende Mehrheit.', 'noun'],
      ['la presión de grupo', 'der Gruppendruck', 'La presión de grupo dobla el criterio propio.', 'Gruppendruck beugt das eigene Urteil.', 'noun'],
      ['el efecto rebaño', 'der Herdeneffekt', 'El efecto rebaño infló la burbuja.', 'Der Herdeneffekt blähte die Blase auf.', 'noun'],
      ['la polarización afectiva', 'die affektive Polarisierung', 'La polarización afectiva impide el diálogo.', 'Affektive Polarisierung verhindert den Dialog.', 'noun'],
      ['la profecía autocumplida', 'die selbsterfüllende Prophezeiung', 'Es una profecía autocumplida de manual.', 'Das ist eine lehrbuchhafte selbsterfüllende Prophezeiung.', 'noun'],
      ['interiorizar', 'verinnerlichen', 'Interiorizamos normas sin advertirlo.', 'Wir verinnerlichen Normen, ohne es zu merken.', 'verb'],
      ['condicionar', 'prägen, bedingen', 'El entorno condiciona la aspiración.', 'Das Umfeld prägt die Ambition.', 'verb'],
      ['reprimir', 'verdrängen, unterdrücken', 'Reprimió el recuerdo durante décadas.', 'Sie verdrängte die Erinnerung jahrzehntelang.', 'verb'],
      ['racionalizar', 'rationalisieren', 'Racionaliza cada decisión a posteriori.', 'Er rationalisiert jede Entscheidung im Nachhinein.', 'verb'],
      ['sublimar', 'sublimieren', 'Sublimó la rabia en su trabajo.', 'Er sublimierte die Wut in seiner Arbeit.', 'verb'],
      ['estigmatizar', 'stigmatisieren', 'El discurso estigmatiza a los usuarios.', 'Der Diskurs stigmatisiert die Betroffenen.', 'verb'],
      ['segregar', 'trennen, segregieren', 'La ciudad segrega por renta.', 'Die Stadt segregiert nach Einkommen.', 'verb'],
      ['empoderar', 'befähigen', 'El programa empodera a las participantes.', 'Das Programm befähigt die Teilnehmerinnen.', 'verb'],
      ['idiosincrásico', 'eigentümlich', 'Es una respuesta idiosincrásica.', 'Das ist eine eigentümliche Reaktion.', 'adjective'],
      ['normativo', 'normativ', 'El juicio es normativo, no descriptivo.', 'Das Urteil ist normativ, nicht deskriptiv.', 'adjective'],
      ['latente', 'latent', 'El conflicto permanece latente.', 'Der Konflikt bleibt latent.', 'adjective'],
      ['patente', 'offenkundig', 'La desigualdad es patente en los datos.', 'Die Ungleichheit ist in den Daten offenkundig.', 'adjective'],
      ['soterrado', 'verdeckt', 'Existe un malestar soterrado.', 'Es gibt ein verdecktes Unbehagen.', 'adjective'],
      ['proclive a', 'geneigt zu', 'Es proclive a la autocrítica.', 'Er neigt zur Selbstkritik.', 'phrase'],
      ['en aras del consenso', 'um des Konsenses willen', 'Cedió en aras del consenso.', 'Sie gab um des Konsenses willen nach.', 'phrase'],
    ],
  },
  {
    title: 'Idiomatik & Feinheiten der Sprache',
    level: CefrLevel.C2,
    description: 'Redewendungen und feste Wendungen, die nur Muttersprachler wirklich beherrschen',
    iconEmoji: '🗝️',
    items: [
      ['no tener desperdicio', 'durch und durch lesenswert sein', 'El prólogo no tiene desperdicio.', 'Das Vorwort ist durch und durch lesenswert.', 'phrase'],
      ['tirar la toalla', 'das Handtuch werfen', 'Tiró la toalla a las primeras de cambio.', 'Er warf gleich beim ersten Hindernis das Handtuch.', 'phrase'],
      ['poner el dedo en la llaga', 'den Finger in die Wunde legen', 'Puso el dedo en la llaga sin querer.', 'Sie legte ungewollt den Finger in die Wunde.', 'phrase'],
      ['ser pan comido', 'ein Kinderspiel sein', 'El examen fue pan comido.', 'Die Prüfung war ein Kinderspiel.', 'phrase'],
      ['estar en el ajo', 'eingeweiht sein', 'Todos en la oficina estaban en el ajo.', 'Alle im Büro waren eingeweiht.', 'phrase'],
      ['irse por las ramas', 'um den heißen Brei reden', 'Deja de irte por las ramas.', 'Hör auf, um den heißen Brei zu reden.', 'phrase'],
      ['hilar fino', 'Haarspalterei betreiben, genau arbeiten', 'Aquí conviene hilar fino.', 'Hier sollte man sehr genau arbeiten.', 'phrase'],
      ['dar gato por liebre', 'jemanden übers Ohr hauen', 'Nos dieron gato por liebre con el coche.', 'Beim Auto hat man uns übers Ohr gehauen.', 'phrase'],
      ['tener entre ceja y ceja', 'sich in den Kopf gesetzt haben', 'Lo tiene entre ceja y ceja desde enero.', 'Er hat es sich seit Januar in den Kopf gesetzt.', 'phrase'],
      ['no dar pie con bola', 'nichts auf die Reihe bekommen', 'Hoy no doy pie con bola.', 'Heute bekomme ich gar nichts auf die Reihe.', 'phrase'],
      ['a regañadientes', 'widerwillig', 'Aceptó a regañadientes.', 'Sie stimmte widerwillig zu.', 'phrase'],
      ['a bombo y platillo', 'mit großem Tamtam', 'Lo anunciaron a bombo y platillo.', 'Sie kündigten es mit großem Tamtam an.', 'phrase'],
      ['de tapadillo', 'heimlich', 'Lo aprobaron de tapadillo en agosto.', 'Sie beschlossen es heimlich im August.', 'phrase'],
      ['a bocajarro', 'ganz direkt', 'Se lo preguntó a bocajarro.', 'Sie fragte ihn ganz direkt.', 'phrase'],
      ['sin paliativos', 'ohne Beschönigung', 'Fue una derrota sin paliativos.', 'Es war eine Niederlage ohne Beschönigung.', 'phrase'],
      ['a todas luces', 'offensichtlich', 'Es a todas luces improcedente.', 'Es ist offensichtlich unzulässig.', 'phrase'],
      ['con pelos y señales', 'haarklein', 'Lo contó con pelos y señales.', 'Er erzählte es haarklein.', 'phrase'],
      ['en un abrir y cerrar de ojos', 'im Handumdrehen', 'Lo resolvió en un abrir y cerrar de ojos.', 'Sie löste es im Handumdrehen.', 'phrase'],
      ['a la vuelta de la esquina', 'in greifbarer Nähe', 'Las elecciones están a la vuelta de la esquina.', 'Die Wahlen stehen unmittelbar bevor.', 'phrase'],
      ['echar leña al fuego', 'Öl ins Feuer gießen', 'Ese titular echa leña al fuego.', 'Diese Schlagzeile gießt Öl ins Feuer.', 'phrase'],
      ['pasar por alto', 'übersehen, übergehen', 'Pasaron por alto un detalle esencial.', 'Sie übergingen ein wesentliches Detail.', 'phrase'],
      ['dar carpetazo', 'zu den Akten legen', 'Dieron carpetazo al asunto.', 'Sie legten die Sache zu den Akten.', 'phrase'],
      ['sacar los colores', 'jemanden beschämen', 'Le sacó los colores delante de todos.', 'Sie beschämte ihn vor allen.', 'phrase'],
      ['llevarse el gato al agua', 'sich durchsetzen', 'Al final se llevó el gato al agua.', 'Am Ende setzte er sich durch.', 'phrase'],
      ['arrimar el hombro', 'mit anpacken', 'Todos arrimaron el hombro.', 'Alle packten mit an.', 'phrase'],
      ['coger el toro por los cuernos', 'den Stier bei den Hörnern packen', 'Cogió el toro por los cuernos.', 'Sie packte den Stier bei den Hörnern.', 'phrase'],
      ['estar en las últimas', 'am Ende sein', 'La batería está en las últimas.', 'Der Akku ist am Ende.', 'phrase'],
      ['costar Dios y ayuda', 'unglaublich mühsam sein', 'Nos costó Dios y ayuda convencerlo.', 'Es kostete uns unendliche Mühe, ihn zu überzeugen.', 'phrase'],
      ['no tener pelos en la lengua', 'kein Blatt vor den Mund nehmen', 'No tiene pelos en la lengua.', 'Sie nimmt kein Blatt vor den Mund.', 'phrase'],
      ['ser harina de otro costal', 'ein ganz anderes Kapitel sein', 'Eso ya es harina de otro costal.', 'Das ist ein ganz anderes Kapitel.', 'phrase'],
      ['quedarse corto', 'untertrieben sein', 'Decir que fue duro se queda corto.', 'Zu sagen, es war hart, ist untertrieben.', 'phrase'],
      ['dar largas', 'hinhalten', 'Llevan meses dándome largas.', 'Sie halten mich seit Monaten hin.', 'phrase'],
      ['salir el tiro por la culata', 'nach hinten losgehen', 'La estrategia les salió el tiro por la culata.', 'Die Strategie ging nach hinten los.', 'phrase'],
      ['ir sobre ruedas', 'wie geschmiert laufen', 'El proyecto va sobre ruedas.', 'Das Projekt läuft wie geschmiert.', 'phrase'],
      ['a título personal', 'in eigener Sache', 'Hablo a título personal.', 'Ich spreche in eigener Sache.', 'phrase'],
      ['puestos a elegir', 'wenn man schon wählen muss', 'Puestos a elegir, prefiero esperar.', 'Wenn man schon wählen muss, warte ich lieber.', 'phrase'],
      ['por lo bajo', 'mindestens, heimlich', 'Costará mil euros por lo bajo.', 'Es wird mindestens tausend Euro kosten.', 'phrase'],
      ['ni por asomo', 'nicht im Entferntesten', 'Ni por asomo es comparable.', 'Es ist nicht im Entferntesten vergleichbar.', 'phrase'],
      ['a ojos vistas', 'zusehends', 'La situación empeora a ojos vistas.', 'Die Lage verschlechtert sich zusehends.', 'phrase'],
      ['contra viento y marea', 'allen Widrigkeiten zum Trotz', 'Siguió adelante contra viento y marea.', 'Sie machte allen Widrigkeiten zum Trotz weiter.', 'phrase'],
      ['a fuerza de', 'durch beharrliches', 'Aprendió a fuerza de repetir.', 'Er lernte durch beharrliches Wiederholen.', 'phrase'],
      ['de mala gana', 'unwillig', 'Contestó de mala gana.', 'Er antwortete unwillig.', 'phrase'],
      ['a la postre', 'schließlich', 'A la postre, nadie se opuso.', 'Schließlich widersprach niemand.', 'phrase'],
      ['por si fuera poco', 'als ob das nicht genug wäre', 'Por si fuera poco, empezó a llover.', 'Als ob das nicht genug wäre, fing es an zu regnen.', 'phrase'],
      ['sin más ni más', 'mir nichts, dir nichts', 'Se marchó sin más ni más.', 'Sie ging mir nichts, dir nichts weg.', 'phrase'],
      ['de un plumazo', 'mit einem Federstrich', 'Eliminaron la ayuda de un plumazo.', 'Sie strichen die Beihilfe mit einem Federstrich.', 'phrase'],
      ['a las bravas', 'mit Gewalt, ohne Umschweife', 'Lo impusieron a las bravas.', 'Sie setzten es mit Gewalt durch.', 'phrase'],
      ['con cuentagotas', 'nur tröpfchenweise', 'La información llega con cuentagotas.', 'Die Informationen kommen nur tröpfchenweise.', 'phrase'],
      ['a sabiendas', 'wissentlich', 'Lo hizo a sabiendas del riesgo.', 'Er tat es wissentlich trotz des Risikos.', 'phrase'],
      ['dicho sea de paso', 'nebenbei bemerkt', 'Dicho sea de paso, nadie lo consultó.', 'Nebenbei bemerkt hat niemand nachgefragt.', 'phrase'],
    ],
  },
];
