import { CefrLevel } from '@prisma/client';

/**
 * 250 spanische Vokabeln für CEFR B1 – fünf Themenpakete zu je 50 Wörtern.
 *
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 * Übersetzt wird ins Deutsche, weil die Oberfläche deutsch ist. Substantive
 * stehen mit Artikel, Verben im Infinitiv. Wörter aus A1/A2 werden nicht wiederholt.
 */
export const SPANISH_VOCAB_B1 = [
  {
    title: 'Arbeit & Beruf',
    level: CefrLevel.B1,
    description: 'Bewerbung, Büroalltag und Karriere',
    iconEmoji: '💼',
    items: [
      ['el trabajo', 'die Arbeit', 'Busco trabajo desde hace tres meses.', 'Ich suche seit drei Monaten Arbeit.', 'noun'],
      ['el empleo', 'die Stelle, Beschäftigung', 'Ha encontrado un empleo estable.', 'Er hat eine feste Stelle gefunden.', 'noun'],
      ['la profesión', 'der Beruf', '¿A qué se dedica usted de profesión?', 'Was sind Sie von Beruf?', 'noun'],
      ['la empresa', 'das Unternehmen', 'La empresa tiene doscientos empleados.', 'Das Unternehmen hat zweihundert Angestellte.', 'noun'],
      ['la oficina', 'das Büro', 'La oficina está en la planta cuarta.', 'Das Büro ist im vierten Stock.', 'noun'],
      ['el despacho', 'das Arbeitszimmer, Chefbüro', 'El director la ha llamado a su despacho.', 'Der Direktor hat sie in sein Büro gerufen.', 'noun'],
      ['el contrato', 'der Vertrag', 'Firmé el contrato la semana pasada.', 'Ich habe letzte Woche den Vertrag unterschrieben.', 'noun'],
      ['el sueldo', 'das Gehalt', 'El sueldo no es alto, pero es seguro.', 'Das Gehalt ist nicht hoch, aber sicher.', 'noun'],
      ['el horario laboral', 'die Arbeitszeit', 'Tenemos un horario laboral flexible.', 'Wir haben flexible Arbeitszeiten.', 'noun'],
      ['la jornada completa', 'die Vollzeit', 'Trabajo a jornada completa.', 'Ich arbeite in Vollzeit.', 'noun'],
      ['la media jornada', 'die Teilzeit', 'Prefiere la media jornada por los niños.', 'Wegen der Kinder bevorzugt sie Teilzeit.', 'noun'],
      ['las horas extras', 'die Überstunden', 'Esta semana he hecho muchas horas extras.', 'Diese Woche habe ich viele Überstunden gemacht.', 'noun'],
      ['la solicitud', 'die Bewerbung', 'He enviado la solicitud por correo.', 'Ich habe die Bewerbung per Post geschickt.', 'noun'],
      ['el currículum', 'der Lebenslauf', 'Actualiza tu currículum antes de enviarlo.', 'Aktualisiere deinen Lebenslauf, bevor du ihn schickst.', 'noun'],
      ['la entrevista', 'das Vorstellungsgespräch', 'La entrevista salió muy bien.', 'Das Vorstellungsgespräch lief sehr gut.', 'noun'],
      ['el candidato', 'der Bewerber', 'Hay quince candidatos para el puesto.', 'Es gibt fünfzehn Bewerber für die Stelle.', 'noun'],
      ['el puesto', 'die Position', 'El puesto exige experiencia previa.', 'Die Stelle erfordert Vorerfahrung.', 'noun'],
      ['la experiencia', 'die Erfahrung', 'Tiene diez años de experiencia.', 'Sie hat zehn Jahre Erfahrung.', 'noun'],
      ['la formación', 'die Ausbildung', 'La empresa ofrece formación continua.', 'Das Unternehmen bietet Weiterbildung an.', 'noun'],
      ['los conocimientos de idiomas', 'die Sprachkenntnisse', 'Se valoran los conocimientos de idiomas.', 'Sprachkenntnisse werden geschätzt.', 'noun'],
      ['la responsabilidad', 'die Verantwortung', 'Asumo la responsabilidad del error.', 'Ich übernehme die Verantwortung für den Fehler.', 'noun'],
      ['la tarea', 'die Aufgabe', 'Esta tarea lleva todo el día.', 'Diese Aufgabe dauert den ganzen Tag.', 'noun'],
      ['el proyecto', 'das Projekt', 'El proyecto termina en junio.', 'Das Projekt endet im Juni.', 'noun'],
      ['la reunión', 'die Besprechung', 'La reunión se ha aplazado al jueves.', 'Die Besprechung wurde auf Donnerstag verschoben.', 'noun'],
      ['el plazo', 'die Frist', 'El plazo vence el viernes.', 'Die Frist läuft am Freitag ab.', 'noun'],
      ['el informe', 'der Bericht', 'Tengo que entregar el informe hoy.', 'Ich muss den Bericht heute abgeben.', 'noun'],
      ['la carrera profesional', 'die berufliche Laufbahn', 'Su carrera profesional avanza rápido.', 'Seine Laufbahn schreitet schnell voran.', 'noun'],
      ['el ascenso', 'die Beförderung', 'Espera un ascenso este año.', 'Sie hofft dieses Jahr auf eine Beförderung.', 'noun'],
      ['el equipo de trabajo', 'das Arbeitsteam', 'El equipo de trabajo funciona muy bien.', 'Das Arbeitsteam funktioniert sehr gut.', 'noun'],
      ['el colega', 'der Kollege', 'Mis colegas son muy competentes.', 'Meine Kollegen sind sehr kompetent.', 'noun'],
      ['la baja', 'die Krankmeldung', 'Está de baja desde el lunes.', 'Er ist seit Montag krankgeschrieben.', 'noun'],
      ['el paro', 'die Arbeitslosigkeit', 'El paro ha bajado este trimestre.', 'Die Arbeitslosigkeit ist dieses Quartal gesunken.', 'noun'],
      ['la jubilación', 'der Ruhestand', 'Le quedan dos años para la jubilación.', 'Bis zum Ruhestand bleiben ihm zwei Jahre.', 'noun'],
      ['el autónomo', 'der Selbstständige', 'Trabaja como autónomo desde 2019.', 'Er arbeitet seit 2019 als Selbstständiger.', 'noun'],
      ['el sindicato', 'die Gewerkschaft', 'El sindicato negocia el convenio.', 'Die Gewerkschaft verhandelt den Tarifvertrag.', 'noun'],
      ['solicitar', 'sich bewerben um', 'He solicitado una beca de investigación.', 'Ich habe mich um ein Forschungsstipendium beworben.', 'verb'],
      ['contratar', 'einstellen', 'Van a contratar a dos programadores.', 'Sie werden zwei Programmierer einstellen.', 'verb'],
      ['despedir', 'entlassen', 'Han despedido a media plantilla.', 'Sie haben die halbe Belegschaft entlassen.', 'verb'],
      ['dimitir', 'kündigen (von sich aus)', 'El ministro ha dimitido esta mañana.', 'Der Minister ist heute Morgen zurückgetreten.', 'verb'],
      ['dirigir', 'leiten', 'Dirige el departamento desde hace un año.', 'Sie leitet die Abteilung seit einem Jahr.', 'verb'],
      ['encargarse de', 'sich kümmern um', 'Yo me encargo de los clientes nuevos.', 'Ich kümmere mich um die neuen Kunden.', 'phrase'],
      ['cumplir', 'erfüllen, einhalten', 'Hemos cumplido todos los plazos.', 'Wir haben alle Fristen eingehalten.', 'verb'],
      ['ascender', 'befördert werden', 'La han ascendido a jefa de equipo.', 'Sie wurde zur Teamleiterin befördert.', 'verb'],
      ['negociar', 'verhandeln', 'Negociamos las condiciones mañana.', 'Wir verhandeln morgen die Bedingungen.', 'verb'],
      ['colaborar', 'zusammenarbeiten', 'Colaboramos con una agencia de Madrid.', 'Wir arbeiten mit einer Agentur in Madrid zusammen.', 'verb'],
      ['exigir', 'verlangen', 'El jefe exige demasiado.', 'Der Chef verlangt zu viel.', 'verb'],
      ['eficaz', 'wirksam, effizient', 'Es un método muy eficaz.', 'Das ist eine sehr wirksame Methode.', 'adjective'],
      ['exigente', 'anspruchsvoll', 'Es un cliente muy exigente.', 'Das ist ein sehr anspruchsvoller Kunde.', 'adjective'],
      ['fijo', 'fest, unbefristet', 'Por fin tiene un contrato fijo.', 'Endlich hat sie einen unbefristeten Vertrag.', 'adjective'],
      ['estresante', 'stressig', 'La temporada alta es muy estresante.', 'Die Hochsaison ist sehr stressig.', 'adjective'],
    ],
  },
  {
    title: 'Schule & Ausbildung',
    level: CefrLevel.B1,
    description: 'Schule, Studium und lebenslanges Lernen',
    iconEmoji: '🎓',
    items: [
      ['la escuela', 'die Schule', 'La escuela está a dos calles.', 'Die Schule ist zwei Straßen entfernt.', 'noun'],
      ['el instituto', 'das Gymnasium, die Oberschule', 'Terminó el instituto con buenas notas.', 'Er beendete die Oberschule mit guten Noten.', 'noun'],
      ['la universidad', 'die Universität', 'Estudia en la universidad de Granada.', 'Sie studiert an der Universität Granada.', 'noun'],
      ['la carrera', 'das Studium', 'Acabó la carrera en cinco años.', 'Sie hat das Studium in fünf Jahren beendet.', 'noun'],
      ['la asignatura', 'das Schulfach', 'Mi asignatura favorita era historia.', 'Mein Lieblingsfach war Geschichte.', 'noun'],
      ['el curso', 'der Kurs, das Schuljahr', 'El curso empieza en septiembre.', 'Das Schuljahr beginnt im September.', 'noun'],
      ['la clase', 'der Unterricht, die Klasse', 'La clase de hoy se ha cancelado.', 'Der heutige Unterricht ist ausgefallen.', 'noun'],
      ['el aula', 'der Klassenraum', 'El aula tiene una pizarra digital.', 'Der Klassenraum hat eine digitale Tafel.', 'noun'],
      ['el examen', 'die Prüfung', 'El examen final es en junio.', 'Die Abschlussprüfung ist im Juni.', 'noun'],
      ['la nota', 'die Note', 'He sacado buena nota en el examen.', 'Ich habe eine gute Note in der Prüfung bekommen.', 'noun'],
      ['el aprobado', 'das Bestehen', 'Con un cinco tienes el aprobado.', 'Mit einer Fünf hast du bestanden.', 'noun'],
      ['el suspenso', 'das Nichtbestehen', 'Un suspenso no es el fin del mundo.', 'Ein Durchfallen ist nicht das Ende der Welt.', 'noun'],
      ['los deberes', 'die Hausaufgaben', 'Haz los deberes antes de cenar.', 'Mach die Hausaufgaben vor dem Abendessen.', 'noun'],
      ['el apunte', 'die Notiz, Mitschrift', 'Le he prestado mis apuntes.', 'Ich habe ihm meine Mitschriften geliehen.', 'noun'],
      ['el cuaderno', 'das Heft', 'Escribe la fecha en el cuaderno.', 'Schreib das Datum ins Heft.', 'noun'],
      ['el manual', 'das Lehrbuch', 'El manual cuesta cuarenta euros.', 'Das Lehrbuch kostet vierzig Euro.', 'noun'],
      ['la biblioteca', 'die Bibliothek', 'Estudio en la biblioteca por la tarde.', 'Nachmittags lerne ich in der Bibliothek.', 'noun'],
      ['el título', 'der Abschluss, Titel', 'Necesita el título para ejercer.', 'Er braucht den Abschluss, um zu praktizieren.', 'noun'],
      ['la beca', 'das Stipendium', 'Le han concedido una beca completa.', 'Ihm wurde ein volles Stipendium gewährt.', 'noun'],
      ['la matrícula', 'die Einschreibung, Studiengebühr', 'La matrícula se paga en octubre.', 'Die Studiengebühr wird im Oktober bezahlt.', 'noun'],
      ['el máster', 'der Master', 'Hace un máster en economía.', 'Er macht einen Master in Wirtschaft.', 'noun'],
      ['el doctorado', 'die Promotion', 'Terminó el doctorado a los treinta.', 'Sie beendete die Promotion mit dreißig.', 'noun'],
      ['la investigación', 'die Forschung', 'Su investigación trata sobre el clima.', 'Ihre Forschung handelt vom Klima.', 'noun'],
      ['el trabajo en grupo', 'die Gruppenarbeit', 'El trabajo en grupo vale un treinta por ciento.', 'Die Gruppenarbeit zählt dreißig Prozent.', 'noun'],
      ['la presentación', 'das Referat', 'Mi presentación dura quince minutos.', 'Mein Referat dauert fünfzehn Minuten.', 'noun'],
      ['el conocimiento previo', 'das Vorwissen', 'No hace falta conocimiento previo.', 'Vorwissen ist nicht nötig.', 'noun'],
      ['el esfuerzo', 'die Anstrengung', 'Con esfuerzo todo se consigue.', 'Mit Anstrengung erreicht man alles.', 'noun'],
      ['el error', 'der Fehler', 'Aprendemos de los errores.', 'Wir lernen aus Fehlern.', 'noun'],
      ['el progreso', 'der Fortschritt', 'Su progreso es notable.', 'Ihr Fortschritt ist bemerkenswert.', 'noun'],
      ['el objetivo', 'das Ziel', 'Mi objetivo es hablar con fluidez.', 'Mein Ziel ist es, fließend zu sprechen.', 'noun'],
      ['el alumno', 'der Schüler', 'Los alumnos entregan el trabajo mañana.', 'Die Schüler geben die Arbeit morgen ab.', 'noun'],
      ['la tutoría', 'die Sprechstunde', 'Pide una tutoría con el profesor.', 'Bitte um eine Sprechstunde beim Professor.', 'noun'],
      ['el recreo', 'die Pause', 'Durante el recreo juegan al fútbol.', 'In der Pause spielen sie Fußball.', 'noun'],
      ['el curso intensivo', 'der Intensivkurs', 'Hice un curso intensivo de verano.', 'Ich habe einen Intensivkurs im Sommer gemacht.', 'noun'],
      ['la práctica', 'das Praktikum, die Übung', 'Las prácticas duran tres meses.', 'Das Praktikum dauert drei Monate.', 'noun'],
      ['aprender', 'lernen', 'Aprendo español desde hace dos años.', 'Ich lerne seit zwei Jahren Spanisch.', 'verb'],
      ['enseñar', 'unterrichten', 'Enseña matemáticas en secundaria.', 'Sie unterrichtet Mathematik in der Sekundarstufe.', 'verb'],
      ['estudiar', 'studieren, lernen', 'Estudio todas las noches una hora.', 'Ich lerne jeden Abend eine Stunde.', 'verb'],
      ['repasar', 'wiederholen', 'Repaso el vocabulario antes de dormir.', 'Ich wiederhole die Vokabeln vor dem Schlafen.', 'verb'],
      ['memorizar', 'auswendig lernen', 'Es inútil memorizar sin entender.', 'Auswendiglernen ohne Verstehen ist nutzlos.', 'verb'],
      ['aprobar', 'bestehen', 'He aprobado todas las asignaturas.', 'Ich habe alle Fächer bestanden.', 'verb'],
      ['suspender', 'durchfallen', 'Suspendí el examen de física.', 'Ich bin in der Physikprüfung durchgefallen.', 'verb'],
      ['matricularse', 'sich einschreiben', 'Me matriculé en dos cursos.', 'Ich habe mich für zwei Kurse eingeschrieben.', 'verb'],
      ['corregir', 'korrigieren', 'El profesor corrige los exámenes el fin de semana.', 'Der Lehrer korrigiert die Prüfungen am Wochenende.', 'verb'],
      ['explicar', 'erklären', '¿Puedes explicarlo otra vez?', 'Kannst du es noch einmal erklären?', 'verb'],
      ['resumir', 'zusammenfassen', 'Resume el texto en diez líneas.', 'Fasse den Text in zehn Zeilen zusammen.', 'verb'],
      ['mejorar', 'verbessern', 'Quiero mejorar mi pronunciación.', 'Ich möchte meine Aussprache verbessern.', 'verb'],
      ['difícil', 'schwierig', 'El subjuntivo es difícil al principio.', 'Der Subjuntivo ist anfangs schwierig.', 'adjective'],
      ['obligatorio', 'verpflichtend', 'La asistencia es obligatoria.', 'Die Anwesenheit ist verpflichtend.', 'adjective'],
      ['avanzado', 'fortgeschritten', 'Está en un nivel avanzado.', 'Sie ist auf einem fortgeschrittenen Niveau.', 'adjective'],
    ],
  },
  {
    title: 'Wohnen & Umzug',
    level: CefrLevel.B1,
    description: 'Wohnung suchen, mieten und einrichten',
    iconEmoji: '🏠',
    items: [
      ['la vivienda', 'die Wohnung, Unterkunft', 'La vivienda es un problema en las ciudades.', 'Wohnraum ist in den Städten ein Problem.', 'noun'],
      ['el inquilino', 'der Mieter', 'El inquilino paga a principios de mes.', 'Der Mieter zahlt Anfang des Monats.', 'noun'],
      ['el propietario', 'der Eigentümer', 'El propietario vive en otra ciudad.', 'Der Eigentümer wohnt in einer anderen Stadt.', 'noun'],
      ['el casero', 'der Vermieter', 'El casero ha subido el alquiler.', 'Der Vermieter hat die Miete erhöht.', 'noun'],
      ['el contrato de alquiler', 'der Mietvertrag', 'El contrato de alquiler dura un año.', 'Der Mietvertrag läuft ein Jahr.', 'noun'],
      ['la fianza', 'die Kaution', 'La fianza son dos meses de alquiler.', 'Die Kaution beträgt zwei Monatsmieten.', 'noun'],
      ['los gastos', 'die Nebenkosten', 'Los gastos no están incluidos.', 'Die Nebenkosten sind nicht enthalten.', 'noun'],
      ['la hipoteca', 'die Hypothek', 'Pagamos la hipoteca hasta 2040.', 'Wir zahlen die Hypothek bis 2040 ab.', 'noun'],
      ['la mudanza', 'der Umzug', 'La mudanza es el sábado que viene.', 'Der Umzug ist nächsten Samstag.', 'noun'],
      ['la caja de cartón', 'der Umzugskarton', 'Faltan cajas de cartón para los libros.', 'Es fehlen Kartons für die Bücher.', 'noun'],
      ['el trastero', 'der Abstellraum', 'Guardamos las bicis en el trastero.', 'Wir lagern die Räder im Abstellraum.', 'noun'],
      ['el garaje', 'die Garage', 'La plaza de garaje cuesta aparte.', 'Der Garagenplatz kostet extra.', 'noun'],
      ['el portal', 'der Hauseingang', 'Te espero en el portal.', 'Ich warte am Hauseingang auf dich.', 'noun'],
      ['la comunidad de vecinos', 'die Hausgemeinschaft', 'La comunidad de vecinos se reúne el martes.', 'Die Hausgemeinschaft trifft sich am Dienstag.', 'noun'],
      ['la calefacción', 'die Heizung', 'La calefacción no calienta bien.', 'Die Heizung wird nicht richtig warm.', 'noun'],
      ['el aire acondicionado', 'die Klimaanlage', 'Sin aire acondicionado no se puede dormir.', 'Ohne Klimaanlage kann man nicht schlafen.', 'noun'],
      ['la instalación eléctrica', 'die Elektroinstallation', 'La instalación eléctrica es antigua.', 'Die Elektroinstallation ist alt.', 'noun'],
      ['la avería', 'der Defekt, die Panne', 'Hay una avería en el ascensor.', 'Der Aufzug hat einen Defekt.', 'noun'],
      ['la reforma', 'die Renovierung', 'La reforma del baño dura un mes.', 'Die Badrenovierung dauert einen Monat.', 'noun'],
      ['el fontanero', 'der Klempner', 'El fontanero viene esta tarde.', 'Der Klempner kommt heute Nachmittag.', 'noun'],
      ['el electricista', 'der Elektriker', 'Llama a un electricista, por favor.', 'Ruf bitte einen Elektriker.', 'noun'],
      ['la pintura de pared', 'die Wandfarbe', 'Elegimos una pintura de pared clara.', 'Wir haben eine helle Wandfarbe gewählt.', 'noun'],
      ['el mueble', 'das Möbelstück', 'Los muebles son de segunda mano.', 'Die Möbel sind gebraucht.', 'noun'],
      ['la estantería', 'das Regal', 'La estantería no cabe en el pasillo.', 'Das Regal passt nicht in den Flur.', 'noun'],
      ['la alfombra', 'der Teppich', 'La alfombra da calidez al salón.', 'Der Teppich macht das Wohnzimmer gemütlich.', 'noun'],
      ['la cortina', 'der Vorhang', 'Corre las cortinas, hay mucho sol.', 'Zieh die Vorhänge zu, es ist zu sonnig.', 'noun'],
      ['el electrodoméstico', 'das Haushaltsgerät', 'Los electrodomésticos están incluidos.', 'Die Haushaltsgeräte sind inbegriffen.', 'noun'],
      ['el horno', 'der Backofen', 'El horno tarda en calentarse.', 'Der Backofen braucht lange zum Aufheizen.', 'noun'],
      ['el lavavajillas', 'die Spülmaschine', 'El lavavajillas hace mucho ruido.', 'Die Spülmaschine ist sehr laut.', 'noun'],
      ['el metro cuadrado', 'der Quadratmeter', 'El piso tiene ochenta metros cuadrados.', 'Die Wohnung hat achtzig Quadratmeter.', 'noun'],
      ['la planta', 'die Etage', 'Vivimos en la tercera planta.', 'Wir wohnen im dritten Stock.', 'noun'],
      ['el amueblado', 'die möblierte Wohnung', 'Buscamos un amueblado por seis meses.', 'Wir suchen eine möblierte Wohnung für sechs Monate.', 'noun'],
      ['la orientación', 'die Ausrichtung', 'La orientación al sur es una ventaja.', 'Die Südausrichtung ist ein Vorteil.', 'noun'],
      ['el ruido', 'der Lärm', 'El ruido de la calle me molesta.', 'Der Straßenlärm stört mich.', 'noun'],
      ['la convivencia', 'das Zusammenleben', 'La convivencia con compañeros de piso no es fácil.', 'Das Zusammenleben mit Mitbewohnern ist nicht einfach.', 'noun'],
      ['mudarse', 'umziehen', 'Nos mudamos a las afueras.', 'Wir ziehen an den Stadtrand.', 'verb'],
      ['instalarse', 'sich einrichten', 'Todavía nos estamos instalando.', 'Wir richten uns noch ein.', 'verb'],
      ['amueblar', 'möblieren', 'Hemos amueblado el piso poco a poco.', 'Wir haben die Wohnung nach und nach möbliert.', 'verb'],
      ['decorar', 'dekorieren', 'Decoró el salón con plantas.', 'Sie hat das Wohnzimmer mit Pflanzen dekoriert.', 'verb'],
      ['reformar', 'renovieren', 'Vamos a reformar la cocina en otoño.', 'Wir renovieren die Küche im Herbst.', 'verb'],
      ['arreglar', 'reparieren', 'Han arreglado la caldera por fin.', 'Sie haben die Therme endlich repariert.', 'verb'],
      ['compartir piso', 'in einer WG wohnen', 'Comparto piso con dos estudiantes.', 'Ich wohne mit zwei Studenten in einer WG.', 'phrase'],
      ['firmar', 'unterschreiben', 'Firmamos el contrato el lunes.', 'Wir unterschreiben den Vertrag am Montag.', 'verb'],
      ['avisar', 'Bescheid geben', 'Avisa al casero de la avería.', 'Gib dem Vermieter wegen des Defekts Bescheid.', 'verb'],
      ['soportar', 'aushalten', 'No soporto el ruido de las obras.', 'Ich halte den Baustellenlärm nicht aus.', 'verb'],
      ['luminoso', 'hell', 'El dormitorio es muy luminoso.', 'Das Schlafzimmer ist sehr hell.', 'adjective'],
      ['espacioso', 'geräumig', 'Es un salón espacioso y cómodo.', 'Es ist ein geräumiges, gemütliches Wohnzimmer.', 'adjective'],
      ['céntrico', 'zentral gelegen', 'Es un barrio céntrico y bien comunicado.', 'Es ist ein zentrales, gut angebundenes Viertel.', 'adjective'],
      ['acogedor', 'gemütlich', 'La casa es pequeña pero acogedora.', 'Das Haus ist klein, aber gemütlich.', 'adjective'],
      ['ruidoso', 'laut', 'La calle es ruidosa por las noches.', 'Die Straße ist nachts laut.', 'adjective'],
    ],
  },
  {
    title: 'Medien & Kommunikation',
    level: CefrLevel.B1,
    description: 'Nachrichten, soziale Medien und Gespräche',
    iconEmoji: '📱',
    items: [
      ['los medios de comunicación', 'die Medien', 'Los medios de comunicación influyen mucho.', 'Die Medien haben großen Einfluss.', 'noun'],
      ['la noticia', 'die Nachricht', 'La noticia salió ayer por la noche.', 'Die Nachricht kam gestern Abend heraus.', 'noun'],
      ['el titular', 'die Schlagzeile', 'El titular exagera bastante.', 'Die Schlagzeile übertreibt ziemlich.', 'noun'],
      ['el artículo', 'der Artikel', 'He leído un artículo muy interesante.', 'Ich habe einen sehr interessanten Artikel gelesen.', 'noun'],
      ['el periodista', 'der Journalist', 'La periodista entrevistó al alcalde.', 'Die Journalistin interviewte den Bürgermeister.', 'noun'],
      ['la entrevista periodística', 'das Interview', 'La entrevista periodística dura media hora.', 'Das Interview dauert eine halbe Stunde.', 'noun'],
      ['la fuente', 'die Quelle', 'No cita ninguna fuente fiable.', 'Er nennt keine verlässliche Quelle.', 'noun'],
      ['el reportaje', 'die Reportage', 'El reportaje muestra la vida en el campo.', 'Die Reportage zeigt das Leben auf dem Land.', 'noun'],
      ['el programa', 'die Sendung', 'Ese programa se emite los domingos.', 'Diese Sendung läuft sonntags.', 'noun'],
      ['el canal', 'der Sender, Kanal', 'Cambia de canal, por favor.', 'Wechsle bitte den Sender.', 'noun'],
      ['la emisora', 'der Radiosender', 'Escucho esa emisora en el coche.', 'Ich höre diesen Sender im Auto.', 'noun'],
      ['el anuncio', 'die Werbung, Anzeige', 'El anuncio se repite cada diez minutos.', 'Die Werbung wiederholt sich alle zehn Minuten.', 'noun'],
      ['la publicidad', 'die Werbung', 'La publicidad en internet es agresiva.', 'Werbung im Internet ist aggressiv.', 'noun'],
      ['la red social', 'das soziale Netzwerk', 'Paso demasiado tiempo en las redes sociales.', 'Ich verbringe zu viel Zeit in sozialen Netzwerken.', 'noun'],
      ['la cuenta de usuario', 'das Benutzerkonto', 'He borrado mi cuenta de usuario.', 'Ich habe mein Benutzerkonto gelöscht.', 'noun'],
      ['el seguidor', 'der Follower', 'Tiene miles de seguidores.', 'Sie hat Tausende Follower.', 'noun'],
      ['el comentario', 'der Kommentar', 'Los comentarios son muy duros.', 'Die Kommentare sind sehr hart.', 'noun'],
      ['la contraseña', 'das Passwort', 'He olvidado la contraseña otra vez.', 'Ich habe das Passwort schon wieder vergessen.', 'noun'],
      ['la pantalla', 'der Bildschirm', 'La pantalla del móvil está rota.', 'Der Handybildschirm ist kaputt.', 'noun'],
      ['el móvil', 'das Handy', 'Se me ha quedado el móvil sin batería.', 'Mein Handy hat keinen Akku mehr.', 'noun'],
      ['el ordenador', 'der Computer', 'El ordenador va muy lento.', 'Der Computer ist sehr langsam.', 'noun'],
      ['la aplicación', 'die App', 'He instalado una aplicación de idiomas.', 'Ich habe eine Sprach-App installiert.', 'noun'],
      ['el correo electrónico', 'die E-Mail', 'Te mando un correo electrónico hoy.', 'Ich schicke dir heute eine E-Mail.', 'noun'],
      ['el mensaje', 'die Nachricht', 'Le dejé un mensaje en el buzón de voz.', 'Ich habe ihm eine Nachricht auf der Mailbox hinterlassen.', 'noun'],
      ['la llamada', 'der Anruf', 'Tengo una llamada perdida tuya.', 'Ich habe einen verpassten Anruf von dir.', 'noun'],
      ['la videollamada', 'der Videoanruf', 'Hacemos una videollamada cada domingo.', 'Wir telefonieren sonntags per Video.', 'noun'],
      ['la conexión', 'die Verbindung', 'La conexión se corta cada dos minutos.', 'Die Verbindung bricht alle zwei Minuten ab.', 'noun'],
      ['la privacidad', 'die Privatsphäre', 'Me preocupa mi privacidad en la red.', 'Meine Privatsphäre im Netz beunruhigt mich.', 'noun'],
      ['el bulo', 'die Falschmeldung', 'Ese vídeo es un bulo.', 'Dieses Video ist eine Falschmeldung.', 'noun'],
      ['la opinión', 'die Meinung', 'Respeto tu opinión aunque no la comparto.', 'Ich respektiere deine Meinung, auch wenn ich sie nicht teile.', 'noun'],
      ['el debate', 'die Debatte', 'El debate se alargó dos horas.', 'Die Debatte zog sich zwei Stunden hin.', 'noun'],
      ['el malentendido', 'das Missverständnis', 'Todo fue un malentendido.', 'Alles war ein Missverständnis.', 'noun'],
      ['el rumor', 'das Gerücht', 'Corre el rumor de que se van.', 'Es geht das Gerücht, dass sie weggehen.', 'noun'],
      ['el consejo', 'der Rat', 'Te doy un consejo: escucha primero.', 'Ich gebe dir einen Rat: Hör erst zu.', 'noun'],
      ['la respuesta', 'die Antwort', 'Todavía espero su respuesta.', 'Ich warte noch auf seine Antwort.', 'noun'],
      ['informar', 'informieren', 'El periódico informa con detalle.', 'Die Zeitung informiert ausführlich.', 'verb'],
      ['publicar', 'veröffentlichen', 'Han publicado el estudio completo.', 'Sie haben die vollständige Studie veröffentlicht.', 'verb'],
      ['compartir', 'teilen', 'No compartas datos personales.', 'Teile keine persönlichen Daten.', 'verb'],
      ['navegar', 'surfen', 'Navego por internet antes de dormir.', 'Ich surfe vor dem Schlafen im Internet.', 'verb'],
      ['descargar', 'herunterladen', 'Descarga el archivo desde la web.', 'Lade die Datei von der Website herunter.', 'verb'],
      ['colgar', 'auflegen, hochladen', 'Ha colgado las fotos del viaje.', 'Sie hat die Reisefotos hochgeladen.', 'verb'],
      ['comentar', 'kommentieren', 'Comentamos la noticia en clase.', 'Wir haben die Nachricht im Unterricht besprochen.', 'verb'],
      ['discutir', 'streiten, diskutieren', 'Discutimos sobre política sin enfadarnos.', 'Wir diskutieren über Politik, ohne uns zu ärgern.', 'verb'],
      ['convencer', 'überzeugen', 'Su argumento no me convence.', 'Sein Argument überzeugt mich nicht.', 'verb'],
      ['avisar de', 'warnen vor', 'Nos avisaron del peligro a tiempo.', 'Man hat uns rechtzeitig vor der Gefahr gewarnt.', 'phrase'],
      ['enterarse', 'erfahren', 'Me enteré por la radio.', 'Ich habe es im Radio erfahren.', 'verb'],
      ['fiable', 'verlässlich', 'Es una fuente fiable.', 'Das ist eine verlässliche Quelle.', 'adjective'],
      ['actual', 'aktuell', 'La información no es actual.', 'Die Information ist nicht aktuell.', 'adjective'],
      ['gratuito', 'kostenlos', 'El acceso al archivo es gratuito.', 'Der Zugang zum Archiv ist kostenlos.', 'adjective'],
      ['polémico', 'umstritten', 'Fue un comentario muy polémico.', 'Das war ein sehr umstrittener Kommentar.', 'adjective'],
    ],
  },
  {
    title: 'Gefühle & Beziehungen',
    level: CefrLevel.B1,
    description: 'Emotionen, Freundschaft und Partnerschaft',
    iconEmoji: '❤️',
    items: [
      ['el sentimiento', 'das Gefühl', 'Es difícil describir este sentimiento.', 'Dieses Gefühl ist schwer zu beschreiben.', 'noun'],
      ['la emoción', 'die Emotion', 'No pudo ocultar su emoción.', 'Sie konnte ihre Rührung nicht verbergen.', 'noun'],
      ['la alegría', 'die Freude', 'La noticia nos dio mucha alegría.', 'Die Nachricht hat uns sehr gefreut.', 'noun'],
      ['la tristeza', 'die Traurigkeit', 'Habla de su tristeza sin vergüenza.', 'Er spricht ohne Scham über seine Traurigkeit.', 'noun'],
      ['el miedo', 'die Angst', 'Tiene miedo a volar.', 'Sie hat Flugangst.', 'noun'],
      ['la rabia', 'die Wut', 'Sentí rabia al leer el mensaje.', 'Beim Lesen der Nachricht empfand ich Wut.', 'noun'],
      ['los celos', 'die Eifersucht', 'Los celos arruinaron la relación.', 'Die Eifersucht hat die Beziehung zerstört.', 'noun'],
      ['la vergüenza', 'die Scham', 'Me da vergüenza hablar en público.', 'Es ist mir peinlich, öffentlich zu sprechen.', 'noun'],
      ['la sorpresa', 'die Überraschung', 'Fue una sorpresa muy agradable.', 'Es war eine sehr angenehme Überraschung.', 'noun'],
      ['la ilusión', 'die Vorfreude', 'Me hace mucha ilusión el viaje.', 'Ich freue mich sehr auf die Reise.', 'noun'],
      ['la confianza', 'das Vertrauen', 'Sin confianza no hay amistad.', 'Ohne Vertrauen gibt es keine Freundschaft.', 'noun'],
      ['el cariño', 'die Zuneigung', 'Le tengo mucho cariño a mi tía.', 'Ich habe meine Tante sehr gern.', 'noun'],
      ['el amor', 'die Liebe', 'El amor no lo resuelve todo.', 'Liebe löst nicht alles.', 'noun'],
      ['la amistad', 'die Freundschaft', 'Nuestra amistad dura veinte años.', 'Unsere Freundschaft besteht seit zwanzig Jahren.', 'noun'],
      ['la pareja', 'die Partnerschaft, der Partner', 'Vive con su pareja desde hace un año.', 'Er lebt seit einem Jahr mit seinem Partner zusammen.', 'noun'],
      ['la relación', 'die Beziehung', 'Tienen una relación muy sana.', 'Sie haben eine sehr gesunde Beziehung.', 'noun'],
      ['la boda', 'die Hochzeit', 'La boda es en septiembre.', 'Die Hochzeit ist im September.', 'noun'],
      ['el divorcio', 'die Scheidung', 'El divorcio fue tranquilo.', 'Die Scheidung verlief ruhig.', 'noun'],
      ['la discusión', 'der Streit', 'Tuvimos una discusión tonta.', 'Wir hatten einen dummen Streit.', 'noun'],
      ['la disculpa', 'die Entschuldigung', 'Acepté sus disculpas.', 'Ich habe seine Entschuldigung angenommen.', 'noun'],
      ['el apoyo', 'die Unterstützung', 'Gracias por tu apoyo estos meses.', 'Danke für deine Unterstützung in diesen Monaten.', 'noun'],
      ['la soledad', 'die Einsamkeit', 'La soledad a veces sienta bien.', 'Einsamkeit tut manchmal gut.', 'noun'],
      ['el estrés', 'der Stress', 'El estrés me quita el sueño.', 'Der Stress raubt mir den Schlaf.', 'noun'],
      ['el carácter', 'der Charakter', 'Tiene un carácter muy fuerte.', 'Sie hat einen sehr starken Charakter.', 'noun'],
      ['el humor', 'die Laune, der Humor', 'Hoy está de mal humor.', 'Heute hat er schlechte Laune.', 'noun'],
      ['la paciencia', 'die Geduld', 'Se me acaba la paciencia.', 'Mir geht die Geduld aus.', 'noun'],
      ['el orgullo', 'der Stolz', 'Su orgullo le impide pedir ayuda.', 'Sein Stolz hindert ihn daran, um Hilfe zu bitten.', 'noun'],
      ['la esperanza', 'die Hoffnung', 'No pierdo la esperanza.', 'Ich verliere die Hoffnung nicht.', 'noun'],
      ['la preocupación', 'die Sorge', 'Su mayor preocupación son los hijos.', 'Ihre größte Sorge sind die Kinder.', 'noun'],
      ['el recuerdo', 'die Erinnerung', 'Guardo un buen recuerdo de aquel verano.', 'Ich habe eine schöne Erinnerung an jenen Sommer.', 'noun'],
      ['querer a alguien', 'jemanden lieb haben', 'Quiero mucho a mis amigos.', 'Ich habe meine Freunde sehr lieb.', 'phrase'],
      ['enamorarse', 'sich verlieben', 'Se enamoró en el primer curso.', 'Sie verliebte sich im ersten Studienjahr.', 'verb'],
      ['echar de menos', 'vermissen', 'Echo de menos a mi familia.', 'Ich vermisse meine Familie.', 'phrase'],
      ['confiar en', 'vertrauen auf', 'Confío en ti completamente.', 'Ich vertraue dir voll und ganz.', 'phrase'],
      ['discutir con', 'sich streiten mit', 'Discutí con mi hermano por una tontería.', 'Ich habe mich wegen einer Kleinigkeit mit meinem Bruder gestritten.', 'phrase'],
      ['perdonar', 'verzeihen', 'Le he perdonado todo.', 'Ich habe ihm alles verziehen.', 'verb'],
      ['apoyar', 'unterstützen', 'Mis padres siempre me apoyaron.', 'Meine Eltern haben mich immer unterstützt.', 'verb'],
      ['preocuparse', 'sich sorgen', 'No te preocupes por eso.', 'Mach dir darüber keine Sorgen.', 'verb'],
      ['alegrarse', 'sich freuen', 'Me alegro mucho por vosotros.', 'Ich freue mich sehr für euch.', 'verb'],
      ['enfadarse', 'sich ärgern', 'Se enfada por cualquier cosa.', 'Er ärgert sich über jede Kleinigkeit.', 'verb'],
      ['sorprenderse', 'sich wundern', 'Me sorprendí al verla allí.', 'Ich war überrascht, sie dort zu sehen.', 'verb'],
      ['soportar a alguien', 'jemanden ertragen', 'No soporto a ese compañero.', 'Ich kann diesen Kollegen nicht ausstehen.', 'phrase'],
      ['acostumbrarse', 'sich gewöhnen', 'Me he acostumbrado al horario español.', 'Ich habe mich an den spanischen Tagesrhythmus gewöhnt.', 'verb'],
      ['agradecer', 'danken', 'Te agradezco mucho el detalle.', 'Ich danke dir sehr für die Aufmerksamkeit.', 'verb'],
      ['celoso', 'eifersüchtig', 'Es celoso sin motivo.', 'Er ist grundlos eifersüchtig.', 'adjective'],
      ['sincero', 'aufrichtig', 'Prefiero una respuesta sincera.', 'Ich ziehe eine aufrichtige Antwort vor.', 'adjective'],
      ['sensible', 'sensibel', 'Es una persona muy sensible.', 'Sie ist ein sehr sensibler Mensch.', 'adjective'],
      ['orgulloso', 'stolz', 'Estoy orgulloso de mi hija.', 'Ich bin stolz auf meine Tochter.', 'adjective'],
      ['fiel', 'treu', 'Es un amigo fiel desde siempre.', 'Er ist schon immer ein treuer Freund.', 'adjective'],
      ['nervioso', 'nervös', 'Me pongo nervioso antes de hablar.', 'Vor dem Sprechen werde ich nervös.', 'adjective'],
    ],
  },
];
