import { CefrLevel } from '@prisma/client';

/**
 * 250 spanische Vokabeln für CEFR C1 – fünf Themenpakete zu je 50 Wörtern.
 *
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 * Übersetzt wird ins Deutsche, weil die Oberfläche deutsch ist. Substantive
 * stehen mit Artikel, Verben im Infinitiv. Wörter aus A1–B2 werden nicht wiederholt.
 */
export const SPANISH_VOCAB_C1 = [
  {
    title: 'Wissenschaft & Forschung',
    level: CefrLevel.C1,
    description: 'Wortschatz für wissenschaftliches Arbeiten, Studien und akademische Diskussionen',
    iconEmoji: '🔬',
    items: [
      ['el planteamiento', 'der Ansatz, die Fragestellung', 'El planteamiento del estudio es novedoso.', 'Die Fragestellung der Studie ist neuartig.', 'noun'],
      ['la metodología', 'die Methodik', 'La metodología se describe en el anexo.', 'Die Methodik wird im Anhang beschrieben.', 'noun'],
      ['el marco teórico', 'der theoretische Rahmen', 'El marco teórico se apoya en dos autores.', 'Der theoretische Rahmen stützt sich auf zwei Autoren.', 'noun'],
      ['la variable', 'die Variable', 'Controlaron todas las variables relevantes.', 'Sie kontrollierten alle relevanten Variablen.', 'noun'],
      ['la correlación', 'die Korrelation', 'La correlación no implica causalidad.', 'Korrelation bedeutet nicht Kausalität.', 'noun'],
      ['la causalidad', 'die Kausalität', 'Establecer causalidad exige un diseño experimental.', 'Kausalität nachzuweisen erfordert ein experimentelles Design.', 'noun'],
      ['el sesgo', 'die Verzerrung, der Bias', 'El sesgo de selección invalida los resultados.', 'Der Selektionsbias entwertet die Ergebnisse.', 'noun'],
      ['la fiabilidad', 'die Reliabilität', 'La fiabilidad del cuestionario es alta.', 'Die Reliabilität des Fragebogens ist hoch.', 'noun'],
      ['la validez', 'die Validität', 'Cuestionan la validez externa del estudio.', 'Sie stellen die externe Validität der Studie infrage.', 'noun'],
      ['la muestra representativa', 'die repräsentative Stichprobe', 'Sin una muestra representativa no se puede generalizar.', 'Ohne repräsentative Stichprobe lässt sich nicht verallgemeinern.', 'noun'],
      ['el indicador', 'der Indikator', 'Este indicador mide la desigualdad.', 'Dieser Indikator misst die Ungleichheit.', 'noun'],
      ['la evidencia empírica', 'die empirische Evidenz', 'La evidencia empírica es todavía escasa.', 'Die empirische Evidenz ist noch dünn.', 'noun'],
      ['el hallazgo', 'der Befund', 'Los hallazgos contradicen la literatura previa.', 'Die Befunde widersprechen der bisherigen Literatur.', 'noun'],
      ['la premisa', 'die Prämisse', 'La premisa de partida es discutible.', 'Die Ausgangsprämisse ist strittig.', 'noun'],
      ['el supuesto', 'die Annahme', 'El modelo descansa en tres supuestos.', 'Das Modell beruht auf drei Annahmen.', 'noun'],
      ['la inferencia', 'die Schlussfolgerung', 'La inferencia va más allá de los datos.', 'Die Schlussfolgerung geht über die Daten hinaus.', 'noun'],
      ['la revisión por pares', 'die Begutachtung durch Fachkollegen', 'El artículo pasó la revisión por pares.', 'Der Artikel durchlief die Peer Review.', 'noun'],
      ['la réplica', 'die Replikation, Erwiderung', 'La réplica del experimento fracasó.', 'Die Replikation des Experiments scheiterte.', 'noun'],
      ['el estado de la cuestión', 'der Forschungsstand', 'El estado de la cuestión ocupa el primer capítulo.', 'Der Forschungsstand füllt das erste Kapitel.', 'noun'],
      ['la bibliografía', 'das Literaturverzeichnis', 'La bibliografía incluye cien referencias.', 'Das Literaturverzeichnis umfasst hundert Titel.', 'noun'],
      ['la cita textual', 'das wörtliche Zitat', 'Toda cita textual debe ir entrecomillada.', 'Jedes wörtliche Zitat muss in Anführungszeichen stehen.', 'noun'],
      ['el plagio', 'das Plagiat', 'El plagio conlleva la retirada del artículo.', 'Plagiat führt zum Rückzug des Artikels.', 'noun'],
      ['la ponencia', 'der Vortrag', 'Presentó una ponencia en el congreso.', 'Sie hielt einen Vortrag auf der Tagung.', 'noun'],
      ['el congreso', 'die Fachtagung', 'El congreso reúne a trescientos investigadores.', 'Die Tagung versammelt dreihundert Forschende.', 'noun'],
      ['la tesis doctoral', 'die Dissertation', 'Defendió su tesis doctoral en octubre.', 'Sie verteidigte ihre Dissertation im Oktober.', 'noun'],
      ['el peritaje', 'das Gutachten', 'El peritaje técnico costó una fortuna.', 'Das technische Gutachten kostete ein Vermögen.', 'noun'],
      ['la interdisciplinariedad', 'die Interdisziplinarität', 'La interdisciplinariedad enriquece el análisis.', 'Interdisziplinarität bereichert die Analyse.', 'noun'],
      ['el paradigma', 'das Paradigma', 'El nuevo paradigma tardó décadas en imponerse.', 'Das neue Paradigma brauchte Jahrzehnte, um sich durchzusetzen.', 'noun'],
      ['la aproximación', 'der Zugang, Ansatz', 'Proponen una aproximación cualitativa.', 'Sie schlagen einen qualitativen Zugang vor.', 'noun'],
      ['la limitación', 'die Einschränkung', 'Los autores reconocen las limitaciones del diseño.', 'Die Autoren erkennen die Grenzen des Designs an.', 'noun'],
      ['plantear', 'aufwerfen, darlegen', 'El texto plantea una cuestión incómoda.', 'Der Text wirft eine unbequeme Frage auf.', 'verb'],
      ['abordar', 'behandeln, angehen', 'El capítulo aborda el problema desde otro ángulo.', 'Das Kapitel geht das Problem aus einem anderen Blickwinkel an.', 'verb'],
      ['contrastar', 'gegenüberstellen, überprüfen', 'Contrastamos los datos con fuentes oficiales.', 'Wir gleichen die Daten mit amtlichen Quellen ab.', 'verb'],
      ['inferir', 'schließen, folgern', 'De ahí se infiere una tendencia clara.', 'Daraus lässt sich eine klare Tendenz folgern.', 'verb'],
      ['refutar', 'widerlegen', 'El experimento refuta la hipótesis inicial.', 'Das Experiment widerlegt die Ausgangshypothese.', 'verb'],
      ['corroborar', 'bestätigen', 'Los datos corroboran lo observado en campo.', 'Die Daten bestätigen die Feldbeobachtung.', 'verb'],
      ['matizar', 'differenzieren, abschwächen', 'Conviene matizar esa afirmación.', 'Diese Behauptung sollte differenziert werden.', 'verb'],
      ['generalizar', 'verallgemeinern', 'No se puede generalizar a otras poblaciones.', 'Man kann es nicht auf andere Populationen verallgemeinern.', 'verb'],
      ['sesgar', 'verzerren', 'La pregunta sesga la respuesta.', 'Die Frage verzerrt die Antwort.', 'verb'],
      ['someter a prueba', 'einer Prüfung unterziehen', 'Sometieron el modelo a prueba con datos reales.', 'Sie unterzogen das Modell einer Prüfung mit echten Daten.', 'phrase'],
      ['divulgar', 'verbreiten, popularisieren', 'Divulga la ciencia en un pódcast.', 'Er vermittelt Wissenschaft in einem Podcast.', 'verb'],
      ['riguroso', 'streng, rigoros', 'Es un trabajo metodológicamente riguroso.', 'Das ist eine methodisch strenge Arbeit.', 'adjective'],
      ['concluyente', 'schlüssig, eindeutig', 'La prueba no es concluyente.', 'Der Beweis ist nicht schlüssig.', 'adjective'],
      ['exhaustivo', 'erschöpfend', 'Realizaron una revisión exhaustiva.', 'Sie führten eine erschöpfende Übersicht durch.', 'adjective'],
      ['preliminar', 'vorläufig', 'Son resultados preliminares.', 'Das sind vorläufige Ergebnisse.', 'adjective'],
      ['significativo', 'signifikant', 'La diferencia es estadísticamente significativa.', 'Der Unterschied ist statistisch signifikant.', 'adjective'],
      ['plausible', 'plausibel', 'La explicación es plausible pero no probada.', 'Die Erklärung ist plausibel, aber unbewiesen.', 'adjective'],
      ['en la medida en que', 'insofern als', 'El método sirve en la medida en que el ruido sea bajo.', 'Die Methode taugt, insofern das Rauschen gering ist.', 'phrase'],
      ['cabe destacar que', 'hervorzuheben ist, dass', 'Cabe destacar que la muestra era joven.', 'Hervorzuheben ist, dass die Stichprobe jung war.', 'phrase'],
      ['a la luz de', 'im Lichte von', 'A la luz de los datos, la tesis se sostiene.', 'Im Lichte der Daten hält die These stand.', 'phrase'],
    ],
  },
  {
    title: 'Recht & Verwaltung',
    level: CefrLevel.C1,
    description: 'Wortschatz für Gesetze, Behörden und juristische Zusammenhänge',
    iconEmoji: '⚖️',
    items: [
      ['el ordenamiento jurídico', 'die Rechtsordnung', 'El ordenamiento jurídico prevé este supuesto.', 'Die Rechtsordnung sieht diesen Fall vor.', 'noun'],
      ['la normativa vigente', 'die geltenden Vorschriften', 'La normativa vigente lo prohíbe expresamente.', 'Die geltenden Vorschriften verbieten es ausdrücklich.', 'noun'],
      ['el decreto', 'das Dekret, die Verordnung', 'El decreto se publicó en el boletín oficial.', 'Das Dekret wurde im Amtsblatt veröffentlicht.', 'noun'],
      ['el reglamento', 'die Verordnung', 'El reglamento desarrolla la ley marco.', 'Die Verordnung konkretisiert das Rahmengesetz.', 'noun'],
      ['la jurisprudencia', 'die Rechtsprechung', 'La jurisprudencia del Supremo es constante.', 'Die Rechtsprechung des Obersten Gerichts ist einheitlich.', 'noun'],
      ['el tribunal', 'das Gericht', 'El tribunal desestimó el recurso.', 'Das Gericht wies die Beschwerde ab.', 'noun'],
      ['el juez', 'der Richter', 'La jueza ordenó una nueva pericia.', 'Die Richterin ordnete ein neues Gutachten an.', 'noun'],
      ['el fiscal', 'der Staatsanwalt', 'El fiscal pidió seis años de prisión.', 'Der Staatsanwalt forderte sechs Jahre Haft.', 'noun'],
      ['el abogado defensor', 'der Verteidiger', 'El abogado defensor alegó nulidad.', 'Der Verteidiger machte Nichtigkeit geltend.', 'noun'],
      ['el demandante', 'der Kläger', 'El demandante reclama daños y perjuicios.', 'Der Kläger fordert Schadensersatz.', 'noun'],
      ['el demandado', 'der Beklagte', 'El demandado no compareció.', 'Der Beklagte erschien nicht.', 'noun'],
      ['la demanda', 'die Klage', 'Presentaron la demanda en plazo.', 'Sie reichten die Klage fristgerecht ein.', 'noun'],
      ['el recurso', 'das Rechtsmittel', 'Cabe recurso ante la audiencia provincial.', 'Gegen die Entscheidung ist Berufung möglich.', 'noun'],
      ['la sentencia', 'das Urteil', 'La sentencia es firme desde ayer.', 'Das Urteil ist seit gestern rechtskräftig.', 'noun'],
      ['la resolución', 'der Bescheid', 'La resolución administrativa llegó por correo.', 'Der Verwaltungsbescheid kam mit der Post.', 'noun'],
      ['el fallo', 'der Urteilsspruch', 'El fallo absuelve a los dos acusados.', 'Der Urteilsspruch spricht beide Angeklagten frei.', 'noun'],
      ['la prueba pericial', 'das Sachverständigengutachten', 'La prueba pericial resultó decisiva.', 'Das Sachverständigengutachten war entscheidend.', 'noun'],
      ['el testigo', 'der Zeuge', 'El testigo se contradijo varias veces.', 'Der Zeuge widersprach sich mehrfach.', 'noun'],
      ['la declaración', 'die Aussage', 'Su declaración consta en acta.', 'Seine Aussage steht im Protokoll.', 'noun'],
      ['el delito', 'die Straftat', 'Los hechos constituyen delito.', 'Die Tat erfüllt einen Straftatbestand.', 'noun'],
      ['la pena', 'die Strafe', 'La pena se redujo por atenuantes.', 'Die Strafe wurde wegen mildernder Umstände gemindert.', 'noun'],
      ['la multa', 'die Geldstrafe', 'Le impusieron una multa considerable.', 'Ihm wurde eine erhebliche Geldstrafe auferlegt.', 'noun'],
      ['la responsabilidad civil', 'die zivilrechtliche Haftung', 'La responsabilidad civil recae en la empresa.', 'Die zivilrechtliche Haftung trifft das Unternehmen.', 'noun'],
      ['la prescripción', 'die Verjährung', 'El delito ya está en prescripción.', 'Die Tat ist bereits verjährt.', 'noun'],
      ['el expediente', 'die Akte, das Verfahren', 'Abrieron un expediente disciplinario.', 'Sie eröffneten ein Disziplinarverfahren.', 'noun'],
      ['el trámite', 'der Verwaltungsvorgang', 'El trámite se hace ahora en línea.', 'Der Vorgang läuft jetzt online.', 'noun'],
      ['la instancia', 'der Antrag, die Instanz', 'Presente la instancia en el registro.', 'Reichen Sie den Antrag beim Register ein.', 'noun'],
      ['el plazo de alegaciones', 'die Einspruchsfrist', 'El plazo de alegaciones es de diez días.', 'Die Einspruchsfrist beträgt zehn Tage.', 'noun'],
      ['la notificación', 'die Zustellung', 'La notificación se practicó el martes.', 'Die Zustellung erfolgte am Dienstag.', 'noun'],
      ['el certificado', 'die Bescheinigung', 'Necesita un certificado de empadronamiento.', 'Sie braucht eine Meldebescheinigung.', 'noun'],
      ['el poder notarial', 'die notarielle Vollmacht', 'Firmó un poder notarial a su hermano.', 'Sie stellte ihrem Bruder eine notarielle Vollmacht aus.', 'noun'],
      ['la escritura', 'die Urkunde', 'La escritura de compraventa está en el notario.', 'Die Kaufurkunde liegt beim Notar.', 'noun'],
      ['la cláusula', 'die Klausel', 'Esa cláusula fue declarada abusiva.', 'Diese Klausel wurde für missbräuchlich erklärt.', 'noun'],
      ['la nulidad', 'die Nichtigkeit', 'Solicitaron la nulidad del contrato.', 'Sie beantragten die Nichtigkeit des Vertrags.', 'noun'],
      ['la competencia territorial', 'die örtliche Zuständigkeit', 'Discuten la competencia territorial del juzgado.', 'Sie streiten über die örtliche Zuständigkeit des Gerichts.', 'noun'],
      ['interponer', 'einlegen (Rechtsmittel)', 'Interpusieron recurso de apelación.', 'Sie legten Berufung ein.', 'verb'],
      ['alegar', 'geltend machen', 'Alegó desconocimiento de la norma.', 'Er machte Unkenntnis der Vorschrift geltend.', 'verb'],
      ['dictaminar', 'begutachten, entscheiden', 'El perito dictaminó sobre las causas.', 'Der Sachverständige begutachtete die Ursachen.', 'verb'],
      ['dictar sentencia', 'ein Urteil fällen', 'El juez dictará sentencia en dos semanas.', 'Der Richter wird in zwei Wochen ein Urteil fällen.', 'phrase'],
      ['absolver', 'freisprechen', 'Lo absolvieron por falta de pruebas.', 'Er wurde aus Mangel an Beweisen freigesprochen.', 'verb'],
      ['condenar', 'verurteilen', 'La condenaron a pagar las costas.', 'Sie wurde zur Zahlung der Kosten verurteilt.', 'verb'],
      ['derogar', 'aufheben', 'La reforma derogó el artículo anterior.', 'Die Reform hob den bisherigen Artikel auf.', 'verb'],
      ['tramitar', 'bearbeiten', 'La solicitud se tramita en quince días.', 'Der Antrag wird in fünfzehn Tagen bearbeitet.', 'verb'],
      ['acreditar', 'nachweisen', 'Debe acreditar su residencia.', 'Sie muss ihren Wohnsitz nachweisen.', 'verb'],
      ['subsanar', 'nachbessern, beheben', 'Tiene diez días para subsanar el error.', 'Sie hat zehn Tage, um den Fehler zu beheben.', 'verb'],
      ['preceptivo', 'vorgeschrieben', 'El informe es preceptivo pero no vinculante.', 'Der Bericht ist vorgeschrieben, aber nicht bindend.', 'adjective'],
      ['vinculante', 'bindend', 'La decisión es vinculante para ambas partes.', 'Die Entscheidung ist für beide Parteien bindend.', 'adjective'],
      ['fehaciente', 'beweiskräftig', 'Aportaron prueba fehaciente del pago.', 'Sie legten einen beweiskräftigen Zahlungsnachweis vor.', 'adjective'],
      ['en su caso', 'gegebenenfalls', 'Se aportará, en su caso, la documentación adicional.', 'Gegebenenfalls werden weitere Unterlagen nachgereicht.', 'phrase'],
      ['a efectos de', 'zum Zwecke von', 'A efectos de notificación, señale un domicilio.', 'Zum Zwecke der Zustellung geben Sie eine Anschrift an.', 'phrase'],
    ],
  },
  {
    title: 'Philosophie & Abstraktes Denken',
    level: CefrLevel.C1,
    description: 'Begriffe für philosophische Konzepte und abstrakte Überlegungen',
    iconEmoji: '💭',
    items: [
      ['el pensamiento', 'das Denken', 'Su pensamiento influyó en toda una escuela.', 'Sein Denken prägte eine ganze Schule.', 'noun'],
      ['la razón', 'die Vernunft', 'La razón no basta para explicar la moral.', 'Die Vernunft reicht nicht aus, um Moral zu erklären.', 'noun'],
      ['el conocimiento', 'die Erkenntnis', 'El conocimiento parte siempre de la duda.', 'Erkenntnis beginnt stets mit dem Zweifel.', 'noun'],
      ['la conciencia', 'das Bewusstsein, Gewissen', 'La conciencia sigue siendo un enigma.', 'Das Bewusstsein bleibt ein Rätsel.', 'noun'],
      ['la percepción', 'die Wahrnehmung', 'La percepción condiciona el juicio.', 'Die Wahrnehmung bedingt das Urteil.', 'noun'],
      ['la realidad', 'die Wirklichkeit', 'Distinguir realidad de apariencia es antiguo.', 'Wirklichkeit von Schein zu trennen ist uralt.', 'noun'],
      ['la esencia', 'das Wesen', 'Discuten sobre la esencia de lo humano.', 'Sie streiten über das Wesen des Menschlichen.', 'noun'],
      ['la existencia', 'die Existenz', 'La existencia precede a la esencia.', 'Die Existenz geht dem Wesen voraus.', 'noun'],
      ['el sentido', 'der Sinn', 'La pregunta por el sentido no admite respuesta fácil.', 'Die Sinnfrage lässt keine leichte Antwort zu.', 'noun'],
      ['el fin', 'der Zweck', 'El fin no justifica los medios.', 'Der Zweck heiligt nicht die Mittel.', 'noun'],
      ['la finalidad', 'die Zielsetzung', 'La finalidad de la norma es protectora.', 'Die Zielsetzung der Norm ist schützend.', 'noun'],
      ['el valor', 'der Wert', 'Los valores cambian con las generaciones.', 'Werte ändern sich mit den Generationen.', 'noun'],
      ['la virtud', 'die Tugend', 'La prudencia era la virtud cardinal.', 'Die Klugheit war die Kardinaltugend.', 'noun'],
      ['la ética', 'die Ethik', 'La ética aplicada gana peso en medicina.', 'Angewandte Ethik gewinnt in der Medizin an Gewicht.', 'noun'],
      ['la moral', 'die Moral', 'Distingue entre moral y legalidad.', 'Sie unterscheidet zwischen Moral und Legalität.', 'noun'],
      ['el dilema', 'das Dilemma', 'Es un dilema sin salida cómoda.', 'Das ist ein Dilemma ohne bequemen Ausweg.', 'noun'],
      ['la libertad de elección', 'die Wahlfreiheit', 'La libertad de elección presupone alternativas.', 'Wahlfreiheit setzt Alternativen voraus.', 'noun'],
      ['el determinismo', 'der Determinismus', 'El determinismo niega el azar.', 'Der Determinismus verneint den Zufall.', 'noun'],
      ['el azar', 'der Zufall', 'El azar desempeña un papel mayor del previsto.', 'Der Zufall spielt eine größere Rolle als gedacht.', 'noun'],
      ['la contradicción', 'der Widerspruch', 'Su argumento cae en contradicción.', 'Sein Argument gerät in einen Widerspruch.', 'noun'],
      ['la paradoja', 'das Paradox', 'La paradoja no se resuelve, se habita.', 'Das Paradox löst man nicht, man bewohnt es.', 'noun'],
      ['la ambigüedad', 'die Mehrdeutigkeit', 'La ambigüedad del término entorpece el debate.', 'Die Mehrdeutigkeit des Begriffs behindert die Debatte.', 'noun'],
      ['el matiz', 'die Nuance', 'El matiz importa más que la tesis.', 'Die Nuance zählt mehr als die These.', 'noun'],
      ['el argumento de autoridad', 'das Autoritätsargument', 'El argumento de autoridad no prueba nada.', 'Das Autoritätsargument beweist nichts.', 'noun'],
      ['la falacia', 'der Trugschluss', 'Eso es una falacia de hombre de paja.', 'Das ist ein Strohmann-Trugschluss.', 'noun'],
      ['la coherencia', 'die Kohärenz', 'Valoro la coherencia interna del sistema.', 'Ich schätze die innere Kohärenz des Systems.', 'noun'],
      ['la abstracción', 'die Abstraktion', 'Toda abstracción pierde detalle.', 'Jede Abstraktion verliert Details.', 'noun'],
      ['el concepto', 'der Begriff', 'Define el concepto antes de usarlo.', 'Definiere den Begriff, bevor du ihn verwendest.', 'noun'],
      ['la interpretación', 'die Deutung', 'Caben varias interpretaciones del pasaje.', 'Die Passage lässt mehrere Deutungen zu.', 'noun'],
      ['la subjetividad', 'die Subjektivität', 'Reconoce la subjetividad de su lectura.', 'Er räumt die Subjektivität seiner Lesart ein.', 'noun'],
      ['la objetividad', 'die Objektivität', 'La objetividad plena es un ideal.', 'Vollständige Objektivität ist ein Ideal.', 'noun'],
      ['la trascendencia', 'die Tragweite, Transzendenz', 'La decisión tiene una trascendencia enorme.', 'Die Entscheidung hat enorme Tragweite.', 'noun'],
      ['la finitud', 'die Endlichkeit', 'La finitud da urgencia a la vida.', 'Die Endlichkeit verleiht dem Leben Dringlichkeit.', 'noun'],
      ['el prejuicio', 'das Vorurteil', 'Ningún lector llega sin prejuicios.', 'Kein Leser kommt ohne Vorurteile.', 'noun'],
      ['la duda metódica', 'der methodische Zweifel', 'Parte de la duda metódica cartesiana.', 'Er geht vom cartesianischen Zweifel aus.', 'noun'],
      ['reflexionar', 'nachdenken', 'Conviene reflexionar antes de responder.', 'Man sollte nachdenken, bevor man antwortet.', 'verb'],
      ['cuestionar', 'hinterfragen', 'Cuestiona incluso sus propias premisas.', 'Er hinterfragt sogar die eigenen Prämissen.', 'verb'],
      ['concebir', 'begreifen, sich vorstellen', 'No concibo una ética sin empatía.', 'Ich kann mir keine Ethik ohne Empathie vorstellen.', 'verb'],
      ['presuponer', 'voraussetzen', 'Esa tesis presupone libre albedrío.', 'Diese These setzt Willensfreiheit voraus.', 'verb'],
      ['deducir', 'ableiten', 'De esas premisas se deduce lo contrario.', 'Aus diesen Prämissen folgt das Gegenteil.', 'verb'],
      ['distinguir', 'unterscheiden', 'Hay que distinguir causa de pretexto.', 'Man muss Ursache und Vorwand unterscheiden.', 'verb'],
      ['relativizar', 'relativieren', 'No pretendo relativizar el daño.', 'Ich will den Schaden nicht relativieren.', 'verb'],
      ['asumir', 'annehmen, übernehmen', 'Asumamos por un momento lo contrario.', 'Nehmen wir für einen Moment das Gegenteil an.', 'verb'],
      ['ahondar en', 'vertiefen', 'El ensayo ahonda en esa contradicción.', 'Der Essay vertieft diesen Widerspruch.', 'phrase'],
      ['intrínseco', 'innewohnend', 'Es un límite intrínseco al método.', 'Das ist eine dem Verfahren innewohnende Grenze.', 'adjective'],
      ['inherente', 'inhärent', 'El riesgo es inherente a la libertad.', 'Das Risiko ist der Freiheit inhärent.', 'adjective'],
      ['arbitrario', 'willkürlich', 'La distinción resulta arbitraria.', 'Die Unterscheidung wirkt willkürlich.', 'adjective'],
      ['universal', 'allgemeingültig', 'Aspira a una norma universal.', 'Er strebt eine allgemeingültige Norm an.', 'adjective'],
      ['por consiguiente', 'folglich', 'Por consiguiente, la premisa debe revisarse.', 'Folglich muss die Prämisse überprüft werden.', 'phrase'],
      ['en última instancia', 'letztlich', 'En última instancia, todo depende del criterio.', 'Letztlich hängt alles vom Kriterium ab.', 'phrase'],
    ],
  },
  {
    title: 'Wirtschaft & Finanzen',
    level: CefrLevel.C1,
    description: 'Vokabular für Märkte, Unternehmen und finanzielle Zusammenhänge',
    iconEmoji: '📈',
    items: [
      ['la coyuntura', 'die Konjunkturlage', 'La coyuntura actual desaconseja invertir.', 'Die aktuelle Lage rät von Investitionen ab.', 'noun'],
      ['el ciclo económico', 'der Konjunkturzyklus', 'El ciclo económico se ha acortado.', 'Der Konjunkturzyklus hat sich verkürzt.', 'noun'],
      ['el producto interior bruto', 'das Bruttoinlandsprodukt', 'El producto interior bruto creció moderadamente.', 'Das Bruttoinlandsprodukt wuchs moderat.', 'noun'],
      ['la balanza comercial', 'die Handelsbilanz', 'La balanza comercial sigue en déficit.', 'Die Handelsbilanz bleibt im Defizit.', 'noun'],
      ['el déficit', 'das Defizit', 'El déficit público supera lo pactado.', 'Das Staatsdefizit übersteigt das Vereinbarte.', 'noun'],
      ['el superávit', 'der Überschuss', 'Cerraron el ejercicio con superávit.', 'Sie schlossen das Geschäftsjahr mit Überschuss ab.', 'noun'],
      ['la liquidez', 'die Liquidität', 'La empresa tiene problemas de liquidez.', 'Das Unternehmen hat Liquiditätsprobleme.', 'noun'],
      ['la solvencia', 'die Bonität', 'Los bancos evalúan su solvencia.', 'Die Banken prüfen ihre Bonität.', 'noun'],
      ['el apalancamiento', 'die Verschuldungshebelwirkung', 'Un apalancamiento excesivo es peligroso.', 'Eine übermäßige Hebelwirkung ist gefährlich.', 'noun'],
      ['la rentabilidad', 'die Rendite', 'La rentabilidad neta ronda el cuatro por ciento.', 'Die Nettorendite liegt bei etwa vier Prozent.', 'noun'],
      ['la cotización', 'der Börsenkurs', 'La cotización se desplomó tras el anuncio.', 'Der Kurs brach nach der Ankündigung ein.', 'noun'],
      ['la acción', 'die Aktie', 'Las acciones repuntaron a media sesión.', 'Die Aktien erholten sich zur Handelsmitte.', 'noun'],
      ['el bono', 'die Anleihe', 'El bono a diez años ofrece poco.', 'Die zehnjährige Anleihe bietet wenig.', 'noun'],
      ['la prima de riesgo', 'der Risikoaufschlag', 'La prima de riesgo se disparó en 2012.', 'Der Risikoaufschlag schoss 2012 in die Höhe.', 'noun'],
      ['el fondo de inversión', 'der Investmentfonds', 'El fondo de inversión cobra comisiones altas.', 'Der Investmentfonds erhebt hohe Gebühren.', 'noun'],
      ['la cartera', 'das Portfolio', 'Diversificó la cartera por sectores.', 'Er streute das Portfolio über Branchen.', 'noun'],
      ['la diversificación', 'die Diversifizierung', 'La diversificación reduce el riesgo específico.', 'Diversifizierung senkt das spezifische Risiko.', 'noun'],
      ['la fusión', 'die Fusion', 'La fusión requiere aprobación regulatoria.', 'Die Fusion bedarf behördlicher Genehmigung.', 'noun'],
      ['la adquisición', 'die Übernahme', 'La adquisición se cerró en marzo.', 'Die Übernahme wurde im März abgeschlossen.', 'noun'],
      ['la filial', 'die Tochtergesellschaft', 'La filial alemana aporta un tercio.', 'Die deutsche Tochter steuert ein Drittel bei.', 'noun'],
      ['el accionariado', 'die Aktionärsstruktur', 'El accionariado está muy fragmentado.', 'Die Aktionärsstruktur ist stark zersplittert.', 'noun'],
      ['la junta de accionistas', 'die Hauptversammlung', 'La junta de accionistas se celebra en junio.', 'Die Hauptversammlung findet im Juni statt.', 'noun'],
      ['el consejo de administración', 'der Verwaltungsrat', 'El consejo de administración cesó al director.', 'Der Verwaltungsrat setzte den Direktor ab.', 'noun'],
      ['la auditoría', 'die Wirtschaftsprüfung', 'La auditoría detectó irregularidades.', 'Die Prüfung stellte Unregelmäßigkeiten fest.', 'noun'],
      ['el balance', 'die Bilanz', 'El balance refleja una mejora clara.', 'Die Bilanz zeigt eine deutliche Verbesserung.', 'noun'],
      ['la cuenta de resultados', 'die Gewinn- und Verlustrechnung', 'La cuenta de resultados se publica el jueves.', 'Die Gewinn- und Verlustrechnung erscheint am Donnerstag.', 'noun'],
      ['el flujo de caja', 'der Cashflow', 'El flujo de caja libre es negativo.', 'Der freie Cashflow ist negativ.', 'noun'],
      ['la amortización', 'die Abschreibung, Tilgung', 'La amortización del préstamo termina en 2030.', 'Die Tilgung des Kredits endet 2030.', 'noun'],
      ['la provisión', 'die Rückstellung', 'Dotaron una provisión por litigios.', 'Sie bildeten eine Rückstellung für Rechtsstreitigkeiten.', 'noun'],
      ['la evasión fiscal', 'die Steuerhinterziehung', 'Investigan un caso de evasión fiscal.', 'Sie ermitteln in einem Steuerhinterziehungsfall.', 'noun'],
      ['la política monetaria', 'die Geldpolitik', 'La política monetaria se endureció.', 'Die Geldpolitik wurde gestrafft.', 'noun'],
      ['el tipo de interés', 'der Zinssatz', 'El banco central subió el tipo de interés.', 'Die Zentralbank erhöhte den Zinssatz.', 'noun'],
      ['la devaluación', 'die Abwertung', 'La devaluación encareció las importaciones.', 'Die Abwertung verteuerte die Importe.', 'noun'],
      ['el tipo de cambio', 'der Wechselkurs', 'El tipo de cambio favorece a los exportadores.', 'Der Wechselkurs begünstigt die Exporteure.', 'noun'],
      ['la especulación', 'die Spekulation', 'La especulación inmobiliaria disparó los alquileres.', 'Immobilienspekulation trieb die Mieten hoch.', 'noun'],
      ['cotizar', 'notiert sein, kotieren', 'La empresa cotiza desde 2018.', 'Das Unternehmen ist seit 2018 börsennotiert.', 'verb'],
      ['amortizar', 'tilgen, abschreiben', 'Amortizaron la deuda anticipadamente.', 'Sie tilgten die Schuld vorzeitig.', 'verb'],
      ['repuntar', 'sich erholen', 'El consumo repuntó en el último trimestre.', 'Der Konsum erholte sich im letzten Quartal.', 'verb'],
      ['desplomarse', 'einbrechen', 'Las ventas se desplomaron en verano.', 'Die Verkäufe brachen im Sommer ein.', 'verb'],
      ['estancarse', 'stagnieren', 'La productividad se ha estancado.', 'Die Produktivität stagniert.', 'verb'],
      ['externalizar', 'auslagern', 'Externalizaron la logística.', 'Sie lagerten die Logistik aus.', 'verb'],
      ['sanear', 'sanieren', 'Sanearon las cuentas en dos años.', 'Sie sanierten die Bilanz in zwei Jahren.', 'verb'],
      ['blanquear capitales', 'Geld waschen', 'Lo acusan de blanquear capitales.', 'Man wirft ihm Geldwäsche vor.', 'phrase'],
      ['solvente', 'solvent', 'Es un cliente solvente y puntual.', 'Das ist ein solventer und pünktlicher Kunde.', 'adjective'],
      ['deficitario', 'defizitär', 'La línea es deficitaria desde 2019.', 'Die Sparte ist seit 2019 defizitär.', 'adjective'],
      ['boyante', 'florierend', 'El sector turístico está boyante.', 'Der Tourismussektor floriert.', 'adjective'],
      ['a la alza', 'im Aufwärtstrend', 'Los salarios reales van a la alza.', 'Die Reallöhne sind im Aufwärtstrend.', 'phrase'],
      ['a medio plazo', 'mittelfristig', 'A medio plazo el ajuste será inevitable.', 'Mittelfristig wird die Anpassung unvermeidlich.', 'phrase'],
      ['en detrimento de', 'zum Nachteil von', 'Creció en detrimento del pequeño comercio.', 'Es wuchs zum Nachteil des Kleinhandels.', 'phrase'],
      ['habida cuenta de', 'in Anbetracht von', 'Habida cuenta de la inflación, el alza es mínima.', 'In Anbetracht der Inflation ist der Anstieg minimal.', 'phrase'],
    ],
  },
  {
    title: 'Nuancierte Ausdrucksweise & Redewendungen',
    level: CefrLevel.C1,
    description: 'Feste Wendungen und differenzierte Formulierungen für gehobenes Spanisch',
    iconEmoji: '🗣️',
    items: [
      ['no obstante', 'nichtsdestotrotz', 'No obstante, conviene ser prudente.', 'Nichtsdestotrotz ist Vorsicht geboten.', 'phrase'],
      ['sin embargo', 'jedoch', 'Sin embargo, los datos dicen otra cosa.', 'Die Daten sagen jedoch etwas anderes.', 'phrase'],
      ['por el contrario', 'im Gegenteil', 'Por el contrario, la medida ayudó.', 'Im Gegenteil, die Maßnahme half.', 'phrase'],
      ['ahora bien', 'nun aber', 'Ahora bien, eso exige una condición.', 'Nun aber setzt das eine Bedingung voraus.', 'phrase'],
      ['dicho esto', 'abgesehen davon', 'Dicho esto, el plan tiene mérito.', 'Abgesehen davon hat der Plan Verdienste.', 'phrase'],
      ['en cambio', 'hingegen', 'Ella, en cambio, prefirió callar.', 'Sie hingegen zog es vor zu schweigen.', 'phrase'],
      ['por lo que respecta a', 'was … betrifft', 'Por lo que respecta al coste, es asumible.', 'Was die Kosten betrifft, sind sie tragbar.', 'phrase'],
      ['a raíz de', 'infolge von', 'A raíz del escándalo dimitió.', 'Infolge des Skandals trat er zurück.', 'phrase'],
      ['a fin de cuentas', 'letzten Endes', 'A fin de cuentas, decidió él solo.', 'Letzten Endes entschied er allein.', 'phrase'],
      ['de hecho', 'tatsächlich', 'De hecho, ya lo habían advertido.', 'Tatsächlich hatten sie schon gewarnt.', 'phrase'],
      ['en rigor', 'genau genommen', 'En rigor, no se trata de un error.', 'Genau genommen handelt es sich nicht um einen Fehler.', 'phrase'],
      ['a grandes rasgos', 'in groben Zügen', 'A grandes rasgos, el plan funciona.', 'In groben Zügen funktioniert der Plan.', 'phrase'],
      ['hasta cierto punto', 'bis zu einem gewissen Grad', 'Tienes razón hasta cierto punto.', 'Bis zu einem gewissen Grad hast du recht.', 'phrase'],
      ['ni mucho menos', 'bei Weitem nicht', 'No está resuelto, ni mucho menos.', 'Es ist bei Weitem nicht gelöst.', 'phrase'],
      ['con creces', 'bei Weitem, mehr als', 'Superó las expectativas con creces.', 'Er übertraf die Erwartungen bei Weitem.', 'phrase'],
      ['a ciencia cierta', 'mit Sicherheit', 'Nadie lo sabe a ciencia cierta.', 'Niemand weiß es mit Sicherheit.', 'phrase'],
      ['sin ir más lejos', 'um ein naheliegendes Beispiel zu nennen', 'Sin ir más lejos, ayer ocurrió lo mismo.', 'Erst gestern geschah dasselbe.', 'phrase'],
      ['dar por sentado', 'als selbstverständlich ansehen', 'No des por sentado su apoyo.', 'Setze seine Unterstützung nicht voraus.', 'phrase'],
      ['dar la razón a alguien', 'jemandem recht geben', 'El tiempo le dio la razón.', 'Die Zeit gab ihm recht.', 'phrase'],
      ['tener en cuenta', 'berücksichtigen', 'Hay que tener en cuenta el contexto.', 'Man muss den Kontext berücksichtigen.', 'phrase'],
      ['poner en tela de juicio', 'infrage stellen', 'Puso en tela de juicio toda la versión.', 'Er stellte die ganze Darstellung infrage.', 'phrase'],
      ['salirse con la suya', 'seinen Willen durchsetzen', 'Al final se salió con la suya.', 'Am Ende setzte er seinen Willen durch.', 'phrase'],
      ['llevar la contraria', 'widersprechen', 'Le encanta llevar la contraria.', 'Er widerspricht für sein Leben gern.', 'phrase'],
      ['echar una mano', 'zur Hand gehen', 'Échame una mano con esto.', 'Geh mir hiermit zur Hand.', 'phrase'],
      ['meter la pata', 'ins Fettnäpfchen treten', 'Metí la pata en la reunión.', 'Ich bin in der Sitzung ins Fettnäpfchen getreten.', 'phrase'],
      ['dar en el clavo', 'den Nagel auf den Kopf treffen', 'Con ese comentario diste en el clavo.', 'Mit dem Kommentar hast du ins Schwarze getroffen.', 'phrase'],
      ['costar un ojo de la cara', 'ein Vermögen kosten', 'La reforma costó un ojo de la cara.', 'Die Renovierung kostete ein Vermögen.', 'phrase'],
      ['estar al tanto', 'auf dem Laufenden sein', 'Mantenme al tanto del asunto.', 'Halte mich in der Sache auf dem Laufenden.', 'phrase'],
      ['a duras penas', 'mit Mühe und Not', 'Llegamos a duras penas a tiempo.', 'Wir kamen mit Mühe und Not rechtzeitig.', 'phrase'],
      ['de buenas a primeras', 'aus heiterem Himmel', 'De buenas a primeras cambió de opinión.', 'Aus heiterem Himmel änderte sie ihre Meinung.', 'phrase'],
      ['por si acaso', 'für alle Fälle', 'Llévate el cargador por si acaso.', 'Nimm das Ladegerät für alle Fälle mit.', 'phrase'],
      ['a más tardar', 'spätestens', 'Entrégalo el viernes a más tardar.', 'Gib es spätestens am Freitag ab.', 'phrase'],
      ['a la larga', 'auf Dauer', 'A la larga sale más barato.', 'Auf Dauer kommt es billiger.', 'phrase'],
      ['en su justa medida', 'im rechten Maß', 'Hay que criticar en su justa medida.', 'Man sollte im rechten Maß kritisieren.', 'phrase'],
      ['salvo error u omisión', 'Irrtum vorbehalten', 'Salvo error u omisión, la cifra es correcta.', 'Irrtum vorbehalten ist die Zahl korrekt.', 'phrase'],
      ['puntualizar', 'präzisieren', 'Permítame puntualizar un detalle.', 'Erlauben Sie mir, ein Detail zu präzisieren.', 'verb'],
      ['recalcar', 'betonen', 'Recalcó la urgencia del asunto.', 'Sie betonte die Dringlichkeit der Sache.', 'verb'],
      ['esbozar', 'skizzieren', 'Esbozó las líneas generales del plan.', 'Er skizzierte die Grundzüge des Plans.', 'verb'],
      ['soslayar', 'umgehen', 'Soslayó la pregunta con elegancia.', 'Er umging die Frage elegant.', 'verb'],
      ['zanjar', 'beilegen, beenden', 'Zanjaron la discusión en diez minutos.', 'Sie beendeten die Diskussion in zehn Minuten.', 'verb'],
      ['sopesar', 'abwägen', 'Sopesamos las dos alternativas.', 'Wir wägen die beiden Alternativen ab.', 'verb'],
      ['ceñirse a', 'sich halten an', 'Cíñete al guion, por favor.', 'Halte dich bitte an das Skript.', 'phrase'],
      ['constatar', 'feststellen', 'Constatamos una mejora sostenida.', 'Wir stellen eine anhaltende Verbesserung fest.', 'verb'],
      ['aducir', 'anführen', 'Adujo razones personales.', 'Er führte persönliche Gründe an.', 'verb'],
      ['tajante', 'kategorisch', 'Su respuesta fue tajante.', 'Ihre Antwort war kategorisch.', 'adjective'],
      ['escueto', 'knapp', 'Envió un correo escueto.', 'Sie schickte eine knappe Mail.', 'adjective'],
      ['sutil', 'subtil', 'Es una diferencia sutil pero real.', 'Das ist ein subtiler, aber realer Unterschied.', 'adjective'],
      ['rotundo', 'entschieden, glatt', 'Fue un fracaso rotundo.', 'Es war ein glatter Misserfolg.', 'adjective'],
      ['acertado', 'treffend', 'Me parece una decisión acertada.', 'Ich halte das für eine treffende Entscheidung.', 'adjective'],
      ['desafortunado', 'unglücklich', 'Fue un comentario desafortunado.', 'Das war eine unglückliche Bemerkung.', 'adjective'],
    ],
  },
];
