import { CefrLevel } from '@prisma/client';

/**
 * 250 spanische Vokabeln für CEFR B2 – fünf Themenpakete zu je 50 Wörtern.
 *
 * Format je Eintrag: [Begriff, Übersetzung, Beispielsatz, Beispielübersetzung, Wortart].
 * Übersetzt wird ins Deutsche, weil die Oberfläche deutsch ist. Substantive
 * stehen mit Artikel, Verben im Infinitiv. Wörter aus A1–B1 werden nicht wiederholt.
 */
export const SPANISH_VOCAB_B2 = [
  {
    title: 'Gesellschaft & Politik',
    level: CefrLevel.B2,
    description: 'Wortschatz rund um Politik, Demokratie und gesellschaftliche Themen',
    iconEmoji: '🏛️',
    items: [
      ['la sociedad', 'die Gesellschaft', 'La sociedad ha cambiado mucho en una generación.', 'Die Gesellschaft hat sich in einer Generation stark verändert.', 'noun'],
      ['el ciudadano', 'der Bürger', 'Los ciudadanos exigen más transparencia.', 'Die Bürger fordern mehr Transparenz.', 'noun'],
      ['la democracia', 'die Demokratie', 'La democracia requiere participación.', 'Demokratie erfordert Beteiligung.', 'noun'],
      ['el gobierno', 'die Regierung', 'El gobierno aprobó la reforma ayer.', 'Die Regierung verabschiedete gestern die Reform.', 'noun'],
      ['el parlamento', 'das Parlament', 'El parlamento debate la propuesta.', 'Das Parlament debattiert den Vorschlag.', 'noun'],
      ['el partido político', 'die Partei', 'Ningún partido político tiene mayoría.', 'Keine Partei hat die Mehrheit.', 'noun'],
      ['la oposición', 'die Opposition', 'La oposición critica el presupuesto.', 'Die Opposition kritisiert den Haushalt.', 'noun'],
      ['las elecciones', 'die Wahlen', 'Las elecciones se celebran en mayo.', 'Die Wahlen finden im Mai statt.', 'noun'],
      ['el voto', 'die Stimme', 'Cada voto cuenta igual.', 'Jede Stimme zählt gleich viel.', 'noun'],
      ['la campaña electoral', 'der Wahlkampf', 'La campaña electoral ha sido agresiva.', 'Der Wahlkampf war aggressiv.', 'noun'],
      ['la ley', 'das Gesetz', 'La ley entra en vigor en enero.', 'Das Gesetz tritt im Januar in Kraft.', 'noun'],
      ['la constitución', 'die Verfassung', 'La constitución garantiza esos derechos.', 'Die Verfassung garantiert diese Rechte.', 'noun'],
      ['el derecho', 'das Recht', 'Es un derecho fundamental.', 'Das ist ein Grundrecht.', 'noun'],
      ['el deber', 'die Pflicht', 'Votar es un derecho y casi un deber.', 'Wählen ist ein Recht und fast eine Pflicht.', 'noun'],
      ['la libertad', 'die Freiheit', 'La libertad de expresión tiene límites legales.', 'Die Meinungsfreiheit hat gesetzliche Grenzen.', 'noun'],
      ['la igualdad', 'die Gleichheit', 'Luchan por la igualdad salarial.', 'Sie kämpfen für Lohngleichheit.', 'noun'],
      ['la justicia', 'die Gerechtigkeit, Justiz', 'La justicia tarda demasiado.', 'Die Justiz braucht zu lange.', 'noun'],
      ['la desigualdad', 'die Ungleichheit', 'La desigualdad ha aumentado.', 'Die Ungleichheit hat zugenommen.', 'noun'],
      ['la pobreza', 'die Armut', 'La pobreza infantil sigue siendo alta.', 'Die Kinderarmut bleibt hoch.', 'noun'],
      ['la manifestación', 'die Demonstration', 'La manifestación reunió a miles de personas.', 'Die Demonstration versammelte Tausende.', 'noun'],
      ['la huelga', 'der Streik', 'La huelga paralizó el transporte.', 'Der Streik legte den Verkehr lahm.', 'noun'],
      ['la protesta', 'der Protest', 'Las protestas duraron una semana.', 'Die Proteste dauerten eine Woche.', 'noun'],
      ['la reforma estructural', 'die Strukturreform', 'La reforma estructural divide al país.', 'Die Strukturreform spaltet das Land.', 'noun'],
      ['el presupuesto', 'der Haushalt, das Budget', 'El presupuesto se aprueba en diciembre.', 'Der Haushalt wird im Dezember verabschiedet.', 'noun'],
      ['la corrupción', 'die Korruption', 'El escándalo de corrupción salpica al alcalde.', 'Der Korruptionsskandal trifft den Bürgermeister.', 'noun'],
      ['la transparencia', 'die Transparenz', 'Exigen más transparencia en las cuentas.', 'Sie fordern mehr Transparenz in den Finanzen.', 'noun'],
      ['la administración', 'die Verwaltung', 'La administración es demasiado lenta.', 'Die Verwaltung ist zu langsam.', 'noun'],
      ['el funcionario', 'der Beamte', 'Los funcionarios atienden hasta las dos.', 'Die Beamten haben bis zwei Uhr geöffnet.', 'noun'],
      ['la inmigración', 'die Einwanderung', 'La inmigración es un tema polarizador.', 'Einwanderung ist ein polarisierendes Thema.', 'noun'],
      ['el refugiado', 'der Geflüchtete', 'El país acogió a miles de refugiados.', 'Das Land nahm Tausende Geflüchtete auf.', 'noun'],
      ['la integración', 'die Integration', 'La integración exige esfuerzo mutuo.', 'Integration verlangt beidseitige Anstrengung.', 'noun'],
      ['la discriminación', 'die Diskriminierung', 'La ley prohíbe cualquier discriminación.', 'Das Gesetz verbietet jede Diskriminierung.', 'noun'],
      ['la solidaridad', 'die Solidarität', 'La crisis despertó una gran solidaridad.', 'Die Krise weckte große Solidarität.', 'noun'],
      ['el bienestar', 'das Wohlergehen', 'El estado del bienestar está bajo presión.', 'Der Sozialstaat steht unter Druck.', 'noun'],
      ['la opinión pública', 'die öffentliche Meinung', 'La opinión pública se ha vuelto crítica.', 'Die öffentliche Meinung ist kritisch geworden.', 'noun'],
      ['gobernar', 'regieren', 'Gobiernan en coalición desde 2023.', 'Sie regieren seit 2023 in einer Koalition.', 'verb'],
      ['votar', 'wählen', 'Votaré aunque no me convenza nadie.', 'Ich werde wählen, auch wenn mich niemand überzeugt.', 'verb'],
      ['aprobar una ley', 'ein Gesetz verabschieden', 'Aprobaron la ley sin debate.', 'Sie verabschiedeten das Gesetz ohne Debatte.', 'phrase'],
      ['exigir responsabilidades', 'zur Rechenschaft ziehen', 'La prensa exige responsabilidades al ministro.', 'Die Presse zieht den Minister zur Rechenschaft.', 'phrase'],
      ['reivindicar', 'einfordern', 'Reivindican mejores condiciones laborales.', 'Sie fordern bessere Arbeitsbedingungen.', 'verb'],
      ['manifestarse', 'demonstrieren', 'Se manifestaron frente al ayuntamiento.', 'Sie demonstrierten vor dem Rathaus.', 'verb'],
      ['denunciar', 'anzeigen, anprangern', 'Denunciaron el caso ante la fiscalía.', 'Sie zeigten den Fall bei der Staatsanwaltschaft an.', 'verb'],
      ['garantizar', 'gewährleisten', 'La ley garantiza el acceso a la educación.', 'Das Gesetz gewährleistet den Zugang zu Bildung.', 'verb'],
      ['fomentar', 'fördern', 'El plan fomenta el empleo juvenil.', 'Der Plan fördert die Jugendbeschäftigung.', 'verb'],
      ['polarizar', 'polarisieren', 'El discurso polariza a la población.', 'Die Rede polarisiert die Bevölkerung.', 'verb'],
      ['vigente', 'geltend, in Kraft', 'La norma sigue vigente.', 'Die Vorschrift ist weiterhin in Kraft.', 'adjective'],
      ['imprescindible', 'unverzichtbar', 'El consenso es imprescindible.', 'Der Konsens ist unverzichtbar.', 'adjective'],
      ['controvertido', 'kontrovers', 'Es una medida muy controvertida.', 'Das ist eine sehr kontroverse Maßnahme.', 'adjective'],
      ['mayoritario', 'mehrheitlich', 'El apoyo fue mayoritario.', 'Die Unterstützung war mehrheitlich.', 'adjective'],
      ['a largo plazo', 'langfristig', 'A largo plazo la reforma saldrá a cuenta.', 'Langfristig wird sich die Reform lohnen.', 'phrase'],
    ],
  },
  {
    title: 'Umwelt & Nachhaltigkeit',
    level: CefrLevel.B2,
    description: 'Wortschatz zu Klimawandel, Umweltschutz und Nachhaltigkeit',
    iconEmoji: '🌍',
    items: [
      ['el medio ambiente', 'die Umwelt', 'Proteger el medio ambiente cuesta dinero.', 'Umweltschutz kostet Geld.', 'noun'],
      ['el cambio climático', 'der Klimawandel', 'El cambio climático ya es visible.', 'Der Klimawandel ist bereits sichtbar.', 'noun'],
      ['el calentamiento global', 'die Erderwärmung', 'El calentamiento global acelera el deshielo.', 'Die Erderwärmung beschleunigt die Eisschmelze.', 'noun'],
      ['la sostenibilidad', 'die Nachhaltigkeit', 'La sostenibilidad no es solo marketing.', 'Nachhaltigkeit ist nicht nur Marketing.', 'noun'],
      ['la contaminación', 'die Verschmutzung', 'La contaminación del aire supera los límites.', 'Die Luftverschmutzung überschreitet die Grenzwerte.', 'noun'],
      ['la emisión', 'die Emission', 'Las emisiones han bajado un diez por ciento.', 'Die Emissionen sind um zehn Prozent gesunken.', 'noun'],
      ['el gas de efecto invernadero', 'das Treibhausgas', 'El metano es un gas de efecto invernadero potente.', 'Methan ist ein starkes Treibhausgas.', 'noun'],
      ['la huella de carbono', 'der CO₂-Fußabdruck', 'Calcula tu huella de carbono anual.', 'Berechne deinen jährlichen CO₂-Fußabdruck.', 'noun'],
      ['el residuo', 'der Abfall', 'Los residuos plásticos tardan siglos en degradarse.', 'Plastikabfälle brauchen Jahrhunderte zum Abbau.', 'noun'],
      ['el reciclaje', 'das Recycling', 'El reciclaje aquí funciona bien.', 'Das Recycling funktioniert hier gut.', 'noun'],
      ['el envase', 'die Verpackung', 'El envase es de cartón reciclado.', 'Die Verpackung besteht aus Recyclingkarton.', 'noun'],
      ['la energía renovable', 'die erneuerbare Energie', 'Las energías renovables cubren la mitad del consumo.', 'Erneuerbare Energien decken die Hälfte des Verbrauchs.', 'noun'],
      ['la energía solar', 'die Solarenergie', 'La energía solar es cada vez más barata.', 'Solarenergie wird immer billiger.', 'noun'],
      ['la energía eólica', 'die Windenergie', 'La energía eólica domina en el norte.', 'Im Norden dominiert die Windenergie.', 'noun'],
      ['el consumo', 'der Verbrauch', 'Hay que reducir el consumo de agua.', 'Der Wasserverbrauch muss gesenkt werden.', 'noun'],
      ['el recurso natural', 'die natürliche Ressource', 'Los recursos naturales son limitados.', 'Natürliche Ressourcen sind begrenzt.', 'noun'],
      ['la biodiversidad', 'die Artenvielfalt', 'La biodiversidad disminuye cada año.', 'Die Artenvielfalt nimmt jedes Jahr ab.', 'noun'],
      ['la especie', 'die Art', 'Es una especie en peligro de extinción.', 'Das ist eine vom Aussterben bedrohte Art.', 'noun'],
      ['el ecosistema', 'das Ökosystem', 'El ecosistema del río se ha recuperado.', 'Das Ökosystem des Flusses hat sich erholt.', 'noun'],
      ['la deforestación', 'die Abholzung', 'La deforestación avanza sin control.', 'Die Abholzung schreitet unkontrolliert voran.', 'noun'],
      ['el bosque', 'der Wald', 'El incendio arrasó cien hectáreas de bosque.', 'Das Feuer zerstörte hundert Hektar Wald.', 'noun'],
      ['el incendio forestal', 'der Waldbrand', 'Los incendios forestales se repiten cada verano.', 'Waldbrände wiederholen sich jeden Sommer.', 'noun'],
      ['la ola de calor', 'die Hitzewelle', 'La ola de calor duró dos semanas.', 'Die Hitzewelle dauerte zwei Wochen.', 'noun'],
      ['el desastre natural', 'die Naturkatastrophe', 'El desastre natural dejó miles de damnificados.', 'Die Naturkatastrophe hinterließ Tausende Geschädigte.', 'noun'],
      ['el nivel del mar', 'der Meeresspiegel', 'El nivel del mar sube cada década.', 'Der Meeresspiegel steigt jedes Jahrzehnt.', 'noun'],
      ['el glaciar', 'der Gletscher', 'El glaciar ha perdido la mitad de su masa.', 'Der Gletscher hat die Hälfte seiner Masse verloren.', 'noun'],
      ['la agricultura ecológica', 'der Biolandbau', 'La agricultura ecológica gana terreno.', 'Der Biolandbau gewinnt an Boden.', 'noun'],
      ['el transporte público', 'der öffentliche Verkehr', 'El transporte público debería ser más barato.', 'Der öffentliche Verkehr sollte billiger sein.', 'noun'],
      ['el vehículo eléctrico', 'das Elektrofahrzeug', 'Los vehículos eléctricos aún son caros.', 'Elektrofahrzeuge sind noch teuer.', 'noun'],
      ['la normativa', 'die Vorschrift', 'La nueva normativa limita las emisiones.', 'Die neue Vorschrift begrenzt die Emissionen.', 'noun'],
      ['contaminar', 'verschmutzen', 'Esa fábrica contamina el río.', 'Diese Fabrik verschmutzt den Fluss.', 'verb'],
      ['reciclar', 'recyceln', 'Reciclamos el vidrio y el papel.', 'Wir recyceln Glas und Papier.', 'verb'],
      ['reducir', 'verringern', 'Hemos reducido el plástico a la mitad.', 'Wir haben den Plastikverbrauch halbiert.', 'verb'],
      ['reutilizar', 'wiederverwenden', 'Reutilizo los botes de cristal.', 'Ich verwende die Glasbehälter wieder.', 'verb'],
      ['ahorrar energía', 'Energie sparen', 'Ahorramos energía apagando los equipos.', 'Wir sparen Energie, indem wir die Geräte ausschalten.', 'phrase'],
      ['proteger', 'schützen', 'Hay que proteger las zonas costeras.', 'Die Küstengebiete müssen geschützt werden.', 'verb'],
      ['conservar', 'bewahren', 'Conservan el hábitat original.', 'Sie bewahren den ursprünglichen Lebensraum.', 'verb'],
      ['agotar', 'erschöpfen', 'Estamos agotando los acuíferos.', 'Wir erschöpfen die Grundwasservorkommen.', 'verb'],
      ['derretirse', 'schmelzen', 'El hielo se derrite antes cada año.', 'Das Eis schmilzt jedes Jahr früher.', 'verb'],
      ['concienciar', 'sensibilisieren', 'La campaña conciencia a los jóvenes.', 'Die Kampagne sensibilisiert junge Menschen.', 'verb'],
      ['invertir en', 'investieren in', 'Invierten en tecnología limpia.', 'Sie investieren in saubere Technologie.', 'phrase'],
      ['sostenible', 'nachhaltig', 'Es un modelo de turismo sostenible.', 'Das ist ein nachhaltiges Tourismusmodell.', 'adjective'],
      ['renovable', 'erneuerbar', 'Toda la electricidad es de origen renovable.', 'Der gesamte Strom stammt aus erneuerbaren Quellen.', 'adjective'],
      ['perjudicial', 'schädlich', 'El pesticida es perjudicial para las abejas.', 'Das Pestizid ist schädlich für Bienen.', 'adjective'],
      ['escaso', 'knapp', 'El agua es un bien escaso aquí.', 'Wasser ist hier ein knappes Gut.', 'adjective'],
      ['irreversible', 'unumkehrbar', 'Algunos daños ya son irreversibles.', 'Manche Schäden sind bereits unumkehrbar.', 'adjective'],
      ['respetuoso con el medio ambiente', 'umweltfreundlich', 'Usan envases respetuosos con el medio ambiente.', 'Sie verwenden umweltfreundliche Verpackungen.', 'phrase'],
      ['a corto plazo', 'kurzfristig', 'A corto plazo la medida es cara.', 'Kurzfristig ist die Maßnahme teuer.', 'phrase'],
      ['el impacto', 'die Auswirkung', 'El impacto ambiental fue subestimado.', 'Die Umweltauswirkung wurde unterschätzt.', 'noun'],
      ['la alternativa', 'die Alternative', 'Buscamos una alternativa viable.', 'Wir suchen eine machbare Alternative.', 'noun'],
    ],
  },
  {
    title: 'Wissenschaft & Technik',
    level: CefrLevel.B2,
    description: 'Wortschatz zu Forschung, Technik und Digitalisierung',
    iconEmoji: '🔬',
    items: [
      ['la ciencia', 'die Wissenschaft', 'La ciencia avanza por corrección de errores.', 'Wissenschaft schreitet durch Fehlerkorrektur voran.', 'noun'],
      ['el científico', 'der Wissenschaftler', 'Los científicos publicaron sus resultados.', 'Die Wissenschaftler veröffentlichten ihre Ergebnisse.', 'noun'],
      ['el experimento', 'das Experiment', 'El experimento se repitió tres veces.', 'Das Experiment wurde dreimal wiederholt.', 'noun'],
      ['la hipótesis', 'die Hypothese', 'La hipótesis no se confirmó.', 'Die Hypothese wurde nicht bestätigt.', 'noun'],
      ['la teoría', 'die Theorie', 'Es una teoría ampliamente aceptada.', 'Das ist eine weithin akzeptierte Theorie.', 'noun'],
      ['la prueba', 'der Beweis, Test', 'Las pruebas apuntan en otra dirección.', 'Die Belege weisen in eine andere Richtung.', 'noun'],
      ['el dato', 'die Daten, das Datum', 'Los datos son públicos desde ayer.', 'Die Daten sind seit gestern öffentlich.', 'noun'],
      ['la muestra', 'die Stichprobe, Probe', 'La muestra era demasiado pequeña.', 'Die Stichprobe war zu klein.', 'noun'],
      ['el resultado', 'das Ergebnis', 'Los resultados sorprendieron a todos.', 'Die Ergebnisse überraschten alle.', 'noun'],
      ['el laboratorio', 'das Labor', 'Trabaja en un laboratorio de biología.', 'Sie arbeitet in einem Biologielabor.', 'noun'],
      ['el descubrimiento', 'die Entdeckung', 'El descubrimiento cambió el campo.', 'Die Entdeckung veränderte das Fachgebiet.', 'noun'],
      ['el invento', 'die Erfindung', 'Ese invento simplificó la producción.', 'Diese Erfindung vereinfachte die Produktion.', 'noun'],
      ['el avance', 'der Fortschritt', 'Los avances médicos alargan la vida.', 'Medizinische Fortschritte verlängern das Leben.', 'noun'],
      ['la tecnología', 'die Technologie', 'La tecnología cambia más rápido que las leyes.', 'Die Technologie verändert sich schneller als die Gesetze.', 'noun'],
      ['la inteligencia artificial', 'die künstliche Intelligenz', 'La inteligencia artificial ya redacta informes.', 'Künstliche Intelligenz verfasst bereits Berichte.', 'noun'],
      ['el algoritmo', 'der Algorithmus', 'El algoritmo decide qué ves primero.', 'Der Algorithmus entscheidet, was du zuerst siehst.', 'noun'],
      ['el software', 'die Software', 'El software se actualiza automáticamente.', 'Die Software aktualisiert sich automatisch.', 'noun'],
      ['el dispositivo', 'das Gerät', 'El dispositivo mide el pulso.', 'Das Gerät misst den Puls.', 'noun'],
      ['el servidor', 'der Server', 'El servidor se cayó durante una hora.', 'Der Server war eine Stunde lang ausgefallen.', 'noun'],
      ['la red', 'das Netz, Netzwerk', 'La red corporativa está aislada.', 'Das Firmennetz ist abgeschottet.', 'noun'],
      ['la base de datos', 'die Datenbank', 'La base de datos contiene un millón de registros.', 'Die Datenbank enthält eine Million Einträge.', 'noun'],
      ['la copia de seguridad', 'die Sicherungskopie', 'Haz una copia de seguridad antes de actualizar.', 'Mach vor dem Update eine Sicherungskopie.', 'noun'],
      ['la ciberseguridad', 'die Cybersicherheit', 'La ciberseguridad es ahora prioritaria.', 'Cybersicherheit hat jetzt Priorität.', 'noun'],
      ['el virus informático', 'der Computervirus', 'Un virus informático bloqueó los equipos.', 'Ein Computervirus blockierte die Rechner.', 'noun'],
      ['la digitalización', 'die Digitalisierung', 'La digitalización del archivo llevó años.', 'Die Digitalisierung des Archivs dauerte Jahre.', 'noun'],
      ['la automatización', 'die Automatisierung', 'La automatización eliminó tareas repetitivas.', 'Die Automatisierung beseitigte wiederkehrende Aufgaben.', 'noun'],
      ['el robot', 'der Roboter', 'El robot monta las piezas pequeñas.', 'Der Roboter montiert die Kleinteile.', 'noun'],
      ['el sensor', 'der Sensor', 'El sensor detecta cualquier movimiento.', 'Der Sensor erkennt jede Bewegung.', 'noun'],
      ['la energía nuclear', 'die Kernenergie', 'La energía nuclear divide a los expertos.', 'Die Kernenergie spaltet die Fachleute.', 'noun'],
      ['la genética', 'die Genetik', 'La genética explica parte del riesgo.', 'Die Genetik erklärt einen Teil des Risikos.', 'noun'],
      ['la vacuna', 'der Impfstoff', 'La vacuna se desarrolló en un año.', 'Der Impfstoff wurde in einem Jahr entwickelt.', 'noun'],
      ['el tratamiento', 'die Behandlung', 'El tratamiento dura seis semanas.', 'Die Behandlung dauert sechs Wochen.', 'noun'],
      ['el ensayo clínico', 'die klinische Studie', 'El ensayo clínico incluyó mil pacientes.', 'Die klinische Studie umfasste tausend Patienten.', 'noun'],
      ['el riesgo', 'das Risiko', 'El riesgo es estadísticamente bajo.', 'Das Risiko ist statistisch gering.', 'noun'],
      ['la precisión', 'die Genauigkeit', 'El instrumento gana precisión con la calibración.', 'Das Instrument gewinnt durch Kalibrierung an Genauigkeit.', 'noun'],
      ['investigar', 'erforschen', 'Investigan el origen del fallo.', 'Sie erforschen die Ursache des Fehlers.', 'verb'],
      ['demostrar', 'nachweisen', 'El estudio demuestra una correlación clara.', 'Die Studie weist eine klare Korrelation nach.', 'verb'],
      ['analizar', 'analysieren', 'Analizamos los datos con dos métodos.', 'Wir analysieren die Daten mit zwei Methoden.', 'verb'],
      ['medir', 'messen', 'Medimos la temperatura cada minuto.', 'Wir messen die Temperatur jede Minute.', 'verb'],
      ['comprobar', 'überprüfen', 'Comprueba los cálculos antes de publicar.', 'Überprüfe die Berechnungen vor der Veröffentlichung.', 'verb'],
      ['desarrollar', 'entwickeln', 'Desarrollan una batería más ligera.', 'Sie entwickeln eine leichtere Batterie.', 'verb'],
      ['aplicar', 'anwenden', 'Aplicaron el método a otro sector.', 'Sie wandten die Methode auf einen anderen Sektor an.', 'verb'],
      ['programar', 'programmieren', 'Programa en tres lenguajes distintos.', 'Er programmiert in drei verschiedenen Sprachen.', 'verb'],
      ['almacenar', 'speichern', 'Los datos se almacenan cifrados.', 'Die Daten werden verschlüsselt gespeichert.', 'verb'],
      ['sustituir', 'ersetzen', 'La máquina sustituye a tres operarios.', 'Die Maschine ersetzt drei Arbeiter.', 'verb'],
      ['vulnerable', 'anfällig', 'El sistema es vulnerable a ataques externos.', 'Das System ist anfällig für externe Angriffe.', 'adjective'],
      ['innovador', 'innovativ', 'Es un enfoque innovador.', 'Das ist ein innovativer Ansatz.', 'adjective'],
      ['complejo', 'komplex', 'El modelo es demasiado complejo.', 'Das Modell ist zu komplex.', 'adjective'],
      ['preciso', 'präzise', 'Necesitamos una medición precisa.', 'Wir brauchen eine präzise Messung.', 'adjective'],
      ['obsoleto', 'veraltet', 'Ese equipo está obsoleto.', 'Dieses Gerät ist veraltet.', 'adjective'],
    ],
  },
  {
    title: 'Kultur & Kunst',
    level: CefrLevel.B2,
    description: 'Wortschatz zu Kunst, Literatur, Musik und Film',
    iconEmoji: '🎭',
    items: [
      ['la cultura', 'die Kultur', 'La cultura popular también merece estudio.', 'Auch Populärkultur verdient Untersuchung.', 'noun'],
      ['la obra', 'das Werk', 'Su obra más conocida es de 1920.', 'Sein bekanntestes Werk stammt von 1920.', 'noun'],
      ['el artista', 'der Künstler', 'La artista expone en tres ciudades.', 'Die Künstlerin stellt in drei Städten aus.', 'noun'],
      ['la galería', 'die Galerie', 'La galería abre una sala nueva.', 'Die Galerie eröffnet einen neuen Saal.', 'noun'],
      ['el cuadro', 'das Gemälde', 'El cuadro está en préstamo.', 'Das Gemälde ist eine Leihgabe.', 'noun'],
      ['la escultura', 'die Skulptur', 'La escultura pesa dos toneladas.', 'Die Skulptur wiegt zwei Tonnen.', 'noun'],
      ['el retrato', 'das Porträt', 'El retrato capta su carácter.', 'Das Porträt erfasst ihren Charakter.', 'noun'],
      ['el paisaje', 'die Landschaft', 'Pintó paisajes durante toda su vida.', 'Er malte sein Leben lang Landschaften.', 'noun'],
      ['la técnica', 'die Technik', 'Domina la técnica del óleo.', 'Sie beherrscht die Öltechnik.', 'noun'],
      ['el estilo', 'der Stil', 'Su estilo evolucionó con los años.', 'Ihr Stil entwickelte sich über die Jahre.', 'noun'],
      ['la corriente artística', 'die Kunstströmung', 'El cubismo fue una corriente artística revolucionaria.', 'Der Kubismus war eine revolutionäre Kunstströmung.', 'noun'],
      ['el patrimonio', 'das Kulturerbe', 'La ciudad es patrimonio de la humanidad.', 'Die Stadt ist Weltkulturerbe.', 'noun'],
      ['la restauración', 'die Restaurierung', 'La restauración duró cuatro años.', 'Die Restaurierung dauerte vier Jahre.', 'noun'],
      ['la literatura', 'die Literatur', 'La literatura latinoamericana le fascina.', 'Die lateinamerikanische Literatur fasziniert ihn.', 'noun'],
      ['el autor', 'der Autor', 'La autora firma ejemplares el sábado.', 'Die Autorin signiert am Samstag Exemplare.', 'noun'],
      ['el personaje', 'die Figur', 'El personaje principal apenas habla.', 'Die Hauptfigur spricht kaum.', 'noun'],
      ['la trama', 'die Handlung', 'La trama se complica en la segunda parte.', 'Die Handlung wird im zweiten Teil komplizierter.', 'noun'],
      ['el argumento', 'die Handlung, das Argument', 'El argumento de la novela es sencillo.', 'Die Handlung des Romans ist schlicht.', 'noun'],
      ['el capítulo', 'das Kapitel', 'El último capítulo lo explica todo.', 'Das letzte Kapitel erklärt alles.', 'noun'],
      ['la poesía', 'die Dichtung', 'Su poesía es breve y precisa.', 'Ihre Dichtung ist knapp und präzise.', 'noun'],
      ['el poema', 'das Gedicht', 'Recitó un poema de memoria.', 'Er trug ein Gedicht auswendig vor.', 'noun'],
      ['el cuento', 'die Erzählung', 'Publicó un libro de cuentos.', 'Sie veröffentlichte einen Erzählband.', 'noun'],
      ['el ensayo', 'der Essay', 'El ensayo critica la modernidad.', 'Der Essay kritisiert die Moderne.', 'noun'],
      ['la editorial', 'der Verlag', 'La editorial rechazó el manuscrito.', 'Der Verlag lehnte das Manuskript ab.', 'noun'],
      ['la traducción', 'die Übersetzung', 'La traducción pierde parte del ritmo.', 'Die Übersetzung verliert einen Teil des Rhythmus.', 'noun'],
      ['la crítica', 'die Kritik', 'La crítica fue demoledora.', 'Die Kritik war vernichtend.', 'noun'],
      ['el guion', 'das Drehbuch', 'El guion se reescribió tres veces.', 'Das Drehbuch wurde dreimal umgeschrieben.', 'noun'],
      ['el director de cine', 'der Filmregisseur', 'La directora de cine ganó un premio.', 'Die Filmregisseurin gewann einen Preis.', 'noun'],
      ['el actor', 'der Schauspieler', 'El actor improvisó la escena final.', 'Der Schauspieler improvisierte die Schlussszene.', 'noun'],
      ['el estreno', 'die Premiere', 'El estreno fue un éxito rotundo.', 'Die Premiere war ein voller Erfolg.', 'noun'],
      ['la banda sonora', 'der Filmsoundtrack', 'La banda sonora se vendió mejor que la película.', 'Der Soundtrack verkaufte sich besser als der Film.', 'noun'],
      ['el escenario', 'die Bühne', 'Salió al escenario sin nervios.', 'Sie betrat die Bühne ohne Nervosität.', 'noun'],
      ['el público', 'das Publikum', 'El público aplaudió de pie.', 'Das Publikum applaudierte im Stehen.', 'noun'],
      ['la orquesta', 'das Orchester', 'La orquesta ensaya cada mañana.', 'Das Orchester probt jeden Morgen.', 'noun'],
      ['el premio', 'der Preis, die Auszeichnung', 'Recibió el premio nacional de narrativa.', 'Sie erhielt den nationalen Erzählpreis.', 'noun'],
      ['crear', 'schaffen', 'Creó un lenguaje visual propio.', 'Er schuf eine eigene Bildsprache.', 'verb'],
      ['interpretar', 'aufführen, deuten', 'Interpretó la pieza con delicadeza.', 'Sie führte das Stück mit Feingefühl auf.', 'verb'],
      ['representar', 'darstellen, aufführen', 'La obra se representa hasta junio.', 'Das Stück wird bis Juni aufgeführt.', 'verb'],
      ['dirigir una película', 'einen Film führen', 'Dirigió su primera película a los treinta.', 'Sie führte mit dreißig bei ihrem ersten Film Regie.', 'phrase'],
      ['inspirarse en', 'sich inspirieren lassen von', 'Se inspiró en la música tradicional.', 'Er ließ sich von traditioneller Musik inspirieren.', 'phrase'],
      ['reflejar', 'widerspiegeln', 'La novela refleja la posguerra.', 'Der Roman spiegelt die Nachkriegszeit wider.', 'verb'],
      ['destacar', 'hervorstechen', 'Destaca por su uso del color.', 'Er sticht durch seinen Farbeinsatz hervor.', 'verb'],
      ['influir en', 'beeinflussen', 'Su obra influyó en toda una generación.', 'Sein Werk beeinflusste eine ganze Generation.', 'phrase'],
      ['apreciar', 'schätzen', 'Aprecio más el teatro que el cine.', 'Ich schätze Theater mehr als Kino.', 'verb'],
      ['conmover', 'bewegen, rühren', 'La escena final conmueve a cualquiera.', 'Die Schlussszene rührt jeden.', 'verb'],
      ['contemporáneo', 'zeitgenössisch', 'Colecciona arte contemporáneo.', 'Sie sammelt zeitgenössische Kunst.', 'adjective'],
      ['clásico', 'klassisch', 'Es un clásico de la literatura española.', 'Das ist ein Klassiker der spanischen Literatur.', 'adjective'],
      ['original', 'originell', 'La puesta en escena es muy original.', 'Die Inszenierung ist sehr originell.', 'adjective'],
      ['impactante', 'eindrucksvoll', 'Fue una exposición impactante.', 'Es war eine eindrucksvolle Ausstellung.', 'adjective'],
      ['profundo', 'tiefgründig', 'Es un ensayo profundo y difícil.', 'Es ist ein tiefgründiger und schwieriger Essay.', 'adjective'],
    ],
  },
  {
    title: 'Wirtschaft & Konsum',
    level: CefrLevel.B2,
    description: 'Wortschatz zu Wirtschaft, Handel und Konsum',
    iconEmoji: '📈',
    items: [
      ['la economía', 'die Wirtschaft', 'La economía creció un dos por ciento.', 'Die Wirtschaft wuchs um zwei Prozent.', 'noun'],
      ['el mercado laboral', 'der Arbeitsmarkt', 'El mercado laboral se ha tensado.', 'Der Arbeitsmarkt hat sich angespannt.', 'noun'],
      ['la oferta y la demanda', 'Angebot und Nachfrage', 'El precio depende de la oferta y la demanda.', 'Der Preis hängt von Angebot und Nachfrage ab.', 'phrase'],
      ['el crecimiento', 'das Wachstum', 'El crecimiento se ha ralentizado.', 'Das Wachstum hat sich verlangsamt.', 'noun'],
      ['la crisis', 'die Krise', 'La crisis afectó sobre todo a los jóvenes.', 'Die Krise traf vor allem junge Menschen.', 'noun'],
      ['la recesión', 'die Rezession', 'El país entró en recesión técnica.', 'Das Land geriet in eine technische Rezession.', 'noun'],
      ['la inflación', 'die Inflation', 'La inflación erosiona los salarios.', 'Die Inflation entwertet die Löhne.', 'noun'],
      ['el poder adquisitivo', 'die Kaufkraft', 'El poder adquisitivo ha caído.', 'Die Kaufkraft ist gesunken.', 'noun'],
      ['el salario mínimo', 'der Mindestlohn', 'Subieron el salario mínimo en enero.', 'Sie erhöhten den Mindestlohn im Januar.', 'noun'],
      ['el beneficio', 'der Gewinn', 'Los beneficios superaron las previsiones.', 'Die Gewinne übertrafen die Prognosen.', 'noun'],
      ['la pérdida', 'der Verlust', 'La empresa cerró el año con pérdidas.', 'Das Unternehmen schloss das Jahr mit Verlusten ab.', 'noun'],
      ['la inversión', 'die Investition', 'La inversión extranjera se ha duplicado.', 'Die Auslandsinvestitionen haben sich verdoppelt.', 'noun'],
      ['el accionista', 'der Aktionär', 'Los accionistas votaron en contra.', 'Die Aktionäre stimmten dagegen.', 'noun'],
      ['la bolsa de valores', 'die Wertpapierbörse', 'La bolsa de valores cerró en negativo.', 'Die Wertpapierbörse schloss im Minus.', 'noun'],
      ['el préstamo', 'der Kredit', 'Pidieron un préstamo al banco.', 'Sie nahmen einen Kredit bei der Bank auf.', 'noun'],
      ['la deuda', 'die Schulden', 'La deuda pública sigue creciendo.', 'Die Staatsschulden wachsen weiter.', 'noun'],
      ['el interés', 'der Zins', 'Los intereses han subido otra vez.', 'Die Zinsen sind wieder gestiegen.', 'noun'],
      ['el impuesto sobre la renta', 'die Einkommensteuer', 'El impuesto sobre la renta es progresivo.', 'Die Einkommensteuer ist progressiv.', 'noun'],
      ['la factura energética', 'die Energierechnung', 'La factura energética se ha disparado.', 'Die Energierechnung ist explodiert.', 'noun'],
      ['el sector', 'die Branche', 'El sector servicios domina la economía.', 'Der Dienstleistungssektor dominiert die Wirtschaft.', 'noun'],
      ['la industria', 'die Industrie', 'La industria pesada perdió peso.', 'Die Schwerindustrie verlor an Bedeutung.', 'noun'],
      ['la producción', 'die Produktion', 'La producción cayó un quince por ciento.', 'Die Produktion fiel um fünfzehn Prozent.', 'noun'],
      ['la exportación', 'der Export', 'Las exportaciones baten un récord.', 'Die Exporte erreichen einen Rekord.', 'noun'],
      ['la importación', 'der Import', 'Las importaciones de gas bajaron.', 'Die Gasimporte gingen zurück.', 'noun'],
      ['la competencia', 'die Konkurrenz', 'La competencia es feroz en este sector.', 'Die Konkurrenz ist in dieser Branche hart.', 'noun'],
      ['la marca', 'die Marke', 'La marca vale más que la fábrica.', 'Die Marke ist mehr wert als die Fabrik.', 'noun'],
      ['el consumidor', 'der Verbraucher', 'El consumidor está mejor informado.', 'Der Verbraucher ist besser informiert.', 'noun'],
      ['el comercio electrónico', 'der Onlinehandel', 'El comercio electrónico creció durante la pandemia.', 'Der Onlinehandel wuchs während der Pandemie.', 'noun'],
      ['la cadena de suministro', 'die Lieferkette', 'La cadena de suministro se rompió.', 'Die Lieferkette riss.', 'noun'],
      ['el proveedor', 'der Lieferant', 'Cambiamos de proveedor el año pasado.', 'Wir haben letztes Jahr den Lieferanten gewechselt.', 'noun'],
      ['la garantía', 'die Garantie', 'La garantía cubre dos años.', 'Die Garantie deckt zwei Jahre ab.', 'noun'],
      ['la devolución', 'die Rückgabe', 'La devolución es gratuita en treinta días.', 'Die Rückgabe ist innerhalb von dreißig Tagen kostenlos.', 'noun'],
      ['la reclamación', 'die Beschwerde', 'Presenté una reclamación por escrito.', 'Ich habe eine schriftliche Beschwerde eingereicht.', 'noun'],
      ['el presupuesto familiar', 'das Haushaltsbudget', 'El presupuesto familiar está muy ajustado.', 'Das Haushaltsbudget ist sehr knapp.', 'noun'],
      ['el consumo responsable', 'bewusster Konsum', 'El consumo responsable requiere información.', 'Bewusster Konsum erfordert Information.', 'noun'],
      ['invertir', 'investieren', 'Invierte en fondos indexados.', 'Er investiert in Indexfonds.', 'verb'],
      ['financiar', 'finanzieren', 'El proyecto se financia con fondos europeos.', 'Das Projekt wird mit EU-Mitteln finanziert.', 'verb'],
      ['endeudarse', 'sich verschulden', 'Se endeudaron para comprar la casa.', 'Sie verschuldeten sich für den Hauskauf.', 'verb'],
      ['facturar', 'Umsatz machen, abrechnen', 'La empresa factura diez millones al año.', 'Das Unternehmen macht zehn Millionen Umsatz im Jahr.', 'verb'],
      ['abaratar', 'verbilligen', 'La competencia abarató los precios.', 'Die Konkurrenz senkte die Preise.', 'verb'],
      ['encarecer', 'verteuern', 'El transporte encarece el producto final.', 'Der Transport verteuert das Endprodukt.', 'verb'],
      ['ahorrar costes', 'Kosten sparen', 'Automatizan para ahorrar costes.', 'Sie automatisieren, um Kosten zu sparen.', 'phrase'],
      ['quebrar', 'bankrottgehen', 'La cadena quebró en 2021.', 'Die Kette ging 2021 bankrott.', 'verb'],
      ['rentable', 'rentabel', 'El negocio aún no es rentable.', 'Das Geschäft ist noch nicht rentabel.', 'adjective'],
      ['asequible', 'erschwinglich', 'Buscamos una vivienda asequible.', 'Wir suchen eine erschwingliche Wohnung.', 'adjective'],
      ['estable', 'stabil', 'El mercado se mantiene estable.', 'Der Markt bleibt stabil.', 'adjective'],
      ['volátil', 'schwankend', 'El precio del gas es muy volátil.', 'Der Gaspreis ist sehr schwankend.', 'adjective'],
      ['creciente', 'wachsend', 'Existe una demanda creciente de reparaciones.', 'Es gibt eine wachsende Nachfrage nach Reparaturen.', 'adjective'],
      ['a la baja', 'rückläufig', 'Los precios van a la baja.', 'Die Preise sind rückläufig.', 'phrase'],
      ['en términos generales', 'im Großen und Ganzen', 'En términos generales, el año fue bueno.', 'Im Großen und Ganzen war das Jahr gut.', 'phrase'],
    ],
  },
];
