/*
  Erzeugt von `npm run videos:refresh` – nicht von Hand ändern.

  Die Auswahl (welche Playlist für welches Niveau und Thema steht) liegt in
  scripts/refresh-video-catalog.ts; hier stehen nur die daraus gezogenen
  Videos. Jede ID war zum Zeitpunkt der Erzeugung öffentlich abrufbar.
  Gelöschte Videos fängt der Seed nicht ab – dafür das Skript erneut laufen
  lassen.

  Zuletzt erzeugt: 2026-09-19
*/
import { CefrLevel, VideoTopic } from '@prisma/client';

export interface VideoSeed {
  youtubeId: string;
  title: string;
  channelName: string;
  channelUrl: string;
  durationSec: number;
  level: CefrLevel;
  topic: VideoTopic;
  slowSpeech: boolean;
  tags: string[];
}

/** Sprachcode (ISO-639-1) → kuratierte Videos für diese Lernsprache. */
export const VIDEO_CATALOG: Record<string, VideoSeed[]> = {
  de: [
    {
      youtubeId: 'huwi-cjPPXU',
      title: 'Introduce Yourself in Slow German (for Absolute Beginners)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 907,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'aRlakaPVrEw',
      title: 'Learn Basic German Greetings & Farewells in Slow German',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1046,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'eKLtI48rvtw',
      title: 'Top 50 Everyday Objects in Slow German',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 997,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'LQiHX6OY_BI',
      title: 'Our Morning Routine in Slow German',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 494,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'hAkxKMlYUI4',
      title: 'German Alphabet & Pronunciation - Full Guide',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1261,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'Ys_GtlFCq_c',
      title: 'Learn German at the Post Office',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 737,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'PndEIjybgb0',
      title: '17 German Reflexive Verbs You Need to Know (Beginner Friendly)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1125,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'IChcogLkMrs',
      title: 'Jobcenter in Slow German | Super Easy German 305',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1223,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: '3KZnAVWL5IQ',
      title: 'German in Real Life: Apartment Viewing in Berlin',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 836,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'paIiikWpnok',
      title: 'A Day at University in Slow German | Super Easy German 303',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1036,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'aZTUJm8O2Ds',
      title: '12 Verbs + Accusative Beginners Should Know',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 589,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: 'W9coIzRQGh4',
      title: 'Learn German with Us at the Supermarket (for Advanced Beginners)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 936,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: 'kRq3WzSwUw0',
      title: 'Street Interviews in Magdeburg (for German Learners)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 958,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: '7zRAEn1qXJ4',
      title: 'What Is the First Thing You Do in the Morning? | Easy German 400',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 681,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: '_F_zkRPRX6A',
      title: 'All German Cases Explained',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 960,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: 'ScseAJrBnH4',
      title: 'Why Germans Love Coffee and Cake (Slow German Conversation)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 855,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: '9xujQRaGN1Q',
      title: '50 German Verbs Every Beginner Must Know',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1291,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: '92Mcmx5gVus',
      title: 'Our Favourite Store in Berlin (Slow German)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1075,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: '6tAMFeWl55o',
      title: 'Cologne in Slow German',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1031,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'aC5IIC5y7UQ',
      title: 'What’s in Our Backpacks? (Slow German Conversation)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1120,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: '-CHCh4nXwmk',
      title: 'The Most Stupid Thing You Have Done | Easy German 565',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 875,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'TaXWJuiITqM',
      title: 'What Is Your Dream? | Easy German 562',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 840,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'eFXS0qZ6SFc',
      title: "What's Childhood in Germany Like? | Easy German 584",
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 875,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 's4R8XtZXYSM',
      title: 'How Has Studying Abroad Changed You? | Easy German 586',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 905,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'G-WTBhyoK7o',
      title: 'Small Things That Make Germans Happy | Easy German 592',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 881,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: '2axHWzwne34',
      title: 'This German Verb Has a True Super Power | Super Easy German 302',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 952,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'fex6ZtZNoSE',
      title: 'When Not To Use Articles in German | Super Easy German 286',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1444,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'Hjiy_ogekcw',
      title:
        '14 Verb + Preposition Combinations You Should Know (B1 Level) | Super Easy German 255',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 890,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: '-nrXMp8ECZI',
      title:
        'Don’t Mix Up "seit", "für" & "vor"! (German Temporal Prepositions) | Super Easy German 230',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 620,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'dV54jc8K6MU',
      title: '16 Verbs + Prepositions You Should Know (A1 Level)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 948,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'QSl-n50nrKM',
      title: 'How to Actually Remember German Vocabulary',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 893,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'zI8IEutHHD4',
      title: 'Germans Describe Their Best Friend (B1 Listening Comprehension)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 855,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'yv5ZHXAeN00',
      title: 'How to Start a Conversation in German',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 793,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'o0xHyMTe9Bk',
      title: 'Where do Berliners Go to Escape their City?',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 874,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'loqocHC9aAU',
      title: 'Do Germans Believe in Aliens? (B2 German Listening Comprehension)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 819,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: '_bXX1IOo4Eg',
      title: '8 Things That Happen Only in Germany | Easy German 522',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 699,
      level: CefrLevel.B1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'OQtPiclJPEU',
      title: '10 Things That Happen Only in Germany (feat @NALFVLOGS )',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 841,
      level: CefrLevel.B1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'hLoatpfE7VM',
      title: '7 More Things NOT to Do in Germany | Easy German 354',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 604,
      level: CefrLevel.B1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'lrrBNFqG1oI',
      title: '8 Things NOT to Do in Germany | Easy German 349',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 521,
      level: CefrLevel.B1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'v-Wf1UoV-wU',
      title: "Germany's Political System Explained | Easy German 388",
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1033,
      level: CefrLevel.B1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: '-TflT1ZrTIg',
      title: 'Which Country Do Germans Want to Visit? | Easy German 510',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 752,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'l_cvrtay9E0',
      title: 'What Foods Do Germans Hate? | Easy German 411',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 728,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'jC-ZZZE4dX0',
      title: 'We Asked People in Munich How Much They Earn | Easy German 499',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 819,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'hVH0waLVCyY',
      title: 'Mental Health in Germany | Easy German 429',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 743,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'uy_3J99ELp4',
      title: 'What Germans Abroad Miss About Germany | Easy German 490',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 878,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'ILjVXsfCoLo',
      title: 'Testing German Restaurants in Australia (Part II)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1222,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog', 'dokumentation'],
    },
    {
      youtubeId: 'NqSmqiJdbJw',
      title: 'Trying German Food in Australia (Part I)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1342,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog', 'dokumentation'],
    },
    {
      youtubeId: 'srGx0oAtkYg',
      title: '48 Hours in Istanbul (German Vlog)',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1444,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog', 'dokumentation'],
    },
    {
      youtubeId: 'b2dsUi67cAw',
      title: "I Took Europe's Longest Train (German Vlog) | Easy German 639",
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1635,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog', 'dokumentation'],
    },
    {
      youtubeId: 'o_GKTemLIfU',
      title: 'How Much of Germany Can You See in One Day? | Easy German 637',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1400,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog', 'dokumentation'],
    },
    {
      youtubeId: 'sTbqHypqM2M',
      title: 'Do Germans Save Money and Invest? | Easy German 450',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 775,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: '2aUt0QjU5ZI',
      title: 'Are Germans Superstitious? | Easy German 452',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 759,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'Y_8VbBOjJJw',
      title: 'How Long Does it Take to Learn German?',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1084,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'nOAg4xyScmI',
      title: '7 Tips to Better Understand Fast Spoken German | Super Easy German 238',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1046,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'XcxmbnrTCA0',
      title: 'This Austrian Tradition is Horrifying! | Easy German 480',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 736,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'Y32m79Ah1ms',
      title: 'A Day in the Life of a German Member of Parliament | Easy German 537',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1385,
      level: CefrLevel.C2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'KucGdktFHic',
      title: 'How Austrians Feel About Their History | Easy German 559',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 864,
      level: CefrLevel.C2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'z4p7mYD6dL8',
      title: 'What Austrians think about Austrian Politics | Easy German 182',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 589,
      level: CefrLevel.C2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'yIjVG1vG5Gs',
      title: 'A Day on a German Vineyard | Easy German 530',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 1210,
      level: CefrLevel.C2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: '3vNefv0dmZQ',
      title: 'German Slang Only Young People Use | Easy German 453',
      channelName: 'Easy German',
      channelUrl: 'https://www.youtube.com/@EasyGerman',
      durationSec: 754,
      level: CefrLevel.C2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
  ],
  en: [
    {
      youtubeId: '9iLcj6kfn_0',
      title: 'Learn 50 English Words and Their Opposites | Super Easy English 30',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 631,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'q9qbH6rw9lg',
      title: 'ESSENTIAL CAR VOCABULARY in Slow ENGLISH 🚗 | Super Easy English 29',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 981,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: '2eXHcmbqFFg',
      title: 'CONVERSATIONS at a HOTEL in SLOW ENGLISH | Super Easy English 28',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 685,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: '-OknSRRyFJE',
      title: 'CONVERSATIONS at the AIRPORT in SLOW English | Super Easy English 27',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 594,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'QdBrS0MQJbg',
      title: 'English CONVERSATION for BEGINNERS - DOG Routine | Super Easy English 26',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 972,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'LLLJwE6vr2k',
      title: 'RESTAURANT CONVERSATION in SLOW ENGLISH | Super Easy English 24',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 638,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'LAYbOaKn8DY',
      title: 'CONVERSATION at the DOCTOR and HOSPITAL | Super Easy English 25',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 816,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'uhOmwkfjROg',
      title: 'Culture Shocks in Germany! 🇩🇪 UK vs Berlin Life | Easy English 211',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 508,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'v8ecvyglvJ8',
      title: 'Conversations in English For Tourists | Easy English 233',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 584,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag', 'gespräch'],
    },
    {
      youtubeId: 'mgYE-v02kds',
      title: 'ESSENTIAL Vocabulary... with REAL Phone CONVERSATIONS | Easy English 232',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 729,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag', 'gespräch'],
    },
    {
      youtubeId: 'j1fh6RTIxx4',
      title: 'Conversations and Vocabulary for WORK | Easy English 231',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 568,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag', 'gespräch'],
    },
    {
      youtubeId: 'mzNcsRmuK7I',
      title: 'CONVERSATIONS with COUPLES in BRIGHTON | Easy English 229',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 606,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag', 'gespräch'],
    },
    {
      youtubeId: 'b7WcAmzNZ88',
      title: 'Everyday CONVERSATIONS and VOCABULARY for Shopping | Easy English 227',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 505,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag', 'gespräch'],
    },
    {
      youtubeId: 'jGn6bIbXlGY',
      title: "How to use 'WAS' and 'WERE' | Super Easy English 21",
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 481,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'mgHUZ2H__a0',
      title: '8 BRITISH ACCENT Tips to Sound Like a NATIVE Speaker | Easy English 138',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 552,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'x_GaTld0Tvw',
      title: '10 CRAZY English IDIOMS | Easy English 137',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 479,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'q7Rtyds5FMk',
      title: "The Modal Verb 'SHOULD' | Super Easy English 20",
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 543,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: '5sDxY8dh0E0',
      title: 'WITH or BY - Prepositions | Super Easy English 19',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 471,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'fEacJtQbTko',
      title: 'Asking FRIENDS in BRIGHTON How They Met | Easy English 182',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 681,
      level: CefrLevel.B1,
      topic: VideoTopic.VOCABULARY,
      slowSpeech: false,
      tags: ['wortschatz'],
    },
    {
      youtubeId: 'ftPWjaZrBCE',
      title: 'How Did YOU Meet Your BEST FRIEND? | Easy English 175',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 843,
      level: CefrLevel.B1,
      topic: VideoTopic.VOCABULARY,
      slowSpeech: false,
      tags: ['wortschatz'],
    },
    {
      youtubeId: '4sEscSxpMKY',
      title: 'How Did You Meet Your Best Friend? | Easy English 83',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 791,
      level: CefrLevel.B1,
      topic: VideoTopic.VOCABULARY,
      slowSpeech: false,
      tags: ['wortschatz'],
    },
    {
      youtubeId: 'UsvNXyblKz8',
      title: 'CONVERSATIONS with Retired People: Life Advice | Easy English 226',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 684,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'YVijbzh48kk',
      title: 'CONVERSATIONS in British Pubs | Easy English 225',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 748,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'TwBYlBjbokU',
      title: 'Everyday Conversations with Strangers | Easy English 224',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 634,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'HU9wGpwUa4U',
      title: 'CONVERSATIONS and Vocabulary for TOURISTS | Easy English 223',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 690,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: '-dgmtJzmOic',
      title: 'Can GERMAN STUDENTS Make CONVERSATIONS in ENGLISH? | Easy English 222',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 716,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'u9uPW7tL_bI',
      title: 'The Easy English Podcast #66 - 20 LOVING NICKNAMES | Easy English 201',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 1026,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'LMJMGRe0MBo',
      title: 'Angela Barnes Explains BRITISH HUMOUR for ENGLISH LEARNERS | Easy English 200',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 807,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'xYgNJ3DjqdU',
      title: 'The Easy English Podcast #65 - How BRITISH are YOU? | Easy English 198',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 1244,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: '5BMlBhM2pHU',
      title: 'The Easy English Podcast #63 - British Culture Quiz | Easy English 196',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 1382,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'NG--e3VxMQo',
      title:
        'The Easy English Podcast #50 - BRIT & GERMAN React to BRITISH MEMES | Easy English 186',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 1017,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'SX5yPu4MjEE',
      title: 'A BRIT on a GERMAN Christmas Market 🎄| Easy English 142',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 887,
      level: CefrLevel.C1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog'],
    },
    {
      youtubeId: 'JE95ppOnv34',
      title: 'Brighton and Hove - the Best City in the UK? | Easy English 159',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 888,
      level: CefrLevel.C1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog'],
    },
    {
      youtubeId: 'ADxTBfGq_r8',
      title: 'UK Travel VLOG - The Peak District | Easy English 170',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 1480,
      level: CefrLevel.C1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog'],
    },
    {
      youtubeId: 'dDkJe_n8iyM',
      title: 'We LIVED on a GERMAN ISLAND | Easy English 197',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 633,
      level: CefrLevel.C1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog'],
    },
    {
      youtubeId: 'SnvM5Wm06UU',
      title: 'Our HOLIDAY in WALES 🏴󠁧󠁢󠁷󠁬󠁳󠁿 | Easy English 208',
      channelName: 'Easy British English',
      channelUrl: 'https://www.youtube.com/@EasyEnglishVideos',
      durationSec: 1427,
      level: CefrLevel.C1,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['vlog'],
    },
  ],
  es: [
    {
      youtubeId: 'CFmfVQx6kP4',
      title: '100 Spanish Words & Phrases All Beginners Should Know | Super Easy Spanish 86',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 652,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'JsGQizTuPSo',
      title: 'Introduce Yourself in Slow Spanish | Super Easy Spanish 120',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 708,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: '8wNakkUBWvw',
      title: '50 Phrases to Survive Your First Spanish Conversation | Super Easy Spanish 138',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 482,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'BMx7tn_Y0oI',
      title: '50 Spanish Verbs Beginners Should Know | Super Easy Spanish 119',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 507,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'bkUtOdQGmxQ',
      title: '50 Adjectives Every Spanish Beginner Should Know | Super Easy Spanish 114',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 447,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: '3blBfMyzsrA',
      title: '11 Typical Colombian Expressions | Super Easy Spanish 142',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 519,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'LNv1Bhcg0jU',
      title: 'How to Say "Usually" in Spanish | Super Easy Spanish 127',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 442,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'Gcx2rqAcn2U',
      title: '100 Simple Subjunctive Phrases | Super Easy Spanish 125',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 665,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'M9uY4QFZRK0',
      title: '7 Key Meanings of QUEDAR in Spanish | Super Easy Spanish 124',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 683,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'KFqqfWZWGU8',
      title: 'Learn to Say "I realise" in Spanish | Super Easy Spanish 121',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 657,
      level: CefrLevel.A1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'obRbyVMIQLo',
      title: "Pau's Morning Routine in Slow Spanish | Super Easy Spanish 108",
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 396,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: 'oYBl3CcVmZ4',
      title: 'Breakfast in Slow Spanish | Super Easy Spanish 105',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 433,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: 'gUGPeMAFZtA',
      title: 'Grocery Shopping in Slow Spanish | Super Easy Spanish 93',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 593,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: 'uHOEHOoQCWA',
      title: 'Useful Spanish Phrases for Restaurants | Super Easy Spanish 60',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 437,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: 'JtLypQpGruo',
      title:
        '3 Ways to Order a Coffee in Spanish (And 3 Mistakes to Avoid) | Super Easy Spanish 74',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 478,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag'],
    },
    {
      youtubeId: 'UPHmXouXHdM',
      title: 'Slow Spanish Exercise Routine From Start to Finish | Super Easy Spanish 101',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 508,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'BhwnAYvzhm4',
      title: 'Slow Spanish Tour of Mexico Park | Super Easy Spanish 98',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 472,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'KvSxhLryGP0',
      title: 'Day of the Dead Traditions in Slow Spanish | Super Easy Spanish 92',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 468,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'Vbm1Z9Qjy0Q',
      title: 'Tour of Madrid in Slow Spanish | Super Easy Spanish 51',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 409,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: '6CwX_8xM8eE',
      title: 'How to Order Mexican Street Food (in Slow Spanish) | Super Easy Spanish 48',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 481,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'ybfyLfI5Ml0',
      title: 'How Do You Start Your Day? | Easy Spanish 342',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 722,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'fcYeXCacyrk',
      title: 'Do Barcelona Locals Prefer Coffee or Tea? | Easy Spanish 354',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 581,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'bQp-7WrU9ow',
      title: 'We Asked People to Describe Themselves in 3 Words | Easy Spanish 351',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 606,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: '5FYGP2Jd1XA',
      title: 'How Many Languages Do Barcelona Locals Speak? | Easy Spanish 356',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 667,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'H5TwdTKaQPc',
      title: 'What Motivates You? | Easy Spanish 350',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 652,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'fOdMIJdD1Kg',
      title: 'How to Say NO in Mexico? (Intermediate Spanish Listening)',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 676,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'ot5L3fIl0z0',
      title: 'What’s the Best Place to Live? (Intermediate Interviews)',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 714,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'J8Bh7D7YXAc',
      title: 'Can a Compliment Change Your Day? (Intermediate Spanish Interviews)',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 732,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'kui7PRSgZzU',
      title: 'What’s Your Apartment Like? | Easy Spanish 401',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 559,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'jMDD2QBCoh0',
      title: 'Is It Easy To Make Friends in Mexico? | Easy Spanish 400',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 573,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'hC-zjqsDYcE',
      title: 'Are You an Introvert or an Extrovert? | Easy Spanish 365',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 634,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: '-_TYh6J75x4',
      title: 'How Do Barcelona Locals Feel About Tourism? | Easy Spanish 368',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 672,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'O4hK5uQc-oU',
      title: 'Are You Wealthy? | Easy Spanish 367',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 631,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'h-ywDS1-nH0',
      title: 'Do the Spanish Still Read Books? | Easy Spanish 364',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 640,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'dQ7UvXzfycw',
      title: 'We Tried to Find Spanish Speakers in Berlin | Easy Spanish 363',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 619,
      level: CefrLevel.B2,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: '6qAmPjTXTCI',
      title: "What's a Typical Lunch in Spain? | Easy Spanish 399",
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 572,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde', 'spanien'],
    },
    {
      youtubeId: 'iPbaaFsbuco',
      title: 'Couples in Barcelona Share Their Love Story | Easy Spanish 398',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 671,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde', 'spanien'],
    },
    {
      youtubeId: 'GBRB4IeUCPw',
      title: "What's Your Greatest Challenge? | Easy Spanish 396",
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 619,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde', 'spanien'],
    },
    {
      youtubeId: 'dOObDVOokwA',
      title:
        '8 Minutes of Festive Phrases to Practise Your Spanish this Christmas | Easy Spanish 395',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 492,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde', 'spanien'],
    },
    {
      youtubeId: '1VUo8Rjaqxk',
      title: 'Do People in Barcelona Still Go to the Cinema? | Easy Spanish 394',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 760,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde', 'spanien'],
    },
    {
      youtubeId: 'lpo0icezg1Y',
      title: 'Spanish Slang That Only Young People Use | Easy Spanish 287',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 658,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: '4DNuopwIbbU',
      title: "What's the Madrid Accent Like? (+12 Typical Phrases) | Easy Spanish 294",
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 627,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: '3OW9h3w8mUM',
      title: 'Foreigners Try to Guess Mexican Expressions | Easy Spanish 312',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 691,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'fcSrWPQcShQ',
      title: 'Is Politics a Taboo Topic in Spain? | Easy Spanish 227',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 559,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'Kc_oHzZTcZw',
      title: '7 Expressions You Only Hear in Mexico | Easy Spanish 244',
      channelName: 'Easy Spanish',
      channelUrl: 'https://www.youtube.com/@EasySpanish',
      durationSec: 539,
      level: CefrLevel.C1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
  ],
  fr: [
    {
      youtubeId: '40IAXVvjSDA',
      title: 'Having Breakfast in Slow French | Super Easy French 152',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 894,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: '__Cu2nwgAjA',
      title:
        '100 French Words, Expressions & Sentences Every Beginner Should Know | Super Easy French 151',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 844,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'ZKnn-l4mLLQ',
      title: 'French for Beginners: Asking & Giving Directions | Super Easy French 147',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 544,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'Gz6rmwx-p0U',
      title: 'Must-Know Phrases If You Don’t Speak French | Super Easy French 114',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 441,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'uOuzm_APZWM',
      title: '100 French Words You Already Know | Super Easy French 94',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 372,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'aMx0d42wzBs',
      title: 'Everyday Conversation In Slow French | Super Easy French 161',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 442,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'tcF32PewZqY',
      title: 'Morning Routine in Slow French | Super Easy French 158',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 524,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'Kw6SlbImmkY',
      title: 'Public Transport in Paris in Slow French | Super Easy French 155',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 477,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'PdmdX9tvJB4',
      title: 'Essential Shops in a Parisian Neighborhood in Slow French | Super Easy French 154',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 531,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: '9JkJeHeI7Ec',
      title: 'Picnic in Paris in Slow French | Super Easy French 162',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 859,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'sOAiwNY6Blo',
      title: "What's Your Name? | Easy French 201",
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 537,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: '071rT-6irr8',
      title: "At The Doctor's In French | Super Easy French 159",
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 433,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: '5mutmziGppo',
      title: 'Stop Making These Beginners’ Mistakes in French! | Super Easy French 157',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 661,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'p65EBC9lW9k',
      title: 'What Do French People Actually Eat? | Easy French 189',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 585,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'zqF32466pDM',
      title:
        'How To Name And Describe Clothes, Shoes, Accessories & Outfits in French | Super Easy French 146',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 647,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'V0mOUg3zK_A',
      title: 'Survival Phrases in French | Super Easy French 63',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 165,
      level: CefrLevel.A2,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: '-4p0fngSbUs',
      title: 'How to Order at a French Bakery Like a Local | Super Easy French 67',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 251,
      level: CefrLevel.A2,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'N6ZCXl7A3F4',
      title: "How to Guess a Word's Gender | Super Easy French 90",
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 391,
      level: CefrLevel.A2,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: '7wUXSXZgNlU',
      title: '35 Most Used French Reflexive Verbs in 3 Short Stories | Super Easy French 93',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 315,
      level: CefrLevel.A2,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'eKMNzA9WQ4s',
      title: 'French Days of The Week | Super Easy French 100',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 435,
      level: CefrLevel.A2,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: true,
      tags: ['grammatik', 'wortschatz'],
    },
    {
      youtubeId: 'xTy21_vWZjY',
      title: 'We Try The Most Popular French Snacks! | Super Easy French 156',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 1098,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'Fj7k0M-g1jw',
      title: 'What Do Locals Like And Dislike About Bordeaux? | Easy French 190',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 507,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'bVANnFMuaW0',
      title: 'French Pronouns: En vs. Y (Explanations, Examples & Quiz) | Super Easy French 150',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 639,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'Vb9NWBcu5Ew',
      title: 'How Many Friends Do You Have? | Easy French 184',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 459,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'kHVtxkXSYik',
      title: 'A Tour of Bordeaux in French | Super Easy French 144',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 435,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'YCuU4SjcS2A',
      title: 'Why Do You Live in Paris? | Easy French 97',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 521,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'ooouJuoeQ1c',
      title: "What's Your Occupation? | Easy French 95",
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 491,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'ZpzeOhRIhi0',
      title: 'How Do French People Celebrate Christmas? | Easy French 94',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 480,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: '0MVzS2L_Hmw',
      title: 'Describe Yourself in French in 3 Words | Easy French 93',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 424,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'ej_TjsyAWf0',
      title: 'How French Is Spoken in Madagascar | Easy French 92',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 381,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: '6xrRoIYZ6A0',
      title: 'Do French People Use AI? | Easy French 199',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 613,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'QIrv10RWVYc',
      title: 'Do French People Smoke? | Easy French 198',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 589,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'noRuQbVi0oA',
      title: 'Are French People Funny? | Easy French 200',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 561,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'O4mCzVDzkmM',
      title: 'What Do The French Think of Tourists? | Easy French 197',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 535,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'zppduEG_1mE',
      title: "How Do French People Celebrate New Year's Eve? | Easy French 194",
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 474,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'Lrpy2CCnJR0',
      title: 'What French People Think About Germans | Easy French 98',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 582,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: '6FZQfsmgaYs',
      title: 'Inspiring Stories of Foreigners in France | Easy French 106',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 862,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'sxKmqEyWDvM',
      title: "French Idiom Compared: It's Raining Like a Peeing Cow | Easy French 107",
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 277,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'HtE9702IRis',
      title: 'Gesture Challenge: France vs. India | Easy French 108',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 803,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'dAzK6i7l8ok',
      title: 'Do You Speak Frenglish? | Easy French 113',
      channelName: 'Easy French',
      channelUrl: 'https://www.youtube.com/@EasyFrench',
      durationSec: 520,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
  ],
  it: [
    {
      youtubeId: 'war17gPDcaE',
      title: 'How To Name And Pronounce Colors In Italian | Super Easy Italian 13',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 477,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'eZ_r24D5Bik',
      title:
        'QUESTO, QUESTA, QUELLO, QUELLA... How to Say This and That in Italian | Super Easy Italian 12',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 334,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'j8aS78ZDVWA',
      title: 'How to Use "Essere" in Italian | Super Easy Italian 11',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 417,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'fqEfqxK5hwU',
      title:
        'SUL, NELLA, NEI, SUGLI... Articulated prepositions in Italian | Super Easy Italian 10',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 913,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'SnevQtPAXs8',
      title: 'Expressions with "avere" | Super Easy Italian 8',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 493,
      level: CefrLevel.A1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['alltag', 'einstieg'],
    },
    {
      youtubeId: 'I30hFP22PyM',
      title: 'Understand Spoken Italian With 4 Words in 20 | Super Easy Italian 93',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 928,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'W9ecfj5N0Vo',
      title: 'Al mercato! Useful Italian Words and Phrases to Remember | Super Easy Italian 91',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 537,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'cexDwGTXlnA',
      title: "What's in Your Suitcase? Italian Travel Words You'll Need | Super Easy Italian 89",
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 623,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'Er843Ktu84I',
      title: 'Aperitivo in Slow Italian | Super Easy Italian 87',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 630,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'D4HLpU75LUg',
      title: 'Tour This Beautiful Town in Slow Italian | Super Easy Italian 86',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 801,
      level: CefrLevel.A2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: true,
      tags: ['langsam gesprochen'],
    },
    {
      youtubeId: 'ux8bIXTbwwc',
      title: 'Potere vs. Riuscire: How to Say "Can" in Italian | Easy Italian 49',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 699,
      level: CefrLevel.A2,
      topic: VideoTopic.VOCABULARY,
      slowSpeech: false,
      tags: ['wortschatz'],
    },
    {
      youtubeId: 'h_cmp2nPA74',
      title: 'What Does "Anzi" Mean? | Easy Italian 47',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 362,
      level: CefrLevel.A2,
      topic: VideoTopic.VOCABULARY,
      slowSpeech: false,
      tags: ['wortschatz'],
    },
    {
      youtubeId: 'osxxBC0W0zo',
      title: '9 Common Italian Verbs Every Learner Should Know | Easy Italian 46',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 515,
      level: CefrLevel.A2,
      topic: VideoTopic.VOCABULARY,
      slowSpeech: false,
      tags: ['wortschatz'],
    },
    {
      youtubeId: 'Y1VyYbpE6KU',
      title: 'Italian Idiom Compared: To Have a Full Barrel and a Drunk Wife | Easy Italian 44',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 659,
      level: CefrLevel.A2,
      topic: VideoTopic.VOCABULARY,
      slowSpeech: false,
      tags: ['wortschatz'],
    },
    {
      youtubeId: 'TSmHXFvY9f4',
      title: '7 Words Italians Hate | Easy Italian 42',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 805,
      level: CefrLevel.A2,
      topic: VideoTopic.VOCABULARY,
      slowSpeech: false,
      tags: ['wortschatz'],
    },
    {
      youtubeId: 'U_6dO2STK4g',
      title: 'Italian Past Tense: Il Passato Prossimo | Easy Italian 50',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 745,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'TyQqNv1aJVQ',
      title: 'The imperfect tense in Italian: learn it with a game! | Easy Italian 34',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 855,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'lb1EWPWdgPg',
      title: 'Piccolino! Diminutives and Augmentatives in Italian | Easy Italian 60',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 825,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'RNqVYQy9TI0',
      title: 'How to Stop Translating in Your Head | Easy Italian 62',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 611,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'wC-Cc6Dw0dw',
      title: 'Meet the New Member, Third Person in Italian | Super Easy Italian 15',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 331,
      level: CefrLevel.B1,
      topic: VideoTopic.GRAMMAR,
      slowSpeech: false,
      tags: ['grammatik'],
    },
    {
      youtubeId: 'hfYubttHxfM',
      title: 'What Italians Say You Must See - and How to Say It | Easy Italian 274',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 792,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: '1YMnHT8_TE4',
      title: 'Essere and Stare: When Italians Use Each One | Easy Italian 273',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 543,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'PwhwnFNGTDg',
      title: 'How Italians Ask What You Do | Easy Italian 272',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 924,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'bNUKwKxRSGQ',
      title: 'How to Know if a Gelato Place is Any Good | Easy Italian 270',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 601,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'cJLmlSoQ7GI',
      title: 'Italian Preposition Quiz: Can You Get These Right? | Easy Italian 269',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 587,
      level: CefrLevel.B1,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['alltag'],
    },
    {
      youtubeId: 'ko8Mk3sfG1g',
      title: 'Why Do You Live in Milan? | Easy Italian 53',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 733,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: '6yGinUaciQA',
      title: 'What Did You Miss During Lockdown | Easy Italian 43',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 630,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'QpeW3jkurV4',
      title: 'What does "vabbè" mean? | Easy Italian 38',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 534,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'MdvvnhzfAhI',
      title: 'What is your favourite Italian food? | Easy Italian 37',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 595,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: '-G0oWWPf5AA',
      title: 'How to use INSOMMA in Italian | Easy Italian 36',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 753,
      level: CefrLevel.B1,
      topic: VideoTopic.STREET_INTERVIEW,
      slowSpeech: false,
      tags: ['straßeninterview'],
    },
    {
      youtubeId: 'NtQUi3nlZIs',
      title: 'What Does a Stay at Italian Agriturismo Farm Look Like? | Easy Italian 51',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 539,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'fDE2vf5diIk',
      title: 'Milan without tourists | Easy Italian 39',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 869,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'sQNIesG2EwI',
      title: 'How to make coffee with an Italian coffee maker | Easy Italian 35',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 726,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'HMAHzsI1SNo',
      title: 'What are Italian men like? | Easy Italian 33',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 608,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'FrMVRGuYxXw',
      title: '14 things you should NEVER DO in Italy | Easy Italian 30',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 638,
      level: CefrLevel.B2,
      topic: VideoTopic.CULTURE,
      slowSpeech: false,
      tags: ['landeskunde'],
    },
    {
      youtubeId: 'UQpg2WUm0Ek',
      title: '4 Words Italians Use All the Time in Conversation | Easy Italian 271',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 636,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: '4uZDDVBQmgg',
      title: 'Do Italians Actually Cook Every Day? | Easy Italian 266',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 821,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'OteHtoidbHg',
      title: 'Is Italian the sexiest language? | Easy Italian 263',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 679,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'rrvwubl7xV4',
      title: 'Is Tourism a Problem in Italy? | Easy Italian 262',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 882,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
    {
      youtubeId: 'GMESW_LNHTI',
      title: 'How to Eat Like an Italian in Italy | Easy Italian 260',
      channelName: 'Easy Italian',
      channelUrl: 'https://www.youtube.com/@EasyItalian',
      durationSec: 684,
      level: CefrLevel.B2,
      topic: VideoTopic.EVERYDAY,
      slowSpeech: false,
      tags: ['diskussion'],
    },
  ],
};
